import { LAYOUT_ADDITION_ADDITIONKIND, LAYOUT_CATEGORY_ADDITION, LAYOUT_CATEGORY_BASICINFO, LAYOUT_CATEGORY_CARD_CREATION, LAYOUT_CATEGORY_CHARGESTAFFINFO, LAYOUT_CATEGORY_DIFFICULTY_MAIN, LAYOUT_CATEGORY_DIFFICULTY_OTHER, LAYOUT_CATEGORY_IMPLANT_INFO, LAYOUT_CATEGORY_INFECT_INFO, LAYOUT_CATEGORY_MEDICALCAREINFO, LAYOUT_CATEGORY_MEDICAL_HST_INFO, LAYOUT_CATEGORY_OTHERCONTACTINFO, LAYOUT_CATEGORY_OTHERCONTACTKEYPERSONINFO, LAYOUT_CATEGORY_PATIENT_GROUP, LAYOUT_CATEGORY_PATMEMOINFO, LAYOUT_CATEGORY_PHYSICAL_INFO, LAYOUT_CATEGORY_PHYSICAL_INFO_CTR, LAYOUT_CATEGORY_PHYSICAL_INFO_DW, LAYOUT_CATEGORY_PHYSICAL_INFO_HEIGHT, LAYOUT_CATEGORY_SEVERITY, LAYOUT_CATEGORY_TABOO_ALLERGY_INFO, LAYOUT_CATEGORY_TRANSPORT, LAYOUT_CATEGORY_VENDORCONTACTINFO, LAYOUT_ITEM_ALLERGY, LAYOUT_ITEM_BASICINFO_AGE, LAYOUT_ITEM_BASICINFO_BIRTHDAY, LAYOUT_ITEM_BASICINFO_BLOODABONAME, LAYOUT_ITEM_BASICINFO_BLOODRHNAME, LAYOUT_ITEM_BASICINFO_BLOODSEROVARNAME, LAYOUT_ITEM_BASICINFO_CONTACT_ADDRESS, LAYOUT_ITEM_BASICINFO_CONTACT_EMAIL, LAYOUT_ITEM_BASICINFO_CONTACT_FAX, LAYOUT_ITEM_BASICINFO_CONTACT_MEMO1, LAYOUT_ITEM_BASICINFO_CONTACT_MEMO2, LAYOUT_ITEM_BASICINFO_CONTACT_TEL1, LAYOUT_ITEM_BASICINFO_CONTACT_TEL2, LAYOUT_ITEM_BASICINFO_CONTACT_WORK_NAME, LAYOUT_ITEM_BASICINFO_CONTACT_WORK_TEL, LAYOUT_ITEM_BASICINFO_CONTACT_ZIPCD, LAYOUT_ITEM_BASICINFO_INHOSPITALSTATE, LAYOUT_ITEM_BASICINFO_INOUT, LAYOUT_ITEM_BASICINFO_NAMEALPHA, LAYOUT_ITEM_BASICINFO_NAMEKANA, LAYOUT_ITEM_BASICINFO_NATIONALITYNAME, LAYOUT_ITEM_BASICINFO_SEXNAME, LAYOUT_ITEM_CARD_CREATION, LAYOUT_ITEM_CAUSE_DEATH_NAME, LAYOUT_ITEM_CHARGESTAFFINFO_CHARGENAME_1, LAYOUT_ITEM_CHARGESTAFFINFO_DOCTORNAME_1, LAYOUT_ITEM_CHARGESTAFFINFO_PUNCTURENAME_1, LAYOUT_ITEM_CTR_BREAST_DIA, LAYOUT_ITEM_CTR_CARDIAC_LATERAL_DIAMETER, LAYOUT_ITEM_CTR_CHEST_DIA, LAYOUT_ITEM_CTR_CTR, LAYOUT_ITEM_CTR_DW, LAYOUT_ITEM_CTR_EXAM_DATE, LAYOUT_ITEM_CTR_EXAM_TIME, LAYOUT_ITEM_CTR_ORDER_CLASS, LAYOUT_ITEM_CTR_TR_WEIGHT, LAYOUT_ITEM_DIFFICULTY_MAIN, LAYOUT_ITEM_DIFFICULTY_OTHER, LAYOUT_ITEM_DISEASE_DATE, LAYOUT_ITEM_DISEASE_NAME, LAYOUT_ITEM_DW_BREAST_DIA, LAYOUT_ITEM_DW_CHEST_DIA, LAYOUT_ITEM_DW_CTR, LAYOUT_ITEM_DW_DW, LAYOUT_ITEM_DW_EXAM_DATE, LAYOUT_ITEM_DW_EXAM_TIME, LAYOUT_ITEM_DW_ORDER_CLASS, LAYOUT_ITEM_DW_TARGET_WEIGHT, LAYOUT_ITEM_DW_TR_WEIGHT, LAYOUT_ITEM_HEIGHT_EXAM_DATE, LAYOUT_ITEM_HEIGHT_EXAM_TIME, LAYOUT_ITEM_HEIGHT_HEIGHT, LAYOUT_ITEM_IMPLANT, LAYOUT_ITEM_IS_BLOOD_SUGER_EXAMNAME, LAYOUT_ITEM_IS_CONFIRMATION_BIOPSYNAME, LAYOUT_ITEM_IS_DIABETESNAME, LAYOUT_ITEM_IS_DIAGNOSEDNAME, LAYOUT_ITEM_IS_NOTICE, LAYOUT_ITEM_MEDICALCAREINFO_DIALYSISCOUNT, LAYOUT_ITEM_MEDICALCAREINFO_DIALYSISCOURSENAME, LAYOUT_ITEM_MEDICALCAREINFO_DIALYSISSTARTDATE, LAYOUT_ITEM_MEDICALCAREINFO_DYALYSISHST, LAYOUT_ITEM_MEDICALCAREINFO_MAINCOURSENAME, LAYOUT_ITEM_MEDICALCAREINFO_PAT_DIALYSIS_COUNT, LAYOUT_ITEM_MEDICALCAREINFO_PURIFICATIONCOUNT, LAYOUT_ITEM_MEDICALCAREINFO_WARDNAME, LAYOUT_ITEM_NEGATIVE_INFECTION, LAYOUT_ITEM_OTHERCONTACTINFO_ADDRESS, LAYOUT_ITEM_OTHERCONTACTINFO_EMAIL, LAYOUT_ITEM_OTHERCONTACTINFO_FAX, LAYOUT_ITEM_OTHERCONTACTINFO_FIRSTNAME, LAYOUT_ITEM_OTHERCONTACTINFO_LASTNAME, LAYOUT_ITEM_OTHERCONTACTINFO_MEMO1, LAYOUT_ITEM_OTHERCONTACTINFO_MEMO2, LAYOUT_ITEM_OTHERCONTACTINFO_RELATION, LAYOUT_ITEM_OTHERCONTACTINFO_TEL1, LAYOUT_ITEM_OTHERCONTACTINFO_TEL2, LAYOUT_ITEM_OTHERCONTACTINFO_WORKNAME, LAYOUT_ITEM_OTHERCONTACTINFO_WORKTEL, LAYOUT_ITEM_OTHERCONTACTINFO_ZIPCD, LAYOUT_ITEM_OUT_COME_DATE, LAYOUT_ITEM_PATMEMOINFO_CONTENT_1, LAYOUT_ITEM_PATMEMOINFO_CONTENT_10, LAYOUT_ITEM_PATMEMOINFO_CONTENT_11, LAYOUT_ITEM_PATMEMOINFO_CONTENT_12, LAYOUT_ITEM_PATMEMOINFO_CONTENT_13, LAYOUT_ITEM_PATMEMOINFO_CONTENT_14, LAYOUT_ITEM_PATMEMOINFO_CONTENT_15, LAYOUT_ITEM_PATMEMOINFO_CONTENT_16, LAYOUT_ITEM_PATMEMOINFO_CONTENT_17, LAYOUT_ITEM_PATMEMOINFO_CONTENT_18, LAYOUT_ITEM_PATMEMOINFO_CONTENT_19, LAYOUT_ITEM_PATMEMOINFO_CONTENT_2, LAYOUT_ITEM_PATMEMOINFO_CONTENT_20, LAYOUT_ITEM_PATMEMOINFO_CONTENT_3, LAYOUT_ITEM_PATMEMOINFO_CONTENT_4, LAYOUT_ITEM_PATMEMOINFO_CONTENT_5, LAYOUT_ITEM_PATMEMOINFO_CONTENT_6, LAYOUT_ITEM_PATMEMOINFO_CONTENT_7, LAYOUT_ITEM_PATMEMOINFO_CONTENT_8, LAYOUT_ITEM_PATMEMOINFO_CONTENT_9, LAYOUT_ITEM_PATMEMOINFO_TITLE_1, LAYOUT_ITEM_PATMEMOINFO_TITLE_10, LAYOUT_ITEM_PATMEMOINFO_TITLE_11, LAYOUT_ITEM_PATMEMOINFO_TITLE_12, LAYOUT_ITEM_PATMEMOINFO_TITLE_13, LAYOUT_ITEM_PATMEMOINFO_TITLE_14, LAYOUT_ITEM_PATMEMOINFO_TITLE_15, LAYOUT_ITEM_PATMEMOINFO_TITLE_16, LAYOUT_ITEM_PATMEMOINFO_TITLE_17, LAYOUT_ITEM_PATMEMOINFO_TITLE_18, LAYOUT_ITEM_PATMEMOINFO_TITLE_19, LAYOUT_ITEM_PATMEMOINFO_TITLE_2, LAYOUT_ITEM_PATMEMOINFO_TITLE_20, LAYOUT_ITEM_PATMEMOINFO_TITLE_3, LAYOUT_ITEM_PATMEMOINFO_TITLE_4, LAYOUT_ITEM_PATMEMOINFO_TITLE_5, LAYOUT_ITEM_PATMEMOINFO_TITLE_6, LAYOUT_ITEM_PATMEMOINFO_TITLE_7, LAYOUT_ITEM_PATMEMOINFO_TITLE_8, LAYOUT_ITEM_PATMEMOINFO_TITLE_9, LAYOUT_ITEM_POSITIVE_INFECTION, LAYOUT_ITEM_PREVIOUS_WEIGHT_ALLOWANCE_LIMIT, LAYOUT_ITEM_PRE_WEIGHT_TOLERANCE_LOWER_LIMIT, LAYOUT_ITEM_SEVERITYNAME, LAYOUT_ITEM_STATURE, LAYOUT_ITEM_TABOO, LAYOUT_ITEM_TRANSPORTNAME, LAYOUT_ITEM_UNCLEAR_INFECTION, LAYOUT_ITEM_VENDORCONTACTINFO_ADDRESS, LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYNAME, LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYTEL, LAYOUT_ITEM_VENDORCONTACTINFO_FAX, LAYOUT_ITEM_VENDORCONTACTINFO_MEMO1, LAYOUT_ITEM_VENDORCONTACTINFO_MEMO2, LAYOUT_ITEM_VENDORCONTACTINFO_WORKEREMAIL, LAYOUT_ITEM_VENDORCONTACTINFO_WORKERFIRSTNAME, LAYOUT_ITEM_VENDORCONTACTINFO_WORKERLASTNAME, LAYOUT_ITEM_VENDORCONTACTINFO_WORKERTEL, LAYOUT_ITEM_VENDORCONTACTINFO_ZIPCD, LAYOUT_ITEM_WEIGHT_AT_TIME_INSPECTION, LAYOUT_PATIENTGROUP_PATIENTGROUP, layout_item_MEMORANDUM } from "@/components/multi-pat-list/Definitions.js";

export const mstPatListLayoutDefine = [
// mod データリストレイアウトマスタコンテンツの変更  王 start
  {
    ...LAYOUT_CATEGORY_CARD_CREATION,
    component: "card_creation",
    categoryItem: [
      LAYOUT_ITEM_CARD_CREATION
    ]
  },
  {
    ...LAYOUT_CATEGORY_BASICINFO,
    categoryItem: [
      // LAYOUT_ITEM_BASICINFO_HOSPPATID,
      // LAYOUT_ITEM_BASICINFO_NAME,
      LAYOUT_ITEM_BASICINFO_NAMEKANA,
      LAYOUT_ITEM_BASICINFO_NAMEALPHA,
      LAYOUT_ITEM_BASICINFO_INOUT,
      LAYOUT_ITEM_BASICINFO_INHOSPITALSTATE,
      LAYOUT_ITEM_BASICINFO_BIRTHDAY,
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 start
      LAYOUT_ITEM_BASICINFO_AGE,
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 end
      LAYOUT_ITEM_BASICINFO_SEXNAME,
      LAYOUT_ITEM_BASICINFO_BLOODABONAME,
      LAYOUT_ITEM_BASICINFO_BLOODRHNAME,
      LAYOUT_ITEM_BASICINFO_BLOODSEROVARNAME,
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 start
      LAYOUT_ITEM_BASICINFO_NATIONALITYNAME,
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 end
      LAYOUT_ITEM_BASICINFO_CONTACT_ZIPCD,
      LAYOUT_ITEM_BASICINFO_CONTACT_ADDRESS,
      LAYOUT_ITEM_BASICINFO_CONTACT_TEL1,
      LAYOUT_ITEM_BASICINFO_CONTACT_TEL2,
      LAYOUT_ITEM_BASICINFO_CONTACT_FAX,
      LAYOUT_ITEM_BASICINFO_CONTACT_EMAIL,
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 start
      LAYOUT_ITEM_BASICINFO_CONTACT_WORK_NAME,
      LAYOUT_ITEM_BASICINFO_CONTACT_WORK_TEL,
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 end
      LAYOUT_ITEM_BASICINFO_CONTACT_MEMO1,
      LAYOUT_ITEM_BASICINFO_CONTACT_MEMO2
    ]
  },
// mod データリストレイアウトマスタコンテンツの変更  王 end
  {
    ...LAYOUT_CATEGORY_OTHERCONTACTKEYPERSONINFO[0],
    categoryItem: [
      LAYOUT_ITEM_OTHERCONTACTINFO_LASTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_FIRSTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_RELATION,
      LAYOUT_ITEM_OTHERCONTACTINFO_ZIPCD,
      LAYOUT_ITEM_OTHERCONTACTINFO_ADDRESS,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL1,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL2,
      LAYOUT_ITEM_OTHERCONTACTINFO_FAX,
      LAYOUT_ITEM_OTHERCONTACTINFO_EMAIL,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKTEL,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO1,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO2
    ]
  },
  {
    ...LAYOUT_CATEGORY_OTHERCONTACTINFO[0],
    categoryItem: [
      LAYOUT_ITEM_OTHERCONTACTINFO_LASTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_FIRSTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_RELATION,
      LAYOUT_ITEM_OTHERCONTACTINFO_ZIPCD,
      LAYOUT_ITEM_OTHERCONTACTINFO_ADDRESS,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL1,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL2,
      LAYOUT_ITEM_OTHERCONTACTINFO_FAX,
      LAYOUT_ITEM_OTHERCONTACTINFO_EMAIL,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKTEL,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO1,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO2
    ]
  },
  {
    ...LAYOUT_CATEGORY_OTHERCONTACTINFO[1],
    categoryItem: [
      LAYOUT_ITEM_OTHERCONTACTINFO_LASTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_FIRSTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_RELATION,
      LAYOUT_ITEM_OTHERCONTACTINFO_ZIPCD,
      LAYOUT_ITEM_OTHERCONTACTINFO_ADDRESS,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL1,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL2,
      LAYOUT_ITEM_OTHERCONTACTINFO_FAX,
      LAYOUT_ITEM_OTHERCONTACTINFO_EMAIL,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKTEL,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO1,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO2
    ]
  },
  {
    ...LAYOUT_CATEGORY_OTHERCONTACTINFO[2],
    categoryItem: [
      LAYOUT_ITEM_OTHERCONTACTINFO_LASTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_FIRSTNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_RELATION,
      LAYOUT_ITEM_OTHERCONTACTINFO_ZIPCD,
      LAYOUT_ITEM_OTHERCONTACTINFO_ADDRESS,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL1,
      LAYOUT_ITEM_OTHERCONTACTINFO_TEL2,
      LAYOUT_ITEM_OTHERCONTACTINFO_FAX,
      LAYOUT_ITEM_OTHERCONTACTINFO_EMAIL,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKNAME,
      LAYOUT_ITEM_OTHERCONTACTINFO_WORKTEL,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO1,
      LAYOUT_ITEM_OTHERCONTACTINFO_MEMO2
    ]
  },
  {
    ...LAYOUT_CATEGORY_VENDORCONTACTINFO[0],
    categoryItem: [
      LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_ZIPCD,
      LAYOUT_ITEM_VENDORCONTACTINFO_ADDRESS,
      LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYTEL,
      LAYOUT_ITEM_VENDORCONTACTINFO_FAX,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERLASTNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERFIRSTNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERTEL,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKEREMAIL,
      LAYOUT_ITEM_VENDORCONTACTINFO_MEMO1,
      LAYOUT_ITEM_VENDORCONTACTINFO_MEMO2
    ]
  },
  {
    ...LAYOUT_CATEGORY_VENDORCONTACTINFO[1],
    categoryItem: [
      LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_ZIPCD,
      LAYOUT_ITEM_VENDORCONTACTINFO_ADDRESS,
      LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYTEL,
      LAYOUT_ITEM_VENDORCONTACTINFO_FAX,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERLASTNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERFIRSTNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERTEL,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKEREMAIL,
      LAYOUT_ITEM_VENDORCONTACTINFO_MEMO1,
      LAYOUT_ITEM_VENDORCONTACTINFO_MEMO2
    ]
  },
  {
    ...LAYOUT_CATEGORY_VENDORCONTACTINFO[2],
    categoryItem: [
      LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_ZIPCD,
      LAYOUT_ITEM_VENDORCONTACTINFO_ADDRESS,
      LAYOUT_ITEM_VENDORCONTACTINFO_COMPANYTEL,
      LAYOUT_ITEM_VENDORCONTACTINFO_FAX,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERLASTNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERFIRSTNAME,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKERTEL,
      LAYOUT_ITEM_VENDORCONTACTINFO_WORKEREMAIL,
      LAYOUT_ITEM_VENDORCONTACTINFO_MEMO1,
      LAYOUT_ITEM_VENDORCONTACTINFO_MEMO2
    ]
  },
  {
    ...LAYOUT_CATEGORY_PATMEMOINFO,
    categoryItem: [
      LAYOUT_ITEM_PATMEMOINFO_TITLE_1,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_1,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_2,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_2,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_3,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_3,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_4,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_4,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_5,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_5,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_6,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_6,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_7,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_7,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_8,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_8,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_9,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_9,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_10,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_10,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_11,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_11,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_12,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_12,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_13,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_13,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_14,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_14,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_15,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_15,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_16,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_16,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_17,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_17,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_18,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_18,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_19,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_19,
      LAYOUT_ITEM_PATMEMOINFO_TITLE_20,
      LAYOUT_ITEM_PATMEMOINFO_CONTENT_20
    ]
  },
  {
    ...LAYOUT_CATEGORY_DIFFICULTY_MAIN,
    categoryItem: [LAYOUT_ITEM_DIFFICULTY_MAIN]
  },
  {
    ...LAYOUT_CATEGORY_DIFFICULTY_OTHER,
    categoryItem: [LAYOUT_ITEM_DIFFICULTY_OTHER]
  },
  {
    ...LAYOUT_CATEGORY_SEVERITY,
    categoryItem: [LAYOUT_ITEM_SEVERITYNAME]
  },
  {
    ...LAYOUT_CATEGORY_TRANSPORT,
    categoryItem: [LAYOUT_ITEM_TRANSPORTNAME]
  },
  {
    ...LAYOUT_CATEGORY_MEDICALCAREINFO,
    categoryItem: [
      LAYOUT_ITEM_MEDICALCAREINFO_MAINCOURSENAME,
      LAYOUT_ITEM_MEDICALCAREINFO_DIALYSISCOURSENAME,
      LAYOUT_ITEM_MEDICALCAREINFO_WARDNAME,
      LAYOUT_ITEM_MEDICALCAREINFO_DIALYSISCOUNT,
      LAYOUT_ITEM_MEDICALCAREINFO_PAT_DIALYSIS_COUNT,
      LAYOUT_ITEM_MEDICALCAREINFO_PURIFICATIONCOUNT,
      LAYOUT_ITEM_MEDICALCAREINFO_DIALYSISSTARTDATE,
      //del 9225 データリストレイアウトマスタのテンプレート「患者情報1」の診療情報修正 zy start
      // LAYOUT_ITEM_MEDICALCAREINFO_FACILITYNAME,
      //del 9225 データリストレイアウトマスタのテンプレート「患者情報1」の診療情報修正 zy end
      LAYOUT_ITEM_MEDICALCAREINFO_DYALYSISHST
    ]
  },
  {
    ...LAYOUT_CATEGORY_CHARGESTAFFINFO,
    categoryItem: [
      LAYOUT_ITEM_CHARGESTAFFINFO_DOCTORNAME_1,
      // LAYOUT_ITEM_CHARGESTAFFINFO_DOCTORNAME_2,
      LAYOUT_ITEM_CHARGESTAFFINFO_CHARGENAME_1,
      // LAYOUT_ITEM_CHARGESTAFFINFO_CHARGENAME_2,
      // LAYOUT_ITEM_CHARGESTAFFINFO_CHARGENAME_3,
      LAYOUT_ITEM_CHARGESTAFFINFO_PUNCTURENAME_1,
      // LAYOUT_ITEM_CHARGESTAFFINFO_PUNCTURENAME_2
    ]
  },
  {
    ...LAYOUT_CATEGORY_TABOO_ALLERGY_INFO,
    categoryItem: [LAYOUT_ITEM_TABOO, LAYOUT_ITEM_ALLERGY]
  },
  {
    ...LAYOUT_CATEGORY_INFECT_INFO,
    categoryItem: [
      LAYOUT_ITEM_POSITIVE_INFECTION,
      LAYOUT_ITEM_NEGATIVE_INFECTION,
      LAYOUT_ITEM_UNCLEAR_INFECTION
// del FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 start
      // LAYOUT_ITEM_INFECTION
// del FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 end
    ]
  },
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 start
  {
    ...LAYOUT_CATEGORY_PATIENT_GROUP,
    categoryItem: [LAYOUT_PATIENTGROUP_PATIENTGROUP]
  },
  {
    ...LAYOUT_CATEGORY_ADDITION,
    categoryItem: [LAYOUT_ADDITION_ADDITIONKIND]
  },
// add FNSI-No.223 テンプレートおよび項目の不足、特定データの編集保存に対応。身体情報は新規追加に対応 陳 end
  {
    ...LAYOUT_CATEGORY_IMPLANT_INFO,
    categoryItem: [LAYOUT_ITEM_IMPLANT]
  },
  {
    ...LAYOUT_CATEGORY_MEDICAL_HST_INFO,
    component: "medical_history",
    categoryItem: [
      LAYOUT_ITEM_DISEASE_NAME,
      LAYOUT_ITEM_IS_CONFIRMATION_BIOPSYNAME,
      LAYOUT_ITEM_DISEASE_DATE,
      LAYOUT_ITEM_OUT_COME_DATE,
      LAYOUT_ITEM_CAUSE_DEATH_NAME,
      LAYOUT_ITEM_IS_DIAGNOSEDNAME,
      LAYOUT_ITEM_IS_DIABETESNAME,
      LAYOUT_ITEM_IS_BLOOD_SUGER_EXAMNAME,
      LAYOUT_ITEM_IS_NOTICE,
      // LAYOUT_ITEM_IS_NOTICE_2,
      // LAYOUT_ITEM_IS_NOTICE_3
    ]
  },
  {
    ...LAYOUT_CATEGORY_PHYSICAL_INFO,
    component: "physical_info",
    categoryItem: [
// mod データリストレイアウトマスタコンテンツの変更  王 start
// del #11321 【たくしん会】データリストレイアウトマスタ＞身体情報(追加登録)とデータリスト表示バグ zkm start
//       LAYOUT_ITEM_INSPECTION_DATE_TIME,
// del #11321 【たくしん会】データリストレイアウトマスタ＞身体情報(追加登録)とデータリスト表示バグ zkm end
      LAYOUT_ITEM_WEIGHT_AT_TIME_INSPECTION,
      LAYOUT_ITEM_STATURE,
      LAYOUT_ITEM_CTR_CARDIAC_LATERAL_DIAMETER,
      LAYOUT_ITEM_DW_TARGET_WEIGHT,
      LAYOUT_ITEM_PREVIOUS_WEIGHT_ALLOWANCE_LIMIT,
      LAYOUT_ITEM_PRE_WEIGHT_TOLERANCE_LOWER_LIMIT,
      layout_item_MEMORANDUM,
      // LAYOUT_ITEM_EXAM_DATE,
      // LAYOUT_ITEM_EXAM_TIME,
      // LAYOUT_ITEM_ORDER_CLASSNAME,
      // LAYOUT_ITEM_HEIGHT,
      // LAYOUT_ITEM_TR_WEIGHT,
      // LAYOUT_ITEM_BREAST_DIA,
      // LAYOUT_ITEM_CHEST_DIA,
      // LAYOUT_ITEM_CTR,
      // LAYOUT_ITEM_DW,
      // LAYOUT_ITEM_TARGET_WEIGHT,
      // LAYOUT_ITEM_INDICATOR_START_DATE,
      // LAYOUT_ITEM_INDICATOR_CDNAME,
      // LAYOUT_ITEM_MEMO
// mod データリストレイアウトマスタコンテンツの変更  王 end
    ]
  },
  {
    ...LAYOUT_CATEGORY_PHYSICAL_INFO_HEIGHT,
    component: "physical_info_height",
    categoryItem: [
      LAYOUT_ITEM_HEIGHT_EXAM_DATE,
      LAYOUT_ITEM_HEIGHT_EXAM_TIME,
      LAYOUT_ITEM_HEIGHT_HEIGHT
    ]
  },
  {
    ...LAYOUT_CATEGORY_PHYSICAL_INFO_DW,
    component: "physical_info_dw",
    categoryItem: [
      LAYOUT_ITEM_DW_EXAM_DATE,
      LAYOUT_ITEM_DW_EXAM_TIME,
      LAYOUT_ITEM_DW_ORDER_CLASS,
      LAYOUT_ITEM_DW_TR_WEIGHT,
      LAYOUT_ITEM_DW_BREAST_DIA,
      LAYOUT_ITEM_DW_CHEST_DIA,
      LAYOUT_ITEM_DW_CTR,
      LAYOUT_ITEM_DW_DW
    ]
  },
  {
    ...LAYOUT_CATEGORY_PHYSICAL_INFO_CTR,
    component: "physical_info_ctr",
    categoryItem: [
      LAYOUT_ITEM_CTR_EXAM_DATE,
      LAYOUT_ITEM_CTR_EXAM_TIME,
      LAYOUT_ITEM_CTR_ORDER_CLASS,
      LAYOUT_ITEM_CTR_TR_WEIGHT,
      LAYOUT_ITEM_CTR_BREAST_DIA,
      LAYOUT_ITEM_CTR_CHEST_DIA,
      LAYOUT_ITEM_CTR_CTR,
      LAYOUT_ITEM_CTR_DW
    ]
  }
];
