import org.gradle.internal.os.OperatingSystem

buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("https://start.spring.io/plugins-release") }
    maven { url = uri("https://start.spring.io/milestone") }
    maven { url = uri("https://plugins.gradle.org/m2/") }
  }
  dependencies {
    classpath "org.springframework.boot:spring-boot-gradle-plugin:${spring_boot_version}"
//    classpath 'io.spring.gradle:propdeps-plugin:0.0.10.RELEASE'
    classpath "io.spring.gradle:dependency-management-plugin:${dependency_management_plugin_version}"
  }
}

apply plugin: 'maven-publish'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'idea'
defaultTasks 'bootRun'

bootJar {
  enabled = false
  archiveBaseName = 'ntss-api'
  mainClass = 'jp.co.nikkiso.ntss.api.NtssApiApplication'
  manifest {
    attributes 'Start-Class': 'jp.co.nikkiso.ntss.api.NtssApiApplication'
  }
}

bootWar {
  mainClass = 'jp.co.nikkiso.ntss.api.NtssApiApplication'
}

war {
  enabled = true
  archiveBaseName = 'ntss-api'
}

jar {
  enabled = true // Jarを作成する(依存元に組み込む)
}

springBoot {
  mainClass = 'jp.co.nikkiso.ntss.api.NtssApiApplication'
  buildInfo()
}

if (OperatingSystem.current().isWindows()) {
  task pathingJar(type: Jar) {
    dependsOn configurations.runtimeClasspath
    archiveAppendix = 'pathing'

    doFirst {
      manifest {
        attributes 'Class-Path': configurations.runtimeClasspath.getFiles().collect {
          it.toURI().toString().replaceFirst(/file:\/+/, '/').replaceAll(' ', '%20')
        }.join(' ')
      }
    }
  }

  bootRun {
    dependsOn pathingJar
    doFirst {
      classpath = files("$buildDir/classes/java/main", "$buildDir/resources/main", pathingJar.archiveFile)
    }
  }
} else {
  bootRun {
    jvmArgs = ["-Dspring.output.ansi.enabled=ALWAYS"]
  }
}

ext {
  snippetsDir = file('build/generated-snippets')
  apiDocDir = file('build/api-docs')
}

apply from: 'gradle/eclipse.gradle'
apply from: 'gradle/docker.gradle'
//jhipster-needle-gradle-apply-from - JHipster will add additional gradle scripts to be applied here

if (project.hasProperty('prod')) {
  apply from: 'gradle/profile_prod.gradle'
} else {
  apply from: 'gradle/profile_dev.gradle'
}

test {
  outputs.dir snippetsDir
  // CI用にテスト時のprofileを設定
  if (project.hasProperty('ci')) {
    jvmArgs = ["-Dspring.profiles.active=ci"]
  }
  maxHeapSize = "1024m"
}

description = ''

repositories {
  mavenLocal()
  mavenCentral()
  maven { url = uri('https://start.spring.io/milestone') }
  maven { url = uri('https://start.spring.io/snapshot') }
  maven { url = uri('https://repository.jboss.org/nexus/content/repositories/releases') }
  maven { url = uri('https://oss.sonatype.org/content/repositories/releases') }
  maven { url = uri('https://oss.sonatype.org/content/repositories/snapshots') }
  maven { url = uri('https://repo.maven.apache.org/maven2') }
  maven { url = uri('https://releases.aspose.com/java/repo/') }
}

dependencies {
  implementation "org.springframework.boot:spring-boot-autoconfigure"
  implementation "org.springframework.boot:spring-boot-starter-web"
  providedRuntime "org.springframework.boot:spring-boot-starter-tomcat"
  implementation "org.springframework.boot:spring-boot-starter-jdbc"
  implementation "org.springframework.boot:spring-boot-starter-actuator"
  implementation "org.springframework.boot:spring-boot-starter-aspectj"
  implementation "org.seasar.doma.boot:doma-spring-boot-starter:${doma_spring_version}"
  implementation "org.projectlombok:lombok:${lombok_version}"
  annotationProcessor "org.projectlombok:lombok:${lombok_version}"
  implementation "org.modelmapper:modelmapper:${modelmapper_version}"
  implementation "com.google.guava:guava:${guava_version}"
  testImplementation ("org.springframework.boot:spring-boot-starter-test") {
    exclude group: 'com.vaadin.external.google', module: 'android-json'
  }
  testImplementation "org.springframework.boot:spring-boot-test"
  testImplementation "junit:junit"
  testImplementation "org.mockito:mockito-core"
  implementation "org.json:json:${json_java_version}"
  implementation platform("software.amazon.awssdk:bom:${aws_sdk_v2_version}")
  implementation "software.amazon.awssdk:auth"
  implementation "software.amazon.awssdk:regions"
  implementation "software.amazon.awssdk:url-connection-client"
  implementation("software.amazon.awssdk:s3") {
    exclude group: "software.amazon.awssdk", module: "apache-client"
  }
  implementation "org.jsoup:jsoup:${jsoup_version}"
  implementation "org.apache.commons:commons-lang3:${commons_lang3_version}"
  implementation "org.apache.commons:commons-collections4:${commons_collections4_version}"
  implementation "org.apache.poi:poi:${poi_version}"
  implementation "org.apache.poi:poi-ooxml:${poi_version}"
//  compile group: 'com.aspose', name: 'aspose-cells', version: '22.9'
  // mod 10499 紹介状画面でセルの縦配置設定が反映しない 吉 start
  // implementation files('lib/aspose-cells-23.10.jar')
  // mod 10957 紹介状画面で罫線の一部が切れる 吉 start
  // implementation files('lib/aspose-cells-24.4.jar')
  implementation files('lib/aspose-cells-24.9.jar')
  // mod 10957 紹介状画面で罫線の一部が切れる 吉 end
  // mod 10499 紹介状画面でセルの縦配置設定が反映しない 吉 end

  //implementation files('lib/Aspose.Cells.Java.lic')
  implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
  // add 9661 複数患者帳票で2人目以降の「増加重量」と「DWとの差」が表示されない。 高 start
  implementation "org.openjdk.nashorn:nashorn-core:15.7"
  // add 9661 複数患者帳票で2人目以降の「増加重量」と「DWとの差」が表示されない。 高 end
  // add #10245 帳票用患者情報履歴mongoDBのマスタ変更影響問題 sunsy start
  implementation "com.google.code.gson:gson:${gson_version}"
  // add #10245 帳票用患者情報履歴mongoDBのマスタ変更影響問題 sunsy end

  // add #10988 データ項目「処方.処方箋情報.QRコード」を追加　V1.1A 吉 start
  // https://mvnrepository.com/artifact/com.google.zxing/core
  implementation "com.google.zxing:core:${zxing_version}"
  // https://mvnrepository.com/artifact/com.google.zxing/javase
  implementation "com.google.zxing:javase:${zxing_version}"
  // add #10988 データ項目「処方.処方箋情報.QRコード」を追加　V1.1A 吉 end

  // add highchart-export-serve change to Playwright  吉 start
  implementation "com.microsoft.playwright:playwright:${playwright_version}"
  // add highchart-export-serve change to Playwright  吉 end
}

clean { delete "target" }

task cleanResources(type: Delete) { delete 'build/resources' }


task stage(dependsOn: [bootWar, bootJar]) {
}

assemble.dependsOn bootJar

// Doma2のSQLファイルをJavaのコンパイル前にコピーしておく
// SQLファイルが存在するかしないとJavaのコンパイル時にSQLファイルが存在するかのチェックでエラーになるため。
def domaResources = ['doma.compile.config', 'META-INF/**/*.sql']
task copyDomaResourcesJava(type: Copy) {
  from sourceSets.main.resources.srcDirs
  into compileJava.destinationDirectory
  include domaResources
}
compileJava {
  dependsOn copyDomaResourcesJava
}
processResources {
  exclude domaResources
}

processResources.dependsOn cleanResources, bootBuildInfo
bootBuildInfo.mustRunAfter cleanResources
