-- Generated By Doma Tools  #12462 患者情報共有 zrx
SELECT
A.pat_id,
addition_info -> 'cd' AS cd,
MAX ( treat_date ) AS last_date
FROM
(
SELECT
ord.pat_id,
jsonb_array_elements ( addition_info ) AS addition_info,
treat_date
	FROM
ord_main ord
		JOIN (
SELECT
o.pat_id,
o.facility_cd
		FROM
shr_pat_info s
			JOIN ord_main o ON o.pat_id = s.from_pat_id
			AND o.facility_cd = s.from_facility_cd
		WHERE
      o.ord_no = /*ordNo*/0
			AND s.to_pat_id = /*patId*/0
			AND s.from_facility_cd = /*facilityCd*/''
      /*%if null != treatDate*/
			AND o.treat_date <= /*treatDate*/'00000000'
      /*%end*/
			AND s.is_from_consent = '1'
			AND s.is_to_consent = '1'
			AND s.is_pat_consent = '1'
			AND s.is_disp = '1'
			AND s.is_del = '0'
) spiom ON ord.facility_cd = spiom.facility_cd AND ord.pat_id = spiom.pat_id
	WHERE
    /*%if null != ordNo*/
		ord.ord_no != /*ordNo*/0
    /*%end*/
    /*%if null != treatDate*/
		AND ord.treat_date <= /*treatDate*/'00000000'
    /*%end*/
		AND ord.addition_info IS NOT NULL
		AND ord.is_del = '0'
) AS A
GROUP BY
pat_id,
cd;
