UPDATE ord_main
SET pat_id                    = tmp.patId,
    fn_pat_id                 = tmp.fnPatId,
    treat_date                = tmp.treatDate,
    treat_week                = tmp.treatWeek,
    facility_cd               = tmp.facilityCd,
    facility_name             = tmp.facilityName,
    ind_va_cd                 = tmp.indVaCd,
    ind_treatment_cd          = tmp.indTreatmentCd,
    ind_treatment_name        = tmp.indTreatmentName,
    ind_kur_cd                = tmp.indKurCd,
    ind_kur_name              = tmp.indKurName,
    ind_treat_start_time      = tmp.indTreatStartTime,
    ind_bed_cd                = tmp.indBedCd,
    ind_bed_name              = tmp.indBedName,
    ind_schedule_user_info    = CAST(tmp.indScheduleUserInfo AS JSONB),
    ind_cond_info             = CAST(tmp.indCondInfo AS JSONB),
    ind_medi_info             = CAST(tmp.indMediInfo AS JSONB),
    ind_equip_info            = CAST(tmp.indEquipInfo AS JSONB),
    ind_ind_comment_info      = CAST(tmp.indIndCommentInfo AS JSONB),
    ind_tare_info             = CAST(tmp.indTareInfo AS JSONB),
    ind_off_water_info        = CAST(tmp.indOffWaterInfo AS JSONB),
    rst_fn_dialysis_no        = CAST(tmp.rstFnDialysisNo AS INTEGER),
    rst_relation_dialysis_no  = CAST(tmp.rstRelationDialysisNo AS INTEGER),
    rst_edition               = CAST(tmp.rstEdition AS INTEGER),
    rst_is_update_edition     = tmp.rstIsUpdateEdition,
    rst_input_class           = CAST(tmp.rstInputClass AS INTEGER),
    rst_dialysis_state        = tmp.rstDialysisState,
    rst_treatment_cd          = CAST(tmp.rstTreatmentCd AS INTEGER),
    rst_treatment_name        = tmp.rstTreatmentName,
    rst_kur_cd                = CAST(tmp.rstKurCd AS INTEGER),
    rst_kur_name              = tmp.rstKurName,
    rst_bed_cd                = CAST(tmp.rstBedCd AS INTEGER),
    rst_bed_name              = tmp.rstBedName,
    rst_machine_no            = CAST(tmp.rstMachineNo AS INTEGER),
    rst_machine_name          = tmp.rstMachineName,
    rst_cond_send_date        = CAST(tmp.rstCondSendDate AS TIMESTAMP),
    rst_accept_date           = CAST(tmp.rstAcceptDate AS TIMESTAMP),
    rst_start_date            = CAST(tmp.rstStartDate AS TIMESTAMP),
    rst_end_date              = CAST(tmp.rstEndDate AS TIMESTAMP),
    rst_return_home_date      = CAST(tmp.rstReturnHomeDate AS TIMESTAMP),
    rst_in_out_class          = CAST(tmp.rstInOutClass AS INTEGER),
    rst_dialysis_cnt          = CAST(tmp.rstDialysisCnt AS INTEGER),
    rst_ward_cd               = CAST(tmp.rstWardCd AS INTEGER),
    rst_ward_name             = tmp.rstWardName,
    rst_course_cd             = CAST(tmp.rstCourseCd AS INTEGER),
    rst_course_name           = tmp.rstCourseName,
    rst_puncture_user_info    = CAST(tmp.rstPunctureUserInfo AS JSONB),
    rst_return_user_info      = CAST(tmp.rstReturnUserInfo AS JSONB),
    rst_charge_user_info      = CAST(tmp.rstChargeUserInfo AS JSONB),
    rst_blood_circulate_total = CAST(tmp.rstBloodCirculateTotal AS NUMERIC),
    rst_running_time          = CAST(tmp.rstRunningTime AS INTEGER),
    rst_kt_v                  = CAST(tmp.rstKtV AS NUMERIC),
    rec_set_date              = CAST(tmp.recSetDate AS TIMESTAMP),
    send_ctl_no               = CAST(tmp.sendCtlNo AS INTEGER),
    blood_purifier_name       = tmp.bloodPurifierName,
    pull_leave_amount         = CAST(tmp.pullLeaveAmount AS NUMERIC),
    rst_cond_info             = CAST(tmp.rstCondInfo AS JSONB),
    rst_medi_info             = CAST(tmp.rstMediInfo AS JSONB),
    rst_equip_info            = CAST(tmp.rstEquipInfo AS JSONB),
    rst_ind_comment_info      = CAST(tmp.rstIndCommentInfo AS JSONB),
    rst_tare_info             = CAST(tmp.rstTareInfo AS JSONB),
    rst_off_water_info        = CAST(tmp.rstOffWaterInfo AS JSONB),
    rst_weight_info           = CAST(tmp.rstWeightInfo AS JSONB),
--   add 10196 by kangjie 20240130 start del
--     rst_vital_info            = CAST(tmp.rstVitalInfo AS JSONB),
--   add 10196 by kangjie 20240130 end del
    rst_complaint_info        = CAST(tmp.rstComplaintInfo AS JSONB),
    rst_treatment_info        = CAST(tmp.rstTreatmentInfo AS JSONB),
    rst_treat_staff_info      = CAST(tmp.rstTreatStaffInfo AS JSONB),
    rst_rounds_info           = CAST(tmp.rstRoundsInfo AS JSONB),
    is_del                    = tmp.isDel,
    reg_date                  = CAST(tmp.regDate AS TIMESTAMP),
    up_date                   = CAST(tmp.upDate AS TIMESTAMP),
    ind_device_set_info       = CAST(tmp.indDeviceSetInfo AS JSONB),
--   add 10196 by kangjie 20240130 start del
--     rst_device_set_info       = CAST(tmp.rstDeviceSetInfo AS JSONB),
--   add 10196 by kangjie 20240130 end del
    rst_dw                    = CAST(tmp.rstDw AS NUMERIC),
    weight_scale_no           = CAST(tmp.weightScaleNo AS INTEGER),
    treat_type                = tmp.treatType,
    is_confirm                = tmp.isConfirm,
    ind_dw                    = CAST(tmp.indDw AS NUMERIC),
    rst_purification_cnt      = CAST(tmp.rstPurificationCnt AS INTEGER),
    addition_info             = CAST(tmp.additionInfo AS JSONB),
    up_ind_user_id            = CAST(tmp.upIndUserId AS INTEGER),
    up_user_id                = CAST(tmp.upUserId AS INTEGER),
    rst_edition_date          = CAST(tmp.rstEditionDate AS TIMESTAMP),
    cur_edition_date          = CAST(tmp.curEditionDate AS TIMESTAMP),
    bvms_path                 = CAST(tmp.bvmsPath AS JSONB) FROM
(VALUES
    /*%for uol : uptOrdList */
        (
            /*uol.ordNo*/null,
            /*uol.patId*/null,
            /*uol.fnPatId*/null,
            /*uol.treatDate*/null,
            /*uol.treatWeek*/null,
            /*uol.facilityCd*/null,
            /*uol.facilityName*/null,
            /*uol.indVaCd*/null,
            /*uol.indTreatmentCd*/null,
            /*uol.indTreatmentName*/null,
            /*uol.indKurCd*/null,
            /*uol.indKurName*/null,
            /*uol.indTreatStartTime*/null,
            /*uol.indBedCd*/null,
            /*uol.indBedName*/null,
            /*uol.indScheduleUserInfo*/null,
            /*uol.indCondInfo*/null,
            /*uol.indMediInfo*/null,
            /*uol.indEquipInfo*/null,
            /*uol.indIndCommentInfo*/null,
            /*uol.indTareInfo*/null,
            /*uol.indOffWaterInfo*/null,
            /*uol.rstFnDialysisNo*/null,
            /*uol.rstRelationDialysisNo*/null,
            /*uol.rstEdition*/null,
            /*uol.rstIsUpdateEdition*/null,
            /*uol.rstInputClass*/null,
            /*uol.rstDialysisState*/null,
            /*uol.rstTreatmentCd*/null,
            /*uol.rstTreatmentName*/null,
            /*uol.rstKurCd*/null,
            /*uol.rstKurName*/null,
            /*uol.rstBedCd*/null,
            /*uol.rstBedName*/null,
            /*uol.rstMachineNo*/null,
            /*uol.rstMachineName*/null,
            /*uol.rstCondSendDate*/null,
            /*uol.rstAcceptDate*/null,
            /*uol.rstStartDate*/null,
            /*uol.rstEndDate*/null,
            /*uol.rstReturnHomeDate*/null,
            /*uol.rstInOutClass*/null,
            /*uol.rstDialysisCnt*/null,
            /*uol.rstWardCd*/null,
            /*uol.rstWardName*/null,
            /*uol.rstCourseCd*/null,
            /*uol.rstCourseName*/null,
            /*uol.rstPunctureUserInfo*/null,
            /*uol.rstReturnUserInfo*/null,
            /*uol.rstChargeUserInfo*/null,
            /*uol.rstBloodCirculateTotal*/null,
            /*uol.rstRunningTime*/null,
            /*uol.rstKtV*/null,
            /*uol.recSetDate*/null,
            /*uol.sendCtlNo*/null,
            /*uol.bloodPurifierName*/null,
            /*uol.pullLeaveAmount*/null,
            /*uol.rstCondInfo*/null,
            /*uol.rstMediInfo*/null,
            /*uol.rstEquipInfo*/null,
            /*uol.rstIndCommentInfo*/null,
            /*uol.rstTareInfo*/null,
            /*uol.rstOffWaterInfo*/null,
            /*uol.rstWeightInfo*/null,
--   add 10196 by kangjie 20240130 start del
--             /*uol.rstVitalInfo*/null,
--   add 10196 by kangjie 20240130 end del
            /*uol.rstComplaintInfo*/null,
            /*uol.rstTreatmentInfo*/null,
            /*uol.rstTreatStaffInfo*/null,
            /*uol.rstRoundsInfo*/null,
            /*uol.isDel*/null,
            /*uol.regDate*/null,
            /*uol.upDate*/null,
            /*uol.indDeviceSetInfo*/null,
--   add 10196 by kangjie 20240130 start del
--             /*uol.rstDeviceSetInfo*/null,
--   add 10196 by kangjie 20240130 end del
            /*uol.rstDw*/null,
            /*uol.weightScaleNo*/null,
            /*uol.treatType*/null,
            /*uol.isConfirm*/null,
            /*uol.indDw*/null,
            /*uol.rstPurificationCnt*/null,
            /*uol.additionInfo*/null,
            /*uol.upIndUserId*/null,
            /*uol.upUserId*/null,
            /*uol.rstEditionDate*/null,
            /*uol.curEditionDate*/null,
            /*uol.bvmsPath*/null
        )
    /*%if uol_has_next */
/*# "," */
    /*%end */
/*%end*/
) AS tmp (ordNo,patId,fnPatId,treatDate,treatWeek,facilityCd,facilityName,indVaCd,indTreatmentCd,indTreatmentName,
indKurCd,indKurName,indTreatStartTime,indBedCd,indBedName,indScheduleUserInfo,indCondInfo,indMediInfo,indEquipInfo,
indIndCommentInfo,indTareInfo,indOffWaterInfo,rstFnDialysisNo,rstRelationDialysisNo,rstEdition,rstIsUpdateEdition,
rstInputClass,rstDialysisState,rstTreatmentCd,rstTreatmentName,rstKurCd,rstKurName,rstBedCd,rstBedName,rstMachineNo,
rstMachineName,rstCondSendDate,rstAcceptDate,rstStartDate,rstEndDate,rstReturnHomeDate,rstInOutClass,rstDialysisCnt,
rstWardCd,rstWardName,rstCourseCd,rstCourseName,rstPunctureUserInfo,rstReturnUserInfo,rstChargeUserInfo,rstBloodCirculateTotal,
rstRunningTime,rstKtV,recSetDate,sendCtlNo,bloodPurifierName,pullLeaveAmount,rstCondInfo,rstMediInfo,rstEquipInfo,
rstIndCommentInfo,rstTareInfo,rstOffWaterInfo,rstWeightInfo,rstComplaintInfo,rstTreatmentInfo,rstTreatStaffInfo,
rstRoundsInfo,isDel,regDate,upDate,indDeviceSetInfo,rstDw,weightScaleNo,treatType,isConfirm,indDw,
rstPurificationCnt,additionInfo,upIndUserId,upUserId,rstEditionDate,curEditionDate,bvmsPath)
WHERE
    ord_no = tmp.ordNo
;
