insert into ord_main_restore
(
ord_no,
del_date,
pat_id
,fn_pat_id
,treat_date
,treat_week
,facility_cd
,facility_name
,ind_va_cd
,ind_treatment_cd
,ind_treatment_name
,ind_kur_cd
,ind_kur_name
,ind_treat_start_time
,ind_bed_cd
,ind_bed_name
,ind_schedule_user_info
,ind_cond_info
,ind_medi_info
,ind_equip_info
,ind_ind_comment_info
,ind_tare_info
,ind_off_water_info
,rst_fn_dialysis_no
,rst_relation_dialysis_no
,rst_edition
,rst_is_update_edition
,rst_input_class
,rst_dialysis_state
,rst_treatment_cd
,rst_treatment_name
,rst_kur_cd
,rst_kur_name
,rst_bed_cd
,rst_bed_name
,rst_machine_no
,rst_machine_name
,rst_cond_send_date
,rst_accept_date
,rst_start_date
,rst_end_date
,rst_return_home_date
,rst_in_out_class
,rst_dialysis_cnt
,rst_ward_cd
,rst_ward_name
,rst_course_cd
,rst_course_name
,rst_puncture_user_info
,rst_return_user_info
,rst_charge_user_info
,rst_blood_circulate_total
,rst_running_time
,rst_kt_v
,rec_set_date
,send_ctl_no
,blood_purifier_name
,pull_leave_amount
,rst_cond_info
,rst_medi_info
,rst_equip_info
,rst_ind_comment_info
,rst_tare_info
,rst_off_water_info
,rst_weight_info
--   add 10196 by kangjie 20240130 start del
-- ,rst_vital_info
--   add 10196 by kangjie 20240130 end del
,rst_complaint_info
,rst_treatment_info
,rst_treat_staff_info
,rst_rounds_info
,is_del
,up_date
,reg_date
,ind_device_set_info
--   add 10196 by kangjie 20240130 start del
-- ,rst_device_set_info
--   add 10196 by kangjie 20240130 end del
,treat_type
,rst_purification_cnt
,up_ind_user_id
,up_user_id
,rst_dw
,weight_scale_no
,fn_plural
,is_confirm
,ind_dw
,addition_info
,bvms_path
--   add 11467 【たくしん会】H12条件送信ができない。患者経過総合ビューアのDW表示が不正。 関 start
,ind_dw_user_info
,ind_device_mode
,rst_device_mode
--   add 11467 【たくしん会】H12条件送信ができない。患者経過総合ビューアのDW表示が不正。 関 end
)
values
(
  /*ordMainRestore.ordNo*/'1',
  /*ordMainRestore.delDate*/null,
  /*ordMainRestore.patId*/'1',
  /*ordMainRestore.fnPatId*/null,
  /*ordMainRestore.treatDate*/null,
  /*ordMainRestore.treatWeek*/null,
  /*ordMainRestore.facilityCd*/null,
  /*ordMainRestore.facilityName*/null,
  /*ordMainRestore.indVaCd*/null,
  /*ordMainRestore.indTreatmentCd*/null,
  /*ordMainRestore.indTreatmentName*/null,
  /*ordMainRestore.indKurCd*/null,
  /*ordMainRestore.indKurName*/null,
  /*ordMainRestore.indTreatStartTime*/null,
  /*ordMainRestore.indBedCd*/null,
  /*ordMainRestore.indBedName*/null,
  /*ordMainRestore.indScheduleUserInfo*/null,
  /*ordMainRestore.indCondInfo*/null,
  /*ordMainRestore.indMediInfo*/null,
  /*ordMainRestore.indEquipInfo*/null,
  /*ordMainRestore.indIndCommentInfo*/null,
  /*ordMainRestore.indTareInfo*/null,
  /*ordMainRestore.indOffWaterInfo*/null,
  /*ordMainRestore.rstFnDialysisNo*/null,
  /*ordMainRestore.rstRelationDialysisNo*/null,
  /*ordMainRestore.rstEdition*/'0',
  /*ordMainRestore.rstIsUpdateEdition*/null,
  /*ordMainRestore.rstInputClass*/null,
  /*ordMainRestore.rstDialysisState*/'0',
  /*ordMainRestore.rstTreatmentCd*/null,
  /*ordMainRestore.rstTreatmentName*/null,
  /*ordMainRestore.rstKurCd*/null,
  /*ordMainRestore.rstKurName*/null,
  /*ordMainRestore.rstBedCd*/null,
  /*ordMainRestore.rstBedName*/null,
  /*ordMainRestore.rstMachineNo*/null,
  /*ordMainRestore.rstMachineName*/null,
  /*ordMainRestore.rstCondSendDate*/null,
  /*ordMainRestore.rstAcceptDate*/null,
  /*ordMainRestore.rstStartDate*/null,
  /*ordMainRestore.rstEndDate*/null,
  /*ordMainRestore.rstReturnHomeDate*/null,
  /*ordMainRestore.rstInOutClass*/null,
  /*ordMainRestore.rstDialysisCnt*/null,
  /*ordMainRestore.rstWardCd*/null,
  /*ordMainRestore.rstWardName*/null,
  /*ordMainRestore.rstCourseCd*/null,
  /*ordMainRestore.rstCourseName*/null,
  /*ordMainRestore.rstPunctureUserInfo*/null,
  /*ordMainRestore.rstReturnUserInfo*/null,
  /*ordMainRestore.rstChargeUserInfo*/null,
  /*ordMainRestore.rstBloodCirculateTotal*/null,
  /*ordMainRestore.rstRunningTime*/null,
  /*ordMainRestore.rstKtV*/null,
  /*ordMainRestore.recSetDate*/null,
  /*ordMainRestore.sendCtlNo*/null,
  /*ordMainRestore.bloodPurifierName*/null,
  /*ordMainRestore.pullLeaveAmount*/null,
  /*ordMainRestore.rstCondInfo*/null,
  /*ordMainRestore.rstMediInfo*/null,
  /*ordMainRestore.rstEquipInfo*/null,
  /*ordMainRestore.rstIndCommentInfo*/null,
  /*ordMainRestore.rstTareInfo*/null,
  /*ordMainRestore.rstOffWaterInfo*/null,
  /*ordMainRestore.rstWeightInfo*/null,
--   add 10196 by kangjie 20240130 start del
--   /*ordMainRestore.rstVitalInfo*/null,
--   add 10196 by kangjie 20240130 end del
  /*ordMainRestore.rstComplaintInfo*/null,
  /*ordMainRestore.rstTreatmentInfo*/null,
  /*ordMainRestore.rstTreatStaffInfo*/null,
  /*ordMainRestore.rstRoundsInfo*/null,
  /*ordMainRestore.isDel*/'0',
  /*ordMainRestore.upDate*/null,
  /*ordMainRestore.regDate*/null,
  /*ordMainRestore.indDeviceSetInfo*/null,
--   add 10196 by kangjie 20240130 start del
--   /*ordMainRestore.rstDeviceSetInfo*/null,
--   add 10196 by kangjie 20240130 end del
  /*ordMainRestore.treatType*/null,
  /*ordMainRestore.rstPurificationCnt*/null,
  /*ordMainRestore.upIndUserId*/null,
  /*ordMainRestore.upUserId*/null,
  /*ordMainRestore.rstDw*/null,
  /*ordMainRestore.weightScaleNo*/null,
  /*ordMainRestore.fnPlural*/null,
  /*ordMainRestore.isConfirm*/null,
  /*ordMainRestore.indDw*/null,
  /*ordMainRestore.additionInfo*/null,
  /*ordMainRestore.bvmsPath*/null
  --   add 11467 【たくしん会】H12条件送信ができない。患者経過総合ビューアのDW表示が不正。 関 start
  ,/*ordMainRestore.indDwUserInfo*/null
  ,/*ordMainRestore.indDeviceMode*/null
  ,/*ordMainRestore.rstDeviceMode*/null
--   add 11467 【たくしん会】H12条件送信ができない。患者経過総合ビューアのDW表示が不正。 関 end
)
;
