TRUNCATE TABLE mst_personal_user;

INSERT INTO mst_personal_user (user_id, facility_cd, user_type, administrator, user_last_name, user_first_name, user_last_name_kana, user_first_name_kana, user_last_name_alpha, user_first_name_alpha, user_email_address_1, user_email_address_2, extension_no, home_no, mobile_phone_no, fax_no, zipcd_3, zipcd_4, address, address_kana, job_cd, reg_date, up_date) VALUES
  (900000000001, '900001', '0', '0', 
  personal_info_encrypt('lastName'), 
  personal_info_encrypt('firstName'), 
  personal_info_encrypt('lastNameKana'), 
  personal_info_encrypt('firstNameKana'), 
  personal_info_encrypt('lastNameAlpha'), 
  personal_info_encrypt('firstNameAlpha'),
  personal_info_encrypt('emailAddress1@abc.jp'), 
  personal_info_encrypt('emailAddress2@xxx.org'), 
  personal_info_encrypt('extensionNo'), 
  personal_info_encrypt('homeNo'), 
  personal_info_encrypt('mobilePhoneNo'), 
  personal_info_encrypt('faxNo'), 
  personal_info_encrypt('001'), 
  personal_info_encrypt('0001'), 
  personal_info_encrypt('address'), 
  personal_info_encrypt('addressKana'),
  personal_info_encrypt('01'), 
   '2018-05-25 17:16:55', 
   '2018-08-22 17:19:19.405'),
  (900000000002, '900001', '0', '0', 
  personal_info_encrypt('lastName'), 
  personal_info_encrypt('firstName'), 
  personal_info_encrypt('lastNameKana'), 
  personal_info_encrypt('firstNameKana'), 
  personal_info_encrypt('lastNameAlpha'), 
  personal_info_encrypt('firstNameAlpha'), 
  personal_info_encrypt('emailAddress1@abc.jp'), 
  personal_info_encrypt('emailAddress2@xxx.org'), 
  personal_info_encrypt('extensionNo'), 
  personal_info_encrypt('homeNo'), 
  personal_info_encrypt('mobilePhoneNo'), 
  personal_info_encrypt('faxNo'), 
  personal_info_encrypt('001'), 
  personal_info_encrypt('0001'), 
  personal_info_encrypt('address'), 
  personal_info_encrypt('addressKana'), 
  personal_info_encrypt('01'),  
  '2018-05-25 17:16:55', 
  '2018-08-22 17:19:19.405'),
  (900000000003, '900001', '0', '0', 
  personal_info_encrypt('lastName'), 
  personal_info_encrypt('firstName'), 
  personal_info_encrypt('lastNameKana'), 
  personal_info_encrypt('firstNameKana'), 
  personal_info_encrypt('lastNameAlpha'), 
  personal_info_encrypt('firstNameAlpha'), 
  personal_info_encrypt('emailAddress1@abc.jp'), 
  personal_info_encrypt('emailAddress2@xxx.org'), 
  personal_info_encrypt('extensionNo'), 
  personal_info_encrypt('homeNo'), 
  personal_info_encrypt('mobilePhoneNo'), 
  personal_info_encrypt('faxNo'), 
  personal_info_encrypt('001'), 
  personal_info_encrypt('0001'), 
  personal_info_encrypt('address'), 
  personal_info_encrypt('addressKana'), 
  personal_info_encrypt('01'),  
  '2018-05-25 17:16:55', 
  '2018-08-22 17:19:19.405'),
  (900000000004, '900001', '0', '0', 
  personal_info_encrypt('lastName'), 
  personal_info_encrypt('firstName'), 
  personal_info_encrypt('lastNameKana'), 
  personal_info_encrypt('firstNameKana'), 
  personal_info_encrypt('lastNameAlpha'), 
  personal_info_encrypt('firstNameAlpha'), 
  personal_info_encrypt('emailAddress1@abc.jp'), 
  personal_info_encrypt('emailAddress2@xxx.org'), 
  personal_info_encrypt('extensionNo'), 
  personal_info_encrypt('homeNo'), 
  personal_info_encrypt('mobilePhoneNo'), 
  personal_info_encrypt('faxNo'), 
  personal_info_encrypt('001'), 
  personal_info_encrypt('0001'), 
  personal_info_encrypt('address'), 
  personal_info_encrypt('addressKana'), 
  personal_info_encrypt('01'),  
  '2018-05-25 17:16:55', 
  '2018-08-22 17:19:19.405');

INSERT INTO mst_personal_user (user_id, facility_cd, user_type, administrator, user_last_name, user_first_name, user_last_name_kana, user_first_name_kana, user_last_name_alpha, user_first_name_alpha, user_email_address_1, user_email_address_2, extension_no, home_no, mobile_phone_no, fax_no, zipcd_3, zipcd_4, address, address_kana, job_cd, reg_date, up_date)
VALUES
(1, '900001', 0, 0,
 personal_info_encrypt('lastName'),
 personal_info_encrypt('firstName'),
 personal_info_encrypt('lastNameKana'),
 personal_info_encrypt('firstNameKana'),
 personal_info_encrypt('lastNameAlpha'),
 personal_info_encrypt('firstNameAlpha'),
 personal_info_encrypt('emailAddress1@abc.jp'),
 personal_info_encrypt('emailAddress2@xxx.org'),
 personal_info_encrypt('extensionNo'),
 personal_info_encrypt('homeNo'),
 personal_info_encrypt('mobilePhoneNo'),
 personal_info_encrypt('faxNo'),
 personal_info_encrypt('001'),
 personal_info_encrypt('0001'),
 personal_info_encrypt('address'),
 personal_info_encrypt('addressKana'),
 personal_info_encrypt('01'),
 '2018-05-25 17:16:55', '2018-08-22 17:19:19.405'),
(2, '900001', 1, 0,
 personal_info_encrypt('lastName2'),
 personal_info_encrypt('firstName2'),
 personal_info_encrypt('lastNameKana2'),
 personal_info_encrypt('firstNameKana2'),
 personal_info_encrypt('lastNameAlpha2'),
 personal_info_encrypt('firstNameAlpha2'),
 personal_info_encrypt('emailAddress1@abc2.jp'),
 personal_info_encrypt('emailAddress2@xxx2.org'),
 personal_info_encrypt('extensionNo2'),
 personal_info_encrypt('homeNo2'),
 personal_info_encrypt('mobilePhoneNo2'),
 personal_info_encrypt('faxNo2'),
 personal_info_encrypt('0012'),
 personal_info_encrypt('00012'),
 personal_info_encrypt('address2'),
 personal_info_encrypt('addressKana2'),
 personal_info_encrypt('02'),
 '2018-05-26 17:16:55', '2018-08-23 17:19:19.405'),
(3, '900001', 1, 0,
 personal_info_encrypt('lastName3'),
 personal_info_encrypt('firstName3'),
 personal_info_encrypt('lastNameKana3'),
 personal_info_encrypt('firstNameKana3'),
 personal_info_encrypt('lastNameAlpha3'),
 personal_info_encrypt('firstNameAlpha3'),
 personal_info_encrypt('emailAddress1@abc3.jp'),
 personal_info_encrypt('emailAddress2@xxx3.org'),
 personal_info_encrypt('extensionNo3'),
 personal_info_encrypt('homeNo3'),
 personal_info_encrypt('mobilePhoneNo3'),
 personal_info_encrypt('faxNo3'),
 personal_info_encrypt('0013'),
 personal_info_encrypt('00013'),
 personal_info_encrypt('address3'),
 personal_info_encrypt('addressKana3'),
 personal_info_encrypt('03'),
 '2018-05-26 17:16:55', '2018-08-23 17:19:19.405')
;

-- editUserAccountInfo
INSERT INTO mst_personal_user (user_id, facility_cd, user_type, administrator, user_last_name, user_first_name, user_last_name_kana, user_first_name_kana, user_last_name_alpha, user_first_name_alpha, user_email_address_1, user_email_address_2, extension_no, home_no, mobile_phone_no, fax_no, zipcd_3, zipcd_4, address, address_kana, job_cd, reg_date, up_date)
VALUES
(999900000001, '999001', 0, 0,
 personal_info_encrypt('lastName'),
 personal_info_encrypt('firstName'),
 personal_info_encrypt('lastNameKana'),
 personal_info_encrypt('firstNameKana'),
 personal_info_encrypt('lastNameAlpha'),
 personal_info_encrypt('firstNameAlpha'),
 personal_info_encrypt('emailAddress1@abc.jp'),
 personal_info_encrypt('emailAddress2@xxx.org'),
 personal_info_encrypt('extensionNo'),
 personal_info_encrypt('homeNo'),
 personal_info_encrypt('mobilePhoneNo'),
 personal_info_encrypt('faxNo'),
 personal_info_encrypt('001'),
 personal_info_encrypt('0001'),
 personal_info_encrypt('address'),
 personal_info_encrypt('addressKana'),
 personal_info_encrypt('01'),
 '2018-05-25 17:16:55', '2018-08-22 17:19:19.405'),
(999900000003, '999003', 1, 0,
 personal_info_encrypt('lastName3'),
 personal_info_encrypt('firstName3'),
 personal_info_encrypt('lastNameKana3'),
 personal_info_encrypt('firstNameKana3'),
 personal_info_encrypt('lastNameAlpha3'),
 personal_info_encrypt('firstNameAlpha3'),
 personal_info_encrypt('emailAddress1@abc3.jp'),
 personal_info_encrypt('emailAddress2@xxx3.org'),
 personal_info_encrypt('extensionNo3'),
 personal_info_encrypt('homeNo3'),
 personal_info_encrypt('mobilePhoneNo3'),
 personal_info_encrypt('faxNo3'),
 personal_info_encrypt('0013'),
 personal_info_encrypt('00013'),
 personal_info_encrypt('address3'),
 personal_info_encrypt('addressKana3'),
 personal_info_encrypt('03'),
 '2018-05-26 17:16:55', '2018-08-23 17:19:19.405')
;
