import org.gradle.internal.os.OperatingSystem

buildscript {
  repositories {
//    jcenter()
    mavenLocal()
    mavenCentral()
    maven { url "https://start.spring.io/plugins-release" }
    maven { url "https://start.spring.io/milestone" }
    maven { url "https://plugins.gradle.org/m2/" }
  }
  dependencies {
    classpath "org.springframework.boot:spring-boot-gradle-plugin:${spring_boot_version}"
//    classpath 'io.spring.gradle:propdeps-plugin:0.0.10.RELEASE'
    classpath "io.spring.gradle:dependency-management-plugin:1.0.7.RELEASE"
  }
}

apply plugin: 'maven-publish'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
//apply plugin: 'propdeps'
//apply plugin: 'propdeps-eclipse'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'idea'
defaultTasks 'bootRun'

bootWar {
  mainClass = 'jp.co.nikkiso.ntss.device_edge_updater.NtssDeviceEdgeUpdaterApplication'
}

war {
  enabled = true
  archiveBaseName = 'device_edge_updater'
}

springBoot {
  mainClass = 'jp.co.nikkiso.ntss.device_edge_updater.NtssDeviceEdgeUpdaterApplication'
  buildInfo()
}

if (OperatingSystem.current().isWindows()) {
  task pathingJar(type: Jar) {
    dependsOn configurations.runtimeClasspath
    archiveAppendix = 'pathing'

    doFirst {
      manifest {
        attributes 'Class-Path': configurations.runtimeClasspath.getFiles().collect {
          it.toURI().toString().replaceFirst(/file:\/+/, '/').replaceAll(' ', '%20')
        }.join(' ')
      }
    }
  }

  bootRun {
    dependsOn pathingJar
    doFirst {
      classpath = files("$buildDir/classes/java/main", "$buildDir/resources/main", pathingJar.archiveFile)
    }
  }
} else {
  bootRun {
    jvmArgs = ["-Dspring.output.ansi.enabled=ALWAYS"]
  }
}

jacoco {
  toolVersion = "0.8.8"
}

jacocoTestReport {
  reports {
      xml.enabled false
      csv.enabled false
  }
}

apply from: 'gradle/eclipse.gradle'
apply from: 'gradle/docker.gradle'
//jhipster-needle-gradle-apply-from - JHipster will add additional gradle scripts to be applied here

//if (project.hasProperty('prod')) {
//  apply from: 'gradle/profile_prod.gradle'
//} else {
//  apply from: 'gradle/profile_dev.gradle'
//}

description = ''

repositories {
  mavenLocal()
  mavenCentral()
//  jcenter()
  maven { url 'https://start.spring.io/milestone' }
  maven { url 'https://start.spring.io/snapshot' }
  maven { url 'https://repository.jboss.org/nexus/content/repositories/releases' }
  maven { url 'https://oss.sonatype.org/content/repositories/releases' }
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
  maven { url 'https://repo.maven.apache.org/maven2' }
}

dependencies {
  implementation "org.springframework.boot:spring-boot-autoconfigure"
  implementation "org.springframework.boot:spring-boot-starter-web"
  providedRuntime "org.springframework.boot:spring-boot-starter-tomcat"
  implementation "org.springframework.boot:spring-boot-starter-jdbc"
  implementation "org.springframework.boot:spring-boot-starter-actuator"
  implementation 'org.projectlombok:lombok:1.18.28'
  annotationProcessor 'org.projectlombok:lombok:1.18.28'
  testImplementation ("org.springframework.boot:spring-boot-starter-test") {
    exclude group: 'com.vaadin.external.google', module: 'android-json'
  }
  testImplementation "org.springframework.boot:spring-boot-test"
  testImplementation "junit:junit"
  testImplementation "org.mockito:mockito-core"
  annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
  implementation "org.json:json:20180813"
//  implementation 'org.mongodb:mongo-java-driver:3.10.1'
  implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
  testCompileOnly 'org.projectlombok:lombok:1.18.28'
  testAnnotationProcessor 'org.projectlombok:lombok:1.18.28'
  implementation "org.springframework.boot:spring-boot-starter-aop"
  implementation "org.seasar.doma.boot:doma-spring-boot-starter:${doma_spring_version}"
  implementation "org.seasar.doma:doma:2.24.0"
  annotationProcessor "org.seasar.doma:doma:2.24.0"
}

clean { delete "target" }

task cleanResources(type: Delete) { delete 'build/resources' }

task wrapper(type: Wrapper) { gradleVersion = '7.2' }

task stage(dependsOn: 'bootWar') {
}

// Doma2のSQLファイルをJavaのコンパイル前にコピーしておく
// SQLファイルが存在するかしないとJavaのコンパイル時にSQLファイルが存在するかのチェックでエラーになるため。
processResources.destinationDir = compileJava.destinationDir
compileJava.dependsOn processResources

processResources.dependsOn cleanResources,bootBuildInfo
bootBuildInfo.mustRunAfter cleanResources
