-- テーブル削除
DROP TABLE IF EXISTS mst_treatment_status_disp_item;
-- テーブル作成
CREATE TABLE mst_treatment_status_disp_item
(
    item_cd integer NOT NULL,  --レイアウト表示項目番号
    data_class character varying(1) NOT NULL DEFAULT '0',  --データ取得種別
    machine_class character varying(1) NOT NULL DEFAULT '0',  --装置種別
    item_name character varying NOT NULL,  --項目名
    table_name character varying,  --参照先テーブル名
    field_name character varying,  --参照先フィールド名
    json_key_name character varying,  --参照先JSONキー名
    disp_order integer DEFAULT 0,  --表示順
    is_disp character varying(1) DEFAULT '1',  --表示フラグ
    is_del character varying(1) DEFAULT '0',  --削除フラグ
    reg_date timestamp(3),  --登録日時
    up_date timestamp(3),  --更新日時

    CONSTRAINT unq_mst_treatment_status_disp_item_01 PRIMARY KEY (item_cd)
)
WITH (
    OIDS=FALSE
);
-- コメント追加
COMMENT ON TABLE "mst_treatment_status_disp_item" IS E'治療状況レイアウト表示項目マスタ';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."item_cd" IS E'レイアウト表示項目番号';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."data_class" IS E'データ取得種別';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."machine_class" IS E'装置種別';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."item_name" IS E'項目名';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."table_name" IS E'参照先テーブル名';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."field_name" IS E'参照先フィールド名';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."json_key_name" IS E'参照先JSONキー名';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."disp_order" IS E'表示順';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."is_disp" IS E'表示フラグ';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."is_del" IS E'削除フラグ';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."reg_date" IS E'登録日時';
COMMENT ON COLUMN "mst_treatment_status_disp_item"."up_date" IS E'更新日時';

--データ登録
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (1, '0', '0', 'ord_no', 'ord_main', 'ord_no', null, 0, '0', '1', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (2, '0', '0', '患者ID', 'ord_main', 'pat_id', null, 0, '0', '1', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (3, '0', '0', '状態', 'mnt_machine_state', 'process_state', null, 0, '0', '1', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (4, '0', '0', 'DW', 'pat_unique', 'physical_info', 'dw', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (5, '1', '0', 'DWから', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (6, '0', '0', '目標体重', 'ord_main', 'rst_weight_info', 'water_removal_target', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (7, '1', '0', '目標体重から', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (8, '1', '0', '透析開始', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (9, '1', '0', '終了予測', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (10, '1', '0', '終了予測(除水完了)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (11, '1', '0', '終了予測(透析終了)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (12, '0', '0', '透析終了', 'ord_main', 'rst_end_date', null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (13, '0', '0', '透析時間', 'ord_main', 'ind_cond_info', '1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (14, '0', '0', '残り時間', 'mni_monitor', 'monitor_data', '4', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (15, '1', '0', '遅れ時間', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (16, '0', '0', '前体重', 'ord_main', 'rst_weight_info', 'weight_before', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (17, '1', '0', '前血圧(最高)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (18, '1', '0', '前血圧(最低)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (19, '1', '0', '前血圧(平均)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (20, '1', '0', '前血圧', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (21, '1', '0', '前脈拍', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (22, '0', '0', '現在血圧', 'mni_monitor', 'monitor_data', null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (23, '0', '0', '担当者1', 'ord_main', 'rst_charge_user_info', 'user_id_1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (24, '0', '0', '担当1日時', 'ord_main', 'rst_charge_user_info', 'date_1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (25, '0', '0', '担当者2', 'ord_main', 'rst_charge_user_info', 'user_id_2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (26, '0', '0', '担当2日時', 'ord_main', 'rst_charge_user_info', 'date_2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (27, '0', '0', '穿刺日時', 'ord_main', 'rst_puncture_user_info', 'date', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (28, '0', '0', '穿刺者1', 'ord_main', 'rst_puncture_user_info', 'user_id_1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (29, '0', '0', '穿刺1日時', 'ord_main', 'rst_puncture_user_info', 'date_1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (30, '0', '0', '穿刺者2', 'ord_main', 'rst_puncture_user_info', 'user_id_2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (31, '0', '0', '穿刺2日時', 'ord_main', 'rst_puncture_user_info', 'date_2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (32, '0', '0', '返血日時', 'ord_main', 'rst_return_user_info', 'date', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (33, '0', '0', '返血者1', 'ord_main', 'rst_return_user_info', 'user_id_1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (34, '0', '0', '返血1日時', 'ord_main', 'rst_return_user_info', 'date_1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (35, '0', '0', '返血者2', 'ord_main', 'rst_return_user_info', 'user_id_2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (36, '0', '0', '返血2日時', 'ord_main', 'rst_return_user_info', 'date_2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (37, '0', '0', '後体重', 'ord_main', 'rst_weight_info', 'weight_after', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (38, '1', '0', '前体重-後体重', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (39, '1', '0', '予想引き残し', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (40, '1', '0', '引き残し', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (41, '1', '0', '後血圧(最高)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (42, '1', '0', '後血圧(最低)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (43, '1', '0', '後血圧(平均)', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (44, '1', '0', '後血圧', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (45, '1', '0', '後脈拍', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (46, '0', '0', '除水目標', 'ord_main', 'rst_weight_info', 'water_removal_target', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (47, '0', '0', '除水速度', 'mni_monitor', 'monitor_data', '6', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (48, '0', '0', '除水量現在値', 'mni_monitor', 'monitor_data', '5', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (49, '1', '0', '達成率', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (50, '1', '0', '確認', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (51, '0', '0', '前体重測定時刻', 'ord_main', 'rst_weight_info', 'weight_before_date', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (52, '1', '0', '終了予定', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (53, '1', '0', '前回後体重', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (54, '1', '0', '増加量', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (55, '1', '0', '増加率', null, null, null, 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (56, '0', '0', '血流量', 'mni_monitor', 'monitor_data', '8', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (57, '0', '0', 'IP速度', 'mni_monitor', 'monitor_data', '10', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (58, '0', '1', '工程', 'mni_monitor', 'monitor_data', '1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (59, '0', '1', '貯槽濃度', 'mni_monitor', 'monitor_data', '2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (60, '0', '1', '透析液濃度', 'mni_monitor', 'monitor_data', '3', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (61, '0', '1', 'Ｂ液濃度', 'mni_monitor', 'monitor_data', '4', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (62, '0', '1', '予備', 'mni_monitor', 'monitor_data', '5', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (63, '0', '1', 'Ｂ原液濃度', 'mni_monitor', 'monitor_data', '6', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (64, '0', '1', 'Ａ原液濃度', 'mni_monitor', 'monitor_data', '7', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (65, '0', '1', '貯槽液温度', 'mni_monitor', 'monitor_data', '8', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (66, '0', '1', '給水流量（水計量シリンダー）', 'mni_monitor', 'monitor_data', '9', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (67, '0', '1', '給水流量（渦流量計）', 'mni_monitor', 'monitor_data', '10', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (68, '0', '1', '給水圧', 'mni_monitor', 'monitor_data', '11', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (69, '0', '1', '送液圧', 'mni_monitor', 'monitor_data', '12', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (70, '0', '1', '予備', 'mni_monitor', 'monitor_data', '13', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (71, '0', '1', '給水流量(FM1)', 'mni_monitor', 'monitor_data', '14', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (72, '0', '1', '給水流量(FM2)', 'mni_monitor', 'monitor_data', '15', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (73, '0', '1', '予備', 'mni_monitor', 'monitor_data', '16', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (74, '0', '1', '予備', 'mni_monitor', 'monitor_data', '17', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (75, '0', '1', '予備', 'mni_monitor', 'monitor_data', '18', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (76, '0', '1', '予備', 'mni_monitor', 'monitor_data', '19', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (77, '0', '1', '予備', 'mni_monitor', 'monitor_data', '20', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (78, '0', '1', 'Ｂ液濃度警報点（上限）', 'mni_monitor', 'monitor_data', '21', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (79, '0', '1', 'Ｂ液濃度警報点（下限）', 'mni_monitor', 'monitor_data', '22', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (80, '0', '1', '透析液濃度警報点（上限）', 'mni_monitor', 'monitor_data', '23', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (81, '0', '1', '透析液濃度警報点（下限）', 'mni_monitor', 'monitor_data', '24', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (82, '0', '1', '貯槽濃度警報点（上限）', 'mni_monitor', 'monitor_data', '25', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (83, '0', '1', '貯槽濃度警報点（下限）', 'mni_monitor', 'monitor_data', '26', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (84, '0', '1', '予備', 'mni_monitor', 'monitor_data', '27', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (85, '0', '1', '予備', 'mni_monitor', 'monitor_data', '28', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (86, '0', '1', '透析液温度警報点（上限）', 'mni_monitor', 'monitor_data', '29', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (87, '0', '1', '透析液温度警報点（下限）', 'mni_monitor', 'monitor_data', '30', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (88, '0', '1', '給水圧警報点（下限）', 'mni_monitor', 'monitor_data', '31', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (89, '0', '1', '送液圧警報点（下限）', 'mni_monitor', 'monitor_data', '32', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (90, '0', '1', '予備', 'mni_monitor', 'monitor_data', '33', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (91, '0', '1', '予備', 'mni_monitor', 'monitor_data', '34', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (92, '0', '1', '予備', 'mni_monitor', 'monitor_data', '35', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (93, '0', '1', '予備', 'mni_monitor', 'monitor_data', '36', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (94, '0', '1', '予備', 'mni_monitor', 'monitor_data', '37', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (95, '0', '1', '予備', 'mni_monitor', 'monitor_data', '38', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (96, '0', '1', '予備', 'mni_monitor', 'monitor_data', '39', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (97, '0', '1', '予備', 'mni_monitor', 'monitor_data', '40', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (98, '0', '2', '工程', 'mni_monitor', 'monitor_data', '1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (99, '0', '2', 'B原液濃度', 'mni_monitor', 'monitor_data', '2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (100, '0', '2', 'A原液濃度', 'mni_monitor', 'monitor_data', '3', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (101, '0', '2', '給水圧', 'mni_monitor', 'monitor_data', '4', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (102, '0', '2', '薬液検知電圧', 'mni_monitor', 'monitor_data', '5', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (103, '0', '2', 'B溶解槽温度', 'mni_monitor', 'monitor_data', '6', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (104, '0', '2', 'A溶解槽温度', 'mni_monitor', 'monitor_data', '7', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (105, '0', '2', 'B貯水槽原液残量', 'mni_monitor', 'monitor_data', '8', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (106, '0', '2', 'A貯水槽原液残量', 'mni_monitor', 'monitor_data', '9', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (107, '0', '2', 'B原液濃度警報点（上限）', 'mni_monitor', 'monitor_data', '10', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (108, '0', '2', 'B原液濃度警報点（下限）', 'mni_monitor', 'monitor_data', '11', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (109, '0', '2', 'A原液濃度警報点（上限）', 'mni_monitor', 'monitor_data', '12', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (110, '0', '2', 'A原液濃度警報点（下限）', 'mni_monitor', 'monitor_data', '13', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (111, '0', '2', '給水圧警報点（下限）', 'mni_monitor', 'monitor_data', '14', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (112, '0', '2', '薬液消毒濃度下限報知点', 'mni_monitor', 'monitor_data', '15', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (113, '0', '2', '薬液消毒漏れ警報点', 'mni_monitor', 'monitor_data', '16', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (114, '0', '2', '貯水槽原液減少報知点１', 'mni_monitor', 'monitor_data', '17', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (115, '0', '2', '貯水槽原液減少報知点２', 'mni_monitor', 'monitor_data', '18', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (116, '0', '2', '貯水槽原液減少報知点３', 'mni_monitor', 'monitor_data', '19', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (117, '0', '2', 'B溶解槽温度警報（上限）', 'mni_monitor', 'monitor_data', '20', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (118, '0', '2', 'A溶解槽温度警報（上限）', 'mni_monitor', 'monitor_data', '21', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (119, '0', '2', '溶解ボトル使用数', 'mni_monitor', 'monitor_data', '22', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (120, '0', '2', '残り薬剤数', 'mni_monitor', 'monitor_data', '23', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (121, '0', '2', '原液減予想時刻', 'mni_monitor', 'monitor_data', '24', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (122, '0', '3', '運転状態', 'mni_monitor', 'monitor_data', '1', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (123, '0', '3', 'RO送水量', 'mni_monitor', 'monitor_data', '2', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (124, '0', '3', 'RO戻り水量', 'mni_monitor', 'monitor_data', '3', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (125, '0', '3', 'RO循環水量', 'mni_monitor', 'monitor_data', '4', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (126, '0', '3', 'RO排水量', 'mni_monitor', 'monitor_data', '5', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (127, '0', '3', 'RO排水戻り水量', 'mni_monitor', 'monitor_data', '6', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (128, '0', '3', 'LRO処理水量', 'mni_monitor', 'monitor_data', '7', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (129, '0', '3', 'LRO循環水量', 'mni_monitor', 'monitor_data', '8', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (130, '0', '3', 'LRO排水量', 'mni_monitor', 'monitor_data', '9', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (131, '0', '3', '原水温度', 'mni_monitor', 'monitor_data', '10', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (132, '0', '3', 'フィルタ入口温度', 'mni_monitor', 'monitor_data', '11', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (133, '0', '3', 'カーボン出口温度', 'mni_monitor', 'monitor_data', '12', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (134, '0', '3', 'LRO膜出口温度', 'mni_monitor', 'monitor_data', '13', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (135, '0', '3', 'RO膜出口温度', 'mni_monitor', 'monitor_data', '14', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (136, '0', '3', 'RO水タンク温度', 'mni_monitor', 'monitor_data', '15', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (137, '0', '3', '排水温度', 'mni_monitor', 'monitor_data', '16', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (138, '0', '3', '原水水質', 'mni_monitor', 'monitor_data', '17', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (139, '0', '3', 'LRO水質', 'mni_monitor', 'monitor_data', '18', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (140, '0', '3', 'RO水質', 'mni_monitor', 'monitor_data', '19', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (141, '0', '3', '原水ポンプインバータ', 'mni_monitor', 'monitor_data', '20', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (142, '0', '3', 'ＬＲＯポンプインバータ', 'mni_monitor', 'monitor_data', '21', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (143, '0', '3', 'ＲＯポンプインバータ', 'mni_monitor', 'monitor_data', '22', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (144, '0', '3', '送水ポンプ１インバータ', 'mni_monitor', 'monitor_data', '23', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (145, '0', '3', '送水ポンプ２インバータ', 'mni_monitor', 'monitor_data', '24', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (146, '0', '3', '10μフィルタ入口圧', 'mni_monitor', 'monitor_data', '25', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (147, '0', '3', 'カーボンフィルタ入口圧', 'mni_monitor', 'monitor_data', '26', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (148, '0', '3', 'LROポンプ入口圧', 'mni_monitor', 'monitor_data', '27', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (149, '0', '3', 'LRO膜入口圧', 'mni_monitor', 'monitor_data', '28', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (150, '0', '3', 'LRO膜出口圧', 'mni_monitor', 'monitor_data', '29', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (151, '0', '3', 'ROポンプ入口圧', 'mni_monitor', 'monitor_data', '30', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (152, '0', '3', 'RO膜入口圧', 'mni_monitor', 'monitor_data', '31', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (153, '0', '3', 'RO膜出口圧', 'mni_monitor', 'monitor_data', '32', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (154, '0', '3', '送水ポンプ1出口圧', 'mni_monitor', 'monitor_data', '33', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (155, '0', '3', '送水ポンプ2出口圧', 'mni_monitor', 'monitor_data', '34', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (156, '0', '3', 'RO処理水圧', 'mni_monitor', 'monitor_data', '35', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (157, '0', '3', 'RO回収率', 'mni_monitor', 'monitor_data', '36', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (158, '0', '3', 'RO送水MV開度', 'mni_monitor', 'monitor_data', '37', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (159, '0', '3', 'RO排水MV開度', 'mni_monitor', 'monitor_data', '38', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (160, '0', '3', '1系洗浄水量', 'mni_monitor', 'monitor_data', '39', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (161, '0', '3', '2系洗浄水量', 'mni_monitor', 'monitor_data', '40', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (162, '0', '3', '1系洗浄積算水量', 'mni_monitor', 'monitor_data', '41', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (163, '0', '3', '2系洗浄積算水量', 'mni_monitor', 'monitor_data', '42', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (164, '0', '3', 'ROタンク水位表示', 'mni_monitor', 'monitor_data', '43', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (165, '0', '3', 'NO.1RO処理水量', 'mni_monitor', 'monitor_data', '44', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (166, '0', '3', 'NO.1RO循環水量', 'mni_monitor', 'monitor_data', '45', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (167, '0', '3', 'NO.1RO排水量', 'mni_monitor', 'monitor_data', '46', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (168, '0', '3', 'NO.1RO排水戻り水量', 'mni_monitor', 'monitor_data', '47', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (169, '0', '3', 'NO.2RO処理水量', 'mni_monitor', 'monitor_data', '48', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (170, '0', '3', 'NO.2RO循環水量', 'mni_monitor', 'monitor_data', '49', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (171, '0', '3', 'NO.2RO排水量', 'mni_monitor', 'monitor_data', '50', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (172, '0', '3', 'NO.2RO排水戻り水量', 'mni_monitor', 'monitor_data', '51', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (173, '0', '3', '軟水タンク温度', 'mni_monitor', 'monitor_data', '52', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (174, '0', '3', 'NO.1RO膜出口温度', 'mni_monitor', 'monitor_data', '53', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (175, '0', '3', 'NO.2RO膜出口温度', 'mni_monitor', 'monitor_data', '54', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (176, '0', '3', 'RO原水水質', 'mni_monitor', 'monitor_data', '55', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (177, '0', '3', 'NO.1RO水質', 'mni_monitor', 'monitor_data', '56', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (178, '0', '3', 'NO.2RO水質', 'mni_monitor', 'monitor_data', '57', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (179, '0', '3', '軟水加圧ポンプインバータ', 'mni_monitor', 'monitor_data', '58', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (180, '0', '3', 'NO.1ROポンプインバータ', 'mni_monitor', 'monitor_data', '59', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (181, '0', '3', 'NO.2ROポンプインバータ', 'mni_monitor', 'monitor_data', '60', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (182, '0', '3', 'NO.1ROポンプ入口圧', 'mni_monitor', 'monitor_data', '61', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (183, '0', '3', 'NO.1RO膜入口圧', 'mni_monitor', 'monitor_data', '62', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (184, '0', '3', 'NO.1RO膜出口圧', 'mni_monitor', 'monitor_data', '63', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (185, '0', '3', 'NO.2ROポンプ入口圧', 'mni_monitor', 'monitor_data', '64', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (186, '0', '3', 'NO.2RO膜入口圧', 'mni_monitor', 'monitor_data', '65', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (187, '0', '3', 'NO.2RO膜出口圧', 'mni_monitor', 'monitor_data', '66', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (188, '0', '3', '原水圧', 'mni_monitor', 'monitor_data', '67', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (189, '0', '3', '原水減圧弁出口圧', 'mni_monitor', 'monitor_data', '68', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (190, '0', '3', '軟水機入口圧', 'mni_monitor', 'monitor_data', '69', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (191, '0', '3', '軟水機出口圧', 'mni_monitor', 'monitor_data', '70', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (192, '0', '3', '減圧弁出口圧', 'mni_monitor', 'monitor_data', '71', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (193, '0', '3', '給湯圧', 'mni_monitor', 'monitor_data', '72', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (194, '0', '3', '給湯減圧弁出口圧', 'mni_monitor', 'monitor_data', '73', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (195, '0', '3', '混合弁出口圧', 'mni_monitor', 'monitor_data', '74', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (196, '0', '3', '原水流量', 'mni_monitor', 'monitor_data', '75', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (197, '0', '3', '洗浄排水量', 'mni_monitor', 'monitor_data', '76', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (198, '0', '3', 'ｼｽﾃﾑ回収率', 'mni_monitor', 'monitor_data', '77', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (199, '0', '3', 'NO.1RO回収率', 'mni_monitor', 'monitor_data', '78', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (200, '0', '3', 'NO.2RO回収率', 'mni_monitor', 'monitor_data', '79', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (201, '0', '3', 'RO阻止率', 'mni_monitor', 'monitor_data', '80', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (202, '0', '3', 'NO.1RO排水戻りMV開度', 'mni_monitor', 'monitor_data', '81', 0, '1', '0', current_timestamp, current_timestamp);
insert into mst_treatment_status_disp_item (item_cd, data_class, machine_class, item_name, table_name, field_name, json_key_name, disp_order, is_disp, is_del, reg_date, up_date) values (203, '0', '3', 'NO.2RO排水戻りMV開度', 'mni_monitor', 'monitor_data', '82', 0, '1', '0', current_timestamp, current_timestamp);
