DELETE FROM ntss.mst_coop_layout
WHERE ctl_no IN (-11035001);

INSERT INTO mst_coop_layout
(ctl_no, facility_cd, coop_cd, coop_cd_index, direction, coop_cd_sub, coop_format, coop_name, coop_vender, description, is_editable, coop_setting, coop_ext_setting, is_disp, is_del, user_id, reg_date, up_date, coop_version)
VALUES(-11035001, 'Secom', 'profile', 'detail', 'R', 'all', 'text', 'セコム連携', 'Secom', '患者プロファイル', '1', '<root name="患者プロファイル(pre)">
  <item name="CRUD" len="0" col="$journal.const.crud" type="string" value="const:C"/>
  <item name="電文種別" len="2" type="string" col="$journal.pat_personal_main.message_type"/>
  <item name="電文長" len="6" type="string" col="$journal.pat_personal_main.total_byte"/>
  <item name="病院ID" len="6" type="string"/>
  <item name="患者ID" len="12" type="string" col="$journal.pat_personal_main.hosp_pat_id"/>
  <occ name="患者プロファイル" len="2" detail="患者プロファイル詳細"/>
</root>
', '{"dataset": {"sqlGroup1": [{"No1": "電文長チェック", "crud": "S", "kind": "0", "judge": "", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": -1101506, "@totalByte": "$journal.pat_personal_main.total_byte", "ExceptionMessage": "[セコム連携-患者プロファイル連携][エラー]電文に設定された電文長が異常です。", "ExceptionCondition": "=0"}], "sqlGroup2": [{"No1": "患者存在チェック", "crud": "S", "kind": "0", "judge": "", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": 1101, "@hospPatId": "$journal.pat_personal_main.hosp_pat_id", "ExceptionMessage": "[セコム連携-患者プロファイル連携][エラー]取込み対象患者が存在しません。", "ExceptionCondition": "=0"}], "sqlGroup3": [{"No1": "電文種別チェック", "crud": "S", "kind": "0", "judge": "", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": -1101501, "@messageType": "$journal.pat_personal_main.message_type", "ExceptionMessage": "[セコム連携-患者プロファイル連携][エラー]電文種別の設定値が異常です。", "ExceptionCondition": "=0"}], "sqlGroup4": [{"No1": "患者存在チェック", "crud": "S", "kind": "0", "judge": "", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": 1101, "@hospPatId": "$journal.pat_personal_main.hosp_pat_id", "ExceptionMessage": "患者[@hospPatId]の個人情報に複数のデータが存在する。", "ExceptionCondition": "=N"}, {"No1": "血液型更新", "crud": "U", "kind": "1", "judge": "$journal.detail.pat_main.profile_code#=#00001", "table": "pat_main", "ctl_no": "1", "sqlCode": -1101502, "@content": "$journal.detail.pat_main.content"}], "sqlGroup5": [{"No1": "患者存在チェック", "crud": "S", "kind": "0", "judge": "", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": 1101, "@hospPatId": "$journal.pat_personal_main.hosp_pat_id", "ExceptionMessage": "患者[@hospPatId]の個人情報に複数のデータが存在する。", "ExceptionCondition": "=N"}, {"No1": "身長更新", "crud": "U", "kind": "1", "judge": "$journal.detail.pat_main.profile_code#=#00002", "table": "pat_main", "ctl_no": "1", "sqlCode": -1101504, "@content": "$journal.detail.pat_main.content"}], "sqlGroup6": [{"No1": "患者存在チェック", "crud": "S", "kind": "0", "judge": "", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": 1101, "@hospPatId": "$journal.pat_personal_main.hosp_pat_id", "ExceptionMessage": "患者[@hospPatId]の個人情報に複数のデータが存在する。", "ExceptionCondition": "=N"}, {"No1": "感染症更新", "crud": "U", "kind": "1", "judge": "$journal.detail.pat_main.profile_code#=#00045", "table": "pat_main", "ctl_no": "1", "sqlCode": -1101505, "@content": "$journal.detail.pat_main.content"}]}}'::jsonb, '1', '0', -1, '2025-05-27 13:22:19.970', CURRENT_TIMESTAMP, 'Secom');