--DELETE from ntss.mst_coop_layout where ctl_no in (-4100003,-4100002,-4100001,-2100002,-2100001,-1100002,-1100001);
--INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-4100003, 'P_hosp', 'exam_ord', '', 'S', 'del', 'text', 'Medicom検査オーダ', 'Medicom', '検査オーダ', '1', '<root name="検査依頼">
--    <item  name="レコード区分" len="2" value="const:O1"/>
--    <item  name="検査機関コード" len="6" value="const:000000"/>
--    <item  name="依頼者KEY（日付）" len="6" value="$SYSDATE" subMode="R"/>
--    <item  name="依頼者KEY（受付番号）" len="4" value="$JOURNAL.accept_no" padding_format="zero" padding_position="left"/>
--    <item  name="RSV" len="10" value="$BLANK"/>
--    <item  name="科コード・科名" len="15" value="$SYSDATE" padding_format="blank" padding_position="right"/>
--    <item  name="病棟コード・病棟名" len="15" value="dataset:-452.ward_cd"/>
--    <item  name="入院外来区分" len="1" value="dataset:-300001.in_out_class"/>
--    <item  name="提出医" len="10" value="dataset:-24.staff_cd"/>
--    <item  name="披験者ID" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="カルテNO" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="被験者名" len="20" value="dataset:-300001.pat_name"/>
--    <item  name="性別" len="1" value="dataset:-300001.pat_sex"/>
--    <item  name="年齢区分" len="1" value="const:Y"/>
--    <item  name="年齢" len="3" value="dataset:-300001.pat_age"/>
--    <item  name="生年月日区分" len="1" value="$BLANK"/>
--    <item  name="生年月日" len="8" value="dataset:-300001.pat_birthday_yyyymmdd"/>
--    <item  name="採取日" len="8" value="dataset:-23.exam_date"/>
--    <item  name="採取時間" len="4" value="dataset:-23.exam_start_time"/>
--    <item  name="項目数" len="3" value="dataset:-454.exam_set_cnt"/>
--    <item  name="身長" len="4" value="$BLANK"/>
--    <item  name="体重" len="4" value="$BLANK"/>
--    <item  name="尿量（量）" len="4" value="$BLANK"/>
--    <item  name="尿量（単位）" len="2" value="$BLANK"/>
--    <item  name="妊娠週数" len="2" value="$BLANK"/>
--    <item  name="透析前後" len="1" value="dataset:-31.exam_timing"/>
--    <item  name="至急報告" len="1" value="$BLANK"/>
--    <item  name="依頼コメント内容" len="50" value="$BLANK"/>
--    <item  name="施設NO" len="6" value="const:000000"/>
--    <item  name="RSV" len="30" value="$BLANK"/>
--    <item  name="ベッド番号" len="4" value="dataset:-31.bed_cd"/>
--    <item  name="改行" len="1" value="$CR"/>
--    <occ  name="明細.検査項目" len="0" detail="検査項目" sqlCode="-453"/>
--</root>', '{"dataset": [{"patId": "patId", "sqlCode": -300001}, {"patId": "patId", "sqlCode": -452}, {"ordNo": "ordNo", "sqlCode": -453}, {"ordNo": "ordNo", "sqlCode": -454}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -24, "facilityCd": "facilityCd"}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -23, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "sqlCode": -31}], "dumpFileName": {"ctlNo": "ctlNo", "patId": "patId", "sqlCode": -99995}}', '1', '0', 4, '2020-05-13 18:35:00.661', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-4100002, 'P_hosp', 'exam_ord', '', 'S', 'upd', 'text', 'Medicom検査オーダ', 'Medicom', '検査オーダ', '1', '<root name="検査依頼">
--    <item  name="レコード区分" len="2" value="const:O1"/>
--    <item  name="検査機関コード" len="6" value="const:000000"/>
--    <item  name="依頼者KEY（日付）" len="6" value="$SYSDATE" subMode="R"/>
--    <item  name="依頼者KEY（受付番号）" len="4" value="$JOURNAL.accept_no" padding_format="zero" padding_position="left"/>
--    <item  name="RSV" len="10" value="$BLANK"/>
--    <item  name="科コード・科名" len="15" value="$SYSDATE" padding_format="blank" padding_position="right"/>
--    <item  name="病棟コード・病棟名" len="15" value="dataset:-452.ward_cd"/>
--    <item  name="入院外来区分" len="1" value="dataset:-300001.in_out_class"/>
--    <item  name="提出医" len="10" value="dataset:-24.staff_cd"/>
--    <item  name="披験者ID" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="カルテNO" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="被験者名" len="20" value="dataset:-300001.pat_name"/>
--    <item  name="性別" len="1" value="dataset:-300001.pat_sex"/>
--    <item  name="年齢区分" len="1" value="const:Y"/>
--    <item  name="年齢" len="3" value="dataset:-300001.pat_age"/>
--    <item  name="生年月日区分" len="1" value="$BLANK"/>
--    <item  name="生年月日" len="8" value="dataset:-300001.pat_birthday_yyyymmdd"/>
--    <item  name="採取日" len="8" value="dataset:-23.exam_date"/>
--    <item  name="採取時間" len="4" value="dataset:-23.exam_start_time"/>
--    <item  name="項目数" len="3" value="dataset:-454.exam_set_cnt"/>
--    <item  name="身長" len="4" value="$BLANK"/>
--    <item  name="体重" len="4" value="$BLANK"/>
--    <item  name="尿量（量）" len="4" value="$BLANK"/>
--    <item  name="尿量（単位）" len="2" value="$BLANK"/>
--    <item  name="妊娠週数" len="2" value="$BLANK"/>
--    <item  name="透析前後" len="1" value="dataset:-31.exam_timing"/>
--    <item  name="至急報告" len="1" value="$BLANK"/>
--    <item  name="依頼コメント内容" len="50" value="$BLANK"/>
--    <item  name="施設NO" len="6" value="const:000000"/>
--    <item  name="RSV" len="30" value="$BLANK"/>
--    <item  name="ベッド番号" len="4" value="dataset:-31.bed_cd"/>
--    <item  name="改行" len="1" value="$CR"/>
--    <occ  name="明細.検査項目" len="0" detail="検査項目" sqlCode="-453"/>
--</root>', '{"dataset": [{"patId": "patId", "sqlCode": -300001}, {"patId": "patId", "sqlCode": -452}, {"ordNo": "ordNo", "sqlCode": -453}, {"ordNo": "ordNo", "sqlCode": -454}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -24, "facilityCd": "facilityCd"}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -23, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "sqlCode": -31}], "dumpFileName": {"ctlNo": "ctlNo", "patId": "patId", "sqlCode": -99995}}', '1', '0', 4, '2020-05-13 18:35:00.661', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-4100001, 'P_hosp', 'exam_ord', '', 'S', 'cre', 'text', 'Medicom検査オーダ', 'Medicom', '検査オーダ', '1', '<root name="検査依頼">
--    <item  name="レコード区分" len="2" value="const:O1"/>
--    <item  name="検査機関コード" len="6" value="const:000000"/>
--    <item  name="依頼者KEY（日付）" len="6" value="$SYSDATE" subMode="R"/>
--    <item  name="依頼者KEY（受付番号）" len="4" value="$JOURNAL.accept_no" padding_format="zero" padding_position="left"/>
--    <item  name="RSV" len="10" value="$BLANK"/>
--    <item  name="科コード・科名" len="15" value="$SYSDATE" padding_format="blank" padding_position="right"/>
--    <item  name="病棟コード・病棟名" len="15" value="dataset:-452.ward_cd"/>
--    <item  name="入院外来区分" len="1" value="dataset:-300001.in_out_class"/>
--    <item  name="提出医" len="10" value="dataset:-24.staff_cd"/>
--    <item  name="披験者ID" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="カルテNO" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="被験者名" len="20" value="dataset:-300001.pat_name"/>
--    <item  name="性別" len="1" value="dataset:-300001.pat_sex"/>
--    <item  name="年齢区分" len="1" value="const:Y"/>
--    <item  name="年齢" len="3" value="dataset:-300001.pat_age"/>
--    <item  name="生年月日区分" len="1" value="$BLANK"/>
--    <item  name="生年月日" len="8" value="dataset:-300001.pat_birthday_yyyymmdd"/>
--    <item  name="採取日" len="8" value="dataset:-23.exam_date"/>
--    <item  name="採取時間" len="4" value="dataset:-23.exam_start_time"/>
--    <item  name="項目数" len="3" value="dataset:-454.exam_set_cnt"/>
--    <item  name="身長" len="4" value="$BLANK"/>
--    <item  name="体重" len="4" value="$BLANK"/>
--    <item  name="尿量（量）" len="4" value="$BLANK"/>
--    <item  name="尿量（単位）" len="2" value="$BLANK"/>
--    <item  name="妊娠週数" len="2" value="$BLANK"/>
--    <item  name="透析前後" len="1" value="dataset:-31.exam_timing"/>
--    <item  name="至急報告" len="1" value="$BLANK"/>
--    <item  name="依頼コメント内容" len="50" value="$BLANK"/>
--    <item  name="施設NO" len="6" value="const:000000"/>
--    <item  name="RSV" len="30" value="$BLANK"/>
--    <item  name="ベッド番号" len="4" value="dataset:-31.bed_cd"/>
--    <item  name="改行" len="1" value="$CR"/>
--    <occ  name="明細.検査項目" len="0" detail="検査項目" sqlCode="-453"/>
--</root>', '{"dataset": [{"patId": "patId", "sqlCode": -300001}, {"patId": "patId", "sqlCode": -452}, {"ordNo": "ordNo", "sqlCode": -453}, {"ordNo": "ordNo", "sqlCode": -454}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -24, "facilityCd": "facilityCd"}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -23, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "sqlCode": -31}], "dumpFileName": {"ctlNo": "ctlNo", "patId": "patId", "sqlCode": -99995}}', '1', '0', 4, '2020-05-13 18:35:00.661', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-2100002, 'F_hosp', 'exam_ord', '', 'S', 'upd', 'text', '富士通検査依頼', 'fujitsu', '検体検査依頼', '1', '<root name="検査依頼">
--    <item  name="電文種別" len="2" value="const:VO"/>
--    <item  name="レコード継続指示" len="1" value="const:E"/>
--    <item  name="送信先システムコード" len="2" value="const:XX"/>
--    <item  name="発信元システムコード" len="2" value="const:VN"/>
--    <item  name="処理情報.処理年月日" len="8" value="$SYSDATE"/>
--    <item  name="処理情報.処理時刻" len="6" value="$SYSTIME"/>
--    <item  name="端末名" len="8" value="const:VOSERVER"/>
--    <item  name="利用者番号" len="8" value="dataset:-75.disp_user_id"/>
--    <item  name="処理区分" len="2" value="const:02"/>
--    <item  name="応答種別" len="2" value="$BLANK"/>
--    <item  name="電文長" len="6" value="$LENGTH"/>
--    <item  name="エラーコード" len="5" value="$BLANK"/>
--    <item  name="予備" len="12" value="$BLANK"/>
--    <item  name="情報種別" len="2" value="const:03"/>
--    <item  name="患者情報.患者番号" len="10" value="dataset:-100001.hosp_pat_id" padding_format="zero" padding_position="left"/>
--    <item  name="伝票情報.オーダ番号(固定)" len="2" value="const:99"/>
--    <item  name="伝票情報.オーダ番号" len="6" value="$JOURNAL.coop_ord_no" padding_format="zero" padding_position="left" subMode="R"/>
--    <item  name="伝票情報.文書番号(先頭8文字）" len="8" value="const:VOSERVER"/>
--    <item  name="伝票情報.文書番号(患者番号)" len="12" value="dataset:-100001.hosp_pat_id" padding_format="zero" padding_position="left"/>
--    <item  name="伝票情報.文書番号(オーダ番号(固定))" len="2" value="const:99"/>
--    <item  name="伝票情報.文書番号(オーダ番号)" len="6" value="$JOURNAL.coop_ord_no" padding_format="zero" padding_position="left" subMode="R"/>
--    <item  name="伝票情報.文書番号(後2文字）" len="2" value="dataset:-48.document_no"/>
--    <item  name="伝票情報.文書版数" len="2" value="const:00"/>
--    <item  name="伝票情報.関連オーダ番号" len="8" value="$BLANK"/>
--    <item  name="伝票情報.オーダ日付" len="8" value="dataset:-23.exam_date"/>
--    <item  name="伝票情報.オーダ時間" len="6" value="dataset:-23.exam_start_time"/>
--    <item  name="伝票情報.保険パターン番号" len="2" value="dataset:-54.insu_no"/>
--    <item  name="伝票情報.入外区分" len="1" value="dataset:-20.exam_in_out"/>
--    <item  name="伝票情報.診療科コード" len="3" value="dataset:-39.course_cd"/>
--    <item  name="伝票情報.病棟コード" len="3" value="dataset:-39.ward_cd"/>
--    <item  name="伝票情報.利用者番号" len="8" value="dataset:-76.disp_user_id"/>
--    <item  name="伝票情報.伝票コード" len="4" value="dataset:-49.slip_code"/>
--    <item  name="伝票情報.伝票名称" len="50" value="dataset:-49.slip_name"/>
--    <item  name="予約情報.予約グループCD" len="4" value="$BLANK"/>
--    <item  name="予約情報.予約枠コード(頭）" len="2" value="$BLANK"/>
--    <item  name="予約情報.予約枠コード" len="6" value="$BLANK"/>
--    <item  name="予約情報.予約開始日" len="8" value="$BLANK"/>
--    <item  name="予約情報.予約開始時間" len="6" value="$BLANK"/>
--    <item  name="予約情報.予約終了日" len="8" value="$BLANK"/>
--    <item  name="予約情報.予約終了時間" len="6" value="$BLANK"/>
--    <occ  name="明細行数" len="4" detail="検査項目" sqlCode="-25" padding_format="zero" padding_position="left"/>
--    <item  name="終端" len="1" value="$CR"/>
--</root>', '{"dataset": [{"ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -54, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -20}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -23, "facilityCd": "facilityCd", "is_zero_end": "true"}, {"ordNo": "ordNo", "sqlCode": -25, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -75, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -76, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -39, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -100001}, {"sqlCode": -48, "facilityCd": "facilityCd"}, {"sqlCode": -49, "facilityCd": "facilityCd"}]}', '1', '0', -1, '2022-01-13 08:11:32.285', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-2100001, 'F_hosp', 'exam_ord', '', 'S', 'cre', 'text', '富士通検査依頼', 'fujitsu', '検体検査依頼', '1', '<root name="検査依頼">
--    <item  name="電文種別" len="2" value="const:VO"/>
--    <item  name="レコード継続指示" len="1" value="const:E"/>
--    <item  name="送信先システムコード" len="2" value="const:XX"/>
--    <item  name="発信元システムコード" len="2" value="const:VN"/>
--    <item  name="処理情報.処理年月日" len="8" value="$SYSDATE"/>
--    <item  name="処理情報.処理時刻" len="6" value="$SYSTIME"/>
--    <item  name="端末名" len="8" value="const:VOSERVER"/>
--    <item  name="利用者番号" len="8" value="dataset:-75.disp_user_id"/>
--    <item  name="処理区分" len="2" value="const:01"/>
--    <item  name="応答種別" len="2" value="$BLANK"/>
--    <item  name="電文長" len="6" value="$LENGTH"/>
--    <item  name="エラーコード" len="5" value="$BLANK"/>
--    <item  name="予備" len="12" value="$BLANK"/>
--    <item  name="情報種別" len="2" value="const:03"/>
--    <item  name="患者情報.患者番号" len="10" value="dataset:-100001.hosp_pat_id" padding_format="zero" padding_position="left"/>
--    <item  name="伝票情報.オーダ番号(固定)" len="2" value="const:99"/>
--    <item  name="伝票情報.オーダ番号" len="6" value="$JOURNAL.coop_ord_no" padding_format="zero" padding_position="left" subMode="R"/>
--    <item  name="伝票情報.文書番号(先頭8文字）" len="8" value="const:VOSERVER"/>
--    <item  name="伝票情報.文書番号(患者番号)" len="12" value="dataset:-100001.hosp_pat_id" padding_format="zero" padding_position="left"/>
--    <item  name="伝票情報.文書番号(オーダ番号(固定))" len="2" value="const:99"/>
--    <item  name="伝票情報.文書番号(オーダ番号)" len="6" value="$JOURNAL.coop_ord_no" padding_format="zero" padding_position="left" subMode="R"/>
--    <item  name="伝票情報.文書番号(後2文字）" len="2" value="dataset:-48.document_no"/>
--    <item  name="伝票情報.文書版数" len="2" value="const:00"/>
--    <item  name="伝票情報.関連オーダ番号" len="8" value="$BLANK"/>
--    <item  name="伝票情報.オーダ日付" len="8" value="dataset:-23.exam_date"/>
--    <item  name="伝票情報.オーダ時間" len="6" value="dataset:-23.exam_start_time"/>
--    <item  name="伝票情報.保険パターン番号" len="2" value="dataset:-54.insu_no"/>
--    <item  name="伝票情報.入外区分" len="1" value="dataset:-20.exam_in_out"/>
--    <item  name="伝票情報.診療科コード" len="3" value="dataset:-39.course_cd"/>
--    <item  name="伝票情報.病棟コード" len="3" value="dataset:-39.ward_cd"/>
--    <item  name="伝票情報.利用者番号" len="8" value="dataset:-76.disp_user_id"/>
--    <item  name="伝票情報.伝票コード" len="4" value="dataset:-49.slip_code"/>
--    <item  name="伝票情報.伝票名称" len="50" value="dataset:-49.slip_name"/>
--    <item  name="予約情報.予約グループCD" len="4" value="$BLANK"/>
--    <item  name="予約情報.予約枠コード(頭）" len="2" value="$BLANK"/>
--    <item  name="予約情報.予約枠コード" len="6" value="$BLANK"/>
--    <item  name="予約情報.予約開始日" len="8" value="$BLANK"/>
--    <item  name="予約情報.予約開始時間" len="6" value="$BLANK"/>
--    <item  name="予約情報.予約終了日" len="8" value="$BLANK"/>
--    <item  name="予約情報.予約終了時間" len="6" value="$BLANK"/>
--    <occ  name="明細行数" len="4" detail="検査項目" sqlCode="-25" padding_format="zero" padding_position="left"/>
--    <item  name="終端" len="1" value="$CR"/>
--</root>', '{"dataset": [{"ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -54, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -20}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -23, "facilityCd": "facilityCd", "is_zero_end": "true"}, {"ordNo": "ordNo", "sqlCode": -25, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -75, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -76, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -39, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -100001}, {"sqlCode": -48, "facilityCd": "facilityCd"}, {"sqlCode": -49, "facilityCd": "facilityCd"}]}', '1', '0', -1, '2022-01-13 08:11:32.235', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-1100002, 'nkknkk', 'exam_ord', '', 'S', 'upd', 'text', '日機装標準', 'nikkiso', '検査依頼(※電文フォーマットはMedicomと一致しています。直接にMedicomのフォーマットを使います。)', '1', '<root name="検査依頼">
--    <item  name="レコード区分" len="2" value="const:O1"/>
--    <item  name="検査機関コード" len="6" value="const:000000"/>
--    <item  name="依頼者KEY（日付）" len="6" value="$SYSDATE" subMode="R"/>
--    <item  name="依頼者KEY（受付番号）" len="4" value="$JOURNAL.accept_no" padding_format="zero" padding_position="left"/>
--    <item  name="RSV" len="10" value="$BLANK"/>
--    <item  name="科コード・科名" len="15" value="$SYSDATE" padding_format="blank" padding_position="right"/>
--    <item  name="病棟コード・病棟名" len="15" value="dataset:-452.ward_cd"/>
--    <item  name="入院外来区分" len="1" value="dataset:-300001.in_out_class"/>
--    <item  name="提出医" len="10" value="dataset:-241.disp_user_id"/>
--    <item  name="披験者ID" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="カルテNO" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="被験者名" len="20" value="dataset:-300001.pat_name"/>
--    <item  name="性別" len="1" value="dataset:-300001.pat_sex"/>
--    <item  name="年齢区分" len="1" value="const:Y"/>
--    <item  name="年齢" len="3" value="dataset:-300001.pat_age"/>
--    <item  name="生年月日区分" len="1" value="$BLANK"/>
--    <item  name="生年月日" len="8" value="dataset:-300001.pat_birthday_yyyymmdd"/>
--    <item  name="採取日" len="8" value="dataset:-23.exam_date"/>
--    <item  name="採取時間" len="4" value="dataset:-23.exam_start_time"/>
--    <item  name="項目数" len="3" value="dataset:-454.exam_set_cnt"/>
--    <item  name="身長" len="4" value="$BLANK"/>
--    <item  name="体重" len="4" value="$BLANK"/>
--    <item  name="尿量（量）" len="4" value="$BLANK"/>
--    <item  name="尿量（単位）" len="2" value="$BLANK"/>
--    <item  name="妊娠週数" len="2" value="$BLANK"/>
--    <item  name="透析前後" len="1" value="dataset:-31.exam_timing"/>
--    <item  name="至急報告" len="1" value="$BLANK"/>
--    <item  name="依頼コメント内容" len="50" value="$BLANK"/>
--    <item  name="施設NO" len="6" value="const:000000"/>
--    <item  name="RSV" len="30" value="$BLANK"/>
--    <item  name="ベッド番号" len="4" value="dataset:-31.bed_cd"/>
--    <item  name="改行" len="1" value="$CR"/>
--    <occ  name="明細.検査項目" len="0" detail="検査項目" sqlCode="-453"/>
--</root>', '{"dataset": [{"patId": "patId", "sqlCode": -300001}, {"patId": "patId", "sqlCode": -452}, {"ordNo": "ordNo", "sqlCode": -453}, {"ordNo": "ordNo", "sqlCode": -454}, {"key0": "key0", "ordNo": "ordNo", "patId": "patId", "sqlCode": -24, "facilityCd": "facilityCd"}, {"key0": "key0", "ordNo": "ordNo", "patId": "patId", "sqlCode": -241, "facilityCd": "facilityCd"}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -23, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "sqlCode": -31}], "dumpFileName": {"ctlNo": "ctlNo", "patId": "patId", "sqlCode": -99995}}', '1', '0', 4, '2020-05-13 14:59:24.07', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-1100001, 'nkknkk', 'exam_ord', '', 'S', 'cre', 'text', '日機装標準', 'nikkiso', '検査依頼(※電文フォーマットはMedicomと一致しています。直接にMedicomのフォーマットを使います。)', '1', '<root name="検査依頼">
--    <item  name="レコード区分" len="2" value="const:O1"/>
--    <item  name="検査機関コード" len="6" value="const:000000"/>
--    <item  name="依頼者KEY（日付）" len="6" value="$SYSDATE" subMode="R"/>
--    <item  name="依頼者KEY（受付番号）" len="4" value="$JOURNAL.accept_no" padding_format="zero" padding_position="left"/>
--    <item  name="RSV" len="10" value="$BLANK"/>
--    <item  name="科コード・科名" len="15" value="$SYSDATE" padding_format="blank" padding_position="right"/>
--    <item  name="病棟コード・病棟名" len="15" value="dataset:-452.ward_cd"/>
--    <item  name="入院外来区分" len="1" value="dataset:-300001.in_out_class"/>
--    <item  name="提出医" len="10" value="dataset:-241.disp_user_id"/>
--    <item  name="披験者ID" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="カルテNO" len="10" value="dataset:-300001.hosp_pat_id"/>
--    <item  name="RSV" len="5" value="$BLANK"/>
--    <item  name="被験者名" len="20" value="dataset:-300001.pat_name"/>
--    <item  name="性別" len="1" value="dataset:-300001.pat_sex"/>
--    <item  name="年齢区分" len="1" value="const:Y"/>
--    <item  name="年齢" len="3" value="dataset:-300001.pat_age"/>
--    <item  name="生年月日区分" len="1" value="$BLANK"/>
--    <item  name="生年月日" len="8" value="dataset:-300001.pat_birthday_yyyymmdd"/>
--    <item  name="採取日" len="8" value="dataset:-23.exam_date"/>
--    <item  name="採取時間" len="4" value="dataset:-23.exam_start_time"/>
--    <item  name="項目数" len="3" value="dataset:-454.exam_set_cnt"/>
--    <item  name="身長" len="4" value="$BLANK"/>
--    <item  name="体重" len="4" value="$BLANK"/>
--    <item  name="尿量（量）" len="4" value="$BLANK"/>
--    <item  name="尿量（単位）" len="2" value="$BLANK"/>
--    <item  name="妊娠週数" len="2" value="$BLANK"/>
--    <item  name="透析前後" len="1" value="dataset:-31.exam_timing"/>
--    <item  name="至急報告" len="1" value="$BLANK"/>
--    <item  name="依頼コメント内容" len="50" value="$BLANK"/>
--    <item  name="施設NO" len="6" value="const:000000"/>
--    <item  name="RSV" len="30" value="$BLANK"/>
--    <item  name="ベッド番号" len="4" value="dataset:-31.bed_cd"/>
--    <item  name="改行" len="1" value="$CR"/>
--    <occ  name="明細.検査項目" len="0" detail="検査項目" sqlCode="-453"/>
--</root>', '{"dataset": [{"patId": "patId", "sqlCode": -300001}, {"patId": "patId", "sqlCode": -452}, {"ordNo": "ordNo", "sqlCode": -453}, {"ordNo": "ordNo", "sqlCode": -454}, {"key0": "key0", "ordNo": "ordNo", "patId": "patId", "sqlCode": -24, "facilityCd": "facilityCd"}, {"key0": "key0", "ordNo": "ordNo", "patId": "patId", "sqlCode": -241, "facilityCd": "facilityCd"}, {"key0": "key0", "ordNo": "ordNo", "sqlCode": -23, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "sqlCode": -31}], "dumpFileName": {"ctlNo": "ctlNo", "patId": "patId", "sqlCode": -99995}}', '1', '0', 4, '2020-05-13 14:59:20.666',CURRENT_TIMESTAMP, '');

