UPDATE ntss.sys_data_list_detail
	SET master_display_name='IAP　Ratio',function_display_name='IAP　Ratio'
	WHERE data_list_detail_cd=769;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='表示',function_display_type='2'
	WHERE data_list_detail_cd=1352;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='装置台数',function_display_type='2'
	WHERE data_list_detail_cd=1353;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='合格台数',function_display_type='2'
	WHERE data_list_detail_cd=1354;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='不合格台数',function_display_type='2'
	WHERE data_list_detail_cd=1355;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='装置名',function_display_type='2'
	WHERE data_list_detail_cd=1356;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='製造番号',function_display_type='2'
	WHERE data_list_detail_cd=1357;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='型式',function_display_type='2'
	WHERE data_list_detail_cd=1358;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='ベッド名',function_display_type='2'
	WHERE data_list_detail_cd=1359;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='設置日',function_display_type='2'
	WHERE data_list_detail_cd=1360;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='[name]'
	WHERE data_list_detail_cd=1361;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='採取時刻',function_display_type='2'
	WHERE data_list_detail_cd=1362;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='結果',function_display_type='2'
	WHERE data_list_detail_cd=1363;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='採取者',function_display_type='2'
	WHERE data_list_detail_cd=1364;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='検査者',function_display_type='2'
	WHERE data_list_detail_cd=1365;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='装置名',function_display_type='2'
	WHERE data_list_detail_cd=1366;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='製造番号',function_display_type='2'
	WHERE data_list_detail_cd=1367;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='型式',function_display_type='2'
	WHERE data_list_detail_cd=1368;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='ベッド名',function_display_type='2'
	WHERE data_list_detail_cd=1369;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='設置日',function_display_type='2'
	WHERE data_list_detail_cd=1370;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='配管自己診断結果',function_display_type='2'
	WHERE data_list_detail_cd=1371;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='配管漏れ（陰圧）',function_display_type='2'
	WHERE data_list_detail_cd=1372;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='配管漏れ（陽圧）',function_display_type='2'
	WHERE data_list_detail_cd=1373;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='除水テスト',function_display_type='2'
	WHERE data_list_detail_cd=1374;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='バランステスト',function_display_type='2'
	WHERE data_list_detail_cd=1375;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='CF漏れ',function_display_type='2'
	WHERE data_list_detail_cd=1376;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='CF2漏れ',function_display_type='2'
	WHERE data_list_detail_cd=1377;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='赤電圧',function_display_type='2'
	WHERE data_list_detail_cd=1378;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='緑電圧',function_display_type='2'
	WHERE data_list_detail_cd=1379;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='透析液流量',function_display_type='2'
	WHERE data_list_detail_cd=1380;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='濃度自己診断結果',function_display_type='2'
	WHERE data_list_detail_cd=1381;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='透析液濃度',function_display_type='2'
	WHERE data_list_detail_cd=1382;
UPDATE ntss.sys_data_list_detail
	SET function_display_name='B原液濃度',function_display_type='2'
	WHERE data_list_detail_cd=1383;
