DELETE FROM ntss.mst_coop_apilink
WHERE ctl_no IN (-1110001,-1110002,-1110003);

INSERT INTO ntss.mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1110001, 'Secom', 'exam_ord', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd"}, "sqlCode": -1105011, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO ntss.mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1110002, 'Secom', 'exam_ord', '', 'U', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd"}, "sqlCode": -1105011, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO ntss.mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1110003, 'Secom', 'exam_ord', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd"}, "sqlCode": -1105012, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '0', NULL, 'Secom');
