--日常・定期点検項目マスタカテゴリー削除
UPDATE ntss.sys_master_define	
SET column_info='{"fields": [{"type": "number", "alias": "code", "title": "コード", "format": null, "hidden": "true", "physical_name": "mainte_detail_cd"}, {"type": "number", "alias": null, "title": "版数", "format": null, "hidden": "true", "editable": "false", "validation": {"max": null, "min": null, "required": null, "maxlength": null}, "defaultValue": 0, "physical_name": "edition_no"}, {"type": "string", "alias": null, "title": "内容1", "format": null, "hidden": "false", "editable": "true", "validation": {"max": null, "min": null, "required": null, "maxlength": null}, "physical_name": "mainte_content_1"}, {"type": "string", "alias": null, "title": "内容2", "format": null, "hidden": "false", "editable": "true", "validation": {"max": null, "min": null, "required": null, "maxlength": null}, "physical_name": "mainte_content_2"}, {"type": "string", "alias": null, "title": "内容3", "format": null, "hidden": "false", "editable": "true", "validation": {"max": null, "min": null, "required": null, "maxlength": null}, "physical_name": "mainte_content_3"}, {"type": "disp", "title": "削除", "physical_name": "is_disp"}, {"type": "del", "title": "削除", "physical_name": "is_del"}]}'
WHERE master_physical_name='mst_mainte_detail';	

--日常・定期点検項目マスタ詳細追加
UPDATE ntss.sys_master_define	
SET column_info='{"fields": [{"type": "number", "alias": "code", "title": "チェックリストカテゴリコード", "format": null, "hidden": "true", "editable": "false", "validation": {"max": null, "min": null, "required": "true", "maxlength": null}, "physical_name": "mainte_category_cd"}, {"type": "number", "alias": null, "title": "版数", "format": null, "hidden": "true", "editable": "false", "validation": {"max": null, "min": null, "required": null, "maxlength": null}, "defaultValue": 0, "physical_name": "edition_no"}, {"type": "string", "alias": null, "title": "名前", "format": null, "hidden": "false", "editable": "true", "validation": {"max": null, "min": null, "required": "true", "maxlength": 256}, "physical_name": "category_name"}, {"type": "json", "title": "詳細", "hidden": "true", "physical_name": "detail"}, {"type": "modal", "alias": null, "title": "グループ情報", "format": null, "hidden": "false", "editable": "false", "validation": {"max": null, "min": null, "required": null, "maxlength": null}, "physical_name": "detail1"}, {"type": "disp", "title": "削除", "physical_name": "is_disp"}, {"type": "del", "title": "削除", "physical_name": "is_del"}]}'
WHERE master_physical_name='mst_mainte_category';	

