delete from "mst_coop_layout" where "ctl_no" in (-3020001);
INSERT INTO "mst_coop_layout"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-3020001, 'N_hosp', 'pre_ord', '', 'R', 'pre', 'text     ', 'NEC想定処方情報受信', 'MEGA', '処方情報連携', '1', '<root name="検査結果(pre)">
  <item name="送信先ＩＤ" len="6" type="string"/>
  <item name="送信元ID" len="6" type="string"/>
  <item name="処理コマンド" len="8" type="string"/>
  <item name="受信結果" len="6" type="string"/>
  <item name="データ長" len="6" type="string"/>
  <item name="コマンド名" len="8" type="string" key="command_name"/>
  <item name="モード" len="1" type="string"/>
  <item name="オーダ番号" len="13" type="string"/>
  <item name="オーダサブ番号" len="3" type="string"/>
  <item name="履歴番号" len="3" type="string"/>
  <item name="オーダ進捗" len="1" type="string"/>
  <item name="病院コード" len="2" type="string"/>
  <item name="オーダ番号" len="13" type="string"/>
  <item name="オーダサブ番号" len="3" type="string"/>
  <item name="患者番号" len="10" type="string"/>
  <item name="情報区分" len="1" type="string"/>
  <item name="最新区分" len="1" type="string"/>
  <item name="有効区分（未使用）" len="1" type="string"/>
  <item name="オーダ種" len="2" type="string"/>
  <item name="オーダ詳細" len="2" type="string"/>
  <item name="オーダ開始日" len="8" type="string"/>
  <item name="オーダ開始時刻" len="4" type="string"/>
  <item name="未展開オーダ日付" len="8" type="string"/>
  <item name="未展開オーダ時刻" len="4" type="string"/>
  <item name="オーダ終了日" len="8" type="string"/>
  <item name="オーダ終了時刻" len="4" type="string"/>
  <item name="オーダ間隔" len="3" type="string"/>
  <item name="日曜オーダ" len="1" type="string"/>
  <item name="月曜オーダ" len="1" type="string"/>
  <item name="火曜オーダ" len="1" type="string"/>
  <item name="水曜オーダ" len="1" type="string"/>
  <item name="木曜オーダ" len="1" type="string"/>
  <item name="金曜オーダ" len="1" type="string"/>
  <item name="土曜オーダ" len="1" type="string"/>
  <item name="POS入力（未使用）" len="1" type="string"/>
  <item name="オーダ関連（未使用）" len="1" type="string"/>
  <item name="予約ステータス（未使用）" len="1" type="string"/>
  <item name="実施進捗１" len="1" type="string"/>
  <item name="実施進捗２" len="1" type="string"/>
  <item name="報告進捗１　“N”固定" len="1" type="string"/>
  <item name="報告進捗２（未使用）" len="1" type="string"/>
  <item name="看護師進捗１（未使用）" len="1" type="string"/>
  <item name="看護師進捗２（未使用）" len="1" type="string"/>
  <item name="会計進捗１" len="1" type="string"/>
  <item name="会計修正（未使用）" len="1" type="string"/>
  <item name="入外区分" len="1" type="string"/>
  <item name="オーダ科" len="2" type="string"/>
  <item name="指示医：職員マスタの職員コード" len="10"/>
  <item name="指示医世代番号" len="1" type="string"/>
  <item name="病棟" len="4" type="string"/>
  <item name="発行者" len="10" type="string"/>
  <item name="発行者世代番号" len="1" type="string"/>
  <item name="発行日" len="8" type="string"/>
  <item name="中止者" len="10" type="string"/>
  <item name="中止者世代番号" len="1" type="string"/>
  <item name="実施病棟" len="4" type="string"/>
  <item name="実施病室" len="4" type="string"/>
  <item name="実施日" len="8" type="string"/>
  <item name="実施時刻" len="4" type="string"/>
  <item name="実施者" len="10" type="string"/>
  <item name="実施者世代番号" len="1" type="string"/>
  <item name="実施番号" len="13" type="string"/>
  <item name="適用保険１" len="3" type="string"/>
  <item name="適用保険２　" len="3" type="string"/>
  <item name="適用保険３　" len="3" type="string"/>
  <item name="会計日付" len="8" type="string"/>
  <item name="会計時刻" len="4" type="string"/>
  <item name="フリーコメント種（未使用）" len="40" type="string"/>
  <item name="フリーコメントタイトル（未使用）" len="80" type="string"/>
  <item name="ポリクリ・治験フラグ" len="1" type="string"/>
  <item name="治験番号" len="4" type="string"/>
  <item name="更新日" len="14" type="string"/>
  <item name="更新端末" len="10" type="string"/>
  <item name="更新者" len="10" type="string"/>
  <item name="更新者世代番号" len="1" type="string"/>
  <item name="指示医講座コード" len="2" type="string"/>
  <item name="指示医グループコード" len="2" type="string"/>
  <item name="新規登録端末" len="10" type="string"/>
  <item name="新規登録者" len="10" type="string"/>
  <item name="新規登録者世代番号" len="1" type="string"/>
  <item name="新規登録日" len="8" type="string"/>
  <item name="監査日" len="8" type="string"/>
  <item name="監査端末" len="10" type="string"/>
  <item name="監査者" len="10" type="string"/>
  <item name="監査者世代番号" len="1" type="string"/>
  <item name="パス一意キー" len="13" type="string"/>
  <item name="パスマスタキー" len="13" type="string"/>
  <item name="基準日からの日付" len="3" type="string"/>
  <item name="パスオーダ付属コメント" len="120" type="string"/>
  <item name="パスマスタオーダ番号" len="13" type="string"/>
  <item name="パスマスタオーダ番号サブ" len="3" type="string"/>
  <item name="パスマスタ履歴番号" len="3" type="string"/>
  <item name="適用者コード" len="10" type="string"/>
  <item name="適用者世代番号" len="1" type="string"/>
  <item name="日付分割区分" len="1" type="string"/>
  <item name="画面表示内容" len="100" type="string"/>
  <item name="適用区分" len="1" type="string"/>
  <item name="必要時指示条件コード" len="6" type="string"/>
  <item name="同一行表示番号" len="13" type="string"/>
  <item name="必要時指示流用時の承認オーダ作成" len="1" type="string"/>
  <item name="必要時指示詳細条件コード" len="6" type="string"/>
  <item name="必要時指示表示順" len="13" type="string"/>
  <item name="必要時指示有効期間開始日" len="8" type="string"/>
  <item name="必要時指示有効期間開始日ステータス" len="1" type="string"/>
  <item name="必要時指示有効期間終了日" len="8" type="string"/>
  <item name="必要時指示有効期間終了日ステータス" len="1" type="string"/>
  <item name="レジメン一意キー" len="6" type="string"/>
  <item name="指示受け対象チェック" len="1" type="string"/>
  <item name="指示受け重要度チェック" len="1" type="string"/>
  <item name="コメント有無" len="1" type="string"/>
  <item name="未使用" len="13" type="string"/>
  <item name="未使用" len="3" type="string"/>
  <item name="未使用" len="1" type="string"/>
  <item name="時間マスタ使用時の時間コード" len="2" type="string"/>
  <item name="時間マスタ使用時の表示名称" len="20" type="string"/>
  <item name="時間マスタ使用時のマスタ設定時間" len="4" type="string"/>
  <item name="時間マスタ使用時の時間コード" len="2" type="string"/>
  <item name="時間マスタ使用時の表示名称" len="20" type="string"/>
  <item name="時間マスタ使用時のマスタ設定時間" len="4" type="string"/>
  <item name="関連オーダのOrderNo" len="13" type="string"/>
  <item name="病院コード" len="2" type="string"/>
  <item name="オーダ番号" len="13" type="string"/>
  <item name="オーダ(サブ)番号" len="3" type="string"/>
  <item name="投与日数" len="3" type="string"/>
  <item name="処方箋番号" len="8" type="string"/>
  <item name="処方箋コメント" len="80" type="string"/>
  <item name="長期投与コメント" len="6" type="string"/>
  <item name="薬剤師修正" len="1" type="string"/>
  <item name="処方箋発行区分" len="1" type="string"/>
  <item name="監査者" len="10" type="string"/>
  <item name="監査日" len="8" type="string"/>
  <item name="一包化" len="1" type="string"/>
  <item name="院内／院外区分" len="1" type="string"/>
  <item name="緊急区分" len="1" type="string"/>
  <item name="服薬説明" len="1" type="string"/>
  <item name="DOステータス" len="1" type="string"/>
  <item name="麻薬処方" len="1" type="string"/>
  <item name="治験処方" len="1" type="string"/>
  <item name="麻薬処方箋番号" len="8" type="string"/>
  <item name="薬剤情報出力" len="1" type="string"/>
  <item name="薬剤自己管理区分" len="1" type="string"/>
  <item name="自己注処方" len="1" type="string"/>
  <item name="治験投与フラグ" len="1" type="string"/>
  <item name="加算情報" len="1" type="string"/>
  <item name="処方箋コメントコード" len="6" type="string"/>
  <item name="配合警告" len="1" type="string"/>
  <item name="中止理由コメントコード" len="6" type="string"/>
  <item name="中止理由コメント名称" len="80" type="string"/>
  <item name="患者番号" len="10" type="string"/>
  <item name="与薬管理区分" len="1" type="string"/>
  <item name="後発薬への変更不可指示" len="1" type="string"/>
  <item name="抗がん剤が含まれる場合の情報提供対象フラグ" len="1" type="string"/>
  <item name="必要時準備データで、配置薬剤のみかどうか" len="1" type="string"/>
  <item name="MODIFYSTATUS" len="1" type="string"/>
  <occ name="グループ数" len="2" detail = "処方グループ詳細_空白"/>
</root>', '{"key": {"command_name": {"O-PRES": "取り込む", "_DEFAULT": "破棄"}}, "dataset": {"sqlGroup1": [{"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "患者番号より、データ＞1件の場合、異常終了。", "crud": "S", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": 1101, "@hospPatId": "$journal.pat_personal_main.hosp_pat_id", "insertResult": "{@fnPatId:'''',@hospPatId:'''',@nkkPatId:'''',@facilityCd:'''',@patLastName:'''',@patFirstName:'''',@patLastNmKana:'''',@patFirstNmKana:'''',@patLastNmAlpha:'''',@patFirstNmAlpha:'''',@patBirthName:'''',@patBirthNmKana:'''',@patBirthNmAlpha:'''',@patBirthday:'''',@patSex:'''',@nationality:'''',@patBloodTypeAbo:'''',@patBloodTypeRh:'''',@patBloodTypeSerovar:'''',@inOutClass:'''',@isDie:'''',@dieCd:'''',@dieDate_Date:'''',@dialDiffComInfoValue:''[]'',@severityCd:'''',@transportCd:'''',@patContactInfoFlg:'''',@patContactInfo.zipCd:'''',@patContactInfo.address:'''',@patContactInfo.tel1:'''',@patContactInfo.tel2:'''',@patContactInfo.fax:'''',@patContactInfo.eMail:'''',@patContactInfo.workName:'''',@patContactInfo.workAddress:'''',@patContactInfo.workTel:'''',@patContactInfo.memo1:'''',@patContactInfo.memo2:'''',@otherContactInfoValue:''[]'',@vendorContactInfoValue:''[]'',@insuranceInfoValue:''[]'',@primaryDiseaseCd:'''',@remoteMonitorService:'''',@remoteMonitorUserId:'''',@remoteMonitorUserPw:''''}", "updateResult": "{@fnPatId:''fn_pat_id'',@hospPatId:''hosp_pat_id'',@nkkPatId:''nkk_pat_id'',@facilityCd:''facility_cd'',@patLastName:''pat_last_name'',@patFirstName:''pat_first_name'',@patLastNmKana:''pat_last_name_kana'',@patFirstNmKana:''pat_first_name_kana'',@patLastNmAlpha:''pat_last_name_alpha'',@patFirstNmAlpha:''pat_first_name_alpha'',@patBirthName:''pat_birth_name'',@patBirthNmKana:''pat_birth_name_kana'',@patBirthNmAlpha:''pat_birth_name_alpha'',@patBirthday:''pat_birthday'',@patSex:''pat_sex'',@nationality:''nationality'',@patBloodTypeAbo:''pat_blood_type_abo'',@patBloodTypeRh:''pat_blood_type_rh'',@patBloodTypeSerovar:''pat_blood_type_serovar'',@inOutClass:''in_out_class'',@isDie:''is_die'',@dieCd:''die_cd'',@dieDate_Date:''die_date'',@dialDiffComInfoValue:''dial_diff_com_info'',@severityCd:''severity_cd'',@transportCd:''transport_cd'',@patContactInfoFlg:'''',@patContactInfoValue:''pat_contact_info'',@patContactInfo.zipCd:'''',@patContactInfo.address:'''',@patContactInfo.tel1:'''',@patContactInfo.tel2:'''',@patContactInfo.fax:'''',@patContactInfo.eMail:'''',@patContactInfo.workName:'''',@patContactInfo.workAddress:'''',@patContactInfo.workTel:'''',@patContactInfo.memo1:'''',@patContactInfo.memo2:'''',@otherContactInfoValue:''other_contact_info'',@vendorContactInfoValue:''vendor_contact_info'',@insuranceInfoValue:''insurance_info'',@regDate:''reg_date'',@primaryDiseaseCd:''primary_disease_cd'',@remoteMonitorService:''remote_monitor_service'',@remoteMonitorUserId:''remote_monitor_user_id'',@remoteMonitorUserPw:''remote_monitor_user_pw''}", "ExceptionMessage": "患者[@hospPatId]の個人情報に複数のデータが存在する。", "ExceptionCondition": "=N"}], "sqlGroup2": [{"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "患者番号より、データが無しの場合、正常終了(異常しません）。", "crud": "S", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "pat_personal_main", "ctl_no": "1", "sqlCode": 9301, "@hospPatId": "$journal.pat_personal_main.hosp_pat_id", "insertResult": "{@fnPatId:'''',@hospPatId:'''',@nkkPatId:'''',@facilityCd:'''',@patLastName:'''',@patFirstName:'''',@patLastNmKana:'''',@patFirstNmKana:'''',@patLastNmAlpha:'''',@patFirstNmAlpha:'''',@patBirthName:'''',@patBirthNmKana:'''',@patBirthNmAlpha:'''',@patBirthday:'''',@patSex:'''',@nationality:'''',@patBloodTypeAbo:'''',@patBloodTypeRh:'''',@patBloodTypeSerovar:'''',@inOutClass:'''',@isDie:'''',@dieCd:'''',@dieDate_Date:'''',@dialDiffComInfoValue:''[]'',@severityCd:'''',@transportCd:'''',@patContactInfoFlg:'''',@patContactInfo.zipCd:'''',@patContactInfo.address:'''',@patContactInfo.tel1:'''',@patContactInfo.tel2:'''',@patContactInfo.fax:'''',@patContactInfo.eMail:'''',@patContactInfo.workName:'''',@patContactInfo.workAddress:'''',@patContactInfo.workTel:'''',@patContactInfo.memo1:'''',@patContactInfo.memo2:'''',@otherContactInfoValue:''[]'',@vendorContactInfoValue:''[]'',@insuranceInfoValue:''[]'',@primaryDiseaseCd:'''',@remoteMonitorService:'''',@remoteMonitorUserId:'''',@remoteMonitorUserPw:''''}", "updateResult": "{@fnPatId:''fn_pat_id'',@hospPatId:''hosp_pat_id'',@nkkPatId:''nkk_pat_id'',@facilityCd:''facility_cd'',@patLastName:''pat_last_name'',@patFirstName:''pat_first_name'',@patLastNmKana:''pat_last_name_kana'',@patFirstNmKana:''pat_first_name_kana'',@patLastNmAlpha:''pat_last_name_alpha'',@patFirstNmAlpha:''pat_first_name_alpha'',@patBirthName:''pat_birth_name'',@patBirthNmKana:''pat_birth_name_kana'',@patBirthNmAlpha:''pat_birth_name_alpha'',@patBirthday:''pat_birthday'',@patSex:''pat_sex'',@nationality:''nationality'',@patBloodTypeAbo:''pat_blood_type_abo'',@patBloodTypeRh:''pat_blood_type_rh'',@patBloodTypeSerovar:''pat_blood_type_serovar'',@inOutClass:''in_out_class'',@isDie:''is_die'',@dieCd:''die_cd'',@dieDate_Date:''die_date'',@dialDiffComInfoValue:''dial_diff_com_info'',@severityCd:''severity_cd'',@transportCd:''transport_cd'',@patContactInfoFlg:'''',@patContactInfoValue:''pat_contact_info'',@patContactInfo.zipCd:'''',@patContactInfo.address:'''',@patContactInfo.tel1:'''',@patContactInfo.tel2:'''',@patContactInfo.fax:'''',@patContactInfo.eMail:'''',@patContactInfo.workName:'''',@patContactInfo.workAddress:'''',@patContactInfo.workTel:'''',@patContactInfo.memo1:'''',@patContactInfo.memo2:'''',@otherContactInfoValue:''other_contact_info'',@vendorContactInfoValue:''vendor_contact_info'',@insuranceInfoValue:''insurance_info'',@regDate:''reg_date'',@primaryDiseaseCd:''primary_disease_cd'',@remoteMonitorService:''remote_monitor_service'',@remoteMonitorUserId:''remote_monitor_user_id'',@remoteMonitorUserPw:''remote_monitor_user_pw''}", "ExceptionMessage": "NORMALEND", "ExceptionCondition": "=0"}], "sqlGroup3": [{"No1": "実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_personal_prescription)のデータを倫理削除する。", "crud": "S", "kind": "1", "judge": "$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "1", "sqlCode": 9302, "@issueDate": "$journal.ord_prescription.issue_date", "insertResult": "{@ordPrescriptionNo:'''', @facilityCd:'''', @patId:'''', @prescriptionType:'''', @issueDate:'''', @issueState:'''', @expirationDate:'''', @prescriptionDetailValue:''[]'', @isDisp:'''', @isDel:'''', @regDate:'''', @upDate:''''}", "updateResult": "{@ordPrescriptionNo:''ord_prescription_no'', @facilityCd:''facility_cd'', @patId:''pat_id'', @prescriptionType:''prescription_type'', @issueDate:''issue_date'', @issueState:''issue_state'', @expirationDate:''expiration_date'', @prescriptionDetailValue:''prescription_detail'', @isDisp:''is_disp'', @isDel:''is_del'', @regDate:''reg_date'', @upDate:''up_date''}"}, {"No1": "実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_personal_prescription)のデータを倫理削除する。", "crud": "U", "kind": "1", "judge": "$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "1", "sqlCode": 9303}], "sqlGroup4": [{"No1": "実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータを倫理削除する。", "crud": "S", "kind": "1", "judge": "$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "1", "sqlCode": 9302, "@issueDate": "$journal.ord_prescription.issue_date", "insertResult": "{@ordPrescriptionNo:'''', @facilityCd:'''', @patId:'''', @prescriptionType:'''', @issueDate:'''', @issueState:'''', @expirationDate:'''', @prescriptionDetailValue:''[]'', @isDisp:'''', @isDel:'''', @regDate:'''', @upDate:''''}", "updateResult": "{@ordPrescriptionNo:''ord_prescription_no'', @facilityCd:''facility_cd'', @patId:''pat_id'', @prescriptionType:''prescription_type'', @issueDate:''issue_date'', @issueState:''issue_state'', @expirationDate:''expiration_date'', @prescriptionDetailValue:''prescription_detail'', @isDisp:''is_disp'', @isDel:''is_del'', @regDate:''reg_date'', @upDate:''up_date''}"}, {"No1": "実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータを倫理削除する。", "crud": "U", "kind": "1", "judge": "$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "2", "sqlCode": 9304, "@issueDate": "$journal.ord_prescription.issue_date"}], "sqlGroup5": [{"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータを新規登録する。", "crud": "S", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "1", "sqlCode": 9302, "@issueDate": "$journal.ord_prescription.issue_date", "insertResult": "{@ordPrescriptionNo:'''', @facilityCd:'''', @patId:'''', @prescriptionType:'''', @issueDate:'''', @issueState:'''', @expirationDate:'''', @prescriptionDetailValue:''[]'', @isDisp:'''', @isDel:'''', @regDate:'''', @upDate:''''}", "updateResult": "{@ordPrescriptionNo:''ord_prescription_no'', @facilityCd:''facility_cd'', @patId:''pat_id'', @prescriptionType:''prescription_type'', @issueDate:''issue_date'', @issueState:''issue_state'', @expirationDate:''expiration_date'', @prescriptionDetailValue:''prescription_detail'', @isDisp:''is_disp'', @isDel:''is_del'', @regDate:''reg_date'', @upDate:''up_date''}"}, {"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータを新規登録する。", "crud": "C", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "2", "sqlCode": 9305, "@issueDate": "$journal.ord_prescription.issue_date", "@issueState": "1", "@expirationDate": "$journal.ord_prescription.expiration_date", "@prescriptionType": "2", "@prescriptionDetailValue": "[]"}], "sqlGroup6": [{"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_personal_prescription)のデータを新規登録する。", "No3": "このSの設定は、検証を通過させるため、データを取得することはありません。", "crud": "S", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_personal_prescription", "ctl_no": "1", "sqlCode": 9306, "@ordPrescriptionNo": "-1"}, {"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_personal_prescription)のデータを新規登録する。", "crud": "C", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_personal_prescription", "ctl_no": "1", "sqlCode": 9307, "@isChild": "0", "@isDoubt": "0", "@insuDrId": "$journal.ord_personal_prescription.insu_dr_cd", "@issueDate": "$journal.ord_prescription.issue_date", "@insuSrName": "", "@isElderly1": "0", "@isElderly7": "0", "@insuranceCd": "0", "@remarksFree": "$journal.ord_personal_prescription.remarks_free", "@isAnesthesia": "0", "@isInformation": "0"}], "sqlGroup7": [{"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータ[処方詳細(prescription_detail)内容(用法部分)]を新規登録する。", "crud": "S", "kind": "1", "type": "json", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "1", "sqlCode": 9302, "@issueDate": "$journal.ord_prescription.issue_date", "updateResult": "{@ordPrescriptionNo:''ord_prescription_no'', @facilityCd:''facility_cd'', @patId:''pat_id'',  @prescriptionDetailFlg:'''', @prescriptionDetailValue:''prescription_detail'', @prescriptionDetail.r:'''', @prescriptionDetail.f1:'''', @prescriptionDetail.f2:'''', @prescriptionDetail.f3:'''', @prescriptionDetail.f4:'''', @prescriptionDetail.f5:'''', @prescriptionDetail.f6:'''', @prescriptionDetail.rp:'''', @prescriptionDetail.type:'''', @prescriptionDetail.unchg:'''', @prescriptionDetail.medicineCd:'''', @prescriptionDetail.medicineType:'''', @prescriptionDetail.medicineUnit1:'''', @prescriptionDetail.medicineUnit2:''''}"}, {"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータ[処方詳細(prescription_detail)内容(用法部分)]を新規登録する。", "No3": "json場合、[D]の設定が必要です。しかし、NECの処方情報をクリアしません。judgeに[crud#=#NG]を設定する。", "crud": "D", "kind": "1", "judge": "$journal.const.crud#=#NG", "table": "ord_prescription", "ctl_no": "2", "sqlCode": 9302}, {"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータ[処方詳細(prescription_detail)内容(用法部分)]を新規登録する。", "crud": "U", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription", "ctl_no": "3", "sqlCode": 9308, "@issueDate": "$journal.ord_prescription.issue_date", "@prescriptionDetail.rp": "$journal.detail.ord_prescription.prescription_detail.rp", "@prescriptionDetail.period": "$journal.detail.ord_prescription.prescription_detail.period", "@prescriptionDetail.dosageName": "$journal.detail.ord_prescription.prescription_detail.dosage_name"}], "sqlGroup8": [{"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータ[処方詳細(prescription_detail)内容(薬剤部分)]を新規登録する。", "crud": "S", "kind": "1", "type": "json", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription_1", "ctl_no": "1", "sqlCode": 9302, "@issueDate": "$journal.ord_prescription.issue_date", "updateResult": "{@ordPrescriptionNo:''ord_prescription_no'', @facilityCd:''facility_cd'', @patId:''pat_id'',  @prescriptionDetailFlg:'''', @prescriptionDetailValue:''prescription_detail'', @prescriptionDetail.r:'''', @prescriptionDetail.f1:'''', @prescriptionDetail.f2:'''', @prescriptionDetail.f3:'''', @prescriptionDetail.f4:'''', @prescriptionDetail.f5:'''', @prescriptionDetail.f6:'''', @prescriptionDetail.rp:'''', @prescriptionDetail.type:'''', @prescriptionDetail.unchg:'''', @prescriptionDetail.medicineCd:'''', @prescriptionDetail.medicineType:'''', @prescriptionDetail.medicineUnit1:'''', @prescriptionDetail.medicineUnit2:''''}"}, {"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータ[処方詳細(prescription_detail)内容(薬剤部分)]を新規登録する。", "No3": "json場合、[D]の設定が必要です。しかし、NECの処方情報をクリアしません。judgeに[crud#=#NG]を設定する。", "crud": "D", "kind": "1", "judge": "$journal.const.crud#=#NG", "table": "ord_prescription_1", "ctl_no": "2", "sqlCode": 9302}, {"No1": "モードが「A：登録」、かつ、実施進捗１が「B：発行済」の場合、取り込む。", "No2": "処方情報(ord_prescription)のデータ[処方詳細(prescription_detail)内容(薬剤部分)]を新規登録する。", "crud": "U", "kind": "1", "judge": "$journal.const.crud#=#C,$journal.ord_prescription.order_status1#=#B", "table": "ord_prescription_1", "ctl_no": "3", "sqlCode": 9309, "@issueDate": "$journal.ord_prescription.issue_date", "@prescriptionDetail.rp": "$journal.detail.ord_prescription.prescription_detail.rp", "@prescriptionDetail.quantity": "$journal.detail.ord_prescription.prescription_detail.quantity", "@prescriptionDetail.medicineCode": "$journal.detail.ord_prescription.prescription_detail.medicine_code"}]}}', '1', '0', -1, '2019-12-13 05:44:54', '2019-12-13 05:44:54');
