DELETE FROM mst_coop_apilink
WHERE ctl_no IN (-1102000, -1102001, -1102002, -1103000, -1103001, -1103002, -1104000, -1104001, -1104002, -1107001, -1107002, -1108001, -1110001, -1110002, -1110003, -1111001, -1111002, -1112001);

INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1102000, 'Secom', 'ind_dial', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1102027, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-29 13:44:51.120', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1102001, 'Secom', 'ind_dial', '', 'U', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1102027, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-29 13:44:51.120', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1102002, 'Secom', 'ind_dial', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1102027, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-29 13:44:51.120', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1103000, 'Secom', 'rst_dial', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1103015, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-01 17:08:51.783', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1103001, 'Secom', 'rst_dial', '', 'U', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1103015, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-01 17:08:51.783', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1103002, 'Secom', 'rst_dial', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1103015, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-01 17:08:51.783', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1104000, 'Secom', 'accept', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1104005, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-13 15:13:29.863', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1104001, 'Secom', 'accept', '', 'U', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1104005, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-13 15:13:29.863', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1104002, 'Secom', 'accept', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "sendStatus": "0", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1104005, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-13 15:13:29.863', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1107001, 'Secom', 'rst_dial', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/create', 'POST', '{"crud": "C", "ope_cd": "006103", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "$JOURNAL.coop_version"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-01 01:06:50.056', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1107002, 'Secom', 'rst_dial', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/create', 'POST', '{"crud": "D", "ope_cd": "006105", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "$JOURNAL.coop_version"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-01 01:06:57.559', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1108001, 'Secom', 'rep_dial', 'pdf', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1108001}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-01 22:49:03.102', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1110001, 'Secom', 'exam_ord', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd"}, "sqlCode": -1105011, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-11 12:47:22.660', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1110002, 'Secom', 'exam_ord', '', 'U', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"key0": "$JOURNAL.key0", "ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd"}, "sqlCode": -1105011, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-11 12:47:22.660', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1110003, 'Secom', 'exam_ord', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd"}, "sqlCode": -1105012, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-11 12:47:22.660', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1111001, 'Secom', 'rad_ord', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1106005, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-14 21:24:14.314', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1111002, 'Secom', 'rad_ord', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ctlNo": "$JOURNAL.ctl_no", "ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "facilityCd": "$JOURNAL.facility_cd", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1106005, "facilityCd": "$JOURNAL.facility_cd", "coop_version": "Secom"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-07-14 21:24:14.314', CURRENT_TIMESTAMP, '0', NULL, 'Secom');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-1112001, 'Secom', 'karte_ord', '', 'C', 'S', 'AS', 'A', 1, 'http://localhost:8080/ntss-coop-api/runDataSet', 'POST', '{"dataKey": {"ordNo": "$JOURNAL.ord_no", "patId": "$JOURNAL.pat_id", "coopCd": "$JOURNAL.coop_cd", "facilityCd": "$JOURNAL.facility_cd", "coopVersion": "$JOURNAL.coop_version"}, "sqlCode": -1107008}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-08-10 12:29:24.081', CURRENT_TIMESTAMP, '0', NULL, 'Secom');