UPDATE	ntss.sys_data_list_detail	SET	master_display_name='DW（kg）',	function_display_name='DW（kg）'	WHERE	data_list_detail_cd=279;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='目標体重（kg）',	function_display_name='目標体重（kg）'	WHERE	data_list_detail_cd=280;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='降水量制限（L）',	function_display_name='降水量制限（L）'	WHERE	data_list_detail_cd=281;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='血流量（mL/min）',	function_display_name='血流量（mL/min）'	WHERE	data_list_detail_cd=291;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析液流量（mL/min）',	function_display_name='透析液流量（mL/min）'	WHERE	data_list_detail_cd=293;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析液温度（°C）',	function_display_name='透析液温度（°C）'	WHERE	data_list_detail_cd=295;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液量（L）',	function_display_name='補液量（L）'	WHERE	data_list_detail_cd=297;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液速度（°C）',	function_display_name='補液速度（°C）'	WHERE	data_list_detail_cd=301;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='抗凝固剤（L/h）',	function_display_name='抗凝固剤（L/h）'	WHERE	data_list_detail_cd=302;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP速度（mL/h）',	function_display_name='IP速度（mL/h）'	WHERE	data_list_detail_cd=309;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP速度最大値（mL/h）',	function_display_name='IP速度最大値（mL/h）'	WHERE	data_list_detail_cd=310;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP電源自動切り時間（min）',	function_display_name='IP電源自動切り時間（min）'	WHERE	data_list_detail_cd=313;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP電源OKモニタ切り時間（min）',	function_display_name='IP電源OKモニタ切り時間（min）'	WHERE	data_list_detail_cd=315;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・名称（g・kg）',	function_display_name='項目1・名称（g・kg）'	WHERE	data_list_detail_cd=516;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・重さ（g・kg）',	function_display_name='項目1・重さ（g・kg）'	WHERE	data_list_detail_cd=517;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・名称（g・kg）',	function_display_name='項目2・名称（g・kg）'	WHERE	data_list_detail_cd=518;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・重さ（g・kg）',	function_display_name='項目2・重さ（g・kg）'	WHERE	data_list_detail_cd=519;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・名称（g・kg）',	function_display_name='項目3・名称（g・kg）'	WHERE	data_list_detail_cd=520;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・重さ（g・kg）',	function_display_name='項目3・重さ（g・kg）'	WHERE	data_list_detail_cd=521;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・名称（g・kg）',	function_display_name='項目4・名称（g・kg）'	WHERE	data_list_detail_cd=522;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・重さ（g・kg）',	function_display_name='項目4・重さ（g・kg）'	WHERE	data_list_detail_cd=523;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・名称（g・kg）',	function_display_name='項目5・名称（g・kg）'	WHERE	data_list_detail_cd=524;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・重さ（g・kg）',	function_display_name='項目5・重さ（g・kg）'	WHERE	data_list_detail_cd=525;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='風袋補正合計量（g・kg）',	function_display_name='風袋補正合計量（g・kg）'	WHERE	data_list_detail_cd=526;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・名称（g・kg）',	function_display_name='項目1・名称（g・kg）'	WHERE	data_list_detail_cd=527;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・重さ（g・kg）',	function_display_name='項目1・重さ（g・kg）'	WHERE	data_list_detail_cd=528;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・名称（g・kg）',	function_display_name='項目2・名称（g・kg）'	WHERE	data_list_detail_cd=529;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・重さ（g・kg）',	function_display_name='項目2・重さ（g・kg）'	WHERE	data_list_detail_cd=530;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・名称（g・kg）',	function_display_name='項目3・名称（g・kg）'	WHERE	data_list_detail_cd=531;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・重さ（g・kg）',	function_display_name='項目3・重さ（g・kg）'	WHERE	data_list_detail_cd=532;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・名称（g・kg）',	function_display_name='項目4・名称（g・kg）'	WHERE	data_list_detail_cd=533;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・重さ（g・kg）',	function_display_name='項目4・重さ（g・kg）'	WHERE	data_list_detail_cd=534;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・名称（g・kg）',	function_display_name='項目5・名称（g・kg）'	WHERE	data_list_detail_cd=535;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・重さ（g・kg）',	function_display_name='項目5・重さ（g・kg）'	WHERE	data_list_detail_cd=536;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='除水補正合計量（g・kg）',	function_display_name='除水補正合計量（g・kg）'	WHERE	data_list_detail_cd=537;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='工数切替時間（min）',	function_display_name='工数切替時間（min）'	WHERE	data_list_detail_cd=584;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='Ｎａ注入濃度最大値（mEq/L）',	function_display_name='Ｎａ注入濃度最大値（mEq/L）'	WHERE	data_list_detail_cd=589;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量1（mL/min）',	function_display_name='QBプログラム血流量1（mL/min）'	WHERE	data_list_detail_cd=621;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量2（mL/min）',	function_display_name='QBプログラム血流量2（mL/min）'	WHERE	data_list_detail_cd=622;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量3（mL/min）',	function_display_name='QBプログラム血流量3（mL/min）'	WHERE	data_list_detail_cd=623;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量4（mL/min）',	function_display_name='QBプログラム血流量4（mL/min）'	WHERE	data_list_detail_cd=624;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量5（mL/min）',	function_display_name='QBプログラム血流量5（mL/min）'	WHERE	data_list_detail_cd=625;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量6（mL/min）',	function_display_name='QBプログラム血流量6（mL/min）'	WHERE	data_list_detail_cd=626;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量7（mL/min）',	function_display_name='QBプログラム血流量7（mL/min）'	WHERE	data_list_detail_cd=627;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量8（mL/min）',	function_display_name='QBプログラム血流量8（mL/min）'	WHERE	data_list_detail_cd=628;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量9（mL/min）',	function_display_name='QBプログラム血流量9（mL/min）'	WHERE	data_list_detail_cd=629;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QBプログラム血流量10（mL/min）',	function_display_name='QBプログラム血流量10（mL/min）'	WHERE	data_list_detail_cd=630;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量1（mL/min）',	function_display_name='QDプログラム透析液流量1（mL/min）'	WHERE	data_list_detail_cd=632;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量2（mL/min）',	function_display_name='QDプログラム透析液流量2（mL/min）'	WHERE	data_list_detail_cd=633;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量3（mL/min）',	function_display_name='QDプログラム透析液流量3（mL/min）'	WHERE	data_list_detail_cd=634;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量4（mL/min）',	function_display_name='QDプログラム透析液流量4（mL/min）'	WHERE	data_list_detail_cd=635;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量5（mL/min）',	function_display_name='QDプログラム透析液流量5（mL/min）'	WHERE	data_list_detail_cd=636;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量6（mL/min）',	function_display_name='QDプログラム透析液流量6（mL/min）'	WHERE	data_list_detail_cd=637;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量7（mL/min）',	function_display_name='QDプログラム透析液流量7（mL/min）'	WHERE	data_list_detail_cd=638;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量8（mL/min）',	function_display_name='QDプログラム透析液流量8（mL/min）'	WHERE	data_list_detail_cd=639;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量9（mL/min）',	function_display_name='QDプログラム透析液流量9（mL/min）'	WHERE	data_list_detail_cd=640;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QDプログラム透析液流量10（mL/min）',	function_display_name='QDプログラム透析液流量10（mL/min）'	WHERE	data_list_detail_cd=641;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間1（min）',	function_display_name='QB,QBプログラム切替時間1（min）'	WHERE	data_list_detail_cd=642;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間2（min）',	function_display_name='QB,QBプログラム切替時間2（min）'	WHERE	data_list_detail_cd=643;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間3（min）',	function_display_name='QB,QBプログラム切替時間3（min）'	WHERE	data_list_detail_cd=644;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間4（min）',	function_display_name='QB,QBプログラム切替時間4（min）'	WHERE	data_list_detail_cd=645;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間5（min）',	function_display_name='QB,QBプログラム切替時間5（min）'	WHERE	data_list_detail_cd=646;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間6（min）',	function_display_name='QB,QBプログラム切替時間6（min）'	WHERE	data_list_detail_cd=647;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間7（min）',	function_display_name='QB,QBプログラム切替時間7（min）'	WHERE	data_list_detail_cd=648;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間8（min）',	function_display_name='QB,QBプログラム切替時間8（min）'	WHERE	data_list_detail_cd=649;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='QB,QBプログラム切替時間9（min）',	function_display_name='QB,QBプログラム切替時間9（min）'	WHERE	data_list_detail_cd=650;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液速度（ml/min）',	function_display_name='補液速度（ml/min）'	WHERE	data_list_detail_cd=653;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液周期（min）',	function_display_name='補液周期（min）'	WHERE	data_list_detail_cd=654;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液量（mL）',	function_display_name='補液量（mL）'	WHERE	data_list_detail_cd=655;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液開始時間（min）',	function_display_name='補液開始時間（min）'	WHERE	data_list_detail_cd=656;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='除水再開時間（min）',	function_display_name='除水再開時間（min）'	WHERE	data_list_detail_cd=657;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='TMPゼロ補正時間（sec）',	function_display_name='TMPゼロ補正時間（sec）'	WHERE	data_list_detail_cd=660;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='予定補液回数（n）',	function_display_name='予定補液回数（n）'	WHERE	data_list_detail_cd=662;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='予定補液量（L）',	function_display_name='予定補液量（L）'	WHERE	data_list_detail_cd=663;									
																
UPDATE ntss.sys_data_list_detail SET  master_display_name='ＵＦＣ期間除水速度上限（L/h）',  function_display_name='ＵＦＣ期間除水速度上限（L/h）' WHERE data_list_detail_cd=697;
UPDATE ntss.sys_data_list_detail SET  master_display_name='ＵＦＣ期間除水速度下限（L/h）',  function_display_name='ＵＦＣ期間除水速度下限（L/h）' WHERE data_list_detail_cd=698;
UPDATE ntss.sys_data_list_detail SET  master_display_name='開始期間　時間（min）', function_display_name='開始期間　時間（min）' WHERE data_list_detail_cd=699;
UPDATE ntss.sys_data_list_detail SET  master_display_name='固定倍率除水期間　時間（min）', function_display_name='固定倍率除水期間　時間（min）' WHERE data_list_detail_cd=701;
UPDATE ntss.sys_data_list_detail SET  master_display_name='固定倍率除水終了条件　最高血圧（mmHg）', function_display_name='固定倍率除水終了条件　最高血圧（mmHg）' WHERE data_list_detail_cd=703;
UPDATE ntss.sys_data_list_detail SET  master_display_name='固定倍率除水終了条件　脈拍（bpm）', function_display_name='固定倍率除水終了条件　脈拍（bpm）' WHERE data_list_detail_cd=704;
UPDATE ntss.sys_data_list_detail SET  master_display_name='固定倍率除水終了条件　ΔBV（%）', function_display_name='固定倍率除水終了条件　ΔBV（%）' WHERE data_list_detail_cd=705;
UPDATE ntss.sys_data_list_detail SET  master_display_name='終了前期間　時間（min）',  function_display_name='終了前期間　時間（min）' WHERE data_list_detail_cd=706;
UPDATE ntss.sys_data_list_detail SET  master_display_name='開始時ΔBV基準値（%）',  function_display_name='開始時ΔBV基準値（%）' WHERE data_list_detail_cd=707;
UPDATE ntss.sys_data_list_detail SET  master_display_name='終了時ΔBV基準値（%）',  function_display_name='終了時ΔBV基準値（%）' WHERE data_list_detail_cd=711;

UPDATE	ntss.sys_data_list_detail	SET	master_display_name='前回後体重（kg）',	function_display_name='前回後体重（kg）'	WHERE	data_list_detail_cd=751;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析前体重測定値（kg）',	function_display_name='透析前体重測定値（kg）'	WHERE	data_list_detail_cd=752;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析前体重（kg）',	function_display_name='透析前体重（kg）'	WHERE	data_list_detail_cd=753;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='DW（kg）',	function_display_name='DW（kg）'	WHERE	data_list_detail_cd=755;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='CTR（%）',	function_display_name='CTR（%）'	WHERE	data_list_detail_cd=756;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='CTR測定時体重（kg）',	function_display_name='CTR測定時体重（kg）'	WHERE	data_list_detail_cd=757;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='目標体重（kg）',	function_display_name='目標体重（kg）'	WHERE	data_list_detail_cd=759;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='目標除水量（L）',	function_display_name='目標除水量（L）'	WHERE	data_list_detail_cd=760;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='実績除水量（L）',	function_display_name='実績除水量（L）'	WHERE	data_list_detail_cd=761;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='除水積算値（L）',	function_display_name='除水積算値（L）'	WHERE	data_list_detail_cd=762;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='捕液量積算（L）',	function_display_name='捕液量積算（L）'	WHERE	data_list_detail_cd=763;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析後体重測定値（kg）',	function_display_name='透析後体重測定値（kg）'	WHERE	data_list_detail_cd=764;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析後体重（kg）',	function_display_name='透析後体重（kg）' 	WHERE	data_list_detail_cd=765;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='減少量（kg）',	function_display_name='減少量（kg）'	WHERE	data_list_detail_cd=767;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='URR（%）',	function_display_name='URR（%）'	WHERE	data_list_detail_cd=773;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='DW（kg）',	function_display_name='DW（kg）'	WHERE	data_list_detail_cd=795;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='目標体重（kg）',	function_display_name='目標体重（kg）'	WHERE	data_list_detail_cd=796;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='降水量制限（L）',	function_display_name='降水量制限（L）'	WHERE	data_list_detail_cd=797;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='血流量（mL/min）',	function_display_name='血流量（mL/min）'	WHERE	data_list_detail_cd=807;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析液流量（mL/min）',	function_display_name='透析液流量（mL/min）'	WHERE	data_list_detail_cd=809;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='透析液温度（°C）',	function_display_name='透析液温度（°C）'		WHERE	data_list_detail_cd=811;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液量（L）',	function_display_name='補液量（L）'		WHERE	data_list_detail_cd=813;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液温度（°C）',	function_display_name='補液温度（°C）'	WHERE	data_list_detail_cd=816;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='補液速度（L/h）',	function_display_name='補液速度（L/h）'	WHERE	data_list_detail_cd=817;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP速度（mL/h）',	function_display_name='IP速度（mL/h）'	WHERE	data_list_detail_cd=825;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP速度最大値（mL/h）',	function_display_name='IP速度最大値（mL/h）'	WHERE	data_list_detail_cd=826;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP電源自動切り時間（min）',	function_display_name='IP電源自動切り時間（min）'	WHERE	data_list_detail_cd=829;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='IP電源OKモニタ切り時間（min）',	function_display_name='IP電源OKモニタ切り時間（min）'	WHERE	data_list_detail_cd=831;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・名称（g・kg）',	function_display_name='項目1・名称（g・kg）'	WHERE	data_list_detail_cd=1032;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・重さ（g・kg）',	function_display_name='項目1・重さ（g・kg）'	WHERE	data_list_detail_cd=1033;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・名称（g・kg）',	function_display_name='項目2・名称（g・kg）'	WHERE	data_list_detail_cd=1034;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・重さ（g・kg）',	function_display_name='項目2・重さ（g・kg）'	WHERE	data_list_detail_cd=1035;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・名称（g・kg）',	function_display_name='項目3・名称（g・kg）'	WHERE	data_list_detail_cd=1036;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・重さ（g・kg）',	function_display_name='項目3・重さ（g・kg）'	WHERE	data_list_detail_cd=1037;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・名称（g・kg）',	function_display_name='項目4・名称（g・kg）'	WHERE	data_list_detail_cd=1038;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・重さ（g・kg）',	function_display_name='項目4・重さ（g・kg）'	WHERE	data_list_detail_cd=1039;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・名称（g・kg）',	function_display_name='項目5・名称（g・kg）'	WHERE	data_list_detail_cd=1040;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・重さ（g・kg）',	function_display_name='項目5・重さ（g・kg）'	WHERE	data_list_detail_cd=1041;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='風袋補正合計量（g・kg）',	function_display_name='風袋補正合計量（g・kg）'	WHERE	data_list_detail_cd=1042;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・名称（g・kg）',	function_display_name='項目1・名称（g・kg）'	WHERE	data_list_detail_cd=1043;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・重さ（g・kg）',	function_display_name='項目1・重さ（g・kg）'	WHERE	data_list_detail_cd=1044;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・名称（g・kg）',	function_display_name='項目2・名称（g・kg）'	WHERE	data_list_detail_cd=1045;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・重さ（g・kg）',	function_display_name='項目2・重さ（g・kg）'	WHERE	data_list_detail_cd=1046;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・名称（g・kg）',	function_display_name='項目3・名称（g・kg）'	WHERE	data_list_detail_cd=1047;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・重さ（g・kg）',	function_display_name='項目3・重さ（g・kg）'	WHERE	data_list_detail_cd=1048;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・名称（g・kg）',	function_display_name='項目4・名称（g・kg）'	WHERE	data_list_detail_cd=1049;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・重さ（g・kg）',	function_display_name='項目4・重さ（g・kg）'	WHERE	data_list_detail_cd=1050;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・名称（g・kg）',	function_display_name='項目5・名称（g・kg）'	WHERE	data_list_detail_cd=1051;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・重さ（g・kg）',	function_display_name='項目5・重さ（g・kg）'	WHERE	data_list_detail_cd=1052;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='除水補正合計量（g・kg）',	function_display_name='除水補正合計量（g・kg）'	WHERE	data_list_detail_cd=1053;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・名称（g・kg）',	function_display_name='項目1・名称（g・kg）'	WHERE	data_list_detail_cd=1054;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・重さ（g・kg）',	function_display_name='項目1・重さ（g・kg）'	WHERE	data_list_detail_cd=1055;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・名称（g・kg）',	function_display_name='項目2・名称（g・kg）'	WHERE	data_list_detail_cd=1056;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・重さ（g・kg）',	function_display_name='項目2・重さ（g・kg）'	WHERE	data_list_detail_cd=1057;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・名称（g・kg）',	function_display_name='項目3・名称（g・kg）'	WHERE	data_list_detail_cd=1058;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・重さ（g・kg）',	function_display_name='項目3・重さ（g・kg）'	WHERE	data_list_detail_cd=1059;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・名称（g・kg）',	function_display_name='項目4・名称（g・kg）'	WHERE	data_list_detail_cd=1060;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・重さ（g・kg）',	function_display_name='項目4・重さ（g・kg）'	WHERE	data_list_detail_cd=1061;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・名称（g・kg）',	function_display_name='項目5・名称（g・kg）'	WHERE	data_list_detail_cd=1062;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・重さ（g・kg）',	function_display_name='項目5・重さ（g・kg）'	WHERE	data_list_detail_cd=1063;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='風袋補正合計量（g・kg）',	function_display_name='風袋補正合計量（g・kg）'	WHERE	data_list_detail_cd=1064;									
																
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・名称（g・kg）',	function_display_name='項目1・名称（g・kg）'	WHERE	data_list_detail_cd=1065;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目1・重さ（g・kg）',	function_display_name='項目1・重さ（g・kg）'	WHERE	data_list_detail_cd=1066;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・名称（g・kg）',	function_display_name='項目2・名称（g・kg）'	WHERE	data_list_detail_cd=1067;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目2・重さ（g・kg）',	function_display_name='項目2・重さ（g・kg）'	WHERE	data_list_detail_cd=1068;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・名称（g・kg）',	function_display_name='項目3・名称（g・kg）'	WHERE	data_list_detail_cd=1069;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目3・重さ（g・kg）',	function_display_name='項目3・重さ（g・kg）'	WHERE	data_list_detail_cd=1070;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・名称（g・kg）',	function_display_name='項目4・名称（g・kg）'	WHERE	data_list_detail_cd=1071;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目4・重さ（g・kg）',	function_display_name='項目4・重さ（g・kg）'	WHERE	data_list_detail_cd=1072;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・名称（g・kg）',	function_display_name='項目5・名称（g・kg）'	WHERE	data_list_detail_cd=1073;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='項目5・重さ（g・kg）',	function_display_name='項目5・重さ（g・kg）'	WHERE	data_list_detail_cd=1074;									
UPDATE	ntss.sys_data_list_detail	SET	master_display_name='除水補正合計量（g・kg）',	function_display_name='除水補正合計量（g・kg）'	WHERE	data_list_detail_cd=1075;									