---- 連携エッジヘルスモニタ
---- 項目追加
--ALTER TABLE mnt_if_edge_healthmon ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN mnt_if_edge_healthmon.coop_version IS E'連携版番号';
--
---- 連携API関連付けマスタ
---- 項目追加
--ALTER TABLE mst_coop_apilink ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN mst_coop_apilink.coop_version IS E'連携版番号';
--
---- 連携配信設定マスタ
---- 項目追加
--ALTER TABLE mst_coop_distribute ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN mst_coop_distribute.coop_version IS E'連携版番号';
--
---- 外部連携用ファイル名管理
---- 項目追加
--ALTER TABLE mst_coop_filename ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN mst_coop_filename.coop_version IS E'連携版番号';
--
---- 連携電文設定マスタ
---- 項目追加
--ALTER TABLE mst_coop_layout ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN mst_coop_layout.coop_version IS E'連携版番号';
--
---- 連携電文設定マスタ詳細
---- 項目追加
--ALTER TABLE mst_coop_layout_detail ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN mst_coop_layout_detail.coop_version IS E'連携版番号';
--
---- 患者連携情報
---- 項目追加
--ALTER TABLE sys_coop_no ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN sys_coop_no.coop_version IS E'連携版番号';
--
---- 連携オーダ番号
---- 項目追加
--ALTER TABLE ord_coop_no ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN ord_coop_no.coop_version IS E'連携版番号';
--
---- 患者連携情報
---- 項目追加
--ALTER TABLE pat_coop_detail ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN pat_coop_detail.coop_version IS E'連携版番号';
--
---- 外部連携用ジャーナル
---- 項目追加
--ALTER TABLE sys_coop_journal ADD COLUMN coop_version character varying(10) NOT NULL DEFAULT '';
--ALTER TABLE sys_coop_journal ADD COLUMN key0 character varying(20) NOT NULL DEFAULT '';
---- コメント追加
--COMMENT ON COLUMN sys_coop_journal.coop_version IS E'連携版番号';
--COMMENT ON COLUMN sys_coop_journal.key0 IS E'電子カルテ種別';
