--INSERT INTO ntss.sys_data_set
--(sql_cd, "sql", db_class, detail, can_repeat, use_application, report_class, memo, reg_date, up_date, pre_sql_info)
--VALUES(-610905, 'WITH pat_grp_cds AS(
--  SELECT
--    pat_group_cd
--  FROM
--    pat_group_detail
--  WHERE
--    facility_cd = @facilityCd
--  AND pat_id = @patId
--),
--pg AS(
--  SELECT
--    pat_group_cd,
--    in_hospital_cd_1
--  FROM
--    pat_group
--  WHERE
--    facility_cd = @facilityCd
--  AND pat_group_cd IN (SELECT pat_group_cd FROM pat_grp_cds)
--  AND COALESCE(in_hospital_cd_1,'''') <> ''''
--)
--SELECT
--  ROW_NUMBER() OVER() AS idx,
--  pg.in_hospital_cd_1
--FROM
--  mst_selector mss
--  CROSS JOIN LATERAL jsonb_to_recordset(mss.order_settings -> ''items'') AS ms(code BIGINT, NAME TEXT)
--  INNER JOIN pg
--  ON  ms.code = pg.pat_group_cd
--WHERE
--  facility_cd = @facilityCd
--AND master_physical_name = ''pat_group''
--AND code IN (SELECT pat_group_cd FROM pg)
--ORDER BY
--  idx ASC
--LIMIT 1', 2, '[]'::jsonb, '0', '{"applications": [4]}'::jsonb, NULL, 'MIRAIS 患者グループ取得', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
--------