delete from "mst_coop_distribute" where "ctl_no" in (-701,-702,-703,-704,-705,-706,-707,-708);
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-701, 'NEC-iS', 'profile', '', 'S', 'NEC-iS(MegaOakiS)', '患者プロファイル', '1', '{"protocolInfo": {"address": "http://172.30.15.190:9100/DataServiceProviderService.svc/B01_PatientProfileByPatientIdAndDateTime", "timeout": "50000", "protocol": "soap", "retryMax": "3", "sendType": "request"}}', '1', '0', -1, '2021-12-09 01:39:03.727', '2021-12-09 01:39:03.727');
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-702, 'NEC-iS', 'ind_dial', '', 'S', 'NEC-iS(MegaOakiS)', '透析予約', '1', '{"protocolInfo": {"address": "http://172.30.15.190:9100/DataServiceProviderService.svc/B01_RegistDialysisIndicationFromDialysis", "timeout": "50000", "protocol": "soap", "retryMax": "3", "sendType": "send"}}', '1', '0', -1, '2021-12-09 01:39:03.73', '2021-12-09 01:39:03.73');
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-703, 'NEC-iS', 'rst_dial', '', 'S', 'NEC-iS(MegaOakiS)', '透析実績', '1', '{"protocolInfo": {"address": "http://172.30.15.190:9100/DataServiceProviderService.svc/B01_RegistDialysisExecutionFromDialysis", "timeout": "50000", "protocol": "soap", "retryMax": "3", "sendType": "send"}}', '1', '0', -1, '2021-12-09 01:39:03.733', '2021-12-09 01:39:03.733');
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-704, 'NEC-iS', 'exam_rst', '', 'S', 'NEC-iS(MegaOakiS)', '検査結果', '1', '{"protocolInfo": {"address": "http://172.30.15.190:9100/DataServiceProviderService.svc/B01_GeneralTestResultsByPatientIdAndPeriod", "timeout": "50000", "protocol": "soap", "retryMax": "3", "sendType": "request"}}', '1', '0', -1, '2021-09-01 07:38:43.683', '2021-09-01 07:38:43.683');
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-705, 'NEC-iS', 'rep_dial', 'pdf', 'S', 'NEC-iS(MegaOakiS)', '透析レポート', '1', '{"protocolInfo": {"dummy": "false", "delete": "true", "address": "/mnt/dia_rep/$HOSP_PAT_ID", "replace": "report_merge", "protocol": "file", "hospPatIdLen": "0", "renameWhenCopying": ""}}', '1', '0', -1, '2021-12-09 01:39:03.736', '2021-12-09 01:39:03.736');
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-706, 'NEC-iS', 'rep_dial', 'xml', 'S', 'NEC-iS(MegaOakiS)', '透析レポート', '1', '{"protocolInfo": {"dummy": "false", "delete": "true", "address": "/mnt/dia_rep/$HOSP_PAT_ID", "replace": "report_merge", "protocol": "file", "hospPatIdLen": "0", "renameWhenCopying": ""}}', '1', '0', -1, '2021-12-09 01:39:03.739', '2021-12-09 01:39:03.739');
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-707, 'NEC-iS', 'rep_dial', 'listxml', 'S', 'NEC-iS(MegaOakiS)', '透析レポート', '1', '{"protocolInfo": {"dummy": "false", "delete": "true", "address": "/mnt/dia_rep", "replace": "report_merge", "protocol": "file", "hospPatIdLen": "0", "renameWhenCopying": ""}}', '1', '0', -1, '2021-12-09 01:39:03.743', '2021-12-09 01:39:03.743');
INSERT INTO "mst_coop_distribute"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_vender", "description", "is_editable", "distribute_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-708, 'NEC-iS', 'rep_dial', 'tar', 'S', 'NEC-iS(MegaOakiS)', '透析レポート', '1', '{"protocolInfo": {"dummy": "false", "delete": "true", "address": "/mnt/dia_rep", "replace": "report_merge", "protocol": "file", "renameWhenCopying": ""}}', '1', '0', -1, '2021-12-09 01:39:03.746', '2021-12-09 01:39:03.746');
