--DELETE FROM ntss.sys_coop_no
--WHERE ctl_no = -601
--;
--
--INSERT INTO ntss.sys_coop_no
--(ctl_no, facility_cd, coop_ord_cd, cur_coop_ord_no, no_of_digit, padding_char, padding_pos, range_max, range_min, prefix_char, suffix_char, is_disp, is_del, user_id, reg_date, up_date, coop_cd, coop_cd_index, coop_version)
--VALUES(-601, 'C_hosp', '[{"ord_cd": "ind_dial"}]'::jsonb, 1, 10, '0', 'left', 9999999999, 1, '', '', '1', '0', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '');
--INSERT INTO ntss.sys_coop_no
--(ctl_no, facility_cd, coop_ord_cd, cur_coop_ord_no, no_of_digit, padding_char, padding_pos, range_max, range_min, prefix_char, suffix_char, is_disp, is_del, user_id, reg_date, up_date, coop_cd, coop_cd_index, coop_version)
--VALUES(-602, 'C_hosp', '[{"ord_cd": "rst_dial"}]'::jsonb, 1, 10, '0', 'left', 9999999999, 1, '', '', '1', '0', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '');
--INSERT INTO ntss.sys_coop_no
--(ctl_no, facility_cd, coop_ord_cd, cur_coop_ord_no, no_of_digit, padding_char, padding_pos, range_max, range_min, prefix_char, suffix_char, is_disp, is_del, user_id, reg_date, up_date, coop_cd, coop_cd_index, coop_version)
--VALUES(-603, 'C_hosp', '[{"ord_cd": "exam_ord"}]'::jsonb, 1, 10, '0', 'left', 9999999999, 1, '', '', '1', '0', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '');
--INSERT INTO ntss.sys_coop_no
--(ctl_no, facility_cd, coop_ord_cd, cur_coop_ord_no, no_of_digit, padding_char, padding_pos, range_max, range_min, prefix_char, suffix_char, is_disp, is_del, user_id, reg_date, up_date, coop_cd, coop_cd_index, coop_version)
--VALUES(-604, 'C_hosp', '[{"ord_cd": "rep_dial"}]'::jsonb, 1, 10, '0', 'left', 9999999999, 1, '', '', '1', '0', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '');