DELETE FROM mst_coop_apilink
WHERE ctl_no IN (-303001, -303002, -303003, -303004, -303005, -303006);

INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-303001, 'P_hosp', 'profile', '', 'C', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/createIfOrdNoExists', 'POST', '{"crud": "$JOURNAL.crud", "ope_cd": "032001", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "coop_cd": "rst_dial", "message": "$JOURNAL.ope_cd", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "MED"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-06-19 10:54:41.499', CURRENT_TIMESTAMP, '0', NULL, 'MED');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-303002, 'P_hosp', 'profile', '', 'C', 'S', 'CE', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/createIfOrdNoExists', 'POST', '{"crud": "$JOURNAL.crud", "ope_cd": "032001", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "coop_cd": "rst_dial", "message": "$JOURNAL.ope_cd", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "MED"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-06-19 10:54:41.499', CURRENT_TIMESTAMP, '0', NULL, 'MED');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-303003, 'P_hosp', 'profile', '', 'U', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/createIfOrdNoExists', 'POST', '{"crud": "$JOURNAL.crud", "ope_cd": "032001", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "coop_cd": "rst_dial", "message": "$JOURNAL.ope_cd", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "MED"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-06-19 10:54:41.499', CURRENT_TIMESTAMP, '0', NULL, 'MED');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-303004, 'P_hosp', 'profile', '', 'U', 'S', 'CE', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/createIfOrdNoExists', 'POST', '{"crud": "$JOURNAL.crud", "ope_cd": "032001", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "coop_cd": "rst_dial", "message": "$JOURNAL.ope_cd", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "MED"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-06-19 10:54:41.499', CURRENT_TIMESTAMP, '0', NULL, 'MED');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-303005, 'P_hosp', 'profile', '', 'D', 'S', 'C9', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/createIfOrdNoExists', 'POST', '{"crud": "$JOURNAL.crud", "ope_cd": "032001", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "coop_cd": "rst_dial", "message": "$JOURNAL.ope_cd", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "MED"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-06-19 10:54:41.499', CURRENT_TIMESTAMP, '0', NULL, 'MED');
INSERT INTO mst_coop_apilink
(ctl_no, facility_cd, coop_cd, coop_cd_index, crud, direction, api_timing_io, api_timing_ba, api_timing_seq, api_uri, api_method, api_body, continue_api_status, after_api_status, is_del, user_id, reg_date, up_date, api_type, sql_setting, coop_version)
VALUES(-303006, 'P_hosp', 'profile', '', 'D', 'S', 'CE', 'A', 1, 'http://localhost:8080/ntss-coop-api/journal/createIfOrdNoExists', 'POST', '{"crud": "$JOURNAL.crud", "ope_cd": "032001", "ord_no": "$JOURNAL.ord_no", "pat_id": "$JOURNAL.pat_id", "coop_cd": "rst_dial", "message": "$JOURNAL.ope_cd", "user_id": "$JOURNAL.user_id", "base_date": "$JOURNAL.base_date", "facility_cd": "$JOURNAL.facility_cd", "hosp_pat_id": "$JOURNAL.hosp_pat_id", "coop_version": "MED"}'::jsonb, '{"exit_code": [], "continue_code": [200]}'::jsonb, '{}'::jsonb, '0', -1, '2025-06-19 10:54:41.499', CURRENT_TIMESTAMP, '0', NULL, 'MED');