INSERT INTO sys_notification(
  notification_no,
  notification_category,
  setting_name,
  message,
  additional_info,
  disp_order,
  available_keys,
  is_disp,
  is_del,
  reg_date,
  up_date,
  help
) VALUES (
  '3',
  '10',
  '感染症患者ON通知',
  '感染症患者ON：[LASTNAME] [FIRSTNAME] さんが感染症患者として登録されました。',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '2',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '感染症患者フラグがONにされると通知します。'
), (
  '4',
  '10',
  '感染症(＋)に変更通知',
  '感染症変更：[LASTNAME] [FIRSTNAME] さんの感染症情報が更新されました。',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '3',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '感染症が( + )にされると通知します。'
), (
  '5',
  '10',
  '禁忌・ｱﾚﾙｷﾞｰ追加・更新・削除通知',
  '禁忌情報更新：[LASTNAME] [FIRSTNAME] さんの禁忌・ｱﾚﾙｷﾞｰ情報が更新されました。',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '4',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '禁忌・ｱﾚﾙｷﾞｰ情報が更新されると通知します。'
), (
  '6',
  '10',
  '転入通知',
  '転入：[LASTNAME] [FIRSTNAME] さんの転入情報が登録されました。' || chr(10) || '【転入日】[STARTDATE]',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '5',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[STARTDATE]：転入日（YYYY年M月D日）、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が転入されると通知します。'
), (
  '7',
  '10',
  '転出通知',
  '転出：[LASTNAME] [FIRSTNAME] さんの転出情報が登録されました。' || chr(10) || '【転出日】[STARTDATE]',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '6',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[STARTDATE]：転出日（YYYY年M月D日）、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が転出されると通知します。'
), (
  '8',
  '10',
  '一時転出通知',
  '一時転出：[LASTNAME] [FIRSTNAME] さんの一時転出情報が登録されました。' || chr(10) || '【転出日】[STARTDATE]～[ENDDATE]',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '7',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[STARTDATE]：転出開始日（YYYY年M月D日）、[ENDDATE]：転出終了日（YYYY年M月D日）、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が一時転出されると通知します。'
), (
  '9',
  '10',
  '離脱通知',
  '離脱：[LASTNAME] [FIRSTNAME] さんの離脱情報が登録されました。' || chr(10) || '【離脱日】[STARTDATE]',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '8',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[STARTDATE]：離脱日（YYYY年M月D日）、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が離脱されると通知します。'
), (
  '10',
  '10',
  '移植通知',
  '移植：[LASTNAME] [FIRSTNAME] さんの移植手術情報が登録されました。' || chr(10) || '【手術日】[STARTDATE]',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '9',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[STARTDATE]：手術日（YYYY年M月D日）、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が移植されると通知します。'
), (
  '11',
  '10',
  '死亡通知',
  '死亡：[LASTNAME] [FIRSTNAME] さんの死亡情報が登録されました。' || chr(10) || '【死亡日】[DIEDATE]',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '10',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[DIEDATE]：死亡日（YYYY年M月D日）、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が亡くなられると通知します。'
), (
  '12',
  '10',
  'DW追加通知',
  'DW追加：[LASTNAME] [FIRSTNAME] さんのDW情報が登録されました。',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '11',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者のDWが登録されると通知します。'
), (
  '13',
  '10',
  '在宅患者ON通知',
  '在宅患者ON：[LASTNAME] [FIRSTNAME] さんが在宅患者として登録されました。',
  '{"FUNC": "025", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '12',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が在宅患者として登録されると通知します。'
), (
  '14',
  '10',
  '患者グループ通知',
  '患者グループ通知：[LASTNAME] [FIRSTNAME] さんが[PATGROUP][OPERATION]されました。',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '13',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[PATGROUP]：患者グループ名、[OPERATION]：操作(に追加/から削除)[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '患者が患者グループに追加および患者グループから削除されると通知します。'
), (
  '15',
  '10',
  '患者情報共有受理側通知',
  '患者情報共有受理：[LASTNAME] [FIRSTNAME] さんの患者情報共有受理が可能です。',
  '{"FUNC": "036", "FACILITYCD": "[FACILITYCD]"}',
  '14',
  '[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '他施設と患者情報の共有を受理できる状態のときに通知します。'
), (
  '16',
  '10',
  '担当者に設定通知',
  '担当者に設定：[STAFFLASTNAME] [STAFFFIRSTNAME] が [LASTNAME] [FIRSTNAME] さんの[STAFFTYPE]に設定されました。',
  '{"FUNC": "007", "PATID": "[PATID]", "FACILITYCD": "[FACILITYCD]"}',
  '15',
  '[STAFFLASTNAME]：担当者名(姓)、[STAFFFIRSTNAME]：担当者名(名)、[LASTNAME]：患者名(姓)、[FIRSTNAME]：患者名(名)、[STAFFTYPE]：担当者種別、[PATID]：内部患者ID、[FACILITYCD]：施設コード',
  '1',
  '0',
  now(),
  now(),
  '他施設と患者情報の共有を受理できる状態のときに通知します。'
);