-- ----------------------------
-- Table structure for V_DIALYSIS_COMP
-- ----------------------------
DROP TABLE "V_DIALYSIS_COMP";
  CREATE TABLE "V_DIALYSIS_COMP" 
   (	"PATID" CHAR(12 BYTE), 
	"OCCUR_DATE" DATE, 
	"MEASURECLASS" VARCHAR2(1 BYTE), 
	"REQCODE" CHAR(10 BYTE), 
	"COMPLAINT" VARCHAR2(256 BYTE), 
	"TREAT_NAME" VARCHAR2(256 BYTE), 
	"MEDICINE_CD1" VARCHAR2(20 BYTE), 
	"MEDICINE_CD2" VARCHAR2(20 BYTE), 
	"MEDICINE_NAME" VARCHAR2(80 BYTE), 
	"AMOUNT" NUMBER, 
	"UNIT" VARCHAR2(20 BYTE), 
	"PROCEDURE_NAME" VARCHAR2(40 BYTE), 
	"PROCEDURE_CD1" VARCHAR2(20 BYTE), 
	"PROCEDURE_CD2" VARCHAR2(20 BYTE), 
	"TREAT_PERSON_NAME" VARCHAR2(20 BYTE), 
	"UP_DATE" DATE, 
	"ORD_NO" NUMBER, 
	"COMP_CD" CHAR(20 BYTE), 
	"TREAT_CD" CHAR(20 BYTE),
	"DIALYSIS_DATE" CHAR(8 BYTE)
   );

   COMMENT ON TABLE "V_DIALYSIS_COMP"  IS '透析愁訴処置情報';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."OCCUR_DATE" IS '発生日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."MEASURECLASS" IS '区分';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."REQCODE" IS '愁訴コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."COMPLAINT" IS '愁訴内容';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."TREAT_NAME" IS '処置名';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."MEDICINE_CD1" IS '薬剤コード1';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."MEDICINE_CD2" IS '薬剤コード2';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."MEDICINE_NAME" IS '薬剤名称';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."AMOUNT" IS '数量';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."UNIT" IS '単位';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."PROCEDURE_NAME" IS '手技名';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."PROCEDURE_CD1" IS '手技コード1';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."PROCEDURE_CD2" IS '手技コード2';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."TREAT_PERSON_NAME" IS '処置者名';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."ORD_NO" IS '透析番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."COMP_CD" IS '愁訴マスタコード';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."TREAT_CD" IS '処置マスタコード';
   COMMENT ON COLUMN "FNSIVIEW"."V_DIALYSIS_COMP"."DIALYSIS_DATE" IS '透析日';
