-- ----------------------------
-- Table structure for V_IND_DIALYSIS_ADD
-- ----------------------------
DROP TABLE "V_IND_DIALYSIS_ADD";
  CREATE TABLE "V_IND_DIALYSIS_ADD" 
   (	"PATID" CHAR(12 BYTE), 
	"DIALYSIS_DATE" CHAR(8 BYTE), 
	"PLURAL" NUMBER, 
	"CTL_NO" CHAR(7 BYTE), 
	"UP_DATE" DATE, 
	"ADDITION" VARCHAR2(1024 BYTE), 
	"INDICATOR_CD" CHAR(10 BYTE), 
	"OPE_IND_PLAN" CHAR(1 BYTE),
   "DIALYSIS_NO" NUMBER(20,0)
   );

   COMMENT ON TABLE "V_IND_DIALYSIS_ADD"  IS '指示簿指示指示';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."DIALYSIS_DATE" IS '透析日';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."PLURAL" IS '同日複数回';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."CTL_NO" IS '項目番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."ADDITION" IS '指示簿指示';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."INDICATOR_CD" IS '指示者';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."OPE_IND_PLAN" IS '予定作成区分';
   COMMENT ON COLUMN "FNSIVIEW"."V_IND_DIALYSIS_ADD"."DIALYSIS_NO" IS '透析番号';
