-- ----------------------------
-- Table structure for V_PAT_MEDICAL_HST
-- ----------------------------
DROP TABLE "V_PAT_MEDICAL_HST";
  CREATE TABLE "V_PAT_MEDICAL_HST" 
   (	"PATID" CHAR(12 BYTE), 
	"CTL_NO" NUMBER, 
	"UP_DATE" DATE, 
	"DISEASE_CD" CHAR(20 BYTE), 
	"DISEASE_NAME" VARCHAR2(100 BYTE), 
	"DISEASE_DATE" DATE, 
	"RECOVER_DATE" DATE, 
	"MAIN_DISEASE" CHAR(1 BYTE), 
	"STATUS" CHAR(1 BYTE), 
	"NOTICE_FLG" CHAR(1 BYTE), 
	"DOCTOR_NAME" VARCHAR2(20 BYTE), 
	"MEMO" VARCHAR2(256 BYTE)
   );

   COMMENT ON TABLE "V_PAT_MEDICAL_HST"  IS '患者病歴情報';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."CTL_NO" IS '管理番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."DISEASE_CD" IS '病名コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."DISEASE_NAME" IS '病名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."DISEASE_DATE" IS '発症日';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."RECOVER_DATE" IS '治癒日';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."MAIN_DISEASE" IS '主病名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."STATUS" IS '転帰';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."NOTICE_FLG" IS '告知有無';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."DOCTOR_NAME" IS '診断医';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_MEDICAL_HST"."MEMO" IS 'メモ';
