-- ----------------------------
-- Table structure for V_PAT_EXAMIN_HST
-- ----------------------------
DROP TABLE "V_PAT_EXAMIN_HST";
  CREATE TABLE "V_PAT_EXAMIN_HST" 
   (	"PATID" CHAR(12 BYTE), 
	"EXAM_DATE" DATE, 
	"ORDER_CLASS" VARCHAR2(6 BYTE), 
	"ITEM_UP_DATE" DATE, 
	"EXAM_ITEM_CODE" CHAR(20 BYTE), 
	"EXAM_ITEM_CODE2" CHAR(20 BYTE), 
	"EXAM_ITEM_CODE3" CHAR(20 BYTE), 
	"EXAM_ITEM_NAME" VARCHAR2(40 BYTE), 
	"EXAM_RST" VARCHAR2(256 BYTE), 
	"EXAM_CLASS_RST" VARCHAR2(256 BYTE), 
	"COMMENTS" VARCHAR2(512 BYTE)
   );

   COMMENT ON TABLE "V_PAT_EXAMIN_HST"  IS '血液検査結果';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."EXAM_DATE" IS '検査日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."ORDER_CLASS" IS '検査区分';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."ITEM_UP_DATE" IS '検査結果更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."EXAM_ITEM_CODE" IS '検査項目コード(院内コード1)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."EXAM_ITEM_CODE2" IS '検査項目コード(院内コード2)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."EXAM_ITEM_CODE3" IS '検査項目コード(院内コード3)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."EXAM_ITEM_NAME" IS '検査項目名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."EXAM_RST" IS '検査結果値';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."EXAM_CLASS_RST" IS '検査結果形態';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_HST"."COMMENTS" IS 'コメント';

  CREATE INDEX IDX_V_PAT_EXAMIN_HST_01 ON V_PAT_EXAMIN_HST (EXAM_DATE);