-- ----------------------------
-- Table structure for V_PAT_INFECT
-- ----------------------------
DROP TABLE "V_PAT_INFECT";
  CREATE TABLE "V_PAT_INFECT" 
   (	"PATID" CHAR(12 BYTE), 
	"INFECTION_CD" CHAR(20 BYTE), 
	"INFECTION_NAME" VARCHAR2(100 BYTE), 
	"UP_DATE" DATE, 
	"INFECT" CHAR(1 BYTE)
   );

   COMMENT ON TABLE "V_PAT_INFECT"  IS '患者感染症情報';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_INFECT"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_INFECT"."INFECTION_CD" IS '感染症コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_INFECT"."INFECTION_NAME" IS '感染症名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_INFECT"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_INFECT"."INFECT" IS '結果コード';
