-- ----------------------------
-- Table structure for V_RST_DIALYSIS_ADD
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_ADD";
  CREATE TABLE "V_RST_DIALYSIS_ADD" 
   (	"PATID" CHAR(12 BYTE), 
	"DIALYSIS_DATE" VARCHAR2(8 BYTE), 
	"DIALYSIS_NO" NUMBER, 
	"CTL_NO" CHAR(7 BYTE), 
	"UP_DATE" DATE, 
	"EFFECT_FLG" CHAR(1 BYTE), 
	"EFFECT_DATE" DATE, 
	"ADDITION" VARCHAR2(1024 BYTE), 
	"STAFF_CD" CHAR(10 BYTE), 
	"STAFF_NAME" VARCHAR2(20 BYTE)
   );

   COMMENT ON TABLE "V_RST_DIALYSIS_ADD"  IS '指示簿指示実績';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."DIALYSIS_DATE" IS '透析日';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."DIALYSIS_NO" IS '透析番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."CTL_NO" IS '項目番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."EFFECT_FLG" IS '実施フラグ';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."EFFECT_DATE" IS '実施日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."ADDITION" IS '補足指示内容';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."STAFF_CD" IS '実施者コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_ADD"."STAFF_NAME" IS '実施者名';
