; デバイスエッジアプリネットワーク設定
;

; 圧縮パスワード
;
ZIP_PW=nkk

; アップロードファイル最大サイズ(MB単位)
; ※超えた場合はファイルが分割されてアップロードされる
;
UPLOAD_FILE_MAXSIZE=80

; AWSホスト名
;
AWS_HOST=https://fnwsi-vpn-dline.nksfn.com

; WebSocket接続先ホストアドレス
;
WEBSOCKET_HOST=wss://fnwsi-vpn-dline.nksfn.com

; configファイルアップロード先
;
UPLOAD_PATH=s3://ntss-s3-root-service/%s/DEfile/%d

; アップロードリトライ回数
;
UPLOAD_RETRY_COUNT=3

; アップロードリトライ待ち時間(秒)
;
UPLOAD_RETRY_WAIT_TIME=30


; WebSocket KeepAlive通知間隔(秒)
;
WEBSOCKET_KEEP_ALIVE_INTERVAL=120
