; データ収集アプリ設定
;
;


; 作業用ファイル格納先フォルダ
;
WORK_FOLDER1=/mnt/usb/ntss/DataCollect_Work
WORK_FOLDER2=/mnt/sd/ntss/DataCollect_Work
WORK_FOLDER3=/home/ntss/ntss/DataCollect_Work


; 装置FTPフォルダ
;
FTP_FOLDER=/DBCT/
; FTPユーザー名
;
FTP_USER=GUEST
; FTPパスワード
;
FTP_PW=GUEST
; FTPウエイト秒数
;
FTP_WAIT=2
; FTPリトライ回数
;
FTP_RETRY=1

; アップロード先
;
UPLOAD_PATH=s3://ntss-s3-root-service/%s/Devicefile
