//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSettingTool.App.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoopSettingTool.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アプリを完了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASK_ABORT {
            get {
                return ResourceManager.GetString("ASK_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon CoopSettingTool {
            get {
                object obj = ResourceManager.GetObject("CoopSettingTool", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   ログイン情報を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ENTER_YOUR_LOGIN_INFORMATION {
            get {
                return ResourceManager.GetString("ENTER_YOUR_LOGIN_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバに接続できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_CONNECT_FAILED {
            get {
                return ResourceManager.GetString("ERROR_CONNECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ形式が壊れています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_DATA_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_DATA_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_DATA_SAVE {
            get {
                return ResourceManager.GetString("ERROR_DATA_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_GET_DATA {
            get {
                return ResourceManager.GetString("ERROR_GET_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   認証に失敗しました。認証情報を確認して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap search_icon {
            get {
                object obj = ResourceManager.GetObject("search-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ただいまメンテナンスしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SERVICE_UNAVAILABLE {
            get {
                return ResourceManager.GetString("SERVICE_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SIGN_IN {
            get {
                return ResourceManager.GetString("SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行が完了するまで待ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WAITING_FOR_EXECUTED {
            get {
                return ResourceManager.GetString("WAITING_FOR_EXECUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワーンニング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーはアカウントロックされています。管理者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING_ACCOUNT_LOCK {
            get {
                return ResourceManager.GetString("WARNING_ACCOUNT_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携がまだインストールされていない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING_COOP_NOT_INSTALLED {
            get {
                return ResourceManager.GetString("WARNING_COOP_NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この連携のレイアウトが見つからない。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING_NO_LAYOUT {
            get {
                return ResourceManager.GetString("WARNING_NO_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2要素認証に{0}回失敗しましたので\r\n2要素認証割り当てデバイスを確認いただき\r\nサインインからやり直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING_OTP_NOT_MATCH_MAX {
            get {
                return ResourceManager.GetString("WARNING_OTP_NOT_MATCH_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得できないデータがあります。管理番号： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING_SOME_DATA_CANNOT_GET {
            get {
                return ResourceManager.GetString("WARNING_SOME_DATA_CANNOT_GET", resourceCulture);
            }
        }
    }
}
