rootProject.name = 'ntss'

include 'ntss-admin-web'
include 'ntss-m-notice'
include 'ntss-core'
include 'ntss-client-comm'
include 'ntss-device-edge'
include 'ntss-device-edge-updater'
include 'ntss-alive-moni'
include 'ntss-alive-moni-auto'
include 'ntss-data-gathering'
include 'ntss-data-gathering-auto'
include 'ntss-web-api'
include 'ntss-api'
include 'ntss-coop-api'
