; 装置間ソケット通信アプリの設定
;

; 新通信用接続待受ポート
RECEIVE_PORT=7000

; NX通信用接続待受ポート
RECEIVE_PORT_NX=7010

; 共通プロトコル通信用リクエスト間隔（秒）
REQUEST_TIME_CP=10

; 装置生存監視時間
DEVICE_TIMEOUT=60

; 新通信用一斉時計合わせ時刻（=hh:mm）
TIMESET_TIME=09:00

; NX通信用一斉時計合わせ時刻（=hh:mm）
TIMESET_TIME_NX=10:00

