spring:
  profiles:
    active: mongo
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,
             org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  main:
    allow-circular-references: true
  mongodb:
    host: 192.168.100.11
    port: 27017
    database: ntss
    username: nkk
    password: nkk
  datasource:
    default:
      jdbc-url: jdbc:postgresql://192.168.100.10:5432/ntss_db5?currentSchema=ntss
      driver-class-name: org.postgresql.Driver
      username: nkk5
      password: nkk5
    personal:
      jdbc-url: jdbc:postgresql://192.168.100.10:5432/ntss_db6?currentSchema=ntss
      driver-class-name: org.postgresql.Driver
      username: nkk6
      password: nkk6
    auth:
      jdbc-url: jdbc:postgresql://192.168.100.10:5432/ntss_db4?currentSchema=ntss
      driver-class-name: org.postgresql.Driver
      username: nkk4
      password: nkk4
  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: ntss-data-gathering-auto
  jmx:
    default-domain: ntss-data-gathering-auto

server:
  compression:
    enabled: true
    min-response-size: 1048576 # 1M = 1024 * 1024(bytes)

doma:
  dialect: postgres

securityporicy:
  accesskeycheck: true

cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-1
    stack:
      auto: false

scheduler:
  initialDelay: 10000
  fixedDelay: 30000

gatheringApi:
  uri: http://localhost:8080/data_gathering/api/request

ntss:
  logging:
    rolling:
      max-history: 14
      max-history-app: 14
---
spring:
  config.activate.on-profile: mongo
  autoconfigure:
    exclude:
