/**
 * 治療記録用パンくず履歴特定用キー定義
 */

// 初期表示（治療記録）
export const HISTORY_KEY_TREATMENT_RECORD_TREATMENT = "TREATMENT";

// 実績情報
export const HISTORY_KEY_TREATMENT_RECORD_RESULT = "RESULT";

// バイタル
export const HISTORY_KEY_TREATMENT_RECORD_VITAL = "VITAL";

// モニタ
export const HISTORY_KEY_TREATMENT_RECORD_MONITOR = "MONITOR";

// 愁訴処置
export const HISTORY_KEY_TREATMENT_RECORD_COMPLAINT = "COMPLAINT";

// 体重
export const HISTORY_KEY_TREATMENT_RECORD_WEIGHT = "WEIGHT";

// 治療条件
export const HISTORY_KEY_TREATMENT_RECORD_CONDITION = "CONDITION";

// 投与薬剤
export const HISTORY_KEY_TREATMENT_RECORD_MEDICINE = "MEDICINE";

// 医療材料
export const HISTORY_KEY_TREATMENT_RECORD_EQUIPMENT = "EQUIPMENT";

// 指示コメント
export const HISTORY_KEY_TREATMENT_RECORD_ADDITION = "ADDITION";

// 装置設定
export const HISTORY_KEY_TREATMENT_RECORD_SETTING = "SETTING";

// 回診記録
export const HISTORY_KEY_TREATMENT_RECORD_ROUND = "ROUND";

// 観察記録
export const HISTORY_KEY_TREATMENT_RECORD_OBSERVATION = "OBSERVATION";

// BVMS
export const HISTORY_KEY_TREATMENT_RECORD_BVMS = "BVMS";
// 加算情報
export const HISTORY_KEY_TREATMENT_RECORD_ADDITION_INFO = "ADDITION_INFO";
