-- ----------------------------
-- Table structure for V_IND_DIALYSIS_MEDI
-- ----------------------------
DROP TABLE "V_IND_DIALYSIS_MEDI";
CREATE TABLE "V_IND_DIALYSIS_MEDI" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "PLURAL" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "MEDICINE_CD" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "MEDI_CLASS_NAME" VARCHAR2(40 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "TIMING_NAME" VARCHAR2(40 BYTE),
  "PROCEDURE_CD" VARCHAR2(20 BYTE),
  "PROCEDURE_CD2" VARCHAR2(20 BYTE),
  "PROCEDURE_NAME" VARCHAR2(40 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE),
  "INDICATOR_CD" CHAR(10 BYTE),
  "OPE_IND_PLAN" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Primary Key structure for table V_IND_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007463" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_IND_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007462" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
