-- ----------------------------
-- Table structure for V_PAT_LIFE_LIST
-- ----------------------------
DROP TABLE "V_PAT_LIFE_LIST";
CREATE TABLE "V_PAT_LIFE_LIST" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "UP_DATE" DATE,
  "NAME" VARCHAR2(40 BYTE),
  "NAME_KANA" VARCHAR2(40 BYTE),
  "REG_DATE" CHAR(8 BYTE),
  "REG_TIME" CHAR(4 BYTE),
  "KIND_ID" NUMBER(3,0),
  "KIND_NAME" VARCHAR2(20 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE),
  "EDIT_CD" CHAR(10 BYTE),
  "EDIT_NAME" VARCHAR2(20 BYTE),
  "DETAIL1" VARCHAR2(1000 BYTE),
  "DETAIL2" VARCHAR2(1000 BYTE),
  "DETAIL3" VARCHAR2(1000 BYTE),
  "DETAIL4" VARCHAR2(1000 BYTE)
)
;

-- ----------------------------
-- Primary Key structure for table V_PAT_LIFE_LIST
-- ----------------------------
ALTER TABLE "V_PAT_LIFE_LIST" ADD CONSTRAINT "SYS_C007480" PRIMARY KEY ("PATID");
