-- ----------------------------
-- Table structure for V_RST_DIALYSIS_MEDI
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_MEDI";
CREATE TABLE "V_RST_DIALYSIS_MEDI" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "MEDICINE_CD" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "MEDICINE_CLASS_NAME" VARCHAR2(40 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "EFFECT_FLG" CHAR(1 BYTE),
  "EFFECT_DATE" DATE,
  "TIMING_NAME" VARCHAR2(40 BYTE),
  "PROCEDURE_CD" VARCHAR2(20 BYTE),
  "PROCEDURE_CD2" VARCHAR2(20 BYTE),
  "PROCEDURE_NAME" VARCHAR2(40 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE)
)
;

-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007450" PRIMARY KEY ("PATID");
