# AWS本番環境DBサーバの設定
spring:
  datasource:
    default:
      jdbc-url: jdbc:postgresql://ntss-platform-service-cluster.cluster-c39h9ck7e4ad.ap-northeast-1.rds.amazonaws.com:5432/ntss_db5?stringtype=unspecified
      username: nkk5
      password: nkk5
    personal:
      jdbc-url: jdbc:postgresql://ntss-platform-service-cluster.cluster-c39h9ck7e4ad.ap-northeast-1.rds.amazonaws.com:5432/ntss_db6?stringtype=unspecified
      username: nkk6
      password: nkk6
    auth:
      jdbc-url: jdbc:postgresql://ntss-platform-service-cluster.cluster-c39h9ck7e4ad.ap-northeast-1.rds.amazonaws.com:5432/ntss_db4?stringtype=unspecified
      username: nkk4
      password: nkk4

ntss:
  logging:
    appender:
      file-name: /opt/ntss-admin-web/log/{0}/{0}.log
    rolling:
      file-name-pattern:  /opt/ntss-admin-web/log/{0}/{0}_%d'{'yyyyMMdd'}'.log
      max-history: 14
  admin-web:
    data-gathering:
      url: 'http://internal-ntss-central-link-alb-1207475684.ap-northeast-1.elb.amazonaws.com:8080/data_gathering/api/request/device'
    web-api:
      url: 'http://internal-ntss-central-link-alb-1207475684.ap-northeast-1.elb.amazonaws.com:8080/ntss-web-api'
