WITH DATE_PARAM AS (SELECT TO_DATE(:START_DATE, 'yyyyMMdd') FROMDATE, TO_DATE( :END_DATE, 'yyyyMMdd' ) TODATE FROM DUAL)
,DAY_TMP AS (
  SELECT 
    TO_CHAR(DP.FROMDATE + rn, 'yyyyMMdd') AS DIALYSIS_DATE
  FROM
    ( SELECT ROWNUM - 1 rn FROM dual CONNECT BY ROWNUM <= ( SELECT TRUNC(TO_DATE( :END_DATE, 'yyyyMMdd' ) +1) - TRUNC(TO_DATE(:START_DATE, 'yyyyMMdd' ) ) FROM dual))
    ,DATE_PARAM DP
  WHERE
    TO_CHAR(DP.FROMDATE + rn, 'yyyy-mm-dd') BETWEEN DP.FROMDATE - 1 AND TO_CHAR(DP.TODATE, 'yyyy-mm-dd')
)
,PLAN_DAY_TMP AS (
  SELECT
    DT.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.OPE_IND_PLAN
    ,TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 YOBI
    ,IND_PLAN.IND_START_DATE
    ,IND_PLAN.IND_END_DATE
    ,IND_PLAN.IND_NO
    ,IND_PLAN.UP_DATE
    ,CASE WHEN
        IND_PLAN.CYCLE_WEEK != 2
        OR
        (IND_PLAN.CYCLE_WEEK = 2 AND 0 = MOD( TO_CHAR( TO_DATE( IND_PLAN.IND_START_DATE, 'YYYYMMDD' ), 'IW' ) - TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYYMMDD' ), 'IW' ), 2 ))
        THEN
        CASE
            ( TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 )
            WHEN 1 THEN VALUE_1W1N
            WHEN 2 THEN VALUE_1W2N
            WHEN 3 THEN VALUE_1W3N
            WHEN 4 THEN VALUE_1W4N
            WHEN 5 THEN VALUE_1W5N
            WHEN 6 THEN VALUE_1W6N
            WHEN 0 THEN VALUE_1W7N
        END
        ELSE
        CASE
            ( TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 )
            WHEN 1 THEN VALUE_2W1N
            WHEN 2 THEN VALUE_2W2N
            WHEN 3 THEN VALUE_2W3N
            WHEN 4 THEN VALUE_2W4N
            WHEN 5 THEN VALUE_2W5N
            WHEN 6 THEN VALUE_2W6N
            WHEN 0 THEN VALUE_2W7N
        END
        END VALUE
	,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
  FROM
    IND_DIALYSIS_PLAN IND_PLAN,
    DAY_TMP DT
  WHERE
    IND_PLAN.OPE_IND_PLAN = '0'
    AND IND_PLAN.IND_CLASS  <> '1'
    AND IND_PLAN.PLURAL = 1
    AND IND_PLAN.PATID IN (SELECT DISTINCT PATID FROM PAT_BASIC_INFO WHERE DIE_FLG = '0' and {0})
    AND (DT.DIALYSIS_DATE BETWEEN IND_PLAN.IND_START_DATE AND IND_PLAN.IND_END_DATE)
)
,UPDATE_TMP AS ( SELECT PATID, DIALYSIS_DATE, MAX( UP_DATE ) MAX_UP_DATE FROM PLAN_DAY_TMP WHERE DIALYSIS_DATE BETWEEN IND_START_DATE AND IND_END_DATE GROUP BY PATID, DIALYSIS_DATE )
,SERIES_CD_TMP AS (
    SELECT PATID, SERIES_CD, START_DATE, END_DATE FROM SYS_PAT_SERIES_FACILITY WHERE SERIES_CD = '{SERIES_CD}' and MAIN_FLG='1'
)
,DIALYSIS_PLAN AS (
  SELECT
    IND_PLAN.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.VALUE
    ,IND_PLAN.IND_START_DATE
    ,IND_PLAN.OPE_IND_PLAN
    ,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
    ,IND_PLAN.UP_DATE
  FROM PLAN_DAY_TMP IND_PLAN
    INNER JOIN UPDATE_TMP
      ON UPDATE_TMP.PATID = IND_PLAN.PATID
      AND UPDATE_TMP.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE
      AND IND_PLAN.UP_DATE = UPDATE_TMP.MAX_UP_DATE
    INNER JOIN SERIES_CD_TMP SERIES
      ON IND_PLAN.PATID = SERIES.PATID
      AND IND_PLAN.DIALYSIS_DATE BETWEEN SERIES.START_DATE AND SERIES.END_DATE
  WHERE
    LENGTH( IND_PLAN.VALUE ) >= 8
    AND IND_PLAN.IND_NO = (
          SELECT MAX( IND_NO ) FROM PLAN_DAY_TMP PDT
          WHERE PDT.PATID = IND_PLAN.PATID AND IND_PLAN.UP_DATE = PDT.UP_DATE AND PDT.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE
        )
)
SELECT
  DIALYSIS_DATE
  ,PATID
  ,TO_CHAR( PATID ) || TO_CHAR( DIALYSIS_DATE ) || '1' IND_ID
  ,VALUE
  ,IND_START_DATE
  ,CASE SUBSTR( VALUE, 0, 4 ) WHEN 'NON' THEN 0 ELSE TO_NUMBER(SUBSTR( VALUE, 0, 4 )) END BED_NO
  ,SUBSTR( VALUE, 5, 3 ) KUR_CD
  ,TO_CHAR(CYCLE_WEEK) CYCLE_WEEK
  ,CASE TO_CHAR(TO_DATE(DIALYSIS_DATE, 'yyyyMMdd'), 'D') 
        WHEN '1' THEN 7
        WHEN '2' THEN 1
        WHEN '3' THEN 2
        WHEN '4' THEN 3
        WHEN '5' THEN 4
        WHEN '6' THEN 5
        WHEN '7' THEN 6
        END ADD_TREAT_WEEK
  ,INDICATOR_CD
  ,UPDATE_STAFF_CD
  ,UP_DATE
FROM
  DIALYSIS_PLAN S
WHERE
   {0}
  AND S.DIALYSIS_DATE >= TO_DATE(:START_DATE, 'yyyyMMdd')
  AND S.DIALYSIS_DATE <= TO_DATE(:END_DATE, 'yyyyMMdd')
ORDER BY
  PATID
  ,DIALYSIS_DATE