WITH DATE_PARAM AS ( SELECT TO_DATE(:START_DATE, 'yyyyMMdd' ) FROMDATE, TO_DATE(:END_DATE, 'yyyyMMdd' ) TODATE FROM DUAL )
  ,DAY_TMP AS (
	  SELECT
		  TO_CHAR( DP.FROMDATE + rn, 'yyyyMMdd' ) AS DIALYSIS_DATE 
	  FROM
		  (SELECT ROWNUM - 1 rn FROM dual CONNECT BY ROWNUM <= ( SELECT TRUNC(TO_DATE(:END_DATE, 'yyyyMMdd' ) +1) - TRUNC(TO_DATE(:START_DATE, 'yyyyMMdd' )) FROM dual)),
		  DATE_PARAM DP 
	  WHERE
		  TO_CHAR( DP.FROMDATE + rn, 'yyyy-mm-dd' ) BETWEEN DP.FROMDATE - 1 
		  AND TO_CHAR( DP.TODATE, 'yyyy-mm-dd' )
	)
  ,MEDI_MAXUPD_TMP AS (
    SELECT
        PATID, PLURAL, CTL_NO, MAX(UP_DATE) MAX_UP_DATE, DIALYSIS_DATE
    FROM
        IND_DIALYSIS_MEDI, DAY_TMP
    WHERE
		{0}
		AND PLURAL = 1
        AND
        (DIALYSIS_DATE BETWEEN IND_START_DATE AND IND_END_DATE)
    GROUP BY PATID, PLURAL, CTL_NO, DIALYSIS_DATE
  )
  ,MEDI_TMP AS (
    SELECT
        MEDI.PATID, MEDI.PLURAL, MAX(MEDI.IND_NO) MAX_IND_NO, MEDI.CTL_NO, MT.MAX_UP_DATE, MT.DIALYSIS_DATE
    FROM
        IND_DIALYSIS_MEDI MEDI, MEDI_MAXUPD_TMP MT
    WHERE
        MEDI.PATID = MT.PATID
      AND MEDI.PLURAL = MT.PLURAL
      AND MEDI.CTL_NO = MT.CTL_NO
      AND MEDI.UP_DATE = MT.MAX_UP_DATE
      AND MT.DIALYSIS_DATE BETWEEN MEDI.IND_START_DATE AND MEDI.IND_END_DATE
    GROUP BY MEDI.PATID, MEDI.PLURAL, MEDI.CTL_NO, MT.MAX_UP_DATE, MT.DIALYSIS_DATE
)
SELECT DISTINCT
  MEDI.PATID || MT.DIALYSIS_DATE || TO_CHAR(MEDI.PLURAL) IND_ID
  ,MEDI.PATID
  ,MT.DIALYSIS_DATE
  ,SM.NO as CTL_NO
  ,MEDI.SET_MEDICINE_FLG
  ,MEDI.MEDICINE_CD
  ,MEDI.INDICATOR_CD
  ,MEDI.VALUE_1W1N
  ,MEDI.VALUE_1W2N
  ,MEDI.VALUE_1W3N
  ,MEDI.VALUE_1W4N
  ,MEDI.VALUE_1W5N
  ,MEDI.VALUE_1W6N
  ,MEDI.VALUE_1W7N
  ,MEDI.VALUE_2W1N
  ,MEDI.VALUE_2W2N
  ,MEDI.VALUE_2W3N
  ,MEDI.VALUE_2W4N
  ,MEDI.VALUE_2W5N
  ,MEDI.VALUE_2W6N
  ,MEDI.VALUE_2W7N
  ,MEDI.VALUE_3W1N
  ,MEDI.VALUE_3W2N
  ,MEDI.VALUE_3W3N
  ,MEDI.VALUE_3W4N
  ,MEDI.VALUE_3W5N
  ,MEDI.VALUE_3W6N
  ,MEDI.VALUE_3W7N
  ,MEDI.VALUE_4W1N
  ,MEDI.VALUE_4W2N
  ,MEDI.VALUE_4W3N
  ,MEDI.VALUE_4W4N
  ,MEDI.VALUE_4W5N
  ,MEDI.VALUE_4W6N
  ,MEDI.VALUE_4W7N
  ,MEDI.COUNT_EVERY_MONTH
  ,MEDI.TIMING_CD
  ,MEDI.PROCEDURE_CD
  ,MEDI.COMMENTS
  ,MEDI.INDICATOR_CD
  ,MEDI.UPDATE_STAFF_CD
  , case 
        WHEN MEDI.SPE_IND_FLG in (0,1) THEN '1' 
        WHEN MEDI.SPE_IND_FLG in (2,3) THEN '2'
      end as SPE_IND_FLG
  ,MEDI.COP_ORDER_NUMBER
  ,MEDI.EDITABLE_FLG
  ,MEDI.PLURAL
  ,MEDI.IND_START_DATE
  ,MEDI.DAY_PATTERN
  ,MEDI.DEL_FLG
FROM
  IND_DIALYSIS_MEDI MEDI 
    INNER JOIN MEDI_TMP MT
      ON MEDI.PATID = MT.PATID
      AND MEDI.PLURAL = MT.PLURAL
      AND MEDI.CTL_NO = MT.CTL_NO
      AND MEDI.UP_DATE = MT.MAX_UP_DATE
      AND MEDI.IND_NO = MT.MAX_IND_NO
      left join SYNC_MEDICINE_LATEST_NO SM on SM.PATID=MEDI.PATID and SM.IND_NO=MEDI.CTL_NO and SM.PLURAL = MEDI.PLURAL  and  SM.SERIES_CD='{SERIES_CD}'
ORDER BY
  SM.NO