WITH DATE_PARAM AS ( SELECT TO_DATE(:START_DATE, 'yyyyMMdd' ) FROMDATE, TO_DATE( :END_DATE, 'yyyyMMdd' ) TODATE FROM DUAL )
  ,DAY_TMP AS (
	  SELECT
		  TO_CHAR( DP.FROMDATE + rn, 'yyyyMMdd' ) AS DIALYSIS_DATE 
	  FROM
		  (SELECT ROWNUM - 1 rn FROM dual CONNECT BY ROWNUM <= ( SELECT TRUNC(TO_DATE( :END_DATE, 'yyyyMMdd' ) +1) - TRUNC(TO_DATE( :START_DATE, 'yyyyMMdd' )) FROM dual)),
		  DATE_PARAM DP 
	  WHERE
		  TO_CHAR( DP.FROMDATE + rn, 'yyyy-mm-dd' ) BETWEEN DP.FROMDATE - 1 
		  AND TO_CHAR( DP.TODATE, 'yyyy-mm-dd' )
	)
  ,ADD_MAXUPD_TMP AS (
	SELECT
		PATID, PLURAL, CTL_NO, MAX(UP_DATE) MAX_UP_DATE, DIALYSIS_DATE
	FROM
		IND_DIALYSIS_ADD, DAY_TMP
	WHERE
		{0} 
		AND PLURAL = 1
		AND
		(DIALYSIS_DATE BETWEEN IND_START_DATE AND IND_END_DATE)
	GROUP BY PATID, PLURAL, CTL_NO, DIALYSIS_DATE
  )
  ,ADD_TMP AS (
    SELECT
        IND_ADD.PATID, IND_ADD.PLURAL, MAX(IND_ADD.IND_NO) MAX_IND_NO, IND_ADD.CTL_NO, AT.MAX_UP_DATE, AT.DIALYSIS_DATE
    FROM
        IND_DIALYSIS_ADD IND_ADD, ADD_MAXUPD_TMP AT
    WHERE
        IND_ADD.PATID = AT.PATID
      AND IND_ADD.PLURAL = AT.PLURAL
      AND IND_ADD.CTL_NO = AT.CTL_NO
      AND IND_ADD.UP_DATE = AT.MAX_UP_DATE
      AND AT.DIALYSIS_DATE BETWEEN IND_ADD.IND_START_DATE AND IND_ADD.IND_END_DATE
    GROUP BY IND_ADD.PATID, IND_ADD.PLURAL, IND_ADD.CTL_NO, AT.MAX_UP_DATE, AT.DIALYSIS_DATE
)
SELECT
  IND_ADD.PATID || AT.DIALYSIS_DATE || TO_CHAR(IND_ADD.PLURAL) IND_ID
  ,IND_ADD.PATID
  ,TO_NUMBER(IND_ADD.CTL_NO) CTL_NO
  ,IND_ADD.ADDITION
  ,IND_ADD.INDICATOR_CD
  ,IND_ADD.UPDATE_STAFF_CD
  , case 
        WHEN IND_ADD.SPE_IND_FLG in (0,1) THEN '1' 
        WHEN IND_ADD.SPE_IND_FLG in (2,3) THEN '2'
      end as SPE_IND_FLG
  ,IND_ADD.COP_ORDER_NUMBER
  ,IND_ADD.EDITABLE_FLG
  ,IND_ADD.DEL_FLG
  ,IND_ADD.PLURAL
  ,IND_ADD.IND_START_DATE,IND_ADD.UP_DATE
FROM
  IND_DIALYSIS_ADD IND_ADD
    INNER JOIN ADD_TMP AT
      ON IND_ADD.PATID = AT.PATID
	  AND IND_ADD.PLURAL = AT.PLURAL
	  AND IND_ADD.CTL_NO = AT.CTL_NO
	  AND IND_ADD.UP_DATE = AT.MAX_UP_DATE
      AND IND_ADD.IND_NO = AT.MAX_IND_NO
ORDER BY IND_ADD.CTL_NO,IND_ADD.UP_DATE