SELECT DISTINCT
  DEVICE_SET.PATID
  ,DEVICE_SET.SET_DATA
  ,DEVICE_SET.CALC_DIALYSIS_DATE
  ,DEVICE_SET.DAY_OF_WEEK
FROM
  PAT_DEVICE_SET DEVICE_SET
  INNER JOIN (
    SELECT
      PATID
      ,DAY_OF_WEEK
      ,MAX(REG_DATE) MAX_REG_DATE
    FROM PAT_DEVICE_SET
    WHERE {0}
    GROUP BY PATID, DAY_OF_WEEK
  ) DS_TMP
  ON DEVICE_SET.PATID = DS_TMP.PATID
  AND DEVICE_SET.DAY_OF_WEEK = DS_TMP.DAY_OF_WEEK
  AND DEVICE_SET.REG_DATE = DS_TMP.MAX_REG_DATE
ORDER BY DEVICE_SET.PATID, DEVICE_SET.DAY_OF_WEEK