WITH MAX_UPD_TARE AS (
  SELECT
		PATID,
		CTL_NO,
		MAX( UP_DATE ) MAX_UP_DATE
	FROM
		PAT_REVISE_TARE 
	WHERE
		{0}
		AND DAY_OF_WEEK = -1
	GROUP BY
		PATID,
		CTL_NO
		UNION ALL
		SELECT
		PATID,
		CTL_NO,
		MAX( UP_DATE ) MAX_UP_DATE
	FROM
		PAT_REVISE_TARE 
	WHERE
		{0}
  AND DAY_OF_WEEK <> -1
	GROUP BY
		PATID,
		CTL_NO
)
,UPD_TARE_INFO AS (
  SELECT
    RT.PATID
    ,RT.DAY_OF_WEEK
    ,RT.CTL_NO
    ,RT.UP_DATE
  FROM
    PAT_REVISE_TARE RT
    INNER JOIN MAX_UPD_TARE TT
      ON TT.PATID = RT.PATID
	  AND TT.CTL_NO = RT.CTL_NO
	  AND TT.MAX_UP_DATE = RT.UP_DATE
 )
,DAY_OF_WEEK_TARE AS (
  SELECT
	TARE.PATID
	,TARE.DAY_OF_WEEK AS DAY_OF_WEEK
	,MAX(TARE.UP_DATE) UP_DATE
	,MAX( CASE TT.CTL_NO WHEN 1 THEN TARE.REVISE_NAME ELSE NULL END ) AS REVISE_NAME1
	,MAX( CASE TT.CTL_NO WHEN 1 THEN TARE.REVISE_WEIGHT ELSE NULL END ) AS REVISE_WEIGHT1
	,MAX( CASE TT.CTL_NO WHEN 2 THEN TARE.REVISE_NAME ELSE NULL END ) AS REVISE_NAME2
	,MAX( CASE TT.CTL_NO WHEN 2 THEN TARE.REVISE_WEIGHT ELSE NULL END ) AS REVISE_WEIGHT2
	,MAX( CASE TT.CTL_NO WHEN 3 THEN TARE.REVISE_NAME ELSE NULL END ) AS REVISE_NAME3
	,MAX( CASE TT.CTL_NO WHEN 3 THEN TARE.REVISE_WEIGHT ELSE NULL END ) AS REVISE_WEIGHT3
	,MAX( CASE TT.CTL_NO WHEN 4 THEN TARE.REVISE_NAME ELSE NULL END ) AS REVISE_NAME4
	,MAX( CASE TT.CTL_NO WHEN 4 THEN TARE.REVISE_WEIGHT ELSE NULL END ) AS REVISE_WEIGHT4
	,MAX( CASE TT.CTL_NO WHEN 5 THEN TARE.REVISE_NAME ELSE NULL END ) AS REVISE_NAME5
	,MAX( CASE TT.CTL_NO WHEN 5 THEN TARE.REVISE_WEIGHT ELSE NULL END ) AS REVISE_WEIGHT5 
  FROM
	PAT_REVISE_TARE TARE
	INNER JOIN UPD_TARE_INFO TT ON TARE.PATID = TT.PATID 
	AND TARE.CTL_NO = TT.CTL_NO 
	AND TARE.DAY_OF_WEEK = TT.DAY_OF_WEEK 
	AND TARE.UP_DATE = TT.UP_DATE 
  GROUP BY
	TARE.PATID, TARE.DAY_OF_WEEK
)
,DEFAULT_TARE AS (
  SELECT * FROM DAY_OF_WEEK_TARE WHERE DAY_OF_WEEK = -1
)
SELECT
  T1.PATID
  ,T1.DAY_OF_WEEK
  ,T1.UP_DATE
  ,NVL(T1.REVISE_NAME1, T2.REVISE_NAME1) REVISE_NAME1
  ,NVL(T1.REVISE_WEIGHT1, T2.REVISE_WEIGHT1) REVISE_WEIGHT1
  ,NVL(T1.REVISE_NAME2, T2.REVISE_NAME2) REVISE_NAME2
  ,NVL(T1.REVISE_WEIGHT2, T2.REVISE_WEIGHT2) REVISE_WEIGHT2
  ,NVL(T1.REVISE_NAME3, T2.REVISE_NAME3) REVISE_NAME3
  ,NVL(T1.REVISE_WEIGHT3, T2.REVISE_WEIGHT3) REVISE_WEIGHT3
  ,NVL(T1.REVISE_NAME4, T2.REVISE_NAME4) REVISE_NAME4
  ,NVL(T1.REVISE_WEIGHT4, T2.REVISE_WEIGHT4) REVISE_WEIGHT4
  ,NVL(T1.REVISE_NAME5, T2.REVISE_NAME5) REVISE_NAME5
  ,NVL(T1.REVISE_WEIGHT5, T2.REVISE_WEIGHT5) REVISE_WEIGHT5
FROM
  DAY_OF_WEEK_TARE T1
  ,DEFAULT_TARE T2
ORDER BY T1.PATID, T1.UP_DATE DESC
