allprojects {
  group = 'jp.co.nikkiso.ntss'
  version = '0.0.1-SNAPSHOT'
  repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri('https://start.spring.io/milestone') }
    maven { url = uri('https://start.spring.io/snapshot') }
    maven { url = uri('https://repository.jboss.org/nexus/content/repositories/releases') }
    maven { url = uri('https://oss.sonatype.org/content/repositories/releases') }
    maven { url = uri('https://oss.sonatype.org/content/repositories/snapshots') }
    maven { url = uri('https://repo.maven.apache.org/maven2') }
  }
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'jacoco'

  def javaLanguageVersion = Integer.parseInt(findProperty('java_language_version').toString())
  def springBootBom = "org.springframework.boot:spring-boot-dependencies:${rootProject.findProperty('spring_boot_version')}"

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(javaLanguageVersion)
    }
  }

  def defaultEncoding = 'UTF-8'
  tasks.withType(AbstractCompile).configureEach {
    options.encoding = defaultEncoding
  }
  tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-parameters', '-proc:full']
  }

  pluginManager.withPlugin('io.spring.dependency-management') {
    dependencyManagement {
      imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${rootProject.findProperty('spring_boot_version')}"
      }
    }
  }

  dependencies {
    implementation platform(springBootBom)
    annotationProcessor platform(springBootBom)
    testImplementation platform(springBootBom)
    testAnnotationProcessor platform(springBootBom)
  }

  if (project.name in ['ntss-core']) return

  dependencies {
    implementation project(':ntss-core')
  }
}
