flyway.user=nkk4
flyway.password=nkk4
flyway.url=jdbc:postgresql://dev-ies-ntss-platform-service-cluster.cluster-cnr7cvlcb4ym.ap-northeast-1.rds.amazonaws.com:5432/ntss_db4_ait1
flyway.locations=filesystem:ntss-core/src/main/resources/db4/migration,filesystem:ntss-core/src/main/resources/db4/testdata,filesystem:ntss-core/src/main/resources/db4/testdata_e2e
flyway.schemas=ntss
