# ※ sudo　で実行不可（権限的に）
# if_edgeで使用するディレクトリの作成
cd /home/ntss
mkdir ~/if_edge
cd ~/if_edge
mkdir backup/
mkdir backup/accept/
mkdir backup/accept/NG/
mkdir backup/accept/OK/
mkdir backup/exam_ord/
mkdir backup/exam_ord/NG/
mkdir backup/exam_ord/OK/
mkdir backup/exam_rst/
mkdir backup/exam_rst/NG/
mkdir backup/exam_rst/OK/
mkdir backup/ind_dial/
mkdir backup/ind_dial/NG/
mkdir backup/ind_dial/OK/
mkdir backup/ini_dial/
mkdir backup/ini_dial/NG/
mkdir backup/ini_dial/OK/
mkdir backup/is_death/
mkdir backup/is_death/NG/
mkdir backup/is_death/OK/
mkdir backup/ord_dial/
mkdir backup/ord_dial/NG/
mkdir backup/ord_dial/OK/
mkdir backup/phy_ord/
mkdir backup/phy_ord/NG/
mkdir backup/phy_ord/OK/
mkdir backup/pre_ord/
mkdir backup/pre_ord/NG/
mkdir backup/pre_ord/OK/
mkdir backup/profile/
mkdir backup/profile/NG/
mkdir backup/profile/OK/
mkdir backup/rad_ord/
mkdir backup/rad_ord/NG/
mkdir backup/rad_ord/OK/
mkdir backup/rep_dial/
mkdir backup/rep_dial/NG/
mkdir backup/rep_dial/OK/
mkdir backup/rst_dial/
mkdir backup/rst_dial/NG/
mkdir backup/rst_dial/OK/
mkdir backup/shot_ord/
mkdir backup/shot_ord/NG/
mkdir backup/shot_ord/OK/
mkdir backup/staff_mst/
mkdir backup/staff_mst/NG/
mkdir backup/staff_mst/OK/
mkdir backup/vit_cop/
mkdir backup/vit_cop/NG/
mkdir backup/vit_cop/OK/
mkdir conf/
mkdir logs/
mkdir logs/receive/
mkdir logs/send/
mkdir logs/view/
mkdir logs/nodered/
mkdir maint/
mkdir save/
mkdir save/receive/
mkdir save/receive/accept/
mkdir save/receive/accept/NG/
mkdir save/receive/accept/OK/
mkdir save/receive/exam_ord/
mkdir save/receive/exam_ord/NG/
mkdir save/receive/exam_ord/OK/
mkdir save/receive/exam_rst/
mkdir save/receive/exam_rst/NG/
mkdir save/receive/exam_rst/OK/
mkdir save/receive/ind_dial/
mkdir save/receive/ind_dial/NG/
mkdir save/receive/ind_dial/OK/
mkdir save/receive/ini_dial/
mkdir save/receive/ini_dial/NG/
mkdir save/receive/ini_dial/OK/
mkdir save/receive/is_death/
mkdir save/receive/is_death/NG/
mkdir save/receive/is_death/OK/
mkdir save/receive/karte_ord/
mkdir save/receive/karte_ord/NG/
mkdir save/receive/karte_ord/OK/
mkdir save/receive/ord_dial/
mkdir save/receive/ord_dial/NG/
mkdir save/receive/ord_dial/OK/
mkdir save/receive/phy_ord/
mkdir save/receive/phy_ord/NG/
mkdir save/receive/phy_ord/OK/
mkdir save/receive/pre_ord/
mkdir save/receive/pre_ord/NG/
mkdir save/receive/pre_ord/OK/
mkdir save/receive/profile/
mkdir save/receive/profile/NG/
mkdir save/receive/profile/OK/
mkdir save/receive/rad_ord/
mkdir save/receive/rad_ord/NG/
mkdir save/receive/rad_ord/OK/
mkdir save/receive/rep_dial/
mkdir save/receive/rep_dial/NG/
mkdir save/receive/rep_dial/OK/
mkdir save/receive/rst_dial/
mkdir save/receive/rst_dial/NG/
mkdir save/receive/rst_dial/OK/
mkdir save/receive/shot_ord/
mkdir save/receive/shot_ord/NG/
mkdir save/receive/shot_ord/OK/
mkdir save/receive/staff_mst/
mkdir save/receive/staff_mst/NG/
mkdir save/receive/staff_mst/OK/
mkdir save/receive/vit_cop/
mkdir save/receive/vit_cop/NG/
mkdir save/receive/vit_cop/OK/
mkdir save/send/
mkdir save/send/accept/
mkdir save/send/accept/NG/
mkdir save/send/accept/OK/
mkdir save/send/exam_ord/
mkdir save/send/exam_ord/NG/
mkdir save/send/exam_ord/OK/
mkdir save/send/exam_rst/
mkdir save/send/exam_rst/NG/
mkdir save/send/exam_rst/OK/
mkdir save/send/ind_dial/
mkdir save/send/ind_dial/NG/
mkdir save/send/ind_dial/OK/
mkdir save/send/ini_dial/
mkdir save/send/ini_dial/NG/
mkdir save/send/ini_dial/OK/
mkdir save/send/is_death/
mkdir save/send/is_death/NG/
mkdir save/send/is_death/OK/
mkdir save/send/karte_ord/
mkdir save/send/karte_ord/NG/
mkdir save/send/karte_ord/OK/
mkdir save/send/ord_dial/
mkdir save/send/ord_dial/NG/
mkdir save/send/ord_dial/OK/
mkdir save/send/phy_ord/
mkdir save/send/phy_ord/NG/
mkdir save/send/phy_ord/OK/
mkdir save/send/pre_ord/
mkdir save/send/pre_ord/NG/
mkdir save/send/pre_ord/OK/
mkdir save/send/profile/
mkdir save/send/profile/NG/
mkdir save/send/profile/OK/
mkdir save/send/rad_ord/
mkdir save/send/rad_ord/NG/
mkdir save/send/rad_ord/OK/
mkdir save/send/rep_dial/
mkdir save/send/rep_dial/NG/
mkdir save/send/rep_dial/OK/
mkdir save/send/rst_dial/
mkdir save/send/rst_dial/NG/
mkdir save/send/rst_dial/OK/
mkdir save/send/shot_ord/
mkdir save/send/shot_ord/NG/
mkdir save/send/shot_ord/OK/
mkdir save/send/staff_mst/
mkdir save/send/staff_mst/NG/
mkdir save/send/staff_mst/OK/
mkdir save/send/vit_cop/
mkdir save/send/vit_cop/NG/
mkdir save/send/vit_cop/OK/
mkdir save/view/
mkdir tmp/

chown -R ntss /home/ntss/if_edge

sudo chown -R syslog logs/nodered/
# ※ 「logs/nodered/」にはsyslogの所有者が必要です。なければ、Node-Redのlogを生成できませんでした。
