WITH IND_DEVELOP_ADD_NEW AS (
	SELECT
		IND_ID,
		ADDITION,
		UPDATE_STAFF_CD,
		SPE_IND_FLG,
		COP_ORDER_NUMBER,
		CTL_NO,
		UP_DATE,
		INDICATOR_CD,
		EDITABLE_FLG,
		TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM UPDATE_STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS UPDATE_STAFF_NAME,
		TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM INDICATOR_NAME ) ), '　', ' ' ), '\s+', ' ')) AS INDICATOR_NAME
	FROM
		IND_DEVELOP_ADD
		WHERE
		{0}
	),
	MAX_IND_DEVELOP_ADD AS (
	SELECT
		IND_ID,
		ADDITION,
		UPDATE_STAFF_CD,
	CASE		
			WHEN instr( UPDATE_STAFF_NAME, ' ' ) = 0 THEN
			UPDATE_STAFF_NAME 
			WHEN instr( UPDATE_STAFF_NAME, ' ' ) > 0 THEN
			substr( UPDATE_STAFF_NAME, 0, instr( UPDATE_STAFF_NAME, ' ' ) - 1 ) 
		END AS UPD_USER_LAST_NAME,
	CASE
			
			WHEN instr( UPDATE_STAFF_NAME, ' ' ) > 0 THEN
			substr( UPDATE_STAFF_NAME, instr( UPDATE_STAFF_NAME, ' ' ) + 1 ) ELSE ' ' 
		END AS UPD_USER_FIRST_NAME,
	CASE		
			WHEN SPE_IND_FLG IN ( 0, 1 ) THEN
			'1' 
			WHEN SPE_IND_FLG IN ( 2, 3 ) THEN
			'2' 
		END AS SPE_IND_FLG,
		COP_ORDER_NUMBER,
		ROW_NUMBER ( ) OVER ( PARTITION BY IND_ID, ADDITION ORDER BY CTL_NO DESC, UP_DATE DESC ) AS rn 
	FROM
		IND_DEVELOP_ADD_NEW 
	),
	MIN_IND_DEVELOP_ADD AS (
	SELECT
		IND_ID,
		TO_NUMBER(CTL_NO) AS CTL_NO,
		ADDITION,
		EDITABLE_FLG,
		INDICATOR_CD,
	CASE
			WHEN instr( INDICATOR_NAME, ' ' ) = 0 THEN
			INDICATOR_NAME 
			WHEN instr( INDICATOR_NAME, ' ' ) > 0 THEN
			substr( INDICATOR_NAME, 0, instr( INDICATOR_NAME, ' ' ) - 1 ) 
		END AS IND_USER_LAST_NAME,
	CASE
			WHEN instr( INDICATOR_NAME, ' ' ) > 0 THEN
			substr( INDICATOR_NAME, instr( INDICATOR_NAME, ' ' ) + 1 ) ELSE ' ' 
		END AS IND_USER_FIRST_NAME, ROW_NUMBER() OVER (PARTITION BY IND_ID, ADDITION ORDER BY CTL_NO,UP_DATE ) AS rn
	FROM
		IND_DEVELOP_ADD_NEW
	) 
SELECT
   max.IND_ID
  ,CTL_NO
  , max.ADDITION
  ,UPDATE_STAFF_CD
  ,INDICATOR_CD
  ,UPD_USER_LAST_NAME
  ,UPD_USER_FIRST_NAME
  ,IND_USER_LAST_NAME 
  ,IND_USER_FIRST_NAME 
  ,SPE_IND_FLG
  ,COP_ORDER_NUMBER
  ,EDITABLE_FLG
FROM
  MAX_IND_DEVELOP_ADD max
	INNER JOIN   MIN_IND_DEVELOP_ADD min ON max.IND_ID=min.IND_ID and  max.ADDITION=min.ADDITION 
WHERE
   max.rn = 1 and min.rn = 1
ORDER BY
  max.IND_ID
  ,CTL_NO