WITH IND_DEVELOP_EQUIP_NEW AS (
	SELECT
		IND_ID,
		NEEDLE_TYPE,
		EQUIP_NAME,
		CLASS_CD,
		CLASS_NAME,
		VALUE,
		UNIT,
		INDICATOR_CD,
		UPDATE_STAFF_CD,
		SPE_IND_FLG,
		COP_ORDER_NUMBER,
		EDITABLE_FLG,
		EQUIP_CD,
        CTL_NO,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM UPDATE_STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS UPDATE_STAFF_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM INDICATOR_NAME ) ), '　', ' ' ), '\s+', ' ')) AS INDICATOR_NAME_NEW
	FROM
		IND_DEVELOP_EQUIP
        WHERE
       {0}
)
SELECT
  IND_ID
  ,NEEDLE_TYPE
  ,CASE NEEDLE_TYPE
    WHEN '3' THEN
        (CASE
        WHEN (LPAD(TRIM(EQUIP_CD), 10, '0') IN (SELECT TRIM( REGEXP_SUBSTR( P_SN, '[^,]+', 1, LEVEL ) ) AS EXTRACTED_VALUE FROM SYNC_CONDSET CONNECT BY LEVEL <= REGEXP_COUNT ( P_SN, ',' ) + 1))
        THEN 'SN' || SUBSTR(LPAD(TRIM(EQUIP_CD), 10, '0'), 3)
        ELSE LPAD(TRIM(EQUIP_CD), 10, '0')
        END)
    ELSE LPAD(TRIM(EQUIP_CD), 10, '0')
    END EQUIP_CD
  ,EQUIP_NAME
  ,CLASS_CD
  ,CLASS_NAME
  ,VALUE
  ,UNIT
  ,INDICATOR_CD
  ,case when instr(UPDATE_STAFF_NAME_NEW,' ')=0 then UPDATE_STAFF_NAME_NEW
      when instr(UPDATE_STAFF_NAME_NEW,' ')>0 then substr(UPDATE_STAFF_NAME_NEW,0,instr(UPDATE_STAFF_NAME_NEW,' ')-1)
    end as UPD_USER_LAST_NAME
  ,case when instr(UPDATE_STAFF_NAME_NEW,' ')>0 then substr(UPDATE_STAFF_NAME_NEW,instr(UPDATE_STAFF_NAME_NEW,' ')+1)
      else ' '
    end as UPD_USER_FIRST_NAME
  ,case when instr(INDICATOR_NAME_NEW,' ')=0 then INDICATOR_NAME_NEW
      when instr(INDICATOR_NAME_NEW,' ')>0 then substr(INDICATOR_NAME_NEW,0,instr(INDICATOR_NAME_NEW,' ')-1)
    end as IND_USER_LAST_NAME
  ,case when instr(INDICATOR_NAME_NEW,' ')>0 then substr(INDICATOR_NAME_NEW,instr(INDICATOR_NAME_NEW,' ')+1)
      else ' '
    end as IND_USER_FIRST_NAME
  ,UPDATE_STAFF_CD
  ,CASE 
    WHEN SPE_IND_FLG IN (0,1) THEN '1' 
    WHEN SPE_IND_FLG IN (2,3) THEN '2'
   END AS SPE_IND_FLG
  ,COP_ORDER_NUMBER
  ,EDITABLE_FLG
  ,0 AS EQUIP_TYPE
FROM
  IND_DEVELOP_EQUIP_NEW 

ORDER BY
    IND_ID
    , CTL_NO