WITH EQUIP_MAXUPD_TMP AS (
	SELECT
		PATID, PLURAL, CTL_NO, MAX(UP_DATE) MAX_UP_DATE, :DIALYSIS_DATE AS DIALYSIS_DATE
	FROM
		IND_DIALYSIS_EQUIP
	WHERE
		PATID=:PATID
	    AND  PLURAL=:PLURAL 
		AND (:DIALYSIS_DATE BETWEEN IND_START_DATE AND IND_END_DATE)
	GROUP BY PATID, PLURAL, CTL_NO)
  ,EQUIP_TMP AS (
    SELECT
        EQUIP.PATID, EQUIP.PLURAL, MAX(EQUIP.IND_NO) MAX_IND_NO, EQUIP.CTL_NO, ET.MAX_UP_DATE, ET.DIALYSIS_DATE, EQUIP.EQUIP_CD
    FROM
        IND_DIALYSIS_EQUIP EQUIP, EQUIP_MAXUPD_TMP ET
    WHERE
        EQUIP.PATID = ET.PATID
      AND EQUIP.PLURAL = ET.PLURAL
      AND EQUIP.CTL_NO = ET.CTL_NO
      AND EQUIP.UP_DATE = ET.MAX_UP_DATE
      AND ET.DIALYSIS_DATE BETWEEN EQUIP.IND_START_DATE AND EQUIP.IND_END_DATE
    GROUP BY EQUIP.PATID, EQUIP.PLURAL, EQUIP.CTL_NO, ET.MAX_UP_DATE, ET.DIALYSIS_DATE, EQUIP.EQUIP_CD
  )
  ,CLASS_NAME_TMP as (
	SELECT
		CLASS_CD
		,CLASS_NAME
		,UP_DATE
		,NVL( LEAD ( UP_DATE, 1, NULL ) OVER ( PARTITION BY CLASS_CD ORDER BY CLASS_CD, UP_DATE ASC ), SYSDATE ) AS END_DATE 
	FROM MST_CLASS_NAME where CLASS_KIND = '2'
  )
  ,MST_EQUIPMENT_TMP AS (
	SELECT
		EQUIP_CD
		,EQUIP_NAME
		,EQUIP_GROUP_CD
		,UNIT
		,UP_DATE
		,NVL( LEAD ( UP_DATE, 1, NULL ) OVER ( PARTITION BY EQUIP_CD ORDER BY EQUIP_CD, UP_DATE ASC ), SYSDATE ) AS END_DATE 
	FROM MST_EQUIPMENT
  )
  ,MST_STAFF_NEW AS (
	SELECT
		STAFF_CD,
		UP_DATE,
		TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS STAFF_NAME
	FROM MST_STAFF
  )
  ,STAFF_TMP AS (
	SELECT
		STAFF_CD
		,CASE WHEN instr( STAFF_NAME, ' ' ) = 0 THEN STAFF_NAME
			WHEN instr( STAFF_NAME, ' ' ) > 0 THEN substr( STAFF_NAME, 0, instr( STAFF_NAME, ' ' ) - 1 ) 
			END AS LAST_NAME
		,CASE WHEN instr( STAFF_NAME, ' ' ) > 0 THEN substr( STAFF_NAME, instr( STAFF_NAME, ' ' ) + 1 ) ELSE ' ' END AS FIRST_NAME
		,UP_DATE
		,NVL( LEAD ( UP_DATE, 1, NULL ) OVER ( PARTITION BY STAFF_CD ORDER BY STAFF_CD, UP_DATE ASC ), SYSDATE ) AS END_DATE 
	FROM MST_STAFF_NEW
  )
SELECT
  EQUIP.PATID || ET.DIALYSIS_DATE || TO_CHAR(EQUIP.PLURAL) IND_ID
  ,EQUIP.CTL_NO
  ,EQUIP.PATID
  ,0 EQUIP_TYPE
  ,EQUIP.SETTING
  ,CASE EQUIP.SETTING
    WHEN '3' THEN
        (CASE
        WHEN (LPAD(TRIM(EQUIP.EQUIP_CD), 10, '0') IN (SELECT TRIM( REGEXP_SUBSTR( P_SN, '[^,]+', 1, LEVEL ) ) AS EXTRACTED_VALUE FROM SYNC_CONDSET CONNECT BY LEVEL <= REGEXP_COUNT ( P_SN, ',' ) + 1))
        THEN 'SN' || SUBSTR(LPAD(TRIM(EQUIP.EQUIP_CD), 10, '0'), 3)
        ELSE LPAD(TRIM(EQUIP.EQUIP_CD), 10, '0')
        END)
    ELSE LPAD(TRIM(EQUIP.EQUIP_CD), 10, '0')
    END EQUIP_CD
  ,MST_EQUIP.EQUIP_NAME
  ,MST_EQUIP.EQUIP_GROUP_CD
  ,CLASS_NAME.CLASS_NAME
  ,MST_EQUIP.UNIT
  ,EQUIP.VALUE_1W1N
  ,EQUIP.VALUE_1W2N
  ,EQUIP.VALUE_1W3N
  ,EQUIP.VALUE_1W4N
  ,EQUIP.VALUE_1W5N
  ,EQUIP.VALUE_1W6N
  ,EQUIP.VALUE_1W7N
  ,EQUIP.VALUE_2W1N
  ,EQUIP.VALUE_2W2N
  ,EQUIP.VALUE_2W3N
  ,EQUIP.VALUE_2W4N
  ,EQUIP.VALUE_2W5N
  ,EQUIP.VALUE_2W6N
  ,EQUIP.VALUE_2W7N
  ,EQUIP.INDICATOR_CD
  ,INDICATOR.FIRST_NAME INDICATOR_FIRST_NAME
  ,INDICATOR.LAST_NAME INDICATOR_LAST_NAME
  ,EQUIP.UPDATE_STAFF_CD
  ,UPDATER.FIRST_NAME UPDATE_STAFF_FIRST_NAME
  ,UPDATER.LAST_NAME UPDATE_STAFF_LAST_NAME
  ,CASE 
    WHEN SPE_IND_FLG IN (0,1) THEN '1' 
    WHEN SPE_IND_FLG IN (2,3) THEN '2'
   END AS SPE_IND_FLG
  ,EQUIP.COP_ORDER_NUMBER
  ,EQUIP.EDITABLE_FLG
  ,EQUIP.DAY_PATTERN
  ,EQUIP.DEL_FLG
FROM
  IND_DIALYSIS_EQUIP EQUIP
    INNER JOIN EQUIP_TMP ET
      ON EQUIP.PATID = ET.PATID
	  AND EQUIP.PLURAL = ET.PLURAL
	  AND EQUIP.CTL_NO = ET.CTL_NO
	  AND EQUIP.UP_DATE = ET.MAX_UP_DATE
      AND EQUIP.IND_NO = ET.MAX_IND_NO
	LEFT JOIN MST_EQUIPMENT_TMP MST_EQUIP
		ON MST_EQUIP.EQUIP_CD = ET.EQUIP_CD
		AND TO_DATE(:SCHUPDATE, 'yyyy-mm-dd hh24:mi:ss') BETWEEN MST_EQUIP.UP_DATE AND MST_EQUIP.END_DATE
	LEFT JOIN CLASS_NAME_TMP CLASS_NAME
		ON CLASS_NAME.CLASS_CD = MST_EQUIP.EQUIP_GROUP_CD
		AND TO_DATE(:SCHUPDATE, 'yyyy-mm-dd hh24:mi:ss') BETWEEN CLASS_NAME.UP_DATE AND CLASS_NAME.END_DATE
	LEFT JOIN STAFF_TMP INDICATOR ON INDICATOR.STAFF_CD = EQUIP.INDICATOR_CD AND TO_DATE(:SCHUPDATE, 'yyyy-mm-dd hh24:mi:ss') BETWEEN INDICATOR.UP_DATE AND INDICATOR.END_DATE
	LEFT JOIN STAFF_TMP UPDATER ON UPDATER.STAFF_CD = EQUIP.INDICATOR_CD AND TO_DATE(:SCHUPDATE, 'yyyy-mm-dd hh24:mi:ss') BETWEEN UPDATER.UP_DATE AND UPDATER.END_DATE
ORDER BY
  EQUIP.CTL_NO