WITH ADD_MAXUPD_TMP AS (
	SELECT
		PATID, PLURAL, CTL_NO, MAX(UP_DATE) MAX_UP_DATE, :DIALYSIS_DATE AS DIALYSIS_DATE
	FROM
		IND_DIALYSIS_ADD
	WHERE
		PATID=:PATID
	    AND  PLURAL=:PLURAL
		AND
		(:DIALYSIS_DATE BETWEEN IND_START_DATE AND IND_END_DATE)
	GROUP BY PATID, PLURAL, CTL_NO
    )
  ,ADD_TMP AS (
    SELECT
        IND_ADD.PATID, IND_ADD.PLURAL, MAX(IND_ADD.IND_NO) MAX_IND_NO, IND_ADD.CTL_NO, AT.MAX_UP_DATE, AT.DIALYSIS_DATE
    FROM
        IND_DIALYSIS_ADD IND_ADD, ADD_MAXUPD_TMP AT
    WHERE
      IND_ADD.PATID = AT.PATID
      AND IND_ADD.PLURAL = AT.PLURAL
      AND IND_ADD.CTL_NO = AT.CTL_NO
      AND IND_ADD.UP_DATE = AT.MAX_UP_DATE
      AND AT.DIALYSIS_DATE BETWEEN IND_ADD.IND_START_DATE AND IND_ADD.IND_END_DATE
    GROUP BY IND_ADD.PATID, IND_ADD.PLURAL, IND_ADD.CTL_NO, AT.MAX_UP_DATE, AT.DIALYSIS_DATE
  )
  ,MST_STAFF_NEW AS (
	SELECT
		STAFF_CD,
		UP_DATE,
		TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS STAFF_NAME
	FROM MST_STAFF
  )
  ,STAFF_TMP AS (
	SELECT
		STAFF_CD
		,CASE WHEN instr( STAFF_NAME, ' ' ) = 0 THEN STAFF_NAME
			WHEN instr( STAFF_NAME, ' ' ) > 0 THEN substr( STAFF_NAME, 0, instr( STAFF_NAME, ' ' ) - 1 ) 
			END AS LAST_NAME
		,CASE WHEN instr( STAFF_NAME, ' ' ) > 0 THEN substr( STAFF_NAME, instr( STAFF_NAME, ' ' ) + 1 ) ELSE ' ' END AS FIRST_NAME
		,UP_DATE
		,NVL( LEAD ( UP_DATE, 1, NULL ) OVER ( PARTITION BY STAFF_CD ORDER BY STAFF_CD, UP_DATE ASC ), SYSDATE ) AS END_DATE 
	FROM MST_STAFF_NEW
  )
SELECT
  IND_ADD.PATID || AT.DIALYSIS_DATE || TO_CHAR(IND_ADD.PLURAL) IND_ID
  ,IND_ADD.PATID
  ,TO_NUMBER(IND_ADD.CTL_NO) AS CTL_NO 
  ,IND_ADD.ADDITION
  ,IND_ADD.INDICATOR_CD
  ,INDICATOR.FIRST_NAME INDICATOR_FIRST_NAME
  ,INDICATOR.LAST_NAME INDICATOR_LAST_NAME
  ,IND_ADD.UPDATE_STAFF_CD
  ,UPDATER.FIRST_NAME UPDATE_STAFF_FIRST_NAME
  ,UPDATER.LAST_NAME UPDATE_STAFF_LAST_NAME
  ,CASE 
    WHEN SPE_IND_FLG IN (0,1) THEN '1' 
    WHEN SPE_IND_FLG IN (2,3) THEN '2'
    END AS SPE_IND_FLG
  ,IND_ADD.COP_ORDER_NUMBER
  ,IND_ADD.EDITABLE_FLG
  ,IND_ADD.DEL_FLG
  ,IND_ADD.PLURAL
  ,IND_ADD.IND_START_DATE,IND_ADD.UP_DATE
FROM
  IND_DIALYSIS_ADD IND_ADD
    INNER JOIN ADD_TMP AT
      ON IND_ADD.PATID = AT.PATID
	  AND IND_ADD.PLURAL = AT.PLURAL
	  AND IND_ADD.CTL_NO = AT.CTL_NO
	  AND IND_ADD.UP_DATE = AT.MAX_UP_DATE
      AND IND_ADD.IND_NO = AT.MAX_IND_NO
	LEFT JOIN STAFF_TMP INDICATOR ON INDICATOR.STAFF_CD = IND_ADD.INDICATOR_CD AND TO_DATE(:SCHUPDATE, 'yyyy-mm-dd hh24:mi:ss') BETWEEN INDICATOR.UP_DATE AND INDICATOR.END_DATE
	LEFT JOIN STAFF_TMP UPDATER ON UPDATER.STAFF_CD = IND_ADD.INDICATOR_CD AND TO_DATE(:SCHUPDATE, 'yyyy-mm-dd hh24:mi:ss') BETWEEN UPDATER.UP_DATE AND UPDATER.END_DATE
ORDER BY IND_ADD.CTL_NO,IND_ADD.UP_DATE