WITH SCH_TMP AS (
	SELECT
		SCH_PLAN.DIALYSIS_DATE,
		SCH_PLAN.PATID,
		SCH_PLAN.PLURAL,
		SCH_PLAN.IND_ID
	FROM
		SYNC_ORD_MAIN_SCH_PLAN SCH_PLAN
	WHERE
		{0}
	)
,DIALYSIS_MAX_UPDINFO AS (
	SELECT
		IND_ADD.PATID,
		IND_ADD.PLURAL,
		SCH_PLAN.DIALYSIS_DATE,
		SCH_PLAN.IND_ID,
		IND_ADD.UP_DATE,
		IND_ADD.INDICATOR_CD,
		IND_ADD.UPDATE_STAFF_CD 
	FROM
		IND_DIALYSIS_ADD IND_ADD
		INNER JOIN (
		SELECT
			IND_ADD.PATID,
			IND_ADD.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID,
			MAX( IND_ADD.UP_DATE ) MAX_ADD_UPDATE 
		FROM
			IND_DIALYSIS_ADD IND_ADD
			INNER JOIN SCH_TMP SCH ON SCH.PATID = IND_ADD.PATID 
			AND SCH.PLURAL = IND_ADD.PLURAL 
			AND SCH.DIALYSIS_DATE BETWEEN IND_ADD.IND_START_DATE 
			AND IND_ADD.IND_END_DATE 
		GROUP BY
			IND_ADD.PATID,
			IND_ADD.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID 
		) SCH_PLAN ON SCH_PLAN.PATID = IND_ADD.PATID 
		AND SCH_PLAN.PLURAL = IND_ADD.PLURAL 
		AND SCH_PLAN.DIALYSIS_DATE BETWEEN IND_ADD.IND_START_DATE 
		AND IND_ADD.IND_END_DATE 
		AND IND_ADD.UP_DATE = MAX_ADD_UPDATE
	UNION ALL
	SELECT DISTINCT
		COND.PATID,
		COND.PLURAL,
		SCH_PLAN.DIALYSIS_DATE,
		SCH_PLAN.IND_ID,
		COND.UP_DATE,
		COND.INDICATOR_CD,
		COND.UPDATE_STAFF_CD 
	FROM
		IND_DIALYSIS_COND COND
		INNER JOIN (
		SELECT
			COND.PATID,
			COND.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID,
			MAX( COND.UP_DATE ) MAX_ADD_UPDATE 
		FROM
			IND_DIALYSIS_COND COND
			INNER JOIN SCH_TMP SCH ON SCH.PATID = COND.PATID 
			AND SCH.PLURAL = COND.PLURAL 
			AND SCH.DIALYSIS_DATE BETWEEN COND.IND_START_DATE 
			AND COND.IND_END_DATE 
		GROUP BY
			COND.PATID,
			COND.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID 
		) SCH_PLAN ON SCH_PLAN.PATID = COND.PATID 
		AND SCH_PLAN.PLURAL = COND.PLURAL 
		AND SCH_PLAN.DIALYSIS_DATE BETWEEN COND.IND_START_DATE 
		AND COND.IND_END_DATE 
		AND COND.UP_DATE = MAX_ADD_UPDATE
	UNION ALL
	SELECT DISTINCT
		EQUIP.PATID,
		EQUIP.PLURAL,
		SCH_PLAN.DIALYSIS_DATE,
		SCH_PLAN.IND_ID,
		EQUIP.UP_DATE,
		EQUIP.INDICATOR_CD,
		EQUIP.UPDATE_STAFF_CD 
	FROM
		IND_DIALYSIS_EQUIP EQUIP
		INNER JOIN (
		SELECT
			EQUIP.PATID,
			EQUIP.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID,
			MAX( EQUIP.UP_DATE ) MAX_ADD_UPDATE 
		FROM
			IND_DIALYSIS_EQUIP EQUIP
			INNER JOIN SCH_TMP SCH ON SCH.PATID = EQUIP.PATID 
			AND SCH.PLURAL = EQUIP.PLURAL 
			AND SCH.DIALYSIS_DATE BETWEEN EQUIP.IND_START_DATE 
			AND EQUIP.IND_END_DATE 
		GROUP BY
			EQUIP.PATID,
			EQUIP.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID 
		) SCH_PLAN ON SCH_PLAN.PATID = EQUIP.PATID 
		AND SCH_PLAN.PLURAL = EQUIP.PLURAL 
		AND SCH_PLAN.DIALYSIS_DATE BETWEEN EQUIP.IND_START_DATE 
		AND EQUIP.IND_END_DATE 
		AND EQUIP.UP_DATE = MAX_ADD_UPDATE
	UNION ALL
	SELECT DISTINCT
		MEDI.PATID,
		MEDI.PLURAL,
		SCH_PLAN.DIALYSIS_DATE,
		SCH_PLAN.IND_ID,
		MEDI.UP_DATE,
		MEDI.INDICATOR_CD,
		MEDI.UPDATE_STAFF_CD 
	FROM
		IND_DIALYSIS_MEDI MEDI
		INNER JOIN (
		SELECT
			MEDI.PATID,
			MEDI.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID,
			MAX( MEDI.UP_DATE ) MAX_ADD_UPDATE 
		FROM
			IND_DIALYSIS_MEDI MEDI
			INNER JOIN SCH_TMP SCH ON SCH.PATID = MEDI.PATID 
			AND SCH.PLURAL = MEDI.PLURAL 
			AND SCH.DIALYSIS_DATE BETWEEN MEDI.IND_START_DATE 
			AND MEDI.IND_END_DATE 
		GROUP BY
			MEDI.PATID,
			MEDI.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID 
		) SCH_PLAN ON SCH_PLAN.PATID = MEDI.PATID 
		AND SCH_PLAN.PLURAL = MEDI.PLURAL 
		AND SCH_PLAN.DIALYSIS_DATE BETWEEN MEDI.IND_START_DATE 
		AND MEDI.IND_END_DATE 
		AND MEDI.UP_DATE = MAX_ADD_UPDATE
	UNION ALL
	SELECT DISTINCT
		PLAN.PATID,
		PLAN.PLURAL,
		SCH_PLAN.DIALYSIS_DATE,
		SCH_PLAN.IND_ID,
		PLAN.UP_DATE,
		PLAN.INDICATOR_CD,
		PLAN.UPDATE_STAFF_CD 
	FROM
		IND_DIALYSIS_PLAN PLAN
		INNER JOIN (
		SELECT
			PLAN.PATID,
			PLAN.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID,
			MAX( PLAN.UP_DATE ) MAX_ADD_UPDATE 
		FROM
			IND_DIALYSIS_PLAN PLAN
			INNER JOIN SCH_TMP SCH ON SCH.PATID = PLAN.PATID 
			AND SCH.PLURAL = PLAN.PLURAL 
			AND SCH.DIALYSIS_DATE BETWEEN PLAN.IND_START_DATE 
			AND PLAN.IND_END_DATE 
		GROUP BY
			PLAN.PATID,
			PLAN.PLURAL,
			SCH.DIALYSIS_DATE,
			SCH.IND_ID
		) SCH_PLAN ON SCH_PLAN.PATID = PLAN.PATID 
		AND SCH_PLAN.PLURAL = PLAN.PLURAL 
		AND SCH_PLAN.DIALYSIS_DATE BETWEEN PLAN.IND_START_DATE 
		AND PLAN.IND_END_DATE 
		AND PLAN.UP_DATE = MAX_ADD_UPDATE 
)
SELECT DISTINCT
	UPDINFO.IND_ID,
	UPDINFO.UP_DATE,
	trim(UPDINFO.INDICATOR_CD) INDICATOR_CD,
	trim(UPDINFO.UPDATE_STAFF_CD) UPDATE_STAFF_CD
FROM
	DIALYSIS_MAX_UPDINFO UPDINFO
	INNER JOIN (
	        SELECT PATID, PLURAL, DIALYSIS_DATE, MAX( UP_DATE ) MAX_ADD_UPDATE
		    FROM DIALYSIS_MAX_UPDINFO
		    GROUP BY PATID, PLURAL, DIALYSIS_DATE
	)MAX_UPD
	ON UPDINFO.PATID = MAX_UPD.PATID 
	    AND UPDINFO.PLURAL = MAX_UPD.PLURAL 
	    AND UPDINFO.UP_DATE = MAX_UPD.MAX_ADD_UPDATE