WITH RST_DIALYSIS_NEW AS (
	SELECT
		PATID,
		DIALYSIS_NO,
		FACILITY_CD,
		RELATION_DIALYSIS_NO,
		REC_CLASS,
		TREAT_ITEM_CD,
		KUR_CD,
		KUR_NAME,
		BED_NO,
		BED_NAME,
		DEVICE_NO,
		UP_DATE,
		COND_SEND_DATE,
		ENTER_DATE,
		START_DATE,
		END_DATE,
		LEAVE_DATE,
		INOUT_FLG,
		DIALYSIS_NUM,
		WARD_CD,
		WARD_NAME,
		COURSE_CD,
		COURSE_NAME,
		PUNCTURE_1,
		PUNCTURE_DATE_1,
		PUNCTURE_2,
		PUNCTURE_DATE_2,
		COLLECT_1,
		COLLECT_DATE_1,
		COLLECT_2,
		COLLECT_DATE_2,
		CHARGE_1,
		CHARGE_DATE_1,
		CHARGE_2,
		CHARGE_DATE_2,
		BLOOD_CIRCULATE_TOTAL,
		DIALYSIS_TIME,
		KT_V,
		REC_SET_DATE,
		SEND_CTL_NO,
		BLOOD_PURIFIER_NAME,
		PULL_LEAVE_AMOUNT,
		CTR,
		MEASURE_DATE,
		CTR_WEIGHT,
		WATER_REMOVAL_TARGET,
		ADD_TOTAL,
		ADD_WATER_TOTAL,
		KT_V_MEASURE,
		URR,
		STATIC_VENOUS_PRESSURE,
		VENOUS_ACCESS_PRESSURE_RATIO,
		RE_LOOP_RATE,
		DEL_FLG,
		SERIES_CD,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM PUNCTURE_1_NAME ) ), '　', ' ' ), '\s+', ' ' )) AS PUNCTURE_1_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM PUNCTURE_2_NAME ) ), '　', ' ' ), '\s+', ' ' )) AS PUNCTURE_2_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM COLLECT_1_NAME ) ), '　', ' ' ), '\s+', ' ' )) AS COLLECT_1_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM COLLECT_2_NAME ) ), '　', ' ' ), '\s+', ' ' )) AS COLLECT_2_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM CHARGE_1_NAME ) ), '　', ' ' ), '\s+', ' ' )) AS CHARGE_1_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM CHARGE_2_NAME ) ), '　', ' ' ), '\s+', ' ' )) AS CHARGE_2_NAME_NEW
	FROM
		RST_DIALYSIS
)
SELECT
  b.PATID
  ,b.DIALYSIS_NO
  ,b.FACILITY_CD
  ,b.RELATION_DIALYSIS_NO
  ,b.REC_CLASS
  ,b.TREAT_ITEM_CD
  ,MST_TREAT_HIST.TREAT_TYPE AS TREAT_TYPE
  ,MST_TREAT_HIST.DEVICE_MODE AS RST_DEVICE_MODE
  ,b.KUR_CD
  ,b.KUR_NAME
  ,b.BED_NO
  ,b.BED_NAME
  ,b.DEVICE_NO
  ,(
    SELECT DEVICE_NAME
    FROM MST_DEVICE
    WHERE
      DEVICE_NO = b.DEVICE_NO
      AND UP_DATE = (SELECT MAX(UP_DATE) FROM MST_DEVICE WHERE DEVICE_NO = b.DEVICE_NO AND UP_DATE < b.UP_DATE)
   ) ADD_DEVICE_NAME
  ,b.COND_SEND_DATE
  ,b.ENTER_DATE
  ,b.START_DATE
  ,b.END_DATE
  ,b.LEAVE_DATE
  ,b.INOUT_FLG
  ,b.DIALYSIS_NUM
  ,b.WARD_CD
  ,b.WARD_NAME
  ,b.COURSE_CD
  ,b.COURSE_NAME
  ,b.PUNCTURE_1
  ,case when instr(b.PUNCTURE_1_NAME_NEW,' ')=0 then b.PUNCTURE_1_NAME_NEW
      when instr(b.PUNCTURE_1_NAME_NEW,' ')>0 then substr(b.PUNCTURE_1_NAME_NEW,0,instr(b.PUNCTURE_1_NAME_NEW,' ')-1)
    end as PUNCTURE_1_LAST_NAME
  ,case when instr(b.PUNCTURE_1_NAME_NEW,' ')>0 then substr(b.PUNCTURE_1_NAME_NEW,instr(b.PUNCTURE_1_NAME_NEW,' ')+1)
      else ' '
    end as PUNCTURE_1_FIRST_NAME
  ,CASE WHEN b.PUNCTURE_DATE_1 IS NOT NULL THEN to_char(b.PUNCTURE_DATE_1, 'yyyy-mm-dd')||'T'||to_char(b.PUNCTURE_DATE_1, 'hh24:mi:ss')||'.000+09:00' END PUNCTURE_DATE_1
  ,b.PUNCTURE_2
  ,case when instr(b.PUNCTURE_2_NAME_NEW,' ')=0 then b.PUNCTURE_2_NAME_NEW
      when instr(b.PUNCTURE_2_NAME_NEW,' ')>0 then substr(b.PUNCTURE_2_NAME_NEW,0,instr(b.PUNCTURE_2_NAME_NEW,' ')-1)
    end as PUNCTURE_2_LAST_NAME
  ,case when instr(b.PUNCTURE_2_NAME_NEW,' ')>0 then substr(b.PUNCTURE_2_NAME_NEW,instr(b.PUNCTURE_2_NAME_NEW,' ')+1)
      else ' '
    end as PUNCTURE_2_FIRST_NAME
  ,CASE WHEN b.PUNCTURE_DATE_2 IS NOT NULL THEN to_char(b.PUNCTURE_DATE_2, 'yyyy-mm-dd')||'T'||to_char(b.PUNCTURE_DATE_2, 'hh24:mi:ss')||'.000+09:00' END PUNCTURE_DATE_2
  ,b.COLLECT_1
  ,case when instr(b.COLLECT_1_NAME_NEW,' ')=0 then b.COLLECT_1_NAME_NEW
      when instr(b.COLLECT_1_NAME_NEW,' ')>0 then substr(b.COLLECT_1_NAME_NEW,0,instr(b.COLLECT_1_NAME_NEW,' ')-1)
    end as COLLECT_1_LAST_NAME
  ,case when instr(b.COLLECT_1_NAME_NEW,' ')>0 then substr(b.COLLECT_1_NAME_NEW,instr(b.COLLECT_1_NAME_NEW,' ')+1)
      else ' '
    end as COLLECT_1_FIRST_NAME
  ,CASE WHEN b.COLLECT_DATE_1 IS NOT NULL THEN to_char(b.COLLECT_DATE_1, 'yyyy-mm-dd')||'T'||to_char(b.COLLECT_DATE_1, 'hh24:mi:ss')||'.000+09:00' END COLLECT_DATE_1
  ,b.COLLECT_2
  ,case when instr(b.COLLECT_2_NAME_NEW,' ')=0 then b.COLLECT_2_NAME_NEW
      when instr(b.COLLECT_2_NAME_NEW,' ')>0 then substr(b.COLLECT_2_NAME_NEW,0,instr(b.COLLECT_2_NAME_NEW,' ')-1)
    end as COLLECT_2_LAST_NAME
  ,case when instr(b.COLLECT_2_NAME_NEW,' ')>0 then substr(b.COLLECT_2_NAME_NEW,instr(b.COLLECT_2_NAME_NEW,' ')+1)
      else ' '
    end as COLLECT_2_FIRST_NAME
  ,CASE WHEN b.COLLECT_DATE_2 IS NOT NULL THEN to_char(b.COLLECT_DATE_2, 'yyyy-mm-dd')||'T'||to_char(b.COLLECT_DATE_2, 'hh24:mi:ss')||'.000+09:00' END COLLECT_DATE_2
  ,b.CHARGE_1
  ,case when instr(b.CHARGE_1_NAME_NEW,' ')=0 then b.CHARGE_1_NAME_NEW
      when instr(b.CHARGE_1_NAME_NEW,' ')>0 then substr(b.CHARGE_1_NAME_NEW,0,instr(b.CHARGE_1_NAME_NEW,' ')-1)
    end as CHARGE_1_LAST_NAME
  ,case when instr(b.CHARGE_1_NAME_NEW,' ')>0 then substr(b.CHARGE_1_NAME_NEW,instr(b.CHARGE_1_NAME_NEW,' ')+1)
      else ' '
    end as CHARGE_1_FIRST_NAME
  ,CASE WHEN b.CHARGE_DATE_1 IS NOT NULL THEN to_char(b.CHARGE_DATE_1, 'yyyy-mm-dd')||'T'||to_char(b.CHARGE_DATE_1, 'hh24:mi:ss')||'.000+09:00' END CHARGE_DATE_1
  ,b.CHARGE_2
  ,case when instr(b.CHARGE_2_NAME_NEW,' ')=0 then b.CHARGE_2_NAME_NEW
      when instr(b.CHARGE_2_NAME_NEW,' ')>0 then substr(b.CHARGE_2_NAME_NEW,0,instr(b.CHARGE_2_NAME_NEW,' ')-1)
    end as CHARGE_2_LAST_NAME
  ,case when instr(b.CHARGE_2_NAME_NEW,' ')>0 then substr(b.CHARGE_2_NAME_NEW,instr(b.CHARGE_2_NAME_NEW,' ')+1)
      else ' '
    end as CHARGE_2_FIRST_NAME
  ,CASE  WHEN b.CHARGE_DATE_2 IS NOT NULL THEN to_char(b.CHARGE_DATE_2, 'yyyy-mm-dd')||'T'||to_char(b.CHARGE_DATE_2, 'hh24:mi:ss')||'.000+09:00' END CHARGE_DATE_2
  ,CASE  WHEN b.PUNCTURE_DATE_1 IS NOT NULL THEN to_char(b.PUNCTURE_DATE_1, 'yyyy-mm-dd')||'T'||to_char(b.PUNCTURE_DATE_1, 'hh24:mi:ss')||'.000+09:00'
     WHEN b.PUNCTURE_DATE_2 IS NOT NULL THEN to_char(b.PUNCTURE_DATE_2, 'yyyy-mm-dd')||'T'||to_char(b.PUNCTURE_DATE_2, 'hh24:mi:ss')||'.000+09:00' END PUNCTURE_DATE
  ,CASE WHEN b.COLLECT_DATE_1 IS NOT NULL THEN to_char(b.COLLECT_DATE_1, 'yyyy-mm-dd')||'T'||to_char(b.COLLECT_DATE_1, 'hh24:mi:ss')||'.000+09:00'
     WHEN b.COLLECT_DATE_2 IS NOT NULL THEN to_char(b.COLLECT_DATE_2, 'yyyy-mm-dd')||'T'||to_char(b.COLLECT_DATE_2, 'hh24:mi:ss')||'.000+09:00' END COLLECT_DATE
  ,b.BLOOD_CIRCULATE_TOTAL
  ,b.DIALYSIS_TIME
  ,b.KT_V
  ,b.REC_SET_DATE
  ,b.SEND_CTL_NO
  ,b.BLOOD_PURIFIER_NAME
  ,b.PULL_LEAVE_AMOUNT
  ,b.CTR
  ,b.MEASURE_DATE
  ,b.CTR_WEIGHT
  ,b.WATER_REMOVAL_TARGET
  ,b.ADD_TOTAL
  ,b.ADD_WATER_TOTAL
  ,b.KT_V_MEASURE
  ,b.URR
  ,b.STATIC_VENOUS_PRESSURE
  ,b.VENOUS_ACCESS_PRESSURE_RATIO
  ,b.RE_LOOP_RATE
  ,b.UP_DATE
  ,NVL(EDITION.MAX_EDITION, 0) RST_EDITION
  ,EDITION.MIN_SEND_DATE SEND_DATE1
  ,EDITION.MAX_SEND_DATE SEND_DATE2
  ,SCH_PLAN.PATID || SCH_PLAN.DIALYSIS_DATE || TO_CHAR(SCH_PLAN.PLURAL) IND_ID
  ,SCH_PLAN.PLURAL
  ,SCH_PLAN.DIALYSIS_DATE
  ,SCH_PLAN.UP_DATE SCH_UPDATE
FROM
  RST_DIALYSIS_NEW b
    LEFT JOIN (
      SELECT
        DIALYSIS_NO
        ,MAX( EDITION ) AS MAX_EDITION
        ,MIN( SEND_DATE ) MIN_SEND_DATE
        ,MAX( SEND_DATE ) MAX_SEND_DATE
      FROM RST_DIALYSIS_HST 
      WHERE PATID IN ({0}) 
      GROUP BY DIALYSIS_NO) EDITION ON EDITION.DIALYSIS_NO = b.DIALYSIS_NO
  LEFT JOIN SCH_DIALYSIS_PLAN SCH_PLAN ON b.DIALYSIS_NO = SCH_PLAN.RESULT_DIALYSISNO
  LEFT JOIN (
    SELECT
        TREAT_ITEM_CD
        ,DEVICE_MODE
        ,TREAT_TYPE
        ,REG_DATE
        ,NVL( LEAD ( REG_DATE, 1, NULL ) OVER ( PARTITION BY TREAT_ITEM_CD ORDER BY TREAT_ITEM_CD, REG_DATE ASC ), SYSDATE ) AS END_DATE 
    FROM MST_TREAT_ITEM
  ) MST_TREAT_HIST
    ON MST_TREAT_HIST.TREAT_ITEM_CD = b.TREAT_ITEM_CD
    AND b.UP_DATE BETWEEN MST_TREAT_HIST.REG_DATE AND MST_TREAT_HIST.END_DATE
WHERE
  b.PATID IN ({0}) 
  AND b.START_DATE >= TO_DATE(:START_DATE, 'yyyyMMdd')
  AND b.START_DATE < TO_DATE(:END_DATE, 'yyyyMMdd')
  AND b.DEL_FLG = '0' 
  AND b.SERIES_CD = '{SERIES_CD}'
  AND ({1})
ORDER BY b.DIALYSIS_NO