WITH MEDI_TMP AS (
	SELECT
		DIALYSIS_NO, CTL_NO, IND_NO, MAX(IND_UP_DATE) MAX_UP_DATE
	FROM
		RST_DIALYSIS_MEDICATION RD
	WHERE
		{0}
	GROUP BY DIALYSIS_NO, CTL_NO, IND_NO
),
IND_DEVELOP_MEDI_NORMAL AS (SELECT w1.*,row_number() over (partition by IND_ID,MEDICINE_CD ORDER BY IND_ID, CTL_NO) as row_no FROM IND_DEVELOP_MEDI w1),
RST_DIALYSIS_MEDICATION_NORMAL AS (SELECT w2.*, CASE WHEN SET_MEDICINE_FLG = '0' THEN MEDICINE_CD   else SET_MEDICINE_CD  END as MEDI_CD,row_number() over (partition by DIALYSIS_NO,MEDICINE_CD ORDER BY DIALYSIS_NO, EFFECT_DATE) as row_no,
	TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS STAFF_NAME_NEW FROM RST_DIALYSIS_MEDICATION w2)
SELECT
  RST_MEDI.DIALYSIS_NO
  ,COALESCE(smln_on_ctl_no.NO, smln_on_dialysis_no.NO) as  CTL_NO
  ,CASE WHEN  RST_MEDI.SET_MEDICINE_FLG = '0' THEN RST_MEDI.MEDICINE_CLASS_NAME 
        WHEN  RST_MEDI.SET_MEDICINE_FLG = '1' THEN  RST_MEDI.SET_MEDICINE_CLASS_NAME 
        END MEDICINE_CLASS_NAME
  ,RST_MEDI.SET_MEDICINE_FLG
  ,CASE WHEN RST_MEDI.SET_MEDICINE_FLG = '0' THEN  RST_MEDI.MEDICINE_CD 
        WHEN RST_MEDI.SET_MEDICINE_FLG = '1' THEN SET_MEDICINE_CD 
        END MEDICINE_CD
  ,CASE WHEN  RST_MEDI.SET_MEDICINE_FLG = '0' THEN  RST_MEDI.MEDICINE_NAME 
        WHEN  RST_MEDI.SET_MEDICINE_FLG = '1' THEN  RST_MEDI.SET_MEDICINE_NAME 
        END MEDICINE_NAME
  ,RST_MEDI.AMOUNT
  ,RST_MEDI.UNIT
  ,RST_MEDI.TIMING_CD
  ,RST_MEDI.TIMING_NAME
  ,RST_MEDI.PROCEDURE_CD
  ,RST_MEDI.PROCEDURE_NAME
  ,RST_MEDI.EFFECT_FLG
  ,RST_MEDI.EFFECT_DATE
  ,RST_MEDI.STAFF_CD
  ,RST_MEDI.STAFF_NAME_NEW as STAFF_NAME
  ,case when instr(RST_MEDI.STAFF_NAME_NEW,' ')=0 then RST_MEDI.STAFF_NAME_NEW
      when instr(RST_MEDI.STAFF_NAME_NEW,' ')>0 then substr(RST_MEDI.STAFF_NAME_NEW,0,instr(RST_MEDI.STAFF_NAME_NEW,' ')-1)
    end as STAFF_NAME_LAST_NAME
  ,case when instr(RST_MEDI.STAFF_NAME_NEW,' ')>0 then substr(RST_MEDI.STAFF_NAME_NEW,instr(RST_MEDI.STAFF_NAME_NEW,' ')+1)
      else ' '
    end as STAFF_NAME_FIRST_NAME
  ,RST_MEDI.COP_ORDER_NUMBER
  ,RST_MEDI.COMMENTS
  ,1 AS INPUT_CLASS
  ,RST_MEDI.EDITABLE_FLG
FROM
  RST_DIALYSIS_MEDICATION_NORMAL RST_MEDI 
    INNER JOIN MEDI_TMP MEDI
      ON RST_MEDI.DIALYSIS_NO = MEDI.DIALYSIS_NO
      AND RST_MEDI.CTL_NO = MEDI.CTL_NO
      AND RST_MEDI.IND_NO = MEDI.IND_NO
      AND RST_MEDI.IND_UP_DATE = MEDI.MAX_UP_DATE
    INNER JOIN RST_DIALYSIS rst  on rst.DIALYSIS_NO=MEDI.DIALYSIS_NO
    LEFT JOIN SCH_DIALYSIS_PLAN SCH_PLAN ON SCH_PLAN.RESULT_DIALYSISNO = RST_MEDI.DIALYSIS_NO
	LEFT  JOIN IND_DEVELOP_MEDI_NORMAL DEVELOP_MEDI ON SCH_PLAN.IND_ID = DEVELOP_MEDI.IND_ID and DEVELOP_MEDI.MEDICINE_CD=RST_MEDI.MEDI_CD and RST_MEDI.row_no = DEVELOP_MEDI.row_no
    LEFT JOIN (  
        SELECT NO, ind_no AS CTL_NO ,PATID,PLURAL
        FROM SYNC_MEDICINE_LATEST_NO  WHERE  DIALYSIS_NO IS  NULL  and SERIES_CD='{SERIES_CD}'
    ) smln_on_ctl_no ON DEVELOP_MEDI.CTL_NO = smln_on_ctl_no.CTL_NO   and smln_on_ctl_no.PATID=rst.PATID and  smln_on_ctl_no.PLURAL=DEVELOP_MEDI.PLURAL
    LEFT JOIN (  
        SELECT NO,  DIALYSIS_NO,PATID,RST_NO 
        FROM SYNC_MEDICINE_LATEST_NO  WHERE  DIALYSIS_NO IS NOT NULL and SERIES_CD='{SERIES_CD}'
    ) smln_on_dialysis_no ON RST_MEDI.DIALYSIS_NO = smln_on_dialysis_no.DIALYSIS_NO   and smln_on_dialysis_no.PATID=rst.PATID and   smln_on_dialysis_no.RST_NO=RST_MEDI.CTL_NO
    AND smln_on_ctl_no.NO IS NULL
order by
    RST_MEDI.DIALYSIS_NO,
	RST_MEDI.EFFECT_DATE NULLS FIRST,DEVELOP_MEDI.CTL_NO,COALESCE(smln_on_ctl_no.NO, smln_on_dialysis_no.NO)