WITH SCH_PLAN_TMP AS (
  SELECT
    PATID
    ,DIALYSIS_DATE
    ,PLURAL
  FROM
    SCH_DIALYSIS_PLAN IND_PLAN
  WHERE
    DUMMY_FLG = 0
    AND SERIES_CD = '{4}'
    AND (IND_PLAN.PATID,IND_PLAN.PLURAL) IN ({0}) 
    AND DIALYSIS_DATE = TO_DATE('{1}', 'yyyyMMdd')
    AND RESULT_DIALYSISNO IS NOT NULL
)
,PLAN_DAY_TMP AS (
  SELECT
    SCH_PLAN.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.OPE_IND_PLAN
    ,TO_CHAR( TO_DATE( SCH_PLAN.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 YOBI
    ,IND_PLAN.IND_START_DATE
    ,IND_PLAN.IND_END_DATE
    ,IND_PLAN.IND_NO
    ,IND_PLAN.UP_DATE
    ,CASE WHEN
        IND_PLAN.CYCLE_WEEK != 2
        OR
        (IND_PLAN.CYCLE_WEEK = 2 AND 0 = MOD( TO_CHAR( TO_DATE( IND_PLAN.IND_START_DATE, 'YYYYMMDD' ), 'IW' ) - TO_CHAR( TO_DATE( SCH_PLAN.DIALYSIS_DATE, 'YYYYMMDD' ), 'IW' ), 2 ))
        THEN
        CASE
            ( TO_CHAR( TO_DATE( SCH_PLAN.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 )
            WHEN 1 THEN VALUE_1W1N
            WHEN 2 THEN VALUE_1W2N
            WHEN 3 THEN VALUE_1W3N
            WHEN 4 THEN VALUE_1W4N
            WHEN 5 THEN VALUE_1W5N
            WHEN 6 THEN VALUE_1W6N
            WHEN 0 THEN VALUE_1W7N
        END
        ELSE
        CASE
            ( TO_CHAR( TO_DATE( SCH_PLAN.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 )
            WHEN 1 THEN VALUE_2W1N
            WHEN 2 THEN VALUE_2W2N
            WHEN 3 THEN VALUE_2W3N
            WHEN 4 THEN VALUE_2W4N
            WHEN 5 THEN VALUE_2W5N
            WHEN 6 THEN VALUE_2W6N
            WHEN 0 THEN VALUE_2W7N
        END
        END VALUE
	,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
  FROM
    IND_DIALYSIS_PLAN IND_PLAN,
    SCH_PLAN_TMP SCH_PLAN
  WHERE
    IND_PLAN.OPE_IND_PLAN = '0'
    AND IND_PLAN.PATID = SCH_PLAN.PATID
    AND IND_PLAN.PLURAL = SCH_PLAN.PLURAL
    AND (SCH_PLAN.DIALYSIS_DATE BETWEEN IND_PLAN.IND_START_DATE AND IND_PLAN.IND_END_DATE)
)
,SINGLE_PLAN_DAY_TMP AS (
  SELECT
    SCH_PLAN.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.OPE_IND_PLAN
    ,TO_CHAR( TO_DATE( SCH_PLAN.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 YOBI
    ,IND_PLAN.VALUE_1W1N VALUE
    ,IND_PLAN.IND_START_DATE
    ,IND_PLAN.IND_END_DATE
    ,IND_PLAN.IND_NO
    ,IND_PLAN.UP_DATE
    ,IND_PLAN.DEL_FLG
	,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
  FROM
    IND_DIALYSIS_PLAN IND_PLAN,
    SCH_PLAN_TMP SCH_PLAN
  WHERE
    IND_PLAN.OPE_IND_PLAN = '1'
    AND IND_PLAN.PATID = SCH_PLAN.PATID
    AND IND_PLAN.PLURAL = SCH_PLAN.PLURAL
	AND ( SCH_PLAN.DIALYSIS_DATE BETWEEN IND_PLAN.IND_START_DATE AND IND_PLAN.IND_END_DATE )
)
,UPDATE_TMP AS ( SELECT PATID, DIALYSIS_DATE, MAX( UP_DATE ) MAX_UP_DATE, PLURAL FROM PLAN_DAY_TMP GROUP BY PATID, DIALYSIS_DATE, PLURAL )
,SINGLE_UPDATE_TMP AS (
  SELECT
    PATID,
    DIALYSIS_DATE,
    PLURAL,
    MAX( UP_DATE ) MAX_UP_DATE
  FROM
    SINGLE_PLAN_DAY_TMP
  GROUP BY PATID, DIALYSIS_DATE, PLURAL
)
,SERIES_CD_TMP AS (
    SELECT PATID, SERIES_CD, START_DATE, END_DATE FROM SYS_PAT_SERIES_FACILITY WHERE SERIES_CD = '{4}' and MAIN_FLG='1'
)
,DIALYSIS_PLAN AS (
  SELECT
    IND_PLAN.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.VALUE
    ,IND_PLAN.OPE_IND_PLAN
    ,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
    ,IND_PLAN.UP_DATE
  FROM PLAN_DAY_TMP IND_PLAN
    INNER JOIN UPDATE_TMP
      ON UPDATE_TMP.PATID = IND_PLAN.PATID
      AND UPDATE_TMP.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE
      AND IND_PLAN.UP_DATE = UPDATE_TMP.MAX_UP_DATE AND UPDATE_TMP.PLURAL = IND_PLAN.PLURAL
    INNER JOIN SERIES_CD_TMP SERIES
      ON IND_PLAN.PATID = SERIES.PATID
      AND IND_PLAN.DIALYSIS_DATE BETWEEN SERIES.START_DATE AND SERIES.END_DATE
  WHERE
    LENGTH( IND_PLAN.VALUE ) >= 8
    AND IND_PLAN.IND_NO = (
          SELECT MAX( IND_NO ) FROM PLAN_DAY_TMP SCH_PLAN
          WHERE SCH_PLAN.PATID = IND_PLAN.PATID AND IND_PLAN.UP_DATE = SCH_PLAN.UP_DATE AND IND_PLAN.PLURAL = SCH_PLAN.PLURAL AND SCH_PLAN.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE 												
        )
  UNION ALL
  SELECT
    IND_PLAN.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.VALUE
    ,IND_PLAN.OPE_IND_PLAN
    ,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
    ,IND_PLAN.UP_DATE
  FROM SINGLE_PLAN_DAY_TMP IND_PLAN
    INNER JOIN SINGLE_UPDATE_TMP UPDATE_TMP
      ON UPDATE_TMP.PATID = IND_PLAN.PATID
      AND UPDATE_TMP.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE
      AND UPDATE_TMP.MAX_UP_DATE = IND_PLAN.UP_DATE
      AND UPDATE_TMP.PLURAL = IND_PLAN.PLURAL
    INNER JOIN SERIES_CD_TMP SERIES
      ON IND_PLAN.PATID = SERIES.PATID
      AND IND_PLAN.DIALYSIS_DATE BETWEEN SERIES.START_DATE AND SERIES.END_DATE
    WHERE
      IND_PLAN.DEL_FLG = '0'
      AND LENGTH( IND_PLAN.VALUE ) >= 8
      AND IND_PLAN.IND_NO = (
        SELECT MAX( IND_NO )
        FROM SINGLE_PLAN_DAY_TMP SCH_PLAN
        WHERE SCH_PLAN.PATID = IND_PLAN.PATID AND IND_PLAN.UP_DATE = SCH_PLAN.UP_DATE AND IND_PLAN.PLURAL = SCH_PLAN.PLURAL AND SCH_PLAN.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE 												
      )
)
SELECT
  DIALYSIS_DATE
  ,PATID
  ,PLURAL
  ,TO_CHAR( PATID ) || TO_CHAR( DIALYSIS_DATE ) || TO_CHAR(PLURAL ) IND_ID
  ,VALUE
  ,OPE_IND_PLAN
  ,TO_NUMBER(SUBSTR( VALUE, 0, 4 )) BED_NO
  ,(SELECT BED_NAME FROM V_MST_BED WHERE BED_NO = TO_NUMBER(SUBSTR( VALUE, 0, 4 ))) BED_NAME
  ,SUBSTR( VALUE, 5, 3 ) KUR_CD
  ,(SELECT KUR_NAME FROM V_MST_KUR WHERE KUR_CD = SUBSTR( VALUE, 5, 3 )) KUR_NAME
  ,'0' CYCLE_WEEK
  ,CASE TO_CHAR(TO_DATE(DIALYSIS_DATE, 'yyyyMMdd'), 'D') 
        WHEN '1' THEN 7
        WHEN '2' THEN 1
        WHEN '3' THEN 2
        WHEN '4' THEN 3
        WHEN '5' THEN 4
        WHEN '6' THEN 5
        WHEN '7' THEN 6
        END ADD_TREAT_WEEK
  ,INDICATOR_CD
  ,UPDATE_STAFF_CD
  ,'0' RST_DIALYSIS_STATE
  ,'' OFF_WATER
  ,'' TARE
  ,UP_DATE
FROM
  DIALYSIS_PLAN
ORDER BY
  PATID
  ,DIALYSIS_DATE