

INSERT INTO NKK.SYNC_ORD_MAIN_SCH_PLAN(DIALYSIS_DATE,PATID,PLURAL,IND_ID,VALUE,OPE_IND_PLAN,CYCLE_WEEK,INDICATOR_CD,UPDATE_STAFF_CD,UP_DATE)
WITH DATE_PARAM AS (SELECT TO_DATE(:START_DATE, 'yyyyMMdd') FROMDATE, TO_DATE( :END_DATE, 'yyyyMMdd' ) TODATE FROM DUAL)
,DAY_TMP AS (
  SELECT 
    TO_CHAR(DP.FROMDATE + rn, 'yyyyMMdd') AS DIALYSIS_DATE
  FROM
    ( SELECT ROWNUM - 1 rn FROM dual CONNECT BY ROWNUM <= ( SELECT TRUNC(TO_DATE( :END_DATE, 'yyyyMMdd' ) +1) - TRUNC(TO_DATE(:START_DATE, 'yyyyMMdd' ) ) FROM dual))
    ,DATE_PARAM DP
  WHERE
    TO_CHAR(DP.FROMDATE + rn, 'yyyy-mm-dd') BETWEEN DP.FROMDATE - 1 AND TO_CHAR(DP.TODATE, 'yyyy-mm-dd')
)
,SCH_PLAN_TMP AS (
  SELECT
    PATID
    ,DIALYSIS_DATE
    ,PLURAL
  FROM
    SCH_DIALYSIS_PLAN IND_PLAN
    ,DATE_PARAM DP
  WHERE
    DUMMY_FLG = 0
    {SERIES_CD}
    AND ({0})
    AND DIALYSIS_DATE BETWEEN DP.FROMDATE - 1 AND DP.TODATE + 1
    AND RESULT_DIALYSISNO IS NOT NULL
)
,PLAN_DAY_TMP AS (
  SELECT
    DT.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.OPE_IND_PLAN
    ,TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 YOBI
    ,IND_PLAN.IND_START_DATE
    ,IND_PLAN.IND_END_DATE
    ,IND_PLAN.IND_NO
    ,IND_PLAN.UP_DATE
    ,CASE WHEN
        IND_PLAN.CYCLE_WEEK != 2
        OR
        (IND_PLAN.CYCLE_WEEK = 2 AND 0 = MOD( TO_CHAR( TO_DATE( IND_PLAN.IND_START_DATE, 'YYYYMMDD' ), 'IW' ) - TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYYMMDD' ), 'IW' ), 2 ))
        THEN
        CASE
            ( TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 )
            WHEN 1 THEN VALUE_1W1N
            WHEN 2 THEN VALUE_1W2N
            WHEN 3 THEN VALUE_1W3N
            WHEN 4 THEN VALUE_1W4N
            WHEN 5 THEN VALUE_1W5N
            WHEN 6 THEN VALUE_1W6N
            WHEN 0 THEN VALUE_1W7N
        END
        ELSE
        CASE
            ( TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 )
            WHEN 1 THEN VALUE_2W1N
            WHEN 2 THEN VALUE_2W2N
            WHEN 3 THEN VALUE_2W3N
            WHEN 4 THEN VALUE_2W4N
            WHEN 5 THEN VALUE_2W5N
            WHEN 6 THEN VALUE_2W6N
            WHEN 0 THEN VALUE_2W7N
        END
        END VALUE
	,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
  FROM
    IND_DIALYSIS_PLAN IND_PLAN,
    DAY_TMP DT
  WHERE
    IND_PLAN.OPE_IND_PLAN = '0'
    AND IND_PLAN.IND_CLASS  <> '1'
    AND ({0})
    AND (DT.DIALYSIS_DATE BETWEEN IND_PLAN.IND_START_DATE AND IND_PLAN.IND_END_DATE)
)
,SINGLE_PLAN_DAY_TMP AS (
  SELECT
    DT.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.OPE_IND_PLAN
    ,TO_CHAR( TO_DATE( DT.DIALYSIS_DATE, 'YYYY-MM-DD' ), 'D' ) - 1 YOBI
    ,IND_PLAN.VALUE_1W1N VALUE
    ,IND_PLAN.IND_START_DATE
    ,IND_PLAN.IND_END_DATE
    ,IND_PLAN.IND_NO
    ,IND_PLAN.UP_DATE
    ,IND_PLAN.DEL_FLG
	,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
  FROM
    IND_DIALYSIS_PLAN IND_PLAN,
    DAY_TMP DT
  WHERE
    IND_PLAN.OPE_IND_PLAN = '1'
    AND IND_PLAN.IND_CLASS  <> '1'
    AND ({0})
	AND ( DT.DIALYSIS_DATE BETWEEN IND_PLAN.IND_START_DATE AND IND_PLAN.IND_END_DATE )
)
,UPDATE_TMP AS ( SELECT PATID, DIALYSIS_DATE, MAX( UP_DATE ) MAX_UP_DATE, PLURAL FROM PLAN_DAY_TMP WHERE DIALYSIS_DATE BETWEEN IND_START_DATE AND IND_END_DATE GROUP BY PATID, DIALYSIS_DATE, PLURAL )
,SINGLE_UPDATE_TMP AS (
  SELECT
    PATID,
    DIALYSIS_DATE,
    PLURAL,
    MAX( UP_DATE ) MAX_UP_DATE
  FROM
    SINGLE_PLAN_DAY_TMP
  WHERE
    DIALYSIS_DATE BETWEEN IND_START_DATE AND IND_END_DATE GROUP BY PATID, DIALYSIS_DATE, PLURAL
)

,DIALYSIS_PLAN AS (
  SELECT
    IND_PLAN.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.VALUE
    ,IND_PLAN.OPE_IND_PLAN
    ,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
    ,IND_PLAN.UP_DATE
  FROM PLAN_DAY_TMP IND_PLAN
    INNER JOIN UPDATE_TMP
      ON UPDATE_TMP.PATID = IND_PLAN.PATID
      AND UPDATE_TMP.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE
      AND IND_PLAN.UP_DATE = UPDATE_TMP.MAX_UP_DATE AND UPDATE_TMP.PLURAL = IND_PLAN.PLURAL

  WHERE
    LENGTH( IND_PLAN.VALUE ) >= 8
    AND IND_PLAN.IND_NO = (
          SELECT MAX( IND_NO ) FROM PLAN_DAY_TMP PDT
          WHERE PDT.PATID = IND_PLAN.PATID AND IND_PLAN.UP_DATE = PDT.UP_DATE AND IND_PLAN.PLURAL = PDT.PLURAL AND PDT.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE 												
        )
    AND NOT EXISTS (
      SELECT 1 FROM SCH_PLAN_TMP SCH_PLAN WHERE IND_PLAN.PATID = SCH_PLAN.PATID AND IND_PLAN.PLURAL = SCH_PLAN.PLURAL AND IND_PLAN.DIALYSIS_DATE = SCH_PLAN.DIALYSIS_DATE
    )
  UNION ALL
  SELECT
    IND_PLAN.DIALYSIS_DATE
    ,IND_PLAN.PATID
    ,IND_PLAN.PLURAL
    ,IND_PLAN.VALUE
    ,IND_PLAN.OPE_IND_PLAN
    ,IND_PLAN.CYCLE_WEEK
    ,IND_PLAN.INDICATOR_CD
    ,IND_PLAN.UPDATE_STAFF_CD
    ,IND_PLAN.UP_DATE
  FROM SINGLE_PLAN_DAY_TMP IND_PLAN
    INNER JOIN SINGLE_UPDATE_TMP UPDATE_TMP
      ON UPDATE_TMP.PATID = IND_PLAN.PATID
      AND UPDATE_TMP.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE
      AND UPDATE_TMP.MAX_UP_DATE = IND_PLAN.UP_DATE
      AND UPDATE_TMP.PLURAL = IND_PLAN.PLURAL

    WHERE
      IND_PLAN.DEL_FLG = '0'
      AND LENGTH( IND_PLAN.VALUE ) >= 8
      AND IND_PLAN.IND_NO = (
        SELECT MAX( IND_NO )
        FROM SINGLE_PLAN_DAY_TMP PDT
        WHERE PDT.PATID = IND_PLAN.PATID AND IND_PLAN.UP_DATE = PDT.UP_DATE AND IND_PLAN.PLURAL = PDT.PLURAL AND PDT.DIALYSIS_DATE = IND_PLAN.DIALYSIS_DATE 												
      )
      AND NOT EXISTS (
	  SELECT 1 FROM SCH_PLAN_TMP SCH_PLAN WHERE IND_PLAN.PATID = SCH_PLAN.PATID AND IND_PLAN.PLURAL = SCH_PLAN.PLURAL AND IND_PLAN.DIALYSIS_DATE = SCH_PLAN.DIALYSIS_DATE
	)
){NoWITHIndTimePeriod}
SELECT
  DIALYSIS_DATE
  ,S.PATID
  ,PLURAL
  ,TO_CHAR( S.PATID ) || TO_CHAR( DIALYSIS_DATE ) || TO_CHAR(PLURAL ) IND_ID
  ,VALUE
  ,OPE_IND_PLAN
  ,CYCLE_WEEK
  ,INDICATOR_CD
  ,UPDATE_STAFF_CD
  ,CASE 
    WHEN :MONTHSDIFF > 0 THEN
      CASE
        WHEN TO_DATE(DIALYSIS_DATE, 'yyyyMMdd') > LAST_DAY(ADD_MONTHS(TO_DATE(:START_DATE, 'yyyyMMdd'),12)) THEN
          SYSDATE 
        ELSE UP_DATE END
    ELSE UP_DATE END AS UP_DATE
FROM
  DIALYSIS_PLAN S
  {IndTimePeriodWhere}
ORDER BY
  S.PATID
  ,DIALYSIS_DATE