-- ----------------------------
-- Table structure for V_DIALYSIS_COMP
-- ----------------------------
DROP TABLE "V_DIALYSIS_COMP";
CREATE TABLE "V_DIALYSIS_COMP" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "OCCUR_DATE" DATE,
  "MEASURECLASS" CHAR(1 BYTE),
  "REQCODE" CHAR(10 BYTE),
  "COMPLAINT" VARCHAR2(256 BYTE),
  "TREAT_NAME" VARCHAR2(256 BYTE),
  "MEDICINE_CD1" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "PROCEDURE_NAME" VARCHAR2(40 BYTE),
  "PROCEDURE_CD1" CHAR(20 BYTE),
  "PROCEDURE_CD2" CHAR(20 BYTE),
  "TREAT_PERSON_NAME" VARCHAR2(20 BYTE),
  "UP_DATE" DATE
)
;
-- ----------------------------
-- Table structure for V_DIALYSIS_VITAL
-- ----------------------------
DROP TABLE "V_DIALYSIS_VITAL";
CREATE TABLE "V_DIALYSIS_VITAL" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "START_DATE" DATE,
  "OCCUR_DATE" DATE,
  "BP_MAX" NUMBER(5,0),
  "BP_MIN" NUMBER(5,0),
  "BP_AVE" NUMBER(5,0),
  "PULSE" NUMBER(5,0),
  "TEMPERATURE" NUMBER,
  "BLOOD_SUGAR_LEVEL" NUMBER(5,0),
  "UP_DATE" DATE,
  "DIADYSIS_NO" NUMBER(12,0),
  "BP_CLASS" CHAR(1 BYTE)
)
;
-- ----------------------------
-- Table structure for V_IND_DIALYSIS_ADD
-- ----------------------------
DROP TABLE "V_IND_DIALYSIS_ADD";
CREATE TABLE "V_IND_DIALYSIS_ADD" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "PLURAL" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "ADDITION" VARCHAR2(1024 BYTE),
  "INDICATOR_CD" CHAR(10 BYTE),
  "OPE_IND_PLAN" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Table structure for V_IND_DIALYSIS_COND
-- ----------------------------
DROP TABLE "V_IND_DIALYSIS_COND";
CREATE TABLE "V_IND_DIALYSIS_COND" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "PLURAL" NUMBER,
  "CTL_NO" CHAR(3 BYTE),
  "UP_DATE" DATE,
  "DIALYSIS_ITEM_NAME" VARCHAR2(40 BYTE),
  "VALUE" VARCHAR2(20 BYTE),
  "VALUE_NAME" VARCHAR2(100 BYTE),
  "UNIT" VARCHAR2(20 BYTE),
  "VALUE_CD2" VARCHAR2(20 BYTE),
  "INDICATOR_CD" CHAR(10 BYTE),
  "OPE_IND_PLAN" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Table structure for V_IND_DIALYSIS_EQUIP
-- ----------------------------
DROP TABLE "V_IND_DIALYSIS_EQUIP";
CREATE TABLE "V_IND_DIALYSIS_EQUIP" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "PLURAL" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "EQUIP_CD" CHAR(20 BYTE),
  "EQUIP_CD2" CHAR(20 BYTE),
  "EQUIP_CLASS_NAME" VARCHAR2(40 BYTE),
  "EQUIP_NAME" VARCHAR2(40 BYTE),
  "PUNCTURE_CLASS" CHAR(1 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE),
  "INDICATOR_CD" CHAR(10 BYTE),
  "OPE_IND_PLAN" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Table structure for V_IND_DIALYSIS_MEDI
-- ----------------------------
DROP TABLE "V_IND_DIALYSIS_MEDI";
CREATE TABLE "V_IND_DIALYSIS_MEDI" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "PLURAL" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "MEDICINE_CD" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "MEDI_CLASS_NAME" VARCHAR2(40 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "TIMING_NAME" VARCHAR2(40 BYTE),
  "PROCEDURE_CD" VARCHAR2(20 BYTE),
  "PROCEDURE_CD2" VARCHAR2(20 BYTE),
  "PROCEDURE_NAME" VARCHAR2(40 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE),
  "INDICATOR_CD" CHAR(10 BYTE),
  "OPE_IND_PLAN" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Table structure for V_MNT_WATER_SURVEY
-- ----------------------------
DROP TABLE "V_MNT_WATER_SURVEY";
CREATE TABLE "V_MNT_WATER_SURVEY" (
  "SURVEY_POINT_CD" CHAR(5 BYTE) NOT NULL,
  "SURVEY_POINT_NAME" VARCHAR2(64 BYTE),
  "UP_DATE" DATE,
  "CHECK_DATE" CHAR(8 BYTE),
  "RESULT" NUMBER,
  "UNIT" VARCHAR2(64 BYTE),
  "DETAIL" VARCHAR2(2048 BYTE)
)
;

-- ----------------------------
-- Table structure for V_ONL_DIALYSIS_VITAL
-- ----------------------------
DROP TABLE "V_ONL_DIALYSIS_VITAL";
CREATE TABLE "V_ONL_DIALYSIS_VITAL" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "START_DATE" DATE,
  "OCCUR_DATE" DATE,
  "BP_MAX" NUMBER(5,0),
  "BP_MIN" NUMBER(5,0),
  "BP_AVE" NUMBER(5,0),
  "PULSE" NUMBER(5,0),
  "TEMPERATURE" NUMBER,
  "BLOOD_SUGAR_LEVEL" NUMBER(5,0),
  "UP_DATE" DATE,
  "DIADYSIS_NO" NUMBER(12,0),
  "BP_CLASS" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Table structure for V_ONL_RST_DIALYSIS
-- ----------------------------
DROP TABLE "V_ONL_RST_DIALYSIS";
CREATE TABLE "V_ONL_RST_DIALYSIS" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE),
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER(12,0),
  "UP_DATE" DATE,
  "BED_NO" NUMBER(4,0),
  "BED_NAME" VARCHAR2(40 BYTE),
  "DEVICE_NO" NUMBER(10,0),
  "DEVICE_NAME" VARCHAR2(40 BYTE),
  "KUR_CD" CHAR(3 BYTE),
  "KUR_NAME" VARCHAR2(40 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "DIALYSIS_TIME" NUMBER(5,0),
  "PLAN_DIALYSIS_TIME" NUMBER(5,0),
  "DIALYSIS_NUM" NUMBER(5,0),
  "LAST_WEIGHT" NUMBER,
  "WEIGHT_BEFORE" NUMBER,
  "WEIGHT_AFTER" NUMBER,
  "BP_BEFORE_MAX" NUMBER(5,0),
  "BP_BEFORE_MIN" NUMBER(5,0),
  "BP_BEFORE_AVE" NUMBER(5,0),
  "BP_AFTER_MAX" NUMBER(5,0),
  "BP_AFTER_MIN" NUMBER(5,0),
  "BP_AFTER_AVE" NUMBER(5,0),
  "WATER_REMOVAL_TARGET" NUMBER,
  "REVISE_NAME1" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT1" NUMBER,
  "REVISE_NAME2" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT2" NUMBER,
  "REVISE_NAME3" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT3" NUMBER,
  "REVISE_NAME4" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT4" NUMBER,
  "REVISE_NAME5" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT5" NUMBER,
  "PULSE_BEFORE" NUMBER(5,0),
  "PULSE_AFTER" NUMBER(5,0),
  "CHARGE_1_NAME" VARCHAR2(50 BYTE),
  "CHARGE_2_NAME" VARCHAR2(50 BYTE),
  "CHARGE_DATE_1" DATE,
  "CHARGE_DATE_2" DATE,
  "PUNCTURE_1_NAME" VARCHAR2(50 BYTE),
  "PUNCTURE_2_NAME" VARCHAR2(50 BYTE),
  "PUNCTURE_DATE_1" DATE,
  "PUNCTURE_DATE_2" DATE,
  "COLLECT_1_NAME" VARCHAR2(50 BYTE),
  "COLLECT_2_NAME" VARCHAR2(50 BYTE),
  "COLLECT_DATE_1" DATE,
  "COLLECT_DATE_2" DATE,
  "INOUT_FLG" CHAR(1 BYTE),
  "KT_V_MEASURE" NUMBER,
  "URR" NUMBER,
  "RE_LOOP_RATE" NUMBER(3,0),
  "PULL_LEAVE_AMOUNT" NUMBER,
  "ADD_TOTL" NUMBER,
  "STATIC_VENOUS_PRESSURE" NUMBER(3,0),
  "VENOUS_ACCESS_PRESSURE_RATIO" NUMBER
)
;

-- ----------------------------
-- Table structure for V_ONL_RST_DIALYSIS_ADD
-- ----------------------------
DROP TABLE "V_ONL_RST_DIALYSIS_ADD";
CREATE TABLE "V_ONL_RST_DIALYSIS_ADD" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "EFFECT_FLG" CHAR(1 BYTE),
  "EFFECT_DATE" DATE,
  "ADDITION" VARCHAR2(1024 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_ONL_RST_DIALYSIS_COND
-- ----------------------------
DROP TABLE "V_ONL_RST_DIALYSIS_COND";
CREATE TABLE "V_ONL_RST_DIALYSIS_COND" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(20 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(3 BYTE),
  "UP_DATE" DATE,
  "DIALYSIS_ITEM_NAME" VARCHAR2(40 BYTE),
  "VALUE" VARCHAR2(20 BYTE),
  "VALUE_NAME" VARCHAR2(100 BYTE),
  "UNIT" VARCHAR2(20 BYTE),
  "VALUE_CD2" VARCHAR2(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_ONL_RST_DIALYSIS_EQUIP
-- ----------------------------
DROP TABLE "V_ONL_RST_DIALYSIS_EQUIP";
CREATE TABLE "V_ONL_RST_DIALYSIS_EQUIP" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "EQUIP_CD" CHAR(20 BYTE),
  "EQUIP_CD2" CHAR(20 BYTE),
  "EQUIP_NAME" VARCHAR2(40 BYTE),
  "EQUIP_CLASS_NAME" VARCHAR2(40 BYTE),
  "PUNCTURE_CLASS" CHAR(1 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE)
)
;

-- ----------------------------
-- Table structure for V_ONL_RST_DIALYSIS_MEDI
-- ----------------------------
DROP TABLE "V_ONL_RST_DIALYSIS_MEDI";
CREATE TABLE "V_ONL_RST_DIALYSIS_MEDI" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "MEDICINE_CD" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "MEDICINE_CLASS_NAME" VARCHAR2(40 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "EFFECT_FLG" CHAR(1 BYTE),
  "EFFECT_DATE" DATE,
  "TIMING_NAME" VARCHAR2(40 BYTE),
  "PROCEDURE_CD" VARCHAR2(20 BYTE),
  "PROCEDURE_CD2" VARCHAR2(20 BYTE),
  "PROCEDURE_NAME" VARCHAR2(40 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE)
)
;

-- ----------------------------
-- Table structure for V_ONL_RST_RECEIPT_MEMO
-- ----------------------------
DROP TABLE "V_ONL_RST_RECEIPT_MEMO";
CREATE TABLE "V_ONL_RST_RECEIPT_MEMO" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER(12,0),
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "DIVISION" CHAR(1 BYTE),
  "CODE" CHAR(4 BYTE),
  "CODE_UPDATE" DATE,
  "ADD_FLG" CHAR(1 BYTE),
  "ITEM_NAME" VARCHAR2(256 BYTE),
  "MAIN_DIAL_DIFF" CHAR(1 BYTE),
  "IN_HOSPITAL_CD" CHAR(20 BYTE),
  "IN_HOSPITAL_CD2" CHAR(20 BYTE)
)
;
-- ----------------------------
-- Table structure for V_PAT_CONTACT
-- ----------------------------
DROP TABLE "V_PAT_CONTACT";
CREATE TABLE "V_PAT_CONTACT" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE),
  "CTL_NO" NUMBER,
  "UP_DATE" DATE,
  "REG_DATE" DATE,
  "RELATION_NAME" VARCHAR2(50 BYTE),
  "RNAME" CHAR(40 BYTE),
  "ZIPCODE" CHAR(8 BYTE),
  "ADDRESS" VARCHAR2(256 BYTE),
  "ADDRESS_DETAIL" VARCHAR2(256 BYTE),
  "TELNO1" CHAR(25 BYTE),
  "TELNO2" CHAR(25 BYTE),
  "MEMO" VARCHAR2(2048 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_DEVICE_SET
-- ----------------------------
DROP TABLE "V_PAT_DEVICE_SET";
CREATE TABLE "V_PAT_DEVICE_SET" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE),
  "CTL_NO" NUMBER(4,0),
  "SET_NAME" VARCHAR2(50 BYTE),
  "VALUE" NUMBER,
  "UP_DATE" DATE,
  "MON_VALUE" NUMBER,
  "MON_UP_DATE" DATE,
  "TUE_VALUE" NUMBER,
  "TUE_UP_DATE" DATE,
  "WED_VALUE" NUMBER,
  "WED_UP_DATE" DATE,
  "THU_VALUE" NUMBER,
  "THU_UP_DATE" DATE,
  "FRI_VALUE" NUMBER,
  "FRI_UP_DATE" DATE,
  "SAT_VALUE" NUMBER,
  "SAT_UP_DATE" DATE,
  "SUN_VALUE" NUMBER,
  "SUN_UP_DATE" DATE
)
;

-- ----------------------------
-- Table structure for V_PAT_EXAMIN_HST
-- ----------------------------
DROP TABLE "V_PAT_EXAMIN_HST";
CREATE TABLE "V_PAT_EXAMIN_HST" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "EXAM_DATE" DATE,
  "ORDER_CLASS" VARCHAR2(6 BYTE),
  "ITEM_UP_DATE" DATE,
  "EXAM_ITEM_CODE" CHAR(20 BYTE),
  "EXAM_ITEM_CODE2" CHAR(20 BYTE),
  "EXAM_ITEM_CODE3" CHAR(20 BYTE),
  "EXAM_ITEM_NAME" VARCHAR2(40 BYTE),
  "EXAM_RST" VARCHAR2(256 BYTE),
  "EXAM_CLASS_RST" VARCHAR2(256 BYTE),
  "COMMENTS" VARCHAR2(512 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_EXAMIN_SCH
-- ----------------------------
DROP TABLE "V_PAT_EXAMIN_SCH";
CREATE TABLE "V_PAT_EXAMIN_SCH" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "UP_DATE" DATE,
  "EXAM_DATE" CHAR(8 BYTE),
  "EXAM_TIME" VARCHAR2(4 BYTE),
  "EXAM_SET_CD" CHAR(20 BYTE),
  "EXAM_SET_NAME" VARCHAR2(40 BYTE),
  "EXAM_DIVISION" CHAR(1 BYTE),
  "EXAM_PROC_CD" CHAR(1 BYTE),
  "DOCTOR_CODE" CHAR(10 BYTE),
  "DOCTOR_NAME" VARCHAR2(20 BYTE),
  "ORDER_STAFF" CHAR(10 BYTE),
  "ORDER_NAME" VARCHAR2(20 BYTE),
  "UPDATE_CODE" CHAR(10 BYTE),
  "UPDATE_NAME" VARCHAR2(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_FREE_COMMENT
-- ----------------------------
DROP TABLE "V_PAT_FREE_COMMENT";
CREATE TABLE "V_PAT_FREE_COMMENT" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "CTL_NO" NUMBER(2,0),
  "TITLE" VARCHAR2(80 BYTE),
  "CONTENT" VARCHAR2(3500 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_INFECT
-- ----------------------------
DROP TABLE "V_PAT_INFECT";
CREATE TABLE "V_PAT_INFECT" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "INFECTION_CD" CHAR(20 BYTE),
  "INFECTION_NAME" VARCHAR2(100 BYTE),
  "UP_DATE" DATE,
  "INFECT" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_INOUT
-- ----------------------------
DROP TABLE "V_PAT_INOUT";
CREATE TABLE "V_PAT_INOUT" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "CTL_NO" CHAR(3 BYTE),
  "REG_DATE" DATE,
  "INOUT_CD" CHAR(1 BYTE),
  "FACILITY_NAME" VARCHAR2(100 BYTE),
  "DR_NAME" VARCHAR2(20 BYTE),
  "MEMO" VARCHAR2(256 BYTE),
  "CODE_NAME" VARCHAR2(4 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_LIFE_LIST
-- ----------------------------
DROP TABLE "V_PAT_LIFE_LIST";
CREATE TABLE "V_PAT_LIFE_LIST" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "UP_DATE" DATE,
  "NAME" VARCHAR2(40 BYTE),
  "NAME_KANA" VARCHAR2(40 BYTE),
  "REG_DATE" CHAR(8 BYTE),
  "REG_TIME" CHAR(4 BYTE),
  "KIND_ID" NUMBER(3,0),
  "KIND_NAME" VARCHAR2(20 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE),
  "EDIT_CD" CHAR(10 BYTE),
  "EDIT_NAME" VARCHAR2(20 BYTE),
  "DETAIL1" VARCHAR2(1000 BYTE),
  "DETAIL2" VARCHAR2(1000 BYTE),
  "DETAIL3" VARCHAR2(1000 BYTE),
  "DETAIL4" VARCHAR2(1000 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_MEDICAL_HST
-- ----------------------------
DROP TABLE "V_PAT_MEDICAL_HST";
CREATE TABLE "V_PAT_MEDICAL_HST" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "CTL_NO" NUMBER,
  "UP_DATE" DATE,
  "DISEASE_CD" CHAR(20 BYTE),
  "DISEASE_NAME" VARCHAR2(100 BYTE),
  "DISEASE_DATE" DATE,
  "RECOVER_DATE" DATE,
  "MAIN_DISEASE" CHAR(1 BYTE),
  "STATUS" CHAR(1 BYTE),
  "NOTICE_FLG" CHAR(1 BYTE),
  "DOCTOR_NAME" VARCHAR2(20 BYTE),
  "MEMO" VARCHAR2(256 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_RECEIPT_MEMO
-- ----------------------------
DROP TABLE "V_PAT_RECEIPT_MEMO";
CREATE TABLE "V_PAT_RECEIPT_MEMO" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "UP_DATE" DATE,
  "DIVISION" CHAR(1 BYTE),
  "CODE" CHAR(4 BYTE),
  "CODE_UPDATE" DATE,
  "ADD_FLG" CHAR(1 BYTE),
  "ITEM_NAME" VARCHAR2(256 BYTE),
  "MAIN_DIAL_DIFF" CHAR(1 BYTE),
  "IN_HOSPITAL_CD" CHAR(20 BYTE),
  "IN_HOSPITAL_CD2" CHAR(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_RECIPE
-- ----------------------------
DROP TABLE "V_PAT_RECIPE";
CREATE TABLE "V_PAT_RECIPE" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "PRESCRIPT_NO" NUMBER,
  "UP_DATE" DATE,
  "EXECUTE_DATE" CHAR(8 BYTE),
  "CTL_NO" CHAR(3 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "MEDICINE_CD" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "QUANTITY" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "DOSAGE" NUMBER,
  "TAKE_MEDICINE_CD" CHAR(3 BYTE),
  "TAKE_MEDICINE_NAME" VARCHAR2(40 BYTE),
  "DAY_COUNT" NUMBER,
  "PRESCRIPTER_CD" CHAR(10 BYTE),
  "PRESCRIPTER_NAME" VARCHAR2(20 BYTE),
  "NOTE" VARCHAR2(1024 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_REVISE_OFFWATER
-- ----------------------------
DROP TABLE "V_PAT_REVISE_OFFWATER";
CREATE TABLE "V_PAT_REVISE_OFFWATER" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE),
  "CTL_NO" NUMBER(3,0),
  "UP_DATE" DATE,
  "REVISE_NAME" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT" NUMBER,
  "MON_UP_DATE" DATE,
  "MON_REVISE_NAME" VARCHAR2(40 BYTE),
  "MON_REVISE_WEIGHT" NUMBER,
  "TUE_UP_DATE" DATE,
  "TUE_REVISE_NAME" VARCHAR2(40 BYTE),
  "TUE_REVISE_WEIGHT" NUMBER,
  "WED_UP_DATE" DATE,
  "WED_REVISE_NAME" VARCHAR2(40 BYTE),
  "WED_REVISE_WEIGHT" NUMBER,
  "THU_UP_DATE" DATE,
  "THU_REVISE_NAME" VARCHAR2(40 BYTE),
  "THU_REVISE_WEIGHT" NUMBER,
  "FRI_UP_DATE" DATE,
  "FRI_REVISE_NAME" VARCHAR2(40 BYTE),
  "FRI_REVISE_WEIGHT" NUMBER,
  "SAT_UP_DATE" DATE,
  "SAT_REVISE_NAME" VARCHAR2(40 BYTE),
  "SAT_REVISE_WEIGHT" NUMBER,
  "SUN_UP_DATE" DATE,
  "SUN_REVISE_NAME" VARCHAR2(40 BYTE),
  "SUN_REVISE_WEIGHT" NUMBER
)
;

-- ----------------------------
-- Table structure for V_PAT_REVISE_TARE
-- ----------------------------
DROP TABLE "V_PAT_REVISE_TARE";
CREATE TABLE "V_PAT_REVISE_TARE" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE),
  "CTL_NO" NUMBER(3,0),
  "UP_DATE" DATE,
  "REVISE_NAME" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT" NUMBER,
  "HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "WHEELCHAIR_NAME" VARCHAR2(256 BYTE),
  "MON_UP_DATE" DATE,
  "MON_REVISE_NAME" VARCHAR2(40 BYTE),
  "MON_REVISE_WEIGHT" NUMBER,
  "MON_HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "MON_WHEELCHAIR_NAME" VARCHAR2(256 BYTE),
  "TUE_UP_DATE" DATE,
  "TUE_REVISE_NAME" VARCHAR2(40 BYTE),
  "TUE_REVISE_WEIGHT" NUMBER,
  "TUE_HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "TUE_WHEELCHAIR_NAME" VARCHAR2(256 BYTE),
  "WED_UP_DATE" DATE,
  "WED_REVISE_NAME" VARCHAR2(40 BYTE),
  "WED_REVISE_WEIGHT" NUMBER,
  "WED_HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "WED_WHEELCHAIR_NAME" VARCHAR2(256 BYTE),
  "THU_UP_DATE" DATE,
  "THU_REVISE_NAME" VARCHAR2(40 BYTE),
  "THU_REVISE_WEIGHT" NUMBER,
  "THU_HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "THU_WHEELCHAIR_NAME" VARCHAR2(256 BYTE),
  "FRI_UP_DATE" DATE,
  "FRI_REVISE_NAME" VARCHAR2(40 BYTE),
  "FRI_REVISE_WEIGHT" NUMBER,
  "FRI_HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "FRI_WHEELCHAIR_NAME" VARCHAR2(256 BYTE),
  "SAT_UP_DATE" DATE,
  "SAT_REVISE_NAME" VARCHAR2(40 BYTE),
  "SAT_REVISE_WEIGHT" NUMBER,
  "SAT_HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "SAT_WHEELCHAIR_NAME" VARCHAR2(256 BYTE),
  "SUN_UP_DATE" DATE,
  "SUN_REVISE_NAME" VARCHAR2(40 BYTE),
  "SUN_REVISE_WEIGHT" NUMBER,
  "SUN_HOSP_WHEELCHAIR_CD" CHAR(8 BYTE),
  "SUN_WHEELCHAIR_NAME" VARCHAR2(256 BYTE)
)
;

-- ----------------------------
-- Table structure for V_PAT_STATUS
-- ----------------------------
DROP TABLE "V_PAT_STATUS";
CREATE TABLE "V_PAT_STATUS" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" CHAR(8 BYTE),
  "DIALYSIS_TIME" CHAR(6 BYTE),
  "START_PLAN_DATE" VARCHAR2(7 BYTE),
  "ENTER_FLG" VARCHAR2(1 BYTE),
  "ENTER_DATE" DATE,
  "MACHINE_CHECK_FLG" VARCHAR2(1 BYTE),
  "MACHINE_CHECK_DATE" DATE,
  "DIALSIS_START_FLG" VARCHAR2(1 BYTE),
  "DIALSIS_START_DATE" DATE,
  "OFFWATER_FLG" VARCHAR2(1 BYTE),
  "OFFWATER_DATE" DATE,
  "WASTE_FLUID_FLG" VARCHAR2(1 BYTE),
  "WASTE_FLUID_DATE" DATE,
  "WEIGHT_AFTER_FLG" VARCHAR2(1 BYTE),
  "WEIGHT_AFTER_DATE" DATE,
  "RECOVERY_BTN_FLG" VARCHAR2(1 BYTE),
  "RECOVERY_BTN_DATE" DATE,
  "UP_DATE" DATE
)
;

-- ----------------------------
-- Table structure for V_PAT_TABOO
-- ----------------------------
DROP TABLE "V_PAT_TABOO";
CREATE TABLE "V_PAT_TABOO" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE),
  "CTL_NO" NUMBER,
  "UP_DATE" DATE,
  "TABOO" VARCHAR2(512 BYTE),
  "MEMO" VARCHAR2(512 BYTE)
)
;

-- ----------------------------
-- Table structure for V_RST_DIALYSIS
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS";
CREATE TABLE "V_RST_DIALYSIS" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "NAME" VARCHAR2(40 BYTE),
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER(12,0),
  "UP_DATE" DATE,
  "BED_NO" NUMBER(4,0),
  "BED_NAME" VARCHAR2(40 BYTE),
  "DEVICE_NO" NUMBER(10,0),
  "DEVICE_NAME" VARCHAR2(40 BYTE),
  "KUR_CD" CHAR(3 BYTE),
  "KUR_NAME" VARCHAR2(40 BYTE),
  "START_DATE" DATE,
  "END_DATE" DATE,
  "DIALYSIS_TIME" NUMBER(5,0),
  "PLAN_DIALYSIS_TIME" NUMBER(5,0),
  "DIALYSIS_NUM" NUMBER(5,0),
  "LAST_WEIGHT" NUMBER,
  "WEIGHT_BEFORE" NUMBER,
  "WEIGHT_AFTER" NUMBER,
  "BP_BEFORE_MAX" NUMBER(5,0),
  "BP_BEFORE_MIN" NUMBER(5,0),
  "BP_BEFORE_AVE" NUMBER(5,0),
  "BP_AFTER_MAX" NUMBER(5,0),
  "BP_AFTER_MIN" NUMBER(5,0),
  "BP_AFTER_AVE" NUMBER(5,0),
  "WATER_REMOVAL_TARGET" NUMBER,
  "REVISE_NAME1" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT1" NUMBER,
  "REVISE_NAME2" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT2" NUMBER,
  "REVISE_NAME3" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT3" NUMBER,
  "REVISE_NAME4" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT4" NUMBER,
  "REVISE_NAME5" VARCHAR2(40 BYTE),
  "REVISE_WEIGHT5" NUMBER,
  "PULSE_BEFORE" NUMBER(5,0),
  "PULSE_AFTER" NUMBER(5,0),
  "CHARGE_1_NAME" VARCHAR2(50 BYTE),
  "CHARGE_2_NAME" VARCHAR2(50 BYTE),
  "CHARGE_DATE_1" DATE,
  "CHARGE_DATE_2" DATE,
  "PUNCTURE_1_NAME" VARCHAR2(50 BYTE),
  "PUNCTURE_2_NAME" VARCHAR2(50 BYTE),
  "PUNCTURE_DATE_1" DATE,
  "PUNCTURE_DATE_2" DATE,
  "COLLECT_1_NAME" VARCHAR2(50 BYTE),
  "COLLECT_2_NAME" VARCHAR2(50 BYTE),
  "COLLECT_DATE_1" DATE,
  "COLLECT_DATE_2" DATE,
  "INOUT_FLG" CHAR(1 BYTE),
  "KT_V_MEASURE" NUMBER,
  "URR" NUMBER,
  "RE_LOOP_RATE" NUMBER(3,0),
  "PULL_LEAVE_AMOUNT" NUMBER,
  "ADD_TOTL" NUMBER,
  "STATIC_VENOUS_PRESSURE" NUMBER(3,0),
  "VENOUS_ACCESS_PRESSURE_RATIO" NUMBER
)
;

-- ----------------------------
-- Table structure for V_RST_DIALYSIS_ADD
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_ADD";
CREATE TABLE "V_RST_DIALYSIS_ADD" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "EFFECT_FLG" CHAR(1 BYTE),
  "EFFECT_DATE" DATE,
  "ADDITION" VARCHAR2(1024 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_RST_DIALYSIS_COND
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_COND";
CREATE TABLE "V_RST_DIALYSIS_COND" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(20 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(3 BYTE),
  "UP_DATE" DATE,
  "DIALYSIS_ITEM_NAME" VARCHAR2(40 BYTE),
  "VALUE" VARCHAR2(20 BYTE),
  "VALUE_NAME" VARCHAR2(100 BYTE),
  "UNIT" VARCHAR2(20 BYTE),
  "VALUE_CD2" VARCHAR2(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_RST_DIALYSIS_COND_CARD
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_COND_CARD";
CREATE TABLE "V_RST_DIALYSIS_COND_CARD" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(3 BYTE),
  "UP_DATE" DATE,
  "DIALYSIS_ITEM_NAME" VARCHAR2(40 BYTE),
  "VALUE" VARCHAR2(20 BYTE),
  "VALUE_NAME" VARCHAR2(100 BYTE),
  "MED_GENERAL_NAME" VARCHAR2(80 BYTE),
  "UNIT" VARCHAR2(20 BYTE),
  "VALUE_CD1" VARCHAR2(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_RST_DIALYSIS_EQUIP
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_EQUIP";
CREATE TABLE "V_RST_DIALYSIS_EQUIP" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "EQUIP_CD" CHAR(20 BYTE),
  "EQUIP_CD2" CHAR(20 BYTE),
  "EQUIP_NAME" VARCHAR2(40 BYTE),
  "EQUIP_CLASS_NAME" VARCHAR2(40 BYTE),
  "PUNCTURE_CLASS" CHAR(1 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE)
)
;

-- ----------------------------
-- Table structure for V_RST_DIALYSIS_MEDI
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_MEDI";
CREATE TABLE "V_RST_DIALYSIS_MEDI" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "MEDICINE_CD" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "MEDICINE_CLASS_NAME" VARCHAR2(40 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "EFFECT_FLG" CHAR(1 BYTE),
  "EFFECT_DATE" DATE,
  "TIMING_NAME" VARCHAR2(40 BYTE),
  "PROCEDURE_CD" VARCHAR2(20 BYTE),
  "PROCEDURE_CD2" VARCHAR2(20 BYTE),
  "PROCEDURE_NAME" VARCHAR2(40 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE)
)
;

-- ----------------------------
-- Table structure for V_RST_DIALYSIS_MEDI_CARD
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_MEDI_CARD";
CREATE TABLE "V_RST_DIALYSIS_MEDI_CARD" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "MEDICINE_CD" CHAR(20 BYTE),
  "MEDICINE_CD2" CHAR(20 BYTE),
  "MEDICINE_NAME" VARCHAR2(80 BYTE),
  "MED_GENERAL_NAME" VARCHAR2(80 BYTE),
  "MEDICINE_CLASS_NAME" VARCHAR2(40 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "EFFECT_FLG" CHAR(1 BYTE),
  "EFFECT_DATE" DATE,
  "TIMING_NAME" VARCHAR2(40 BYTE),
  "PROCEDURE_CD" VARCHAR2(20 BYTE),
  "PROCEDURE_CD2" VARCHAR2(20 BYTE),
  "PROCEDURE_NAME" VARCHAR2(40 BYTE),
  "STAFF_CD" CHAR(10 BYTE),
  "STAFF_NAME" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE)
)
;

-- ----------------------------
-- Table structure for V_RST_RECEIPT_MEMO
-- ----------------------------
DROP TABLE "V_RST_RECEIPT_MEMO";
CREATE TABLE "V_RST_RECEIPT_MEMO" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER(12,0),
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "DIVISION" CHAR(1 BYTE),
  "CODE" CHAR(4 BYTE),
  "CODE_UPDATE" DATE,
  "ADD_FLG" CHAR(1 BYTE),
  "ITEM_NAME" VARCHAR2(256 BYTE),
  "MAIN_DIAL_DIFF" CHAR(1 BYTE),
  "IN_HOSPITAL_CD" CHAR(20 BYTE),
  "IN_HOSPITAL_CD2" CHAR(20 BYTE)
)
;

-- ----------------------------
-- Table structure for V_SCH_DIALYSIS_PLAN
-- ----------------------------
DROP TABLE "V_SCH_DIALYSIS_PLAN";
CREATE TABLE "V_SCH_DIALYSIS_PLAN" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "BED_NO" NUMBER(4,0),
  "BED_NAME" VARCHAR2(40 BYTE),
  "KUR_CD" VARCHAR2(6 BYTE),
  "KUR_NAME" VARCHAR2(40 BYTE),
  "PLURAL" NUMBER(1,0),
  "UP_DATE" DATE,
  "RESULT_DIALYSISNO" NUMBER(12,0),
  "OPE_IND_PLAN" CHAR(1 BYTE),
  "DUMMY_FLG" NUMBER(1,0),
  "START_TIME" VARCHAR2(6 BYTE)
)
;

-- ----------------------------
-- Table structure for V_SCH_DIALYSIS_PLAN_CARD
-- ----------------------------
DROP TABLE "V_SCH_DIALYSIS_PLAN_CARD";
CREATE TABLE "V_SCH_DIALYSIS_PLAN_CARD" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "BED_NO" NUMBER(4,0),
  "BED_NAME" VARCHAR2(40 BYTE),
  "KUR_CD" VARCHAR2(6 BYTE),
  "KUR_NAME" VARCHAR2(40 BYTE),
  "PLURAL" NUMBER(1,0),
  "UP_DATE" DATE,
  "RESULT_DIALYSISNO" NUMBER(12,0),
  "OPE_IND_PLAN" CHAR(1 BYTE),
  "DUMMY_FLG" NUMBER(1,0),
  "START_TIME" VARCHAR2(6 BYTE)
)
;

-- ----------------------------
-- Primary Key structure for table V_DIALYSIS_COMP
-- ----------------------------
ALTER TABLE "V_DIALYSIS_COMP" ADD CONSTRAINT "SYS_C007469" PRIMARY KEY ("PATID");
-- ----------------------------
-- Primary Key structure for table V_DIALYSIS_VITAL
-- ----------------------------
ALTER TABLE "V_DIALYSIS_VITAL" ADD CONSTRAINT "SYS_C007468" PRIMARY KEY ("PATID");
-- ----------------------------
-- Primary Key structure for table V_IND_DIALYSIS_ADD
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_ADD" ADD CONSTRAINT "SYS_C007465" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_IND_DIALYSIS_ADD
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_ADD" ADD CONSTRAINT "SYS_C007464" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_IND_DIALYSIS_COND
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_COND" ADD CONSTRAINT "SYS_C007460" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_IND_DIALYSIS_EQUIP
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_EQUIP" ADD CONSTRAINT "SYS_C007461" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_IND_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007463" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_IND_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007462" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_MNT_WATER_SURVEY
-- ----------------------------
ALTER TABLE "V_MNT_WATER_SURVEY" ADD CONSTRAINT "SYS_C007474" PRIMARY KEY ("SURVEY_POINT_CD");

-- ----------------------------
-- Checks structure for table V_MNT_WATER_SURVEY
-- ----------------------------
ALTER TABLE "V_MNT_WATER_SURVEY" ADD CONSTRAINT "SYS_C007473" CHECK ("SURVEY_POINT_CD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_ONL_DIALYSIS_VITAL
-- ----------------------------
ALTER TABLE "V_ONL_DIALYSIS_VITAL" ADD CONSTRAINT "SYS_C007496" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_ONL_DIALYSIS_VITAL
-- ----------------------------
ALTER TABLE "V_ONL_DIALYSIS_VITAL" ADD CONSTRAINT "SYS_C007495" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_ONL_RST_DIALYSIS
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS" ADD CONSTRAINT "SYS_C007483" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_ONL_RST_DIALYSIS
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS" ADD CONSTRAINT "SYS_C007482" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_ONL_RST_DIALYSIS_ADD
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_ADD" ADD CONSTRAINT "SYS_C007491" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_ONL_RST_DIALYSIS_ADD
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_ADD" ADD CONSTRAINT "SYS_C007490" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_ONL_RST_DIALYSIS_COND
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_COND" ADD CONSTRAINT "SYS_C007485" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_ONL_RST_DIALYSIS_COND
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_COND" ADD CONSTRAINT "SYS_C007484" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_ONL_RST_DIALYSIS_EQUIP
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_EQUIP" ADD CONSTRAINT "SYS_C007487" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_ONL_RST_DIALYSIS_EQUIP
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_EQUIP" ADD CONSTRAINT "SYS_C007486" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_ONL_RST_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007489" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_ONL_RST_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_ONL_RST_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007488" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_ONL_RST_RECEIPT_MEMO
-- ----------------------------
ALTER TABLE "V_ONL_RST_RECEIPT_MEMO" ADD CONSTRAINT "SYS_C007493" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_ONL_RST_RECEIPT_MEMO
-- ----------------------------
ALTER TABLE "V_ONL_RST_RECEIPT_MEMO" ADD CONSTRAINT "SYS_C007492" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_PAT_CONTACT
-- ----------------------------
ALTER TABLE "V_PAT_CONTACT" ADD CONSTRAINT "SYS_C007426" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_PAT_CONTACT
-- ----------------------------
ALTER TABLE "V_PAT_CONTACT" ADD CONSTRAINT "SYS_C007425" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


-- ----------------------------
-- Primary Key structure for table V_PAT_DEVICE_SET
-- ----------------------------
ALTER TABLE "V_PAT_DEVICE_SET" ADD CONSTRAINT "SYS_C007497" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_PAT_EXAMIN_HST
-- ----------------------------
ALTER TABLE "V_PAT_EXAMIN_HST" ADD CONSTRAINT "SYS_C007471" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_PAT_EXAMIN_SCH
-- ----------------------------
ALTER TABLE "V_PAT_EXAMIN_SCH" ADD CONSTRAINT "SYS_C007472" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_PAT_FREE_COMMENT
-- ----------------------------
ALTER TABLE "V_PAT_FREE_COMMENT" ADD CONSTRAINT "SYS_C007481" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_PAT_INFECT
-- ----------------------------
ALTER TABLE "V_PAT_INFECT" ADD CONSTRAINT "SYS_C007428" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_PAT_INFECT
-- ----------------------------
ALTER TABLE "V_PAT_INFECT" ADD CONSTRAINT "SYS_C007427" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_PAT_INOUT
-- ----------------------------
ALTER TABLE "V_PAT_INOUT" ADD CONSTRAINT "SYS_C007470" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_PAT_LIFE_LIST
-- ----------------------------
ALTER TABLE "V_PAT_LIFE_LIST" ADD CONSTRAINT "SYS_C007480" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_PAT_MEDICAL_HST
-- ----------------------------
ALTER TABLE "V_PAT_MEDICAL_HST" ADD CONSTRAINT "SYS_C007420" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_PAT_MEDICAL_HST
-- ----------------------------
ALTER TABLE "V_PAT_MEDICAL_HST" ADD CONSTRAINT "SYS_C007419" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_PAT_RECEIPT_MEMO
-- ----------------------------
ALTER TABLE "V_PAT_RECEIPT_MEMO" ADD CONSTRAINT "SYS_C007430" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_PAT_RECEIPT_MEMO
-- ----------------------------
ALTER TABLE "V_PAT_RECEIPT_MEMO" ADD CONSTRAINT "SYS_C007429" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_PAT_RECIPE
-- ----------------------------
ALTER TABLE "V_PAT_RECIPE" ADD CONSTRAINT "SYS_C007467" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_PAT_RECIPE
-- ----------------------------
ALTER TABLE "V_PAT_RECIPE" ADD CONSTRAINT "SYS_C007466" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_PAT_REVISE_OFFWATER
-- ----------------------------
ALTER TABLE "V_PAT_REVISE_OFFWATER" ADD CONSTRAINT "SYS_C007432" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_PAT_REVISE_OFFWATER
-- ----------------------------
ALTER TABLE "V_PAT_REVISE_OFFWATER" ADD CONSTRAINT "SYS_C007431" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_PAT_REVISE_TARE
-- ----------------------------
ALTER TABLE "V_PAT_REVISE_TARE" ADD CONSTRAINT "SYS_C007440" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_PAT_REVISE_TARE
-- ----------------------------
ALTER TABLE "V_PAT_REVISE_TARE" ADD CONSTRAINT "SYS_C007437" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "V_PAT_REVISE_TARE" ADD CONSTRAINT "SYS_C007438" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table V_PAT_STATUS
-- ----------------------------
ALTER TABLE "V_PAT_STATUS" ADD CONSTRAINT "SYS_C007479" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_PAT_TABOO
-- ----------------------------
ALTER TABLE "V_PAT_TABOO" ADD CONSTRAINT "SYS_C007494" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS" ADD CONSTRAINT "SYS_C007446" PRIMARY KEY ("PATID");

-- ----------------------------
-- Checks structure for table V_RST_DIALYSIS
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS" ADD CONSTRAINT "SYS_C007445" CHECK ("PATID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_ADD
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_ADD" ADD CONSTRAINT "SYS_C007452" PRIMARY KEY ("PATID");


-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_COND
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_COND" ADD CONSTRAINT "SYS_C007447" PRIMARY KEY ("PATID");


-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_COND_CARD
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_COND_CARD" ADD CONSTRAINT "SYS_C007448" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_EQUIP
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_EQUIP" ADD CONSTRAINT "SYS_C007449" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_MEDI
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_MEDI" ADD CONSTRAINT "SYS_C007450" PRIMARY KEY ("PATID");


-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_MEDI_CARD
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_MEDI_CARD" ADD CONSTRAINT "SYS_C007451" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_RST_RECEIPT_MEMO
-- ----------------------------
ALTER TABLE "V_RST_RECEIPT_MEMO" ADD CONSTRAINT "SYS_C007453" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_SCH_DIALYSIS_PLAN
-- ----------------------------
ALTER TABLE "V_SCH_DIALYSIS_PLAN" ADD CONSTRAINT "SYS_C007458" PRIMARY KEY ("PATID");

-- ----------------------------
-- Primary Key structure for table V_SCH_DIALYSIS_PLAN_CARD
-- ----------------------------
ALTER TABLE "V_SCH_DIALYSIS_PLAN_CARD" ADD CONSTRAINT "SYS_C007459" PRIMARY KEY ("PATID");