-- ----------------------------
-- Table structure for V_IND_DIALYSIS_EQUIP
-- ----------------------------
DROP TABLE "V_IND_DIALYSIS_EQUIP";
CREATE TABLE "V_IND_DIALYSIS_EQUIP" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "PLURAL" NUMBER,
  "CTL_NO" CHAR(7 BYTE),
  "UP_DATE" DATE,
  "EQUIP_CD" CHAR(20 BYTE),
  "EQUIP_CD2" CHAR(20 BYTE),
  "EQUIP_CLASS_NAME" VARCHAR2(40 BYTE),
  "EQUIP_NAME" VARCHAR2(40 BYTE),
  "PUNCTURE_CLASS" CHAR(1 BYTE),
  "AMOUNT" NUMBER,
  "UNIT" VARCHAR2(20 BYTE),
  "COMMENTS" VARCHAR2(1024 BYTE),
  "INDICATOR_CD" CHAR(10 BYTE),
  "OPE_IND_PLAN" CHAR(1 BYTE)
)
;

-- ----------------------------
-- Primary Key structure for table V_IND_DIALYSIS_EQUIP
-- ----------------------------
ALTER TABLE "V_IND_DIALYSIS_EQUIP" ADD CONSTRAINT "SYS_C007461" PRIMARY KEY ("PATID");
