-- ----------------------------
-- Table structure for V_RST_DIALYSIS_COND_CARD
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_COND_CARD";
CREATE TABLE "V_RST_DIALYSIS_COND_CARD" (
  "PATID" CHAR(12 BYTE) NOT NULL,
  "DIALYSIS_DATE" VARCHAR2(8 BYTE),
  "DIALYSIS_NO" NUMBER,
  "CTL_NO" CHAR(3 BYTE),
  "UP_DATE" DATE,
  "DIALYSIS_ITEM_NAME" VARCHAR2(40 BYTE),
  "VALUE" VARCHAR2(20 BYTE),
  "VALUE_NAME" VARCHAR2(100 BYTE),
  "MED_GENERAL_NAME" VARCHAR2(80 BYTE),
  "UNIT" VARCHAR2(20 BYTE),
  "VALUE_CD1" VARCHAR2(20 BYTE)
)
;

-- ----------------------------
-- Primary Key structure for table V_RST_DIALYSIS_COND_CARD
-- ----------------------------
ALTER TABLE "V_RST_DIALYSIS_COND_CARD" ADD CONSTRAINT "SYS_C007448" PRIMARY KEY ("PATID");
