; デバイスエッジアプリネットワーク設定
;

; 圧縮パスワード
;
ZIP_PW=NTSS

; アップロードファイル最大サイズ(MB単位)
; ※超えた場合はファイルが分割されてアップロードされる
;
UPLOAD_FILE_MAXSIZE=80

; AWSホスト名
;
; TDC開発環境
AWS_HOST=http://192.168.102.65:8080
; NKK開発環境
;AWS_HOST=http://ntss-platform-public-app-alb-2041513679.ap-northeast-1.elb.amazonaws.com
; NKK検証環境(非IoT)
;AWS_HOST=http://ntss-platform-public-app-alb02-743132961.ap-northeast-1.elb.amazonaws.com

; アップロードリトライ回数
;
UPLOAD_RETRY_COUNT=3

; アップロードリトライ待ち時間(秒)
;
UPLOAD_RETRY_WAIT_TIME=30
