UPDATE ord_main
SET pat_id                    = tmp.pat_id,
    fn_pat_id                 = tmp.fn_pat_id,
    treat_date                = tmp.treat_date,
    treat_week                = tmp.treat_week,
    facility_cd               = tmp.facility_cd,
    facility_name             = tmp.facility_name,
    ind_va_cd                 = tmp.ind_va_cd,
    ind_treatment_cd          = tmp.ind_treatment_cd,
    ind_treatment_name        = tmp.ind_treatment_name,
    ind_kur_cd                = tmp.ind_kur_cd,
    ind_kur_name              = tmp.ind_kur_name,
    ind_treat_start_time      = tmp.ind_treat_start_time,
    ind_bed_cd                = tmp.ind_bed_cd,
    ind_bed_name              = tmp.ind_bed_name,
    ind_schedule_user_info    = tmp.ind_schedule_user_info,
    ind_cond_info             = tmp.ind_cond_info,
    ind_medi_info             = tmp.ind_medi_info,
    ind_equip_info            = tmp.ind_equip_info,
    ind_ind_comment_info      = tmp.ind_ind_comment_info,
    ind_tare_info             = tmp.ind_tare_info,
    ind_off_water_info        = tmp.ind_off_water_info,
    rst_fn_dialysis_no        = tmp.rst_fn_dialysis_no,
    rst_relation_dialysis_no  = tmp.rst_relation_dialysis_no,
    rst_edition               = tmp.rst_edition,
    rst_is_update_edition     = tmp.rst_is_update_edition,
    rst_input_class           = tmp.rst_input_class,
    rst_dialysis_state        = tmp.rst_dialysis_state,
    rst_treatment_cd          = tmp.rst_treatment_cd,
    rst_treatment_name        = tmp.rst_treatment_name,
    rst_kur_cd                = tmp.rst_kur_cd,
    rst_kur_name              = tmp.rst_kur_name,
    rst_bed_cd                = tmp.rst_bed_cd,
    rst_bed_name              = tmp.rst_bed_name,
    rst_machine_no            = tmp.rst_machine_no,
    rst_machine_name          = tmp.rst_machine_name,
    rst_cond_send_date        = tmp.rst_cond_send_date,
    rst_accept_date           = tmp.rst_accept_date,
    rst_start_date            = tmp.rst_start_date,
    rst_end_date              = tmp.rst_end_date,
    rst_return_home_date      = tmp.rst_return_home_date,
    rst_in_out_class          = tmp.rst_in_out_class,
    rst_dialysis_cnt          = tmp.rst_dialysis_cnt,
    rst_ward_cd               = tmp.rst_ward_cd,
    rst_ward_name             = tmp.rst_ward_name,
    rst_course_cd             = tmp.rst_course_cd,
    rst_course_name           = tmp.rst_course_name,
    rst_puncture_user_info    = tmp.rst_puncture_user_info,
    rst_return_user_info      = tmp.rst_return_user_info,
    rst_charge_user_info      = tmp.rst_charge_user_info,
    rst_blood_circulate_total = tmp.rst_blood_circulate_total,
    rst_running_time          = tmp.rst_running_time,
    rst_kt_v                  = tmp.rst_kt_v,
    rec_set_date              = tmp.rec_set_date,
    send_ctl_no               = tmp.send_ctl_no,
    blood_purifier_name       = tmp.blood_purifier_name,
    pull_leave_amount         = tmp.pull_leave_amount,
    rst_cond_info             = tmp.rst_cond_info,
    rst_medi_info             = tmp.rst_medi_info,
    rst_equip_info            = tmp.rst_equip_info,
    rst_ind_comment_info      = tmp.rst_ind_comment_info,
    rst_tare_info             = tmp.rst_tare_info,
    rst_off_water_info        = tmp.rst_off_water_info,
    rst_weight_info           = tmp.rst_weight_info,
--   add 10196 by kangjie 20240130 start del
--     rst_vital_info            = tmp.rst_vital_info,
--   add 10196 by kangjie 20240130 end del
    rst_complaint_info        = tmp.rst_complaint_info,
    rst_treatment_info        = tmp.rst_treatment_info,
    rst_treat_staff_info      = tmp.rst_treat_staff_info,
    rst_rounds_info           = tmp.rst_rounds_info,
    is_del                    = tmp.is_del,
    reg_date                  = tmp.reg_date,
    up_date                   = tmp.up_date,
    ind_device_set_info       = tmp.ind_device_set_info,
--   add 10196 by kangjie 20240130 start del
--     rst_device_set_info       = tmp.rst_device_set_info,
--   add 10196 by kangjie 20240130 end del
    rst_dw                    = tmp.rst_dw,
    weight_scale_no           = tmp.weight_scale_no,
    treat_type                = tmp.treat_type,
    is_confirm                = tmp.is_confirm,
    ind_dw                    = tmp.ind_dw,
    rst_purification_cnt      = tmp.rst_purification_cnt,
    addition_info             = tmp.addition_info,
    up_ind_user_id            = tmp.up_ind_user_id,
    up_user_id                = tmp.up_user_id,
    rst_edition_date          = tmp.rst_edition_date,
    cur_edition_date          = tmp.cur_edition_date FROM
    (VALUES
    /*%for pat : uptOrdList */
    (
    /*pat.ordNo*/null,
    /*pat.patId*/null,
    /*pat.fnPatId*/null,
    /*pat.treatDate*/null,
    /*pat.treatWeek*/null,
    /*pat.facilityCd*/null,
    /*pat.facilityName*/null,
    /*pat.indVaCd*/null,
    /*pat.indTreatmentCd*/null,
    /*pat.indTreatmentName*/null,
    /*pat.indKurCd*/null,
    /*pat.indKurName*/null,
    /*pat.indTreatStartTime*/null,
    /*pat.indBedCd*/null,
    /*pat.indBedName*/null,
    /*pat.indScheduleUserInfo*/null,
    /*pat.indCondInfo*/null,
    /*pat.indMediInfo*/null,
    /*pat.indEquipInfo*/null,
    /*pat.indIndCommentInfo*/null,
    /*pat.indTareInfo*/null,
    /*pat.indOffWaterInfo*/null,
    /*pat.rstFnDialysisNo*/null,
    /*pat.rstRelationDialysisNo*/null,
    /*pat.rstEdition*/null,
    /*pat.rstIsUpdateEdition*/null,
    /*pat.rstInputClass*/null,
    /*pat.rstDialysisState*/null,
    /*pat.rstTreatmentCd*/null,
    /*pat.rstTreatmentName*/null,
    /*pat.rstKurCd*/null,
    /*pat.rstKurName*/null,
    /*pat.rstBedCd*/null,
    /*pat.rstBedName*/null,
    /*pat.rstMachineNo*/null,
    /*pat.rstMachineName*/null,
    /*pat.rstCondSendDate*/null,
    /*pat.rstAcceptDate*/null,
    /*pat.rstStartDate*/null,
    /*pat.rstEndDate*/null,
    /*pat.rstReturnHomeDate*/null,
    /*pat.rstInOutClass*/null,
    /*pat.rstDialysisCnt*/null,
    /*pat.rstWardCd*/null,
    /*pat.rstWardName*/null,
    /*pat.rstCourseCd*/null,
    /*pat.rstCourseName*/null,
    /*pat.rstPunctureUserInfo*/null,
    /*pat.rstReturnUserInfo*/null,
    /*pat.rstChargeUserInfo*/null,
    /*pat.rstBloodCirculateTotal*/null,
    /*pat.rstRunningTime*/null,
    /*pat.rstKtV*/null,
    /*pat.recSetDate*/null,
    /*pat.sendCtlNo*/null,
    /*pat.bloodPurifierName*/null,
    /*pat.pullLeaveAmount*/null,
    /*pat.rstCondInfo*/null,
    /*pat.rstMediInfo*/null,
    /*pat.rstEquipInfo*/null,
    /*pat.rstIndCommentInfo*/null,
    /*pat.rstTareInfo*/null,
    /*pat.rstOffWaterInfo*/null,
    /*pat.rstWeightInfo*/null,

--   add 10196 by kangjie 20240130 start del
--     /*pat.rstVitalInfo*/null,
--   add 10196 by kangjie 20240130 end del

    /*pat.rstComplaintInfo*/null,
    /*pat.rstTreatmentInfo*/null,
    /*pat.rstTreatStaffInfo*/null,
    /*pat.rstRoundsInfo*/null,
    /*pat.isDel*/null,
    /*pat.regDate*/null,
    /*pat.upDate*/null,
    /*pat.indDeviceSetInfo*/null,

--   add 10196 by kangjie 20240130 start del
--     /*pat.rstDeviceSetInfo*/null,
--   add 10196 by kangjie 20240130 end del

    /*pat.rstDw*/null,
    /*pat.weightScaleNo*/null,
    /*pat.treatType*/null,
    /*pat.isConfirm*/null,
    /*pat.indDw*/null,
    /*pat.rstPurificationCnt*/null,
    /*pat.additionInfo*/null,
    /*pat.upIndUserId*/null,
    /*pat.upUserId*/null,
    /*pat.rstEditionDate*/null,
    /*pat.curEditionDate*/null
    )
/*%if pat_has_next */
/*# "," */
/*%end */
/*%end*/
    ) AS tmp (ord_no, pat_id, fn_pat_id, treat_date, treat_week, facility_cd, facility_name, ind_va_cd, ind_treatment_cd,
    ind_treatment_name, ind_kur_cd, ind_kur_name, ind_treat_start_time, ind_bed_cd, ind_bed_name, ind_schedule_user_info,
    ind_cond_info, ind_medi_info, ind_equip_info, ind_ind_comment_info, ind_tare_info, ind_off_water_info, rst_fn_dialysis_no,
    rst_relation_dialysis_no, rst_edition, rst_is_update_edition, rst_input_class, rst_dialysis_state, rst_treatment_cd,
    rst_treatment_name, rst_kur_cd, rst_kur_name, rst_bed_cd, rst_bed_name, rst_machine_no, rst_machine_name,
    rst_cond_send_date, rst_accept_date, rst_start_date, rst_end_date, rst_return_home_date, rst_in_out_class, rst_dialysis_cnt,
    rst_ward_cd, rst_ward_name, rst_course_cd, rst_course_name, rst_puncture_user_info, rst_return_user_info, rst_charge_user_info,
    rst_blood_circulate_total, rst_running_time, rst_kt_v, rec_set_date, send_ctl_no, blood_purifier_name, pull_leave_amount,
    rst_cond_info, rst_medi_info, rst_equip_info, rst_ind_comment_info, rst_tare_info, rst_off_water_info, rst_weight_info,
    rst_complaint_info, rst_treatment_info, rst_treat_staff_info, rst_rounds_info, is_del, reg_date,
    up_date, ind_device_set_info, rst_dw, weight_scale_no, treat_type, is_confirm, ind_dw,
    rst_purification_cnt, addition_info, up_ind_user_id, up_user_id, rst_edition_date, cur_edition_date)
WHERE
    ord_main.ord_no = tmp.ord_no
