-- Generated By Doma Tools #12462 患者情報共有 zrx
SELECT
j1.cd,
j1.NAME,
j1.is_enable,
j1.start_date
FROM
ord_main o
	JOIN shr_pat_info s ON o.pat_id = s.from_pat_id
	AND o.facility_cd = s.from_facility_cd
	CROSS JOIN LATERAL jsonb_to_recordset ( o.addition_info ) AS j1 ( cd BIGINT, NAME TEXT, is_enable TEXT, start_date TEXT )
WHERE
o.is_del = '0'
	AND o.ord_no = /*ordNo*/0
	AND s.is_from_consent = '1'
	AND s.is_to_consent = '1'
	AND s.is_pat_consent = '1'
	AND s.is_disp = '1'
	AND s.is_del = '0'
