rootProject.name=ntss
profile=dev
java_language_version=25

node_version=24.15.0
npm_version=11.12.1
node_gradle_plugin_version=7.1.0
jackson2_buildscript_version=2.21.3
jackson2_annotations_version=2.21
spring_boot_version=4.0.6
tomcat_version=11.0.22
netty_version=4.2.13.Final
spring_restdocs_version=4.0.0
dependency_management_plugin_version=1.1.7
asciidoctor_plugin_version=4.0.5
asciidoctorj_version=3.0.1
doma_spring_version=3.0.0
doma_core_version=3.11.1
aws_sdk_v2_version=2.44.4
flyway_version=12.6.0
flyway_postgresql_driver_version=42.7.11
postgresql_version=42.7.11
bcprov_version=1.84
commons_compress_version=1.28.0
commons_csv_version=1.14.1
commons_beanutils_version=1.11.0
commons_lang3_version=3.20.0
commons_collections4_version=4.5.0
commons_text_version=1.15.0
gson_version=2.14.0
guava_version=33.6.0-jre
json_java_version=20251224
jakarta_xml_bind_api_version=4.0.5
jakarta_xml_bind_runtime_version=4.0.8
jsoup_version=1.22.2
lombok_version=1.18.46
modelmapper_version=3.2.6
poi_version=5.5.1
zxing_version=3.5.4
playwright_version=1.59.0
## below are some of the gradle performance improvement settings that can be used as required, these are not enabled by default
org.gradle.jvmargs=-Xmx1g
## The Gradle daemon aims to improve the startup and execution time of Gradle.
## The daemon is enabled by default in Gradle 3+ setting this to false will disable this.
## TODO: disable daemon on CI, since builds should be clean and reliable on servers
## https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:ways_to_disable_gradle_daemon
## un comment the below line to disable the daemon

#org.gradle.daemon=false

## Specifies the JVM arguments used for the daemon process.
## The setting is particularly useful for tweaking memory settings.
## Default value: -Xmx1024m -XX:MaxPermSize=256m
## un comment the below line to override the daemon defaults

#org.gradle.jvmargs=-Xmx1024m -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

## When configured, Gradle will run in incubating parallel mode.
## This option should only be used with decoupled projects. More details, visit
## http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
## un comment the below line to enable parallel mode

#org.gradle.parallel=true

## Enables new incubating mode that makes Gradle selective when configuring projects.
## Only relevant projects are configured which results in faster builds for large multi-projects.
## http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:configuration_on_demand
## un comment the below line to enable the selective mode

#org.gradle.configureondemand=true
