# 永和ST環境用
spring:
  main:
    allow-circular-references: true
  datasource:
    default:
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db5?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk5
      password: nkk5
    personal:
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db6?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk6
      password: nkk6
    auth:
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db4?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk4
      password: nkk4
  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: ntss-m-notice
  jmx:
    default-domain: ntss-m-notice

doma:
  dialect: postgres

securityporicy:
  accesskeycheck: true

spring.thymeleaf.cache: false

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-1 # 東京リージョン
    credentials:
      accessKey: AKIAJDQJBT6P6C2NMPYA
      secretKey: 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

ntss:
  m-notice:
    mail:
      sesRegion: us-west-2
      fromAddress: NTSS-Support@nikkiso.co.jp
    viewer:
      url: 'http://172.16.80.64:8080/ntss-admin-web/#/?key=%s&FUNC=00103&FACILITYCD=%s&MACHINETYPECD=%s&MACHINESERIAL=%s'
    nikkiso-facility-cd: nkknkk
    nikkiso-user-mail-address-regex: ^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@nikkiso\.(co|biz\.ezweb\.ne)\.jp$
