INSERT INTO sys_facility_setting ( 
  facility_setting_no,
  setting_name,
  default_value,
  input_type,
  option_value,
  function_name,
  maker_setting,
  description,
  disp_order,
  reg_date,
  up_date
) 
VALUES (
  '1028',
  '薬剤・調整薬剤マスタ手技デフォルト',
  '-1',
  5,
  '[{"master_physical_name":"mst_procedure"}]',
  '薬剤・調整薬剤マスタ手技デフォルト',
  0,
  '薬剤マスタおよび調製薬剤マスタの新規追加時に設定されるデフォルトの手技を設定します。',
  28,
  current_timestamp,
  current_timestamp
);
INSERT INTO sys_facility_setting ( 
  facility_setting_no,
  setting_name,
  default_value,
  input_type,
  option_value,
  function_name,
  maker_setting,
  description,
  disp_order,
  reg_date,
  up_date
) 
VALUES (
  '1029',
  '薬剤・調整薬剤マスタ投与タイミングデフォルト',
  '-1',
  5,
  '[{"master_physical_name":"mst_medicate_timing"}]',
  '薬剤・調整薬剤マスタ投与タイミングデフォルト',
  0,
  '薬剤マスタおよび調製薬剤マスタの新規追加時に設定されるデフォルトの投与タイミングを設定します。',
  29,
  current_timestamp,
  current_timestamp
);