UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name, 1 as kubun from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd union select medicine_mix_cd as id, medicine_mix_name as name, 2 as kubun from mst_medicine_mix where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 6 AND "disp_order" = 1;
UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 1 AND "disp_order" = 1;
UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name, 1 as kubun from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd union select medicine_mix_cd as id, medicine_mix_name as name, 2 as kubun from mst_medicine_mix where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 2 AND "disp_order" = 1;
UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 5 AND "disp_order" = 1;
DELETE FROM "ntss"."sys_data_list_detail" WHERE "category_cd" = 10 AND "disp_order" = 8;

UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name, 1 as kubun from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd union select medicine_mix_cd as id, medicine_mix_name as name, 2 as kubun from mst_medicine_mix where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 14 AND "disp_order" = 1;
UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name, 1 as kubun from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd union select medicine_mix_cd as id, medicine_mix_name as name, 2 as kubun from mst_medicine_mix where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 18 AND "disp_order" = 1;
UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 13 AND "disp_order" = 1;
UPDATE "ntss"."sys_data_list_detail" SET "function_display_sql" = 'select medicine_cd as id, medicine_name as name from mst_medicine where class_cd in (@ids) and facility_cd = @facilityCd' WHERE "category_cd" = 17 AND "disp_order" = 1;
DELETE FROM "ntss"."sys_data_list_detail" WHERE "category_cd" = 22 AND "disp_order" = 8;