DELETE from ntss.mst_coop_layout where ctl_no in (-2080009,-2080008,-1010013,-1010007,-1010006);
INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-2080009, 'F_hosp', 'rep_dial', 'nkklistxml', 'S', 'upd', 'xml', 'listxml', 'fujitsu', '透析レポート（URL連携→日機装（LISTXMLとXMLとPDFファイルの送信））→report_type(nkk_rep)', '1', '<rootNode DISP_PATID_LENGTH="dataset:-100010.hosp_pat_id_len">
<PATIENT DISP_PATID="dataset:-100001.hosp_pat_id" PATID="$JOURNAL.pat_id"  NAME="dataset:-100001.pat_name" KANA="dataset:-100001.pat_name_kana"  SEX="dataset:-100001.pat_sex" BLOODABO="dataset:-100011.pat_blood_type_abo" BLOODRH="dataset:-100011.pat_blood_type_rh" AGE="dataset:-100001.pat_age" UPDATE_DATETIME="dataset:-100001.up_date"></PATIENT>
</rootNode>', '{"dataset": [{"patId": "patId", "sqlCode": -100001}, {"sqlCode": -100010, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -100011}]}', '1', '0', 4, '2020-05-25 18:26:36.811',CURRENT_TIMESTAMP, '');
INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-2080008, 'F_hosp', 'rep_dial', 'nkklistxml', 'S', 'cre', 'xml', 'listxml', 'fujitsu', '透析レポート（URL連携→日機装（LISTXMLとXMLとPDFファイルの送信））→report_type(nkk_rep)', '1', '<rootNode DISP_PATID_LENGTH="dataset:-100010.hosp_pat_id_len">
<PATIENT DISP_PATID="dataset:-100001.hosp_pat_id" PATID="$JOURNAL.pat_id"  NAME="dataset:-100001.pat_name" KANA="dataset:-100001.pat_name_kana"  SEX="dataset:-100001.pat_sex" BLOODABO="dataset:-100011.pat_blood_type_abo" BLOODRH="dataset:-100011.pat_blood_type_rh" AGE="dataset:-100001.pat_age" UPDATE_DATETIME="dataset:-100001.up_date"></PATIENT>
</rootNode>', '{"dataset": [{"patId": "patId", "sqlCode": -100001}, {"sqlCode": -100010, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -100011}]}', '1', '0', 4, '2020-05-25 18:26:36.811', CURRENT_TIMESTAMP, '');
INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-1010013, 'nkknkk', 'rep_dial', 'listxml', 'S', 'del', 'xml', '日機装 透析レポート(listxml)', '日機装', 'テスト用report', '1', '<rootNode DISP_PATID_LENGTH="dataset:-400010.hosp_pat_id_len">
<PATIENT DISP_PATID="dataset:-400001.hosp_pat_id" PATID="$JOURNAL.pat_id"  NAME="dataset:-400001.pat_name" KANA="dataset:-400001.pat_name_kana"  SEX="dataset:-400001.pat_sex" BLOODABO="dataset:-400016.pat_blood_type_abo" BLOODRH="dataset:-400016.pat_blood_type_rh" AGE="dataset:-400001.pat_age" UPDATE_DATETIME="dataset:-400001.up_date"></PATIENT>
</rootNode>', '{"dataset": [{"patId": "patId", "sqlCode": -400001}, {"sqlCode": -400010, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -400016}]}', '1', '0', -1, '2022-07-04 12:22:10.543', CURRENT_TIMESTAMP, '');
INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-1010007, 'nkknkk', 'rep_dial', 'listxml', 'S', 'cre', 'xml', '日機装 透析レポート(listxml)', '日機装', 'テスト用report', '1', '<rootNode DISP_PATID_LENGTH="dataset:-400010.hosp_pat_id_len">
<PATIENT DISP_PATID="dataset:-400001.hosp_pat_id" PATID="$JOURNAL.pat_id"  NAME="dataset:-400001.pat_name" KANA="dataset:-400001.pat_name_kana"  SEX="dataset:-400001.pat_sex" BLOODABO="dataset:-400016.pat_blood_type_abo" BLOODRH="dataset:-400016.pat_blood_type_rh" AGE="dataset:-400001.pat_age" UPDATE_DATETIME="dataset:-400001.up_date"></PATIENT>
</rootNode>', '{"dataset": [{"patId": "patId", "sqlCode": -400001}, {"sqlCode": -400010, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -400016}]}', '1', '0', -1, '2021-09-01 07:38:44.069',CURRENT_TIMESTAMP, '');
INSERT INTO "ntss"."mst_coop_layout" ("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-1010006, 'nkknkk', 'rep_dial', 'listxml', 'S', 'upd', 'xml', '日機装 透析レポート(listxml)', '日機装', 'テスト用report', '1', '<rootNode DISP_PATID_LENGTH="dataset:-400010.hosp_pat_id_len">
<PATIENT DISP_PATID="dataset:-400001.hosp_pat_id" PATID="$JOURNAL.pat_id"  NAME="dataset:-400001.pat_name" KANA="dataset:-400001.pat_name_kana"  SEX="dataset:-400001.pat_sex" BLOODABO="dataset:-400016.pat_blood_type_abo" BLOODRH="dataset:-400016.pat_blood_type_rh" AGE="dataset:-400001.pat_age" UPDATE_DATETIME="dataset:-400001.up_date"></PATIENT>
</rootNode>', '{"dataset": [{"patId": "patId", "sqlCode": -400001}, {"sqlCode": -400010, "facilityCd": "facilityCd"}, {"patId": "patId", "sqlCode": -400016}]}', '1', '0', -1, '2021-09-01 07:38:44.069', CURRENT_TIMESTAMP, '');
