--DELETE FROM "ntss"."mst_coop_layout_detail" WHERE ctl_no in (66662,66661,12859,7926,7925,7924,7497);
--
--INSERT INTO "ntss"."mst_coop_layout_detail" ("ctl_no", "facility_cd", "coop_cd", "direction", "coop_cd_detail", "coop_cd_detail_sub", "coop_name", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-212000002, 'F_hosp', 'phy_ord', 'S', '透析心電図詳細', '検査項目', '透析心電図', '透析心電図', '1', '<root name="明細詳細(透析心電図)">
--    <item  name="明細.項目コード" len="8" value="dataset:-66670.in_hospital_cd1"/>
--    <item  name="明細.項目属性" len="3" value="dataset:-66670.sbt_cd1"/>
--    <item  name="明細.項目名称" len="50" value="dataset:-66670.item_name"/>
--    <item  name="明細.数量" len="11" value="const:0000000.000"/>
--    <item  name="明細.選択単位フラグ" len="1" value="const:0"/>
--    <item  name="明細.単位コード" len="3" value="$BLANK"/>
--    <item  name="明細.単位名称" len="4" value="$BLANK"/>
--    <item  name="明細.第２単位コード" len="3" value="$BLANK"/>
--    <item  name="明細.第２単位名称" len="4" value="$BLANK"/>
--    <item  name="明細.単位換算量" len="11" value="const:0000000.000"/>
--    <item  name="明細.タグ名称" len="20" value="dataset:-66670.tag_name"/>
--</root>', '{}', '1', '0', -1, '2023-07-17 21:01:55.612', CURRENT_TIMESTAMP, 'gx002');
--INSERT INTO "ntss"."mst_coop_layout_detail" ("ctl_no", "facility_cd", "coop_cd", "direction", "coop_cd_detail", "coop_cd_detail_sub", "coop_name", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-212000001, 'F_hosp', 'phy_ord', 'S', '透析心電図詳細del', '検査項目', '透析心電図', '透析心電図', '1', '<root name="明細詳細(透析心電図)">
--    <item  name="明細.項目コード" len="8" value="dataset:-66671.in_hospital_cd1"/>
--    <item  name="明細.項目属性" len="3" value="dataset:-66671.sbt_cd1"/>
--    <item  name="明細.項目名称" len="50" value="dataset:-66671.item_name"/>
--    <item  name="明細.数量" len="11" value="const:0000000.000"/>
--    <item  name="明細.選択単位フラグ" len="1" value="const:0"/>
--    <item  name="明細.単位コード" len="3" value="$BLANK"/>
--    <item  name="明細.単位名称" len="4" value="$BLANK"/>
--    <item  name="明細.第２単位コード" len="3" value="$BLANK"/>
--    <item  name="明細.第２単位名称" len="4" value="$BLANK"/>
--    <item  name="明細.単位換算量" len="11" value="const:0000000.000"/>
--    <item  name="明細.タグ名称" len="20" value="dataset:-66671.tag_name"/>
--</root>', '{}', '1', '0', -1, '2023-07-17 21:01:55.612', CURRENT_TIMESTAMP, 'gx002');
--INSERT INTO "ntss"."mst_coop_layout_detail" ("ctl_no", "facility_cd", "coop_cd", "direction", "coop_cd_detail", "coop_cd_detail_sub", "coop_name", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-212000003, 'F_hosp', 'pre_ord', 'R', '処方情報詳細', 'all', '処方情報受信', '処方情報受信', '1', '<root name="処方明細">
--  <item name="項目コード" len="8" type="string" col="$journal.detail.ord_prescription.prescription_detail.code"/>
--  <item name="項目属性" len="3" type="string" col="$journal.detail.ord_prescription.prescription_detail.attr"/>
--  <item name="項目名称" len="50" type="string" col="$journal.detail.ord_prescription.prescription_detail.name"/>
--  <item name="数量" len="11" type="string" col="$journal.detail.ord_prescription.prescription_detail.quantity"/>
--  <item name="選択単位フラグ" len="1" type="string" col="$journal.detail.ord_prescription.prescription_detail.unit_flg"/>
--  <item name="選択単位コード" len="3" type="string" col="$journal.detail.ord_prescription.prescription_detail.unit_code"/>
--  <item name="選択単位名称" len="4" type="string" col="$journal.detail.ord_prescription.prescription_detail.unit_name"/>
--  <item name="第２単位コード" len="3" type="string" col="$journal.detail.ord_prescription.prescription_detail.unit2_code"/>
--  <item name="第２単位名称" len="4" type="string" col="$journal.detail.ord_prescription.prescription_detail.unit2_name"/>
--  <item name="極量フラグ" len="1" type="string" col="$journal.detail.ord_prescription.prescription_detail.extremeQuantity_flg"/>
--  <item name="項目行日" len="8" type="string"/>
--  <item name="項目行時間" len="6" type="string"/>
--  <item name="付帯コード" len="20" type="string"/>
--</root>', '{}', '1', '0', 4126, '2023-07-17 21:01:57.473', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout_detail" ("ctl_no", "facility_cd", "coop_cd", "direction", "coop_cd_detail", "coop_cd_detail_sub", "coop_name", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-103000018, 'nkknkk', 'profile', 'R', '詳細項目', '造影剤アレルギー', '日機装標準', '患者情報（XML)', '1', '<DetailInfo Function="5" SEQ="" info="造影剤アレルギー">
--  <Item Code="col:$journal.detail.pat_main_10.taboo_allergy_info.taboo_allergy_cd">col:$journal.detail.pat_main_10.taboo_allergy_info.content</Item>
--  <Contents>col:$journal.detail.pat_main_10.taboo_allergy_info.memo</Contents>
--  <Date></Date>
--</DetailInfo>', '{}', '1', '0', -1, '2022-07-11 23:36:54.776', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout_detail" ("ctl_no", "facility_cd", "coop_cd", "direction", "coop_cd_detail", "coop_cd_detail_sub", "coop_name", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-103000017, 'nkknkk', 'profile', 'R', '詳細項目', '食物アレルギー', '日機装標準', '患者情報（XML)', '1', '<DetailInfo Function="4" SEQ="" info="食物アレルギー">
--  <Item Code="col:$journal.detail.pat_main_9.taboo_allergy_info.taboo_allergy_cd">col:$journal.detail.pat_main_9.taboo_allergy_info.content</Item>
--  <Contents>col:$journal.detail.pat_main_9.taboo_allergy_info.memo</Contents>
--  <Date></Date>
--</DetailInfo>', '{}', '1', '0', -1, '2022-07-11 23:36:54.776', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout_detail" ("ctl_no", "facility_cd", "coop_cd", "direction", "coop_cd_detail", "coop_cd_detail_sub", "coop_name", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-103000016, 'nkknkk', 'profile', 'R', '詳細項目', 'その他アレルギー', '日機装標準', '患者情報（XML)', '1', '<DetailInfo Function="7" SEQ="" info="その他アレルギー">
--  <Item Code="col:$journal.detail.pat_main_8.taboo_allergy_info.taboo_allergy_cd">col:$journal.detail.pat_main_8.taboo_allergy_info.content</Item>
--  <Contents>col:$journal.detail.pat_main_8.taboo_allergy_info.memo</Contents>
--  <Date></Date>
--</DetailInfo>', '{}', '1', '0', -1, '2022-07-11 23:36:54.776', CURRENT_TIMESTAMP, '');
--INSERT INTO "ntss"."mst_coop_layout_detail" ("ctl_no", "facility_cd", "coop_cd", "direction", "coop_cd_detail", "coop_cd_detail_sub", "coop_name", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date", "coop_version") VALUES (-103000015, 'nkknkk', 'profile', 'R', '詳細項目', '金属アレルギー', '日機装標準', '患者情報（XML)', '1', '<DetailInfo Function="6" SEQ="" info="金属アレルギー">
--  <Item Code="col:$journal.detail.pat_main_5.taboo_allergy_info.taboo_allergy_cd">col:$journal.detail.pat_main_5.taboo_allergy_info.content</Item>
--  <Contents>col:$journal.detail.pat_main_5.taboo_allergy_info.memo</Contents>
--  <Date></Date>
--</DetailInfo>', '{}', '1', '0', 4, '2020-05-21 18:36:58.999', CURRENT_TIMESTAMP, '');
----