--治療状況透析液調製装置グラフレイアウトマスタ  モニタ項目   データ補正
UPDATE ntss.sys_monitor_item
	SET upper=250.0
	WHERE moni_data_no='I2';
UPDATE ntss.sys_monitor_item
	SET upper=45.0
	WHERE moni_data_no='I3';
UPDATE ntss.sys_monitor_item
	SET upper=150.0
	WHERE moni_data_no='I4';
UPDATE ntss.sys_monitor_item
	SET upper=300.0,lower=-10.0
	WHERE moni_data_no='I6';
UPDATE ntss.sys_monitor_item
	SET upper=4.500
	WHERE moni_data_no='I7';
UPDATE ntss.sys_monitor_item
	SET upper=100.0
	WHERE moni_data_no='J2';
UPDATE ntss.sys_monitor_item
	SET upper=45.0
	WHERE moni_data_no='J3';
UPDATE ntss.sys_monitor_item
	SET upper=300,lower=-10.0
	WHERE moni_data_no='J4';
UPDATE ntss.sys_monitor_item
	SET upper=4.500
	WHERE moni_data_no='J5';