DELETE FROM "ntss"."sys_system_define" WHERE ctl_no = 7;
INSERT INTO "ntss"."sys_system_define" ("ctl_no", "service_cd", "name", "value", "description", "is_enable", "up_date") VALUES ('7', '003', '帳票レイアウトデザイナーアプリケーション最新バージョン', '{"version": "2.0.0.36"}', '対象アプリケーションの最新版バージョンを設定することでアプリケーションのアップデートを実施する', '1', CURRENT_TIMESTAMP);
DELETE FROM "ntss"."sys_system_define" WHERE ctl_no = 35;
INSERT INTO "ntss"."sys_system_define" ("ctl_no", "service_cd", "name", "value", "description", "is_enable", "up_date") VALUES ('35', '003', 'データセット最新バージョン', '{"version": "2.0.0.30"}', 'データセット最新バージョン', '1',CURRENT_TIMESTAMP);
DELETE FROM "ntss"."sys_system_define" WHERE ctl_no = 8;
INSERT INTO "ntss"."sys_system_define" ("ctl_no", "service_cd", "name", "value", "description", "is_enable", "up_date") VALUES ('8', '003', '体重計アプリケーション最新バージョン', '{"version": "2.0.0.4"}', '対象アプリケーションの最新版バージョンを設定することでアプリケーションのアップデートを実施する', '1', CURRENT_TIMESTAMP);
DELETE FROM "ntss"."sys_system_define" WHERE ctl_no = 9;
INSERT INTO "ntss"."sys_system_define" ("ctl_no", "service_cd", "name", "value", "description", "is_enable", "up_date") VALUES ('9', '003', '印刷サーバーアプリケーション最新バージョン', '{"version": "2.0.0.4"}', '対象アプリケーションの最新版バージョンを設定することでアプリケーションのアップデートを実施する', '1', CURRENT_TIMESTAMP);
DELETE FROM "ntss"."sys_system_define" WHERE ctl_no = 15;
INSERT INTO "ntss"."sys_system_define" ("ctl_no", "service_cd", "name", "value", "description", "is_enable", "up_date") VALUES ('15', '003', 'カードアクセスアプリケーション', '{"version": "2.0.0.4"}', 'カードアクセスアプリケーション', '1', CURRENT_TIMESTAMP);
DELETE FROM "ntss"."sys_system_define" WHERE ctl_no = 11;
INSERT INTO "ntss"."sys_system_define" ("ctl_no", "service_cd", "name", "value", "description", "is_enable", "up_date") VALUES ('11', '003', '浄化装置通信アプリケーション最新バージョン', '{"version": "2.0.0.3"}', '対象アプリケーションの最新版バージョンを設定することでアプリケーションのアップデートを実施する', '1', CURRENT_TIMESTAMP);
