delete from "mst_coop_layout" where "ctl_no" in (-7020001,-7020002,-7020003);
INSERT INTO "mst_coop_layout"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-7020001, 'NEC-iS', 'ind_dial', '', 'S', 'cre', 'xml', 'NEC-iS 予約情報連携', 'NEC-iS(MegaOakiS)', '予約情報連携', '1', '<soap:Envelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <Request
            xmlns="http://medical.nec.co.jp/">
            <requestData>
                <Request>
                    <Header>
                        <Command>B01_RegistDialysisIndicationFromDialysis</Command>
                        <Type>REGIST</Type>
                        <Conditions>
                            <Condition>
                                <FunctionId>1</FunctionId>
                                <PatientId>dataset:-1004.hosp_pat_id10</PatientId>
                                <StaffCode>dataset:-207.up_ind_user_id</StaffCode>
                                <DepartmentCode>dataset:-208.department_code</DepartmentCode>
                                <IndicateStaffCode>dataset:-208.indicate_staff_code</IndicateStaffCode>
                                <IsWarningMessageCancel>1</IsWarningMessageCancel>
                            </Condition>
                        </Conditions>
                        <RequesterInfomation>
                            <EventDateTime>$SYSDATE yyyy/MM/dd HH:mm:ss</EventDateTime>
                            <UserId></UserId>
                            <UserName></UserName>
                            <ProfessionCode></ProfessionCode>
                            <ProfessionName></ProfessionName>
                            <DepartmentCode></DepartmentCode>
                            <DepartmentName></DepartmentName>
                            <SystemIdTypeCode>4</SystemIdTypeCode>
                            <SystemId>dataset:-1003.system_id</SystemId>
                            <ComputerIdTypeCode></ComputerIdTypeCode>
                            <ComputerId></ComputerId>
                            <ApplicationName></ApplicationName>
                        </RequesterInfomation>
                    </Header>
                    <Contents>
                        <ExternalDialysisIndication>
                            <PatientContent>
                                <PatientNo>dataset:-1004.hosp_pat_id10</PatientNo>
                            </PatientContent>
                            <DialysisIndicationContent>
                                <IndicateOrderNo>$JOURNAL.ord_no</IndicateOrderNo>
                                <ExecuteOrderNo></ExecuteOrderNo>
                                <StartDate>dataset:-207.start_date</StartDate>
                                <StartTime>dataset:-207.start_time</StartTime>
                                <EndDate>dataset:-207.end_date</EndDate>
                                <EndTime>dataset:-207.end_time</EndTime>
                                <AppointmentBedTimeKbn></AppointmentBedTimeKbn>
                                <DialysisIntroductionDate>dataset:-207.dialysis_start_date</DialysisIntroductionDate>
                                <DialysisPlace>dataset:-207.hospital_bed_cd</DialysisPlace>
                                <UpdateDate>dataset:-207.update_date</UpdateDate>
                                <UpdateTime>dataset:-207.update_time</UpdateTime>
                                <UpdateTerminal>dataset:-1003.update_terminal</UpdateTerminal>
                                <UpdateOperator>dataset:-207.up_ind_user_id</UpdateOperator>
                                <UpdateOperatorGenerationNo></UpdateOperatorGenerationNo>
                                <DepartmentContent>
                                    <Code>dataset:-208.department_code</Code>
                                    <GenerationNo></GenerationNo>
                                </DepartmentContent>
                                <DoctorContent>
                                    <Code>dataset:-208.indicate_staff_code</Code>
                                    <GenerationNo></GenerationNo>
                                </DoctorContent>
                                <BloodMethodContent>
                                    <Code>dataset:-207.hospital_treatment_cd</Code>
                                    <GenerationNo></GenerationNo>
                                </BloodMethodContent>
                                <DialysisDetailContentList>
                                    <DialysisDetailContent _sqlCode="-209">
                                        <DetailSeq>dataset:-209.seq_no</DetailSeq>
                                        <FunctionID>dataset:-209.function_id</FunctionID>
                                        <ItemContent>
                                            <Code>dataset:-209.item_code</Code>
                                            <GenerationNo></GenerationNo>
                                        </ItemContent>
                                        <QuantityContent>
                                            <Quantity>dataset:-209.quantity</Quantity>
                                            <UnitCode>dataset:-209.unit_code</UnitCode>
                                            <UnitCodeGenerationNo></UnitCodeGenerationNo>
                                        </QuantityContent>
                                    </DialysisDetailContent>
                                </DialysisDetailContentList>
                            </DialysisIndicationContent>
                        </ExternalDialysisIndication>
                    </Contents>
                </Request>
            </requestData>
        </Request>
    </soap:Body>
</soap:Envelope>', '{"soap": {"xmlEncoding": "utf-8"}, "dataset": [{"ordNo": "ordNo", "sqlCode": -207}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -208, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -209, "facilityCd": "facilityCd"}, {"sqlCode": -1003, "facilityCd": "facilityCd"}, {"ctlNo": "ctlNo", "sqlCode": -1004}]}', '1', '0', -1, '2021-12-20 09:00:00', '2021-12-20 09:00:00');
INSERT INTO "mst_coop_layout"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-7020002, 'NEC-iS', 'ind_dial', '', 'S', 'upd', 'xml', 'NEC-iS 予約情報連携', 'NEC-iS(MegaOakiS)', '予約情報連携', '1', '<soap:Envelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <Request
            xmlns="http://medical.nec.co.jp/">
            <requestData>
                <Request>
                    <Header>
                        <Command>B01_RegistDialysisIndicationFromDialysis</Command>
                        <Type>REGIST</Type>
                        <Conditions>
                            <Condition>
                                <FunctionId>2</FunctionId>
                                <PatientId>dataset:-1004.hosp_pat_id10</PatientId>
                                <StaffCode>dataset:-207.up_ind_user_id</StaffCode>
                                <DepartmentCode>dataset:-208.department_code</DepartmentCode>
                                <IndicateStaffCode>dataset:-208.indicate_staff_code</IndicateStaffCode>
                                <IsWarningMessageCancel>1</IsWarningMessageCancel>
                            </Condition>
                        </Conditions>
                        <RequesterInfomation>
                            <EventDateTime>$SYSDATE yyyy/MM/dd HH:mm:ss</EventDateTime>
                            <UserId></UserId>
                            <UserName></UserName>
                            <ProfessionCode></ProfessionCode>
                            <ProfessionName></ProfessionName>
                            <DepartmentCode></DepartmentCode>
                            <DepartmentName></DepartmentName>
                            <SystemIdTypeCode>4</SystemIdTypeCode>
                            <SystemId>dataset:-1003.system_id</SystemId>
                            <ComputerIdTypeCode></ComputerIdTypeCode>
                            <ComputerId></ComputerId>
                            <ApplicationName></ApplicationName>
                        </RequesterInfomation>
                    </Header>
                    <Contents>
                        <ExternalDialysisIndication>
                            <PatientContent>
                                <PatientNo>dataset:-1004.hosp_pat_id10</PatientNo>
                            </PatientContent>
                            <DialysisIndicationContent>
                                <IndicateOrderNo>$JOURNAL.ord_no</IndicateOrderNo>
                                <ExecuteOrderNo></ExecuteOrderNo>
                                <StartDate>dataset:-207.start_date</StartDate>
                                <StartTime>dataset:-207.start_time</StartTime>
                                <EndDate>dataset:-207.end_date</EndDate>
                                <EndTime>dataset:-207.end_time</EndTime>
                                <AppointmentBedTimeKbn></AppointmentBedTimeKbn>
                                <DialysisIntroductionDate>dataset:-207.dialysis_start_date</DialysisIntroductionDate>
                                <DialysisPlace>dataset:-207.hospital_bed_cd</DialysisPlace>
                                <UpdateDate>dataset:-207.update_date</UpdateDate>
                                <UpdateTime>dataset:-207.update_time</UpdateTime>
                                <UpdateTerminal>dataset:-1003.update_terminal</UpdateTerminal>
                                <UpdateOperator>dataset:-207.up_ind_user_id</UpdateOperator>
                                <UpdateOperatorGenerationNo></UpdateOperatorGenerationNo>
                                <DepartmentContent>
                                    <Code>dataset:-208.department_code</Code>
                                    <GenerationNo></GenerationNo>
                                </DepartmentContent>
                                <DoctorContent>
                                    <Code>dataset:-208.indicate_staff_code</Code>
                                    <GenerationNo></GenerationNo>
                                </DoctorContent>
                                <BloodMethodContent>
                                    <Code>dataset:-207.hospital_treatment_cd</Code>
                                    <GenerationNo></GenerationNo>
                                </BloodMethodContent>
                                <DialysisDetailContentList>
                                    <DialysisDetailContent _sqlCode="-209">
                                        <DetailSeq>dataset:-209.seq_no</DetailSeq>
                                        <FunctionID>dataset:-209.function_id</FunctionID>
                                        <ItemContent>
                                            <Code>dataset:-209.item_code</Code>
                                            <GenerationNo></GenerationNo>
                                        </ItemContent>
                                        <QuantityContent>
                                            <Quantity>dataset:-209.quantity</Quantity>
                                            <UnitCode>dataset:-209.unit_code</UnitCode>
                                            <UnitCodeGenerationNo></UnitCodeGenerationNo>
                                        </QuantityContent>
                                    </DialysisDetailContent>
                                </DialysisDetailContentList>
                            </DialysisIndicationContent>
                        </ExternalDialysisIndication>
                    </Contents>
                </Request>
            </requestData>
        </Request>
    </soap:Body>
</soap:Envelope>', '{"soap": {"xmlEncoding": "utf-8"}, "dataset": [{"ordNo": "ordNo", "sqlCode": -207}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -208, "facilityCd": "facilityCd"}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -209, "facilityCd": "facilityCd"}, {"sqlCode": -1003, "facilityCd": "facilityCd"}, {"ctlNo": "ctlNo", "sqlCode": -1004}]}', '1', '0', -1, '2021-12-20 09:00:00', '2021-12-20 09:00:00');
INSERT INTO "mst_coop_layout"("ctl_no", "facility_cd", "coop_cd", "coop_cd_index", "direction", "coop_cd_sub", "coop_format", "coop_name", "coop_vender", "description", "is_editable", "coop_setting", "coop_ext_setting", "is_disp", "is_del", "user_id", "reg_date", "up_date") VALUES (-7020003, 'NEC-iS', 'ind_dial', '', 'S', 'del', 'xml', 'NEC-iS 予約情報連携', 'NEC-iS(MegaOakiS)', '予約情報連携', '1', '<soap:Envelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <Request
            xmlns="http://medical.nec.co.jp/">
            <requestData>
                <Request>
                    <Header>
                        <Command>B01_RegistDialysisIndicationFromDialysis</Command>
                        <Type>REGIST</Type>
                        <Conditions>
                            <Condition>
                                <FunctionId>3</FunctionId>
                                <PatientId>dataset:-1004.hosp_pat_id10</PatientId>
                                <StaffCode>dataset:-207.up_ind_user_id</StaffCode>
                                <DepartmentCode>dataset:-208.department_code</DepartmentCode>
                                <IndicateStaffCode>dataset:-208.indicate_staff_code</IndicateStaffCode>
                                <IsWarningMessageCancel>1</IsWarningMessageCancel>
                            </Condition>
                        </Conditions>
                        <RequesterInfomation>
                            <EventDateTime>$SYSDATE yyyy/MM/dd HH:mm:ss</EventDateTime>
                            <UserId></UserId>
                            <UserName></UserName>
                            <ProfessionCode></ProfessionCode>
                            <ProfessionName></ProfessionName>
                            <DepartmentCode></DepartmentCode>
                            <DepartmentName></DepartmentName>
                            <SystemIdTypeCode>4</SystemIdTypeCode>
                            <SystemId>dataset:-1003.system_id</SystemId>
                            <ComputerIdTypeCode></ComputerIdTypeCode>
                            <ComputerId></ComputerId>
                            <ApplicationName></ApplicationName>
                        </RequesterInfomation>
                    </Header>
                    <Contents>
                        <ExternalDialysisIndication>
                            <PatientContent>
                                <PatientNo>dataset:-1004.hosp_pat_id10</PatientNo>
                            </PatientContent>
                            <DialysisIndicationContent>
                                <IndicateOrderNo>$JOURNAL.ord_no</IndicateOrderNo>
                                <ExecuteOrderNo></ExecuteOrderNo>
                                <StartDate>dataset:-207.start_date</StartDate>
                                <StartTime>dataset:-207.start_time</StartTime>
                                <EndDate>dataset:-207.end_date</EndDate>
                                <EndTime>dataset:-207.end_time</EndTime>
                                <AppointmentBedTimeKbn></AppointmentBedTimeKbn>
                                <DialysisIntroductionDate>dataset:-207.dialysis_start_date</DialysisIntroductionDate>
                                <DialysisPlace>dataset:-207.hospital_bed_cd</DialysisPlace>
                                <UpdateDate>dataset:-207.update_date</UpdateDate>
                                <UpdateTime>dataset:-207.update_time</UpdateTime>
                                <UpdateTerminal>dataset:-1003.update_terminal</UpdateTerminal>
                                <UpdateOperator>dataset:-207.up_ind_user_id</UpdateOperator>
                                <UpdateOperatorGenerationNo></UpdateOperatorGenerationNo>
                                <DepartmentContent>
                                    <Code>dataset:-208.department_code</Code>
                                    <GenerationNo></GenerationNo>
                                </DepartmentContent>
                                <DoctorContent>
                                    <Code>dataset:-208.indicate_staff_code</Code>
                                    <GenerationNo></GenerationNo>
                                </DoctorContent>
                                <BloodMethodContent>
                                    <Code>dataset:-207.hospital_treatment_cd</Code>
                                    <GenerationNo></GenerationNo>
                                </BloodMethodContent>
                                <DialysisDetailContentList>
                                    <DialysisDetailContent>
                                        <DetailSeq></DetailSeq>
                                        <FunctionID></FunctionID>
                                        <ItemContent>
                                            <Code></Code>
                                            <GenerationNo></GenerationNo>
                                        </ItemContent>
                                        <QuantityContent>
                                            <Quantity></Quantity>
                                            <UnitCode></UnitCode>
                                            <UnitCodeGenerationNo></UnitCodeGenerationNo>
                                        </QuantityContent>
                                    </DialysisDetailContent>
                                </DialysisDetailContentList>
                            </DialysisIndicationContent>
                        </ExternalDialysisIndication>
                    </Contents>
                </Request>
            </requestData>
        </Request>
    </soap:Body>
</soap:Envelope>', '{"soap": {"xmlEncoding": "utf-8"}, "dataset": [{"ordNo": "ordNo", "sqlCode": -207}, {"ordNo": "ordNo", "patId": "patId", "sqlCode": -208, "facilityCd": "facilityCd"}, {"sqlCode": -1003, "facilityCd": "facilityCd"}, {"ctlNo": "ctlNo", "sqlCode": -1004}]}', '1', '0', -1, '2021-12-20 09:00:00', '2021-12-20 09:00:00');
