insert into ntss.sys_data_list_detail(data_list_detail_cd,disp_order,category_cd,master_display_name,master_display_type,master_display_sql,function_display_name,function_display_type,function_display_sql,data_set,cell_display) values (1441,8,9,'クール未確定','2',null,'クール未確定治療予定件数','2',null,'[{"param": "count", "sql_cd": -11046}]','[count] 件');
insert into ntss.sys_data_list_detail(data_list_detail_cd,disp_order,category_cd,master_display_name,master_display_type,master_display_sql,function_display_name,function_display_type,function_display_sql,data_set,cell_display) values (1442,8,10,'クール未確定','2',null,'クール未確定治療実績件数','2',null,'[{"param": "count", "sql_cd": -11047}]','[count] 件');
insert into ntss.sys_data_list_detail(data_list_detail_cd,disp_order,category_cd,master_display_name,master_display_type,master_display_sql,function_display_name,function_display_type,function_display_sql,data_set,cell_display) values (1443,8,21,'クール未確定','2',null,'クール未確定治療予定件数','2',null,'[{"param": "count", "sql_cd": -11046}]','[count] 件');
insert into ntss.sys_data_list_detail(data_list_detail_cd,disp_order,category_cd,master_display_name,master_display_type,master_display_sql,function_display_name,function_display_type,function_display_sql,data_set,cell_display) values (1444,8,22,'クール未確定','2',null,'クール未確定治療実績件数','2',null,'[{"param": "count", "sql_cd": -11047}]','[count] 件');

insert into ntss.sys_data_set(sql_cd,"sql",db_class,detail,can_repeat,use_application,report_class,memo,reg_date,up_date,pre_sql_info) values (-11046,'select count(*) from ord_main 
where treat_date between @dateFrom and @dateTo and facility_cd = @facilityCd and (ind_kur_cd is null or ind_kur_cd = 0) AND is_del = ''0'' and rst_dialysis_state = ''0''',2,'[]','0','{"applications": []}','{"classes": []}','データリスト','2020/07/31 18:29:49','2020/07/31 18:29:49',null);
insert into ntss.sys_data_set(sql_cd,"sql",db_class,detail,can_repeat,use_application,report_class,memo,reg_date,up_date,pre_sql_info) values (-11047,'select count(*) from ord_main 
where rst_dialysis_state = ''6'' AND treat_date between @dateFrom and @dateTo and facility_cd = @facilityCd and (rst_kur_cd is null or rst_kur_cd = 0) AND is_del = ''0''',2,'[]','0','{"applications": []}','{"classes": []}','データリスト','2020/07/31 18:29:49','2020/07/31 18:29:49',null);

