-- DELETE (by ctl_no) + INSERT (rows for facility_cd = 'Secom')

DELETE FROM ntss.mst_coop_layout WHERE facility_cd::text = 'Secom' AND ctl_no::text IN ('-11040013','-11040015','-11070000','-11070001','-11100000','-11100002','-11110000','-11110001');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11040013','Secom','ind_dial','','S','cre','csv','セコム連携_透析指示連携','Secom','透析指示連携（rootレイアウト）','1','<root name="透析指⽰電文" useSharedSysdate="true">
<file name="予約受付" detail="res_top_cre" sqlCode="-1102006"/>
<file name="処置依頼" detail="trt_top_cre" sqlCode="-1100011"/>
<file name="注射依頼" detail="inj_top_cre" sqlCode="-1102032"/>
<file name="カルテ記録" detail="med_top_cre" sqlCode="-1100010"/>
</root>
','{"dataset": [{"crud": "cre", "key0": "key0", "key1": "SCM_DIALYSISSCHESEND", "key2": "SCHE_FILE_NAME", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "ind_dial", "sqlCode": -1102006, "fileKind": "schedule", "facilityCd": "facilityCd", "file_extension": "csv"}, {"key0": "key0", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1100011, "facilityCd": "facilityCd"}, {"key0": "key0", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1102032, "facilityCd": "facilityCd"}, {"crud": "cre", "key0": "key0", "key1": "SCM_DIALYSISSCHESEND", "key2": "KARTE_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "ind_dial", "sqlCode": -1100010, "fileKind": "medical", "facilityCd": "facilityCd", "file_extension": "txt"}]}'::jsonb,'1','0','-1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11040015','Secom','ind_dial','','S','del','csv','セコム連携_透析指示連携','Secom','透析指示連携（rootレイアウト）','1','<root name="透析指⽰電文" useSharedSysdate="true">
<file name="予約受付" detail="res_top_del" sqlCode="-1102006"/>
<file name="処置依頼" detail="trt_top_del" sqlCode="-1100011"/>
<file name="注射依頼" detail="inj_top_del" sqlCode="-1102033"/>
<file name="カルテ記録" detail="med_top_del" sqlCode="-1100010"/>
</root>
','{"dataset": [{"crud": "del", "key0": "key0", "key1": "SCM_DIALYSISSCHESEND", "key2": "SCHE_FILE_NAME", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "ind_dial", "sqlCode": -1102006, "fileKind": "schedule", "facilityCd": "facilityCd", "file_extension": "csv"}, {"key0": "key0", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1100011, "facilityCd": "facilityCd"}, {"key0": "key0", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "ind_dial", "sqlCode": -1102033, "facilityCd": "facilityCd", "fileSubKind": "inj_item"}, {"crud": "del", "key0": "key0", "key1": "SCM_DIALYSISSCHESEND", "key2": "KARTE_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "ind_dial", "sqlCode": -1100010, "fileKind": "medical", "facilityCd": "facilityCd", "file_extension": "txt"}]}'::jsonb,'1','0','-1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11070000','Secom','rst_dial','','S','cre','csv','セコム連携_透析実績連携','Secom','透析実績連携（rootレイアウト）','1','<root name="透析実績電文" useSharedSysdate="true">
<file name="処置実績" detail="trt_top_cre" sqlCode="-1103014"/>
<file name="注射実績" detail="inj_top_cre" sqlCode="-1103004"/>
<file name="カルテ記録" detail="med_top_cre" sqlCode="-1100010"/>
</root>','{"dataset": [{"key0": "key0", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1103014, "facilityCd": "facilityCd"}, {"key0": "key0", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1103004, "facilityCd": "facilityCd"}, {"crud": "cre", "key0": "key0", "key1": "SCM_DIALYSISSEND", "key2": "KARTE_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rst_dial", "sqlCode": -1100010, "fileKind": "medical", "facilityCd": "facilityCd", "file_extension": "txt"}]}'::jsonb,'1','0','5843',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11070001','Secom','rst_dial','','S','del','csv','セコム連携_透析実績連携','Secom','透析実績連携（rootレイアウト）','1','<root name="透析実績電文" useSharedSysdate="true">
<file name="処置実績" detail="trt_top_del" sqlCode="-1103017"/>
<file name="注射実績" detail="inj_top_del" sqlCode="-1103018"/>
<file name="カルテ記録" detail="med_top_del" sqlCode="-1100010"/>
<file name="注射中止" detail="inj_cancel_top_del" sqlCode="-1103013"/>
</root>
','{"dataset": [{"key0": "key0", "ordNo": "ord_no", "patId": "pat_id", "coopCd": "rst_dial", "sqlCode": -1103017, "facilityCd": "facility_cd", "fileSubKind": "trt_item"}, {"crud": "del", "key0": "key0", "ctlNo": "ctl_no", "ordNo": "ord_no", "patId": "pat_id", "coopCd": "rst_dial", "sqlCode": -1103018, "facilityCd": "facility_cd", "fileSubKind": "inj_index"}, {"crud": "del", "key0": "key0", "key1": "SCM_DIALYSISSEND", "key2": "KARTE_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rst_dial", "sqlCode": -1100010, "fileKind": "medical", "facilityCd": "facilityCd", "file_extension": "txt"}, {"crud": "del", "key0": "key0", "ctlNo": "ctl_no", "ordNo": "ord_no", "patId": "pat_id", "coopCd": "rst_dial", "sqlCode": -1103013, "facilityCd": "facility_cd", "fileSubKind": "inj_index"}]}'::jsonb,'1','0','-1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11100000','Secom','exam_ord','','S','cre','csv','セコム連携_検体検査オーダ連携','Secom','検体検査オーダ連携（検体検査オーダファイル）','1','<root name="透析指⽰電文" useSharedSysdate="true">
<file name="オーダーインデックス" detail="exam_idx_cre" sqlCode="-1105008"/>
<file name="検体検査" detail="exam_item_cre" sqlCode="-1105009"/>
<file name="検体検査依頼ファイル作成終了" detail="exam_finish" sqlCode="-1105010"/>
</root>
','{"dataset": [{"crud": "cre", "key0": "key0", "key1": "SCM_EXAM_ORDER_SEND", "key2": "EXAM_IDX_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "exam_ord", "sqlCode": -1105008, "fileKind": "examind", "facilityCd": "facilityCd", "file_extension": "txt"}, {"crud": "cre", "key0": "key0", "key1": "SCM_EXAM_ORDER_SEND", "key2": "EXAM_KEN_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "exam_ord", "sqlCode": -1105009, "fileKind": "examsken", "facilityCd": "facilityCd", "file_extension": "txt"}, {"key0": "key0", "key1": "SCM_EXAM_ORDER_SEND", "key2": "NULL", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1105010, "fileKind": "null", "facilityCd": "facilityCd", "file_extension": "txt"}]}'::jsonb,'1','0','-1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11100002','Secom','exam_ord','','S','del','csv','セコム連携_検体検査オーダ連携','Secom','検体検査オーダ連携（検体検査オーダファイル_オーダーインデックス）','1','<root name="透析指⽰電文" useSharedSysdate="true">
<file name="オーダーインデックス" detail="exam_idx_del" sqlCode="-1105008"/>
<file name="検体検査" detail="exam_item_del" sqlCode="-1105009"/>
<file name="検体検査依頼ファイル作成終了" detail="exam_finish" sqlCode="-1105010"/>
</root>','{"dataset": [{"crud": "del", "key0": "key0", "key1": "SCM_EXAM_ORDER_SEND", "key2": "EXAM_IDX_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "exam_ord", "sqlCode": -1105008, "fileKind": "examind", "facilityCd": "facilityCd", "file_extension": "txt"}, {"crud": "del", "key0": "key0", "key1": "SCM_EXAM_ORDER_SEND", "key2": "EXAM_KEN_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "exam_ord", "sqlCode": -1105009, "fileKind": "examsken", "facilityCd": "facilityCd", "file_extension": "txt"}, {"key0": "key0", "key1": "SCM_EXAM_ORDER_SEND", "key2": "NULL", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1105010, "fileKind": "null", "facilityCd": "facilityCd", "file_extension": "txt"}]}'::jsonb,'1','0','-1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11110000','Secom','rad_ord','','S','cre','csv','セコム連携_放射線オーダー連携','Secom','放射線オーダー（rootレイアウト）','1','<root name="放射線オーダー電文" useSharedSysdate="true">
<file name="オーダーインデックス" detail="idx_top_cre" sqlCode="-1106001"/>
<file name="処方ヘッダー" detail="head_top_cre" sqlCode="-1106002"/>
<file name="実施単位" detail="ipn_top_cre" sqlCode="-1106003"/>
<file name="画像依頼ファイル作成終了" detail="rad_finish" sqlCode="-1106004"/>
</root>
','{"dataset": [{"ordNo": "ordNo", "patId": "patId", "sqlCode": -1106009, "facilityCd": "facilityCd", "is_zero_end": "true"}, {"crud": "cre", "key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "XRAY_IDX_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rad_ord", "sqlCode": -1106001, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}, {"crud": "cre", "key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "XRAY_HEAD_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rad_ord", "sqlCode": -1106002, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}, {"crud": "cre", "key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "XRAY_IPN_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rad_ord", "sqlCode": -1106003, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}, {"key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "NULL", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1106004, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}]}'::jsonb,'1','0','-1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
INSERT INTO ntss.mst_coop_layout(ctl_no,facility_cd,coop_cd,coop_cd_index,direction,coop_cd_sub,coop_format,coop_name,coop_vender,description,is_editable,coop_setting,coop_ext_setting,is_disp,is_del,user_id,reg_date,up_date,coop_version) VALUES ('-11110001','Secom','rad_ord','','S','del','csv','セコム連携_放射線オーダー連携','Secom','放射線オーダー（rootレイアウト）','1','<root name="放射線オーダー電文" useSharedSysdate="true">
<file name="オーダーインデックス" detail="idx_top_del" sqlCode="-1106001"/>
<file name="処方ヘッダー" detail="head_top_del" sqlCode="-1106002"/>
<file name="実施単位" detail="ipn_top_del" sqlCode="-1106003"/>
<file name="画像依頼ファイル作成終了" detail="rad_finish" sqlCode="-1106004"/>
</root>
','{"dataset": [{"crud": "del", "key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "XRAY_IDX_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rad_ord", "sqlCode": -1106001, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}, {"crud": "del", "key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "XRAY_HEAD_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rad_ord", "sqlCode": -1106002, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}, {"crud": "del", "key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "XRAY_IPN_FILE_STR", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "coopCd": "rad_ord", "sqlCode": -1106003, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}, {"key0": "key0", "key1": "SCM_XRAY_ORDER_SEND", "key2": "NULL", "time": "$SHARED_SYSDATE:yyyy/MM/dd HH:mm:ss", "ctlNo": "ctlNo", "ordNo": "ordNo", "patId": "patId", "sqlCode": -1106004, "fileKind": "xray", "facilityCd": "facilityCd", "file_extension": "txt"}]}'::jsonb,'1','0','-1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Secom');
