--INSERT INTO ntss.sys_data_set
--(sql_cd, "sql", db_class, detail, can_repeat, use_application, report_class, memo, reg_date, up_date, pre_sql_info)
--VALUES(-600300, 'WITH user_map AS (
--SELECT user_id, disp_user_id
--FROM mst_user_authentication mua
--WHERE facility_cd = @facilityCd
--)
--SELECT jsonb_agg(user_map)::text AS user_list
--FROM user_map', 1, '[{}]'::jsonb, '0', '{"applications": [4]}'::jsonb, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
--