plugins {
    id 'org.springframework.boot' version '4.0.7'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id 'application'
}

group = 'batch'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

bootJar {
    mainClass = 'web.BatchServerApplication'
}

// mongo切替用profileの設定
if (project.hasProperty('mongo')) {
    bootRun {
        jvmArgs = ['-Dspring.profiles.active=mongo']
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

configurations.all {
    exclude group: 'org.apache.logging.log4j', module: 'log4j-to-slf4j'
    exclude group: 'org.apache.logging.log4j', module: 'log4j-api'
    exclude group: 'org.slf4j', module: 'slf4j-log4j12'
    exclude group: 'log4j', module: 'log4j'
}

repositories {
    mavenLocal()
    mavenCentral()
}

ext {
    set('springBootAdminVersion', '4.0.4')
}

dependencies {
    implementation 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-batch-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation "de.codecentric:spring-boot-admin-starter-client:${springBootAdminVersion}"
    implementation "de.codecentric:spring-boot-admin-starter-server:${springBootAdminVersion}"
    implementation 'net.lingala.zip4j:zip4j:2.11.6'
    compileOnly 'org.projectlombok:lombok:1.18.46'
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.5'
    runtimeOnly 'org.glassfish.jaxb:jaxb-runtime:4.0.8'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
        implementation platform('software.amazon.awssdk:bom:2.44.4')
    implementation 'software.amazon.awssdk:auth'
    implementation 'software.amazon.awssdk:regions'
    implementation 'software.amazon.awssdk:url-connection-client'
    implementation('software.amazon.awssdk:s3') {
        exclude group: 'software.amazon.awssdk', module: 'apache-client'
    }
    implementation 'org.seasar.doma.boot:doma-spring-boot-starter:3.0.0'
    implementation 'org.seasar.doma:doma-core:3.14.0'
    implementation 'org.json:json:20251224'
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.aspectj:aspectjweaver'
    implementation 'de.siegmar:fastcsv:4.2.0'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
        implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}

ext {
    javaMainClass = 'web.BatchServerApplication'
}

application {
    mainClass = javaMainClass
    applicationDefaultJvmArgs = ["-Dspring.profiles.active=${project.gradle.startParameter.systemPropertiesArgs['spring.profiles.active']}"]
}

bootRun {
    if (project.hasProperty('args')) {
        args project.args.split(',' as Closure)
    }
}

jar {
    enabled = false
    manifest {
        attributes 'Main-Class': 'web.BatchServerApplication'
    }
}

javadoc {
    options.charSet = 'UTF-8'
    options.encoding = 'UTF-8'
    failOnError = false
}
tasks.withType(JavaCompile).configureEach {
    options.fork = true
}
