flyway.user=nkk6
flyway.password=nkk6
flyway.url=jdbc:postgresql://172.16.80.64:5432/ntss_db6
flyway.locations=filesystem:ntss-core/src/main/resources/db6/migration,filesystem:ntss-core/src/main/resources/db6/testdata
flyway.schemas=ntss
