-- ----------------------------
-- Table structure for V_CHANGE_HST
-- ----------------------------
DROP TABLE "V_CHANGE_HST";
  CREATE TABLE "V_CHANGE_HST" 
   (	"PATID" CHAR(12 BYTE), 
	"NAME" VARCHAR2(40 BYTE), 
	"OCCUR_DATE" DATE, 
	"LOG_TYPE1" CHAR(2 BYTE), 
	"LOG_TYPE2" CHAR(2 BYTE), 
	"DIALYSIS_NO" NUMBER, 
	"LOG_CHANGE" VARCHAR2(2048 BYTE), 
	"LOG_REASON" VARCHAR2(1024 BYTE), 
	"STAFF_CD" CHAR(10 BYTE)
   );

   COMMENT ON TABLE "FNSIVIEW"."V_CHANGE_HST"  IS '変更履歴';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."NAME" IS '氏名';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."OCCUR_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."LOG_TYPE1" IS '変更内容区分１';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."LOG_TYPE2" IS '変更内容区分２';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."DIALYSIS_NO" IS '透析番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."LOG_CHANGE" IS '変更内容';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."LOG_REASON" IS '変更理由';
   COMMENT ON COLUMN "FNSIVIEW"."V_CHANGE_HST"."STAFF_CD" IS 'スタッフコード';
