-- ----------------------------
-- Table structure for V_PAT_RECIPE
-- ----------------------------
DROP TABLE "V_PAT_RECIPE";
  CREATE TABLE "V_PAT_RECIPE" 
   (	"PATID" CHAR(12 BYTE), 
	"PRESCRIPT_NO" NUMBER, 
	"UP_DATE" DATE, 
	"EXECUTE_DATE" CHAR(8 BYTE), 
	"CTL_NO" CHAR(3 BYTE), 
	"MEDICINE_NAME" VARCHAR2(80 BYTE), 
	"MEDICINE_CD" CHAR(20 BYTE), 
	"MEDICINE_CD2" CHAR(20 BYTE), 
	"QUANTITY" NUMBER, 
	"UNIT" VARCHAR2(20 BYTE), 
	"DOSAGE" NUMBER, 
	"TAKE_MEDICINE_CD" CHAR(3 BYTE), 
	"TAKE_MEDICINE_NAME" VARCHAR2(40 BYTE), 
	"DAY_COUNT" NUMBER, 
	"PRESCRIPTER_CD" CHAR(10 BYTE), 
	"PRESCRIPTER_NAME" VARCHAR2(20 BYTE), 
	"NOTE" VARCHAR2(1024 BYTE)
   );

   COMMENT ON TABLE "V_PAT_RECIPE"  IS '処方情報';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."PRESCRIPT_NO" IS '処方番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."EXECUTE_DATE" IS '交付日';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."CTL_NO" IS '項目番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."MEDICINE_NAME" IS '薬剤名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."MEDICINE_CD" IS '薬剤コード(院内コード1)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."MEDICINE_CD2" IS '薬剤コード(院内コード2)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."QUANTITY" IS '分量';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."UNIT" IS '単位';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."DOSAGE" IS '用量';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."TAKE_MEDICINE_CD" IS '用法コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."TAKE_MEDICINE_NAME" IS '用法名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."DAY_COUNT" IS '調剤日数';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."PRESCRIPTER_CD" IS '処方者コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."PRESCRIPTER_NAME" IS '処方者名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_RECIPE"."NOTE" IS '備考';
