-- ----------------------------
-- Table structure for V_PAT_FREE_COMMENT
-- ----------------------------
DROP TABLE "V_PAT_FREE_COMMENT";
  CREATE TABLE "V_PAT_FREE_COMMENT" 
   (	"PATID" CHAR(12 BYTE), 
	"CTL_NO" NUMBER(2,0), 
	"TITLE" VARCHAR2(80 BYTE), 
	"CONTENT" VARCHAR2(3500 BYTE)
   );

   COMMENT ON TABLE "V_PAT_FREE_COMMENT"  IS '患者フリーコメント';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_FREE_COMMENT"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_FREE_COMMENT"."CTL_NO" IS '管理番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_FREE_COMMENT"."TITLE" IS 'タイトル';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_FREE_COMMENT"."CONTENT" IS '内容';
