-- ----------------------------
-- Table structure for V_PAT_CONTACT
-- ----------------------------
DROP TABLE "V_PAT_CONTACT";
  CREATE TABLE "V_PAT_CONTACT" 
   (	"PATID" CHAR(12 BYTE), 
	"NAME" VARCHAR2(40 BYTE), 
	"CTL_NO" NUMBER, 
	"UP_DATE" DATE, 
	"REG_DATE" DATE, 
	"RELATION_NAME" VARCHAR2(50 BYTE), 
	"RNAME" CHAR(40 BYTE), 
	"ZIPCODE" CHAR(8 BYTE), 
	"ADDRESS" VARCHAR2(256 BYTE), 
	"ADDRESS_DETAIL" VARCHAR2(256 BYTE), 
	"TELNO1" CHAR(25 BYTE), 
	"TELNO2" CHAR(25 BYTE), 
	"MEMO" VARCHAR2(2048 BYTE)
   );

   COMMENT ON TABLE "V_PAT_CONTACT"  IS '患者連絡先情報';
   COMMENT ON COLUMN "FNSIVIEW"."V_ONL_RST_RECEIPT_MEMO"."IN_HOSPITAL_CD2" IS '院内コード２';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."NAME" IS '氏名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."CTL_NO" IS '管理番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."REG_DATE" IS '登録日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."RELATION_NAME" IS '続柄';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."RNAME" IS '連絡先氏名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."ZIPCODE" IS '郵便番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."ADDRESS" IS '住所(市町村）';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."ADDRESS_DETAIL" IS '住所(番地アパート）';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."TELNO1" IS '電話番号１';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."TELNO2" IS '電話番号２';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_CONTACT"."MEMO" IS 'メモ';
