-- ----------------------------
-- Table structure for V_PAT_EXAMIN_SCH
-- ----------------------------
DROP TABLE "V_PAT_EXAMIN_SCH";
  CREATE TABLE "V_PAT_EXAMIN_SCH" 
   (	"PATID" CHAR(12 BYTE), 
	"UP_DATE" DATE, 
	"EXAM_DATE" CHAR(8 BYTE), 
	"EXAM_TIME" VARCHAR2(4 BYTE), 
	"EXAM_SET_CD" CHAR(20 BYTE), 
	"EXAM_SET_NAME" VARCHAR2(40 BYTE), 
	"EXAM_DIVISION" CHAR(1 BYTE), 
	"EXAM_PROC_CD" CHAR(1 BYTE), 
	"DOCTOR_CODE" CHAR(10 BYTE), 
	"DOCTOR_NAME" VARCHAR2(20 BYTE), 
	"ORDER_STAFF" CHAR(10 BYTE), 
	"ORDER_NAME" VARCHAR2(20 BYTE), 
	"UPDATE_CODE" CHAR(10 BYTE), 
	"UPDATE_NAME" VARCHAR2(20 BYTE),
   "EXAM_NO" NUMBER(20,0)
   );

   COMMENT ON TABLE "V_PAT_EXAMIN_SCH"  IS '検査予定';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."EXAM_DATE" IS '検査予定日';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."EXAM_TIME" IS '検査予定時刻';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."EXAM_SET_CD" IS '検査セットNo(院内コード)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."EXAM_SET_NAME" IS '検査セット名称';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."EXAM_DIVISION" IS '検査予定区分';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."EXAM_PROC_CD" IS '検査実施予定コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."DOCTOR_CODE" IS '指示者';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."DOCTOR_NAME" IS '指示者名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."ORDER_STAFF" IS 'オーダー入力者';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."ORDER_NAME" IS 'オーダ入力者名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."UPDATE_CODE" IS '更新者';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."UPDATE_NAME" IS '更新者名';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_EXAMIN_SCH"."EXAM_NO" IS '依頼番号';
