-- ----------------------------
-- Table structure for V_PAT_REVISE_OFFWATER
-- ----------------------------
DROP TABLE "V_PAT_REVISE_OFFWATER";
  CREATE TABLE "V_PAT_REVISE_OFFWATER" 
   (	"PATID" CHAR(12 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"CTL_NO" NUMBER(3,0), 
	"UP_DATE" DATE, 
	"REVISE_NAME" VARCHAR2(512 BYTE), 
	"REVISE_WEIGHT" NUMBER, 
	"MON_UP_DATE" DATE, 
	"MON_REVISE_NAME" VARCHAR2(512 BYTE), 
	"MON_REVISE_WEIGHT" NUMBER, 
	"TUE_UP_DATE" DATE, 
	"TUE_REVISE_NAME" VARCHAR2(512 BYTE), 
	"TUE_REVISE_WEIGHT" NUMBER, 
	"WED_UP_DATE" DATE, 
	"WED_REVISE_NAME" VARCHAR2(512 BYTE), 
	"WED_REVISE_WEIGHT" NUMBER, 
	"THU_UP_DATE" DATE, 
	"THU_REVISE_NAME" VARCHAR2(512 BYTE), 
	"THU_REVISE_WEIGHT" NUMBER, 
	"FRI_UP_DATE" DATE, 
	"FRI_REVISE_NAME" VARCHAR2(512 BYTE), 
	"FRI_REVISE_WEIGHT" NUMBER, 
	"SAT_UP_DATE" DATE, 
	"SAT_REVISE_NAME" VARCHAR2(512 BYTE), 
	"SAT_REVISE_WEIGHT" NUMBER, 
	"SUN_UP_DATE" DATE, 
	"SUN_REVISE_NAME" VARCHAR2(512 BYTE), 
	"SUN_REVISE_WEIGHT" NUMBER
   );

   COMMENT ON TABLE "V_PAT_REVISE_OFFWATER"  IS 'Š³ŽÒœ…—Êî•ñ';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."PATID" IS 'Š³ŽÒID';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."NAME" IS 'Ž–¼';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."CTL_NO" IS 'ŠÇ—”Ô†';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."UP_DATE" IS 'XV“úŽž(“–“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."REVISE_NAME" IS 'œ…•â³–¼(“–“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."REVISE_WEIGHT" IS 'd—Ê(“–“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."MON_UP_DATE" IS 'XV“úŽž(ŒŽ—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."MON_REVISE_NAME" IS 'œ…•â³–¼(ŒŽ—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."MON_REVISE_WEIGHT" IS 'd—Ê(ŒŽ—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."TUE_UP_DATE" IS 'XV“úŽž(‰Î—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."TUE_REVISE_NAME" IS 'œ…•â³–¼(‰Î—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."TUE_REVISE_WEIGHT" IS 'd—Ê(‰Î—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."WED_UP_DATE" IS 'XV“úŽž(…—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."WED_REVISE_NAME" IS 'œ…•â³–¼(…—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."WED_REVISE_WEIGHT" IS 'd—Ê(…—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."THU_UP_DATE" IS 'XV“úŽž(–Ø—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."THU_REVISE_NAME" IS 'œ…•â³–¼(–Ø—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."THU_REVISE_WEIGHT" IS 'd—Ê(–Ø—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."FRI_UP_DATE" IS 'XV“úŽž(‹à—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."FRI_REVISE_NAME" IS 'œ…•â³–¼(‹à—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."FRI_REVISE_WEIGHT" IS 'd—Ê(‹à—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."SAT_UP_DATE" IS 'XV“úŽž(“y—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."SAT_REVISE_NAME" IS 'œ…•â³–¼(“y—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."SAT_REVISE_WEIGHT" IS 'd—Ê(“y—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."SUN_UP_DATE" IS 'XV“úŽž(“ú—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."SUN_REVISE_NAME" IS 'œ…•â³–¼(“ú—j“ú)';
   COMMENT ON COLUMN "FNSIVIEW"."V_PAT_REVISE_OFFWATER"."SUN_REVISE_WEIGHT" IS 'd—Ê(“ú—j“ú)';
