-- ----------------------------
-- Table structure for V_RST_DIALYSIS_MEDI_CARD
-- ----------------------------
DROP TABLE "V_RST_DIALYSIS_MEDI_CARD";
  CREATE TABLE "V_RST_DIALYSIS_MEDI_CARD" 
   (	"PATID" CHAR(12 BYTE), 
	"DIALYSIS_DATE" VARCHAR2(8 BYTE), 
	"DIALYSIS_NO" NUMBER, 
	"CTL_NO" CHAR(7 BYTE), 
	"UP_DATE" DATE, 
	"MEDICINE_CD" CHAR(20 BYTE), 
	"MEDICINE_CD2" CHAR(20 BYTE), 
	"MEDICINE_NAME" VARCHAR2(80 BYTE), 
	"MED_GENERAL_NAME" VARCHAR2(80 BYTE), 
	"MEDI_CLASS_NAME" VARCHAR2(40 BYTE), 
	"AMOUNT" NUMBER, 
	"UNIT" VARCHAR2(20 BYTE), 
	"EFFECT_FLG" CHAR(1 BYTE), 
	"EFFECT_DATE" DATE, 
	"TIMING_NAME" VARCHAR2(40 BYTE), 
	"PROCEDURE_CD" VARCHAR2(20 BYTE), 
	"PROCEDURE_CD2" VARCHAR2(20 BYTE), 
	"PROCEDURE_NAME" VARCHAR2(40 BYTE), 
	"STAFF_CD" CHAR(10 BYTE), 
	"STAFF_NAME" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(1024 BYTE)
   );

   COMMENT ON TABLE "V_RST_DIALYSIS_MEDI_CARD"  IS '投与薬剤実績(ロイコ式カード専用)';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."PATID" IS '患者ID';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."DIALYSIS_DATE" IS '透析日';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."DIALYSIS_NO" IS '透析番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."CTL_NO" IS '項目番号';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."UP_DATE" IS '更新日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."MEDICINE_CD" IS '薬剤コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."MEDICINE_CD2" IS '薬剤コード(院内コード1)';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."MEDICINE_NAME" IS '薬剤名';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."MED_GENERAL_NAME" IS '一般名';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."MEDI_CLASS_NAME" IS '薬剤分類名';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."AMOUNT" IS '数量';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."UNIT" IS '単位';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."EFFECT_FLG" IS '実施フラグ';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."EFFECT_DATE" IS '実施日時';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."TIMING_NAME" IS '投与時間帯名';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."PROCEDURE_CD" IS '手技コード(院内コード1)';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."PROCEDURE_CD2" IS '手技コード(院内コード2)';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."PROCEDURE_NAME" IS '手技名';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."STAFF_CD" IS '実施者コード';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."STAFF_NAME" IS '実施者名';
   COMMENT ON COLUMN "FNSIVIEW"."V_RST_DIALYSIS_MEDI_CARD"."COMMENTS" IS 'コメント';
