INSERT INTO SYNC_SYS_CHECKLIST( PATID, JOIN_ITEM_NUMBER, ITEM_NUMBER, LIST_CD, FUNK_FLG, CLASS_CD, UP_DATE, SERIES_CD )
  WITH MST_CHECKLIST_CORRECT_PK AS (
	SELECT
		MST.LIST_CD
		,DIALYSIS.PATID
		,MST.SERIES_CD
		,MAX( MST.UP_DATE ) UP_DATE
		,TO_CHAR( DIALYSIS.DIALYSIS_NO ) DIALYSIS_KEY 
	FROM
		SYS_CHECKLST_SETTING MST,
		(
	SELECT
		DIALYSIS.DIALYSIS_NO
		,DIALYSIS.PATID
		,DIALYSIS.UP_DATE 
	FROM RST_DIALYSIS DIALYSIS 
	WHERE
		{0}
		AND TO_CHAR(DIALYSIS.START_DATE, 'yyyyMMdd') BETWEEN :START_DATE AND :END_DATE 
		AND DIALYSIS.DEL_FLG = '0'
		AND DIALYSIS.SERIES_CD = '{4}'
	) DIALYSIS 
	WHERE
		MST.UP_DATE < DIALYSIS.UP_DATE 
		AND MST.SERIES_CD = '{4}'
	GROUP BY
		LIST_CD
		,SERIES_CD
		,DIALYSIS.DIALYSIS_NO
		,DIALYSIS.PATID
	UNION ALL
	SELECT
		MST.LIST_CD
		,DIALYSIS.PATID
		,MST.SERIES_CD
		,MST.UP_DATE UP_DATE
		,DIALYSIS.IND_ID DIALYSIS_KEY 
	FROM
		SYS_CHECKLST_SETTING MST,
		(
	SELECT DISTINCT
		DIALYSIS.IND_ID
		,DIALYSIS.PATID
		,RC.LIST_CD
		,RC.LIST_CD_UP_DATE 
	FROM
		SYNC_CHECKLIST_HIST rc 
		INNER JOIN SCH_DIALYSIS_PLAN DIALYSIS
		ON {0}
		AND RC.DIALYSIS_NO = - 1 
		AND DIALYSIS.PATID = RC.PATID 
		AND DIALYSIS.DIALYSIS_DATE = RC.DIALYSIS_DATE 
		AND DIALYSIS.BED_NO = RC.BED_NO 
		AND DIALYSIS.KUR_CD = RC.KUR_CD 
		AND DIALYSIS.DIALYSIS_DATE BETWEEN :START_DATE  AND :END_DATE
		and DIALYSIS.SERIES_CD='{4}'
	) DIALYSIS 
	WHERE
		MST.UP_DATE = DIALYSIS.LIST_CD_UP_DATE 
		AND MST.LIST_CD = DIALYSIS.LIST_CD 
		AND MST.SERIES_CD = '{4}'
	)
  ,MST_CHECKLIST_CONV AS (
	SELECT
		DIALYSIS_KEY
		,MST_PK.PATID
		,SYS.LIST_CD
		,SYS.UP_DATE
		,SYS.SERIES_CD
		,COUNT( 1 ) DIALYZER_FLG 
	FROM
		SYS_CHECKLST_SETTING SYS
		INNER JOIN MST_CHECKLIST_CORRECT_PK MST_PK
		ON MST_PK.LIST_CD = SYS.LIST_CD 
		AND MST_PK.UP_DATE = SYS.UP_DATE 
		AND MST_PK.SERIES_CD = SYS.SERIES_CD 
	WHERE
	   SYS.SERIES_CD = '{4}'　AND 
		(FUNK_FLAG_1 = '1' OR FUNK_FLAG_2 = '1' OR FUNK_FLAG_3 = '1' 
     OR FUNK_FLAG_4 = '1' OR FUNK_FLAG_5 = '1' OR FUNK_FLAG_6 = '1'
     OR FUNK_FLAG_7 = '1' OR FUNK_FLAG_8 = '1' OR FUNK_FLAG_9 = '1' 
     OR FUNK_FLAG_10 = '1')
    AND (
        CLASS_CD_1 IN ('008','009') OR CLASS_CD_2 IN ('008','009') 
        OR CLASS_CD_3 IN ('008','009') OR CLASS_CD_4 IN ('008','009')
        OR CLASS_CD_5 IN ('008','009') OR CLASS_CD_6 IN ('008','009')
        OR CLASS_CD_7 IN ('008','009') OR CLASS_CD_8 IN ('008','009')
        OR CLASS_CD_9 IN ('008','009') OR CLASS_CD_10 IN ('008','009')
    )
	GROUP BY
		SYS.SERIES_CD
		,SYS.LIST_CD
		,SYS.UP_DATE
		,DIALYSIS_KEY
		,MST_PK.PATID
	)
  ,CORRECT_CHECKLIST AS (
    SELECT DISTINCT
		A.LIST_CD
		,A.SERIES_CD
		,A.UP_DATE
		,FUNK_FLAG_1
		,FUNK_FLAG_2
		,FUNK_FLAG_3
		,FUNK_FLAG_4
		,FUNK_FLAG_5
		,FUNK_FLAG_6
		,FUNK_FLAG_7
		,FUNK_FLAG_8
		,FUNK_FLAG_9
		,FUNK_FLAG_10
		,LIST_ITEM_1
		,LIST_ITEM_2
		,LIST_ITEM_3
		,LIST_ITEM_4
		,LIST_ITEM_5
		,LIST_ITEM_6
		,LIST_ITEM_7
		,LIST_ITEM_8
		,LIST_ITEM_9
		,LIST_ITEM_10
		,CLASS_CD_1
		,CLASS_CD_2
		,CLASS_CD_3
		,CLASS_CD_4
		,CLASS_CD_5
		,CLASS_CD_6
		,CLASS_CD_7
		,CLASS_CD_8
		,CLASS_CD_9
		,CLASS_CD_10
		,DIALYSIS_PROG_CD
		,MST_PK.DIALYSIS_KEY
		,MST_PK.PATID
	FROM
		MST_CHECKLIST_CORRECT_PK MST_PK
		INNER JOIN SYS_CHECKLST_SETTING A ON MST_PK.LIST_CD = A.LIST_CD 
		AND MST_PK.SERIES_CD = A.SERIES_CD 
		AND MST_PK.UP_DATE = A.UP_DATE
		AND A.DEL_FLG = '0' AND  A.SERIES_CD='{4}'
  )
  ,MST_CHECKLIST AS (
	SELECT DISTINCT
		SYS_TMP.DIALYSIS_KEY
		,SYS_TMP.PATID
		,SYS_TMP.LIST_CD AS LIST_CD
		,SYS_TMP.ITEM_NUMBER
		,CASE WHEN SYS_TMP.FUNK_FLG = '2' AND SYS_TMP.CLASS_CD IN ( '001', '002', '201' ) THEN '1' ELSE SYS_TMP.FUNK_FLG END AS FUNK_FLG
		,CASE WHEN SYS_TMP.FUNK_FLG = '2' AND SYS_TMP.CLASS_CD IN ( '001', '002', '201' ) THEN '5' ELSE SYS_TMP.CLASS_CD END AS CLASS_CD
		,SYS_TMP.UP_DATE
		,SYS_TMP.SERIES_CD
	FROM (
		SELECT
			CC.LIST_CD
			,1 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_1 = '2' AND CLASS_CD_1 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_1 END AS FUNK_FLG
			,LIST_ITEM_1 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_1 = '2' AND CLASS_CD_1 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_1 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD
		UNION ALL
		SELECT
			CC.LIST_CD
			,2 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_2 = '2' AND CLASS_CD_2 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_2 END AS FUNK_FLG
			,LIST_ITEM_2 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_2 = '2' AND CLASS_CD_2 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_2 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD
		UNION ALL
		SELECT
			CC.LIST_CD
			,3 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_3 = '2' AND CLASS_CD_3 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_3 END AS FUNK_FLG
			,LIST_ITEM_3 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_3 = '2' AND CLASS_CD_3 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_3 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD 
		UNION ALL
		SELECT
			CC.LIST_CD
			,4 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_4 = '2' AND CLASS_CD_4 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_4 END AS FUNK_FLG
			,LIST_ITEM_4 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_4 = '2' AND CLASS_CD_4 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_4 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID 
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD
		UNION ALL
		SELECT
			CC.LIST_CD
			,5 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_5 = '2' AND CLASS_CD_5 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_5 END AS FUNK_FLG
			,LIST_ITEM_5 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_5 = '2' AND CLASS_CD_5 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_5 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD 
		UNION ALL
		SELECT
			CC.LIST_CD
			,6 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_6 = '2' AND CLASS_CD_6 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_6 END AS FUNK_FLG
			,LIST_ITEM_6 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_6 = '2' AND CLASS_CD_6 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_6 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID 
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD
		UNION ALL
		SELECT
			CC.LIST_CD
			,7 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_7 = '2' AND CLASS_CD_7 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_7 END AS FUNK_FLG
			,LIST_ITEM_7 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_7 = '2' AND CLASS_CD_7 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_7 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD 
		UNION ALL
		SELECT
			CC.LIST_CD
			,8 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_8 = '2' AND CLASS_CD_8 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_8 END AS FUNK_FLG
			,LIST_ITEM_8 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_8 = '2' AND CLASS_CD_8 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_8 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD 
		UNION ALL
		SELECT
			CC.LIST_CD
			,9 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_9 = '2' AND CLASS_CD_9 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_9 END AS FUNK_FLG
			,LIST_ITEM_9 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_9 = '2' AND CLASS_CD_9 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_9 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD 
		UNION ALL
		SELECT
			CC.LIST_CD
			,10 AS ITEM_NUMBER
			,CASE WHEN FUNK_FLAG_10 = '2' AND CLASS_CD_10 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE FUNK_FLAG_10 END AS FUNK_FLG
			,LIST_ITEM_10 AS LIST_ITEM
			,CASE WHEN FUNK_FLAG_10 = '2' AND CLASS_CD_10 IN ( '001', '002', '201' ) AND CONV.DIALYZER_FLG > 0 THEN NULL ELSE CLASS_CD_10 END AS CLASS_CD
			,CC.UP_DATE
			,CC.SERIES_CD
			,CC.DIALYSIS_PROG_CD
			,CC.DIALYSIS_KEY
			,CC.PATID
		FROM CORRECT_CHECKLIST CC
			LEFT JOIN MST_CHECKLIST_CONV CONV
				ON CC.LIST_CD = CONV.LIST_CD 
				AND CC.UP_DATE = CONV.UP_DATE 
				AND CC.SERIES_CD = CONV.SERIES_CD 
		) SYS_TMP
	)
SELECT DISTINCT
	PATID
	,LISTAGG ( ITEM_NUMBER, ',' ) WITHIN GROUP ( ORDER BY LIST_CD, UP_DATE, SERIES_CD, DIALYSIS_KEY, PATID ) AS JOIN_ITEM_NUMBER
	,MIN(ITEM_NUMBER) ITEM_NUMBER
	,LIST_CD
	,'1' FUNK_FLG
	,'5' CLASS_CD
	,UP_DATE
	,SERIES_CD 
	FROM
		MST_CHECKLIST 
	WHERE
		FUNK_FLG = '1' 
		AND CLASS_CD = '5' 
	GROUP BY
		LIST_CD
		,UP_DATE
		,SERIES_CD
		,DIALYSIS_KEY
		,PATID
UNION ALL
	SELECT DISTINCT
	PATID
	,'' JOIN_ITEM_NUMBER
	,ITEM_NUMBER
	,LIST_CD
	,CASE WHEN FUNK_FLG = '1' AND CLASS_CD IN ( '008', '009' ) THEN '1' ELSE FUNK_FLG END AS FUNK_FLG
	,CASE WHEN FUNK_FLG = '1' AND CLASS_CD = '008' THEN '5' WHEN FUNK_FLG = '1' AND CLASS_CD = '009' THEN '6' ELSE CLASS_CD END AS CLASS_CD
	,UP_DATE
	,SERIES_CD 
	FROM MST_CHECKLIST 
	WHERE ( FUNK_FLG || CLASS_CD ) != '15' 