INSERT INTO mst_dialyzer(
facility_cd,
fn_dialyzer_cd,
maker,
model_number,
dialyzer_type,
function_class,
area,
ufr,
koa,
material,
wetdry,
sterilization,
ufr_warning_max,
ufr_warning_min,
ufr_warning_reduction,
bloodamt,
alqd_flood_vol,
urea_clearance,
gas_purge_time,
substituent_wash_amt,
membrane_wash,
in_number,
use_start_date,
use_end_date,
in_hospital_cd_1,
in_hospital_cd_2,
in_hospital_cd_3,
is_disp,
is_del,
reg_date,
up_date,
in_hospital_cd_4)
VALUES(
/* mstDialyzer.facilityCd */null,
/* mstDialyzer.fnDialyzerCd*/null,
/* mstDialyzer.maker */null,
/* mstDialyzer.modelNumber */null,
/* mstDialyzer.dialyzerType */null,
/* mstDialyzer.functionClass */null,
/* mstDialyzer.area */null,
/* mstDialyzer.ufr */null,
/* mstDialyzer.koa */null,
/* mstDialyzer.material */null,
/* mstDialyzer.wetdry */null,
/* mstDialyzer.sterilization */null,
/* mstDialyzer.ufrWarningMax */null,
/* mstDialyzer.ufrWarningMin */null,
/* mstDialyzer.ufrWarningReduction */null,
/* mstDialyzer.bloodamt */null,
/* mstDialyzer.alqdFloodVol */null,
/* mstDialyzer.ureaClearance */null,
/* mstDialyzer.gasPurgeTime */null,
/* mstDialyzer.substituentWashAmt */null,
/* mstDialyzer.membraneWash */null,
/* mstDialyzer.inNumber */null,
/* mstDialyzer.useStartDate */null,
/* mstDialyzer.useEndDate */null,
/* mstDialyzer.inHospitalCd_1 */null,
/* mstDialyzer.inHospitalCd_2 */null,
/* mstDialyzer.inHospitalCd_3 */null,
/* mstDialyzer.isDisp */'1',
/* mstDialyzer.isDel */'0',
to_timestamp(/*mstDialyzer.regDate*/null, 'YYYY-MM-DD HH24:MI:SS'),
to_timestamp(/*mstDialyzer.upDate*/null, 'YYYY-MM-DD HH24:MI:SS'),
/* mstDialyzer.inHospitalCd_4 */null);
