-- 処理結果出力
set feedback on
-- 不要なスペースは削除
set trimspool on
-- 出力ページ設定
set pages 999
-- 1行の出力サイズ設定
set linesize 32767
-- dbms_output出力設定
set serveroutput on size 200000

-- 出力ファイル名
spool .\データコンバート環境構築削除.log

set echo on


-- 接続
-- 【注意】実行前に接続先を必ず確認すること
connect nkk/nkk@nkkfn3;

--@.\SQL\aaa.sql

-------------------------------
-- インデックス
-------------------------------
DROP INDEX idx_sync_convert_history_01;
DROP INDEX idx_sync_convert_hstry_dtl_01;
-------------------------------
-- テーブル作成
-------------------------------
DROP TABLE TSS_MST;
DROP TABLE TSS_ORD;
DROP TABLE TSS_PAT;
DROP TABLE SYNC_CONV_VALUE;
DROP TABLE SYNC_CUSTOM_CONVERT_VALUE;
DROP TABLE SYNC_FK_CONV_INFO;
DROP TABLE SYNC_SEQ_COLUMN;
DROP TABLE SYNC_UNIQUE;
DROP TABLE SYNC_SYS_CHECKLIST;
DROP TABLE SYNC_ORD_CHECKLIST_HIST;
DROP TABLE SYNC_CHECKLIST_HIST;
DROP TABLE SYNC_CONVERT_HISTORY;
DROP TABLE SYNC_CONVERT_HISTORY_DTL;
DROP TABLE SYNC_TABLE_INFO;
DROP TABLE SYNC_FACILITY_CD;
DROP TABLE SYNC_CondSet;
DROP TABLE SYNC_CONV_REASON;
DROP TABLE SYNC_MST_HIS;
DROP TABLE SYNC_SYS_PAT_CUSTOM_KEY;
DROP TABLE SYNC_IND_HISTORY_DETAIL;
DROP TABLE SYNC_MEDICINE_LATEST_NO;
DROP TABLE SYNC_LOGIN;
DROP TABLE SYNC_WATER_SURVEY_TYPE_TEXT;
DROP TABLE SYNC_MAINTE_PARTS_DETAIL;
DROP TABLE SYNC_CHECKLIST_PERIOD_DETAIL;
DROP TABLE SYNC_MON_DATA_MAP;
DROP TABLE SYNC_TREATEMENT_LAYOUT;
DROP TABLE SYNC_FNSI_MEDICINE_LATEST_NO;
DROP TABLE SYNC_DISP_ITEM_INFO;
DROP TABLE SYNC_SET_MEDICINE;
DROP TABLE SYNC_MST_DEVICE_HIS;
DROP TABLE SYNC_COOP_CONVERT_SET;


exit ;
