export const HISTORY_KEY_FACILITY_CALENDAR_LIST = "FACILITY_CALENDAR";
export const HISTORY_KEY_FACILITY_CALENDAR_CREATE = "FACILITY_CALENDAR_CREATE";
export const HISTORY_KEY_FACILITY_CALENDAR_DETAIL = "FACILITY_CALENDAR_DETAIL";
