//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDT.APP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDT.APP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規追加.
        /// </summary>
        public static string ADD_NEW {
            get {
                return ResourceManager.GetString("ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空白.
        /// </summary>
        public static string BLANK_VALUE {
            get {
                return ResourceManager.GetString("BLANK_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが変更されました。実施してもよろしいでしょうか.
        /// </summary>
        public static string CANCEL_OR_RELOAD_CONFIRM {
            get {
                return ResourceManager.GetString("CANCEL_OR_RELOAD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coop cd is invalid.
        /// </summary>
        public static string COOP_CD_INVALID {
            get {
                return ResourceManager.GetString("COOP_CD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COOP CDビュー.
        /// </summary>
        public static string COOP_CD_VIEW {
            get {
                return ResourceManager.GetString("COOP_CD_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウトビュー.
        /// </summary>
        public static string COOP_LAYOUT_VIEW {
            get {
                return ResourceManager.GetString("COOP_LAYOUT_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが空です.
        /// </summary>
        public static string DATA_EMPTY {
            get {
                return ResourceManager.GetString("DATA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが変更されました。実施してもよろしいでしょうか.
        /// </summary>
        public static string DATA_IS_MODIFINED {
            get {
                return ResourceManager.GetString("DATA_IS_MODIFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データの保存に失敗しました.
        /// </summary>
        public static string DATA_SAVED_FAILED {
            get {
                return ResourceManager.GetString("DATA_SAVED_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが正常に保存されました.
        /// </summary>
        public static string DATA_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("DATA_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除しますか.
        /// </summary>
        public static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のタブのデータを削除しますか？.
        /// </summary>
        public static string DELETE_DATA_CURRENT_TAB {
            get {
                return ResourceManager.GetString("DELETE_DATA_CURRENT_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キービューを編集.
        /// </summary>
        public static string EDIT_KEY_VIEW {
            get {
                return ResourceManager.GetString("EDIT_KEY_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要素設定.
        /// </summary>
        public static string ELEMENT_SETTING {
            get {
                return ResourceManager.GetString("ELEMENT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空白.
        /// </summary>
        public static string EMPTY {
            get {
                return ResourceManager.GetString("EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前を入力してください。.
        /// </summary>
        public static string ENTER_YOUR_COOP_NAME {
            get {
                return ResourceManager.GetString("ENTER_YOUR_COOP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キーを入力してください。.
        /// </summary>
        public static string ENTER_YOUR_KEY {
            get {
                return ResourceManager.GetString("ENTER_YOUR_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン情報を入力してください。.
        /// </summary>
        public static string ENTER_YOUR_LOGIN_INFORMATION {
            get {
                return ResourceManager.GetString("ENTER_YOUR_LOGIN_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを入力してください。.
        /// </summary>
        public static string ENTER_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("ENTER_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要素名ルートを入力してください.
        /// </summary>
        public static string ENTER_YOUR_ROOT_NAME {
            get {
                return ResourceManager.GetString("ENTER_YOUR_ROOT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーIDを入力してください。.
        /// </summary>
        public static string ENTER_YOUR_USER_ID {
            get {
                return ResourceManager.GetString("ENTER_YOUR_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたの。。。を入力してください。.
        /// </summary>
        public static string ENTER_YOUR_VENDER_NAME {
            get {
                return ResourceManager.GetString("ENTER_YOUR_VENDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーションを終了しますが、よろしいでしょうか。.
        /// </summary>
        public static string EXIT_APP {
            get {
                return ResourceManager.GetString("EXIT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 施設情報.
        /// </summary>
        public static string FACILITY_INFORMATION {
            get {
                return ResourceManager.GetString("FACILITY_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 施設ビュー.
        /// </summary>
        public static string FACILITY_VIEW {
            get {
                return ResourceManager.GetString("FACILITY_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 施設リストの取得が失敗しました。.
        /// </summary>
        public static string GET_FACILITY_LIST_FAILED {
            get {
                return ResourceManager.GetString("GET_FACILITY_LIST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        public static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キー.
        /// </summary>
        public static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このサブキーが既に存在しています。.
        /// </summary>
        public static string KEY_EXISTS {
            get {
                return ResourceManager.GetString("KEY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト一覧.
        /// </summary>
        public static string LIST_COOP_LAYOUT {
            get {
                return ResourceManager.GetString("LIST_COOP_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 施設一覧.
        /// </summary>
        public static string LIST_FACILITY {
            get {
                return ResourceManager.GetString("LIST FACILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キー一覧.
        /// </summary>
        public static string LIST_KEY {
            get {
                return ResourceManager.GetString("LIST_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証に失敗しました。認証情報を確認して下さい。.
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインページ.
        /// </summary>
        public static string LOIGN_PAGE {
            get {
                return ResourceManager.GetString("LOIGN_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電文種別詳細コードが重複しています。.
        /// </summary>
        public static string NAME_EXISTED {
            get {
                return ResourceManager.GetString("NAME_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found data by key name is .
        /// </summary>
        public static string NOT_FOUND_BY_KEY {
            get {
                return ResourceManager.GetString("NOT_FOUND_BY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 質問.
        /// </summary>
        public static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データセットのリロード.
        /// </summary>
        public static string REALOAD_DATASET {
            get {
                return ResourceManager.GetString("REALOAD_DATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受信.
        /// </summary>
        public static string RECEIVE {
            get {
                return ResourceManager.GetString("RECEIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リロード.
        /// </summary>
        public static string RELOAD {
            get {
                return ResourceManager.GetString("RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リセット.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Name is invalid.
        /// </summary>
        public static string ROOT_NAME_INVALID {
            get {
                return ResourceManager.GetString("ROOT_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データを保存しますが、よろしいでしょうか。.
        /// </summary>
        public static string SAVE_CONFIRM {
            get {
                return ResourceManager.GetString("SAVE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテムを選択してください。.
        /// </summary>
        public static string SELECT_ONE_ITEM {
            get {
                return ResourceManager.GetString("SELECT_ONE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信.
        /// </summary>
        public static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string SIGN_IN {
            get {
                return ResourceManager.GetString("SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このサブキーが既に存在しています。.
        /// </summary>
        public static string SUB_KEY_EXISTS {
            get {
                return ResourceManager.GetString("SUB_KEY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーID.
        /// </summary>
        public static string USER_ID {
            get {
                return ResourceManager.GetString("USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実行が完了するまで待ってください。.
        /// </summary>
        public static string WAITING_FOR_EXECUTED {
            get {
                return ResourceManager.GetString("WAITING_FOR_EXECUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
    }
}
