spring:
  datasource:
    default:
      jdbc-url: jdbc:postgresql://172.30.15.151:5432/ntss_db5?currentSchema=ntss&stringtype=unspecified
      username: nkk5
      password: nkk5
    personal:
      jdbc-url: jdbc:postgresql://172.30.15.151:5432/ntss_db6?currentSchema=ntss&stringtype=unspecified
      username: nkk6
      password: nkk6
    auth:
      jdbc-url: jdbc:postgresql://172.30.15.151:5432/ntss_db4?currentSchema=ntss&stringtype=unspecified
      username: nkk4
      password: nkk4
