spring:
  main:
    allow-circular-references: true
  datasource:
    default:
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db5?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk5
      password: nkk5
    personal:
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db6?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk6
      password: nkk6
    auth:
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db4?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk4
      password: nkk4
  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: Asia/Tokyo
  application:
    name: ntss-api
  jmx:
    default-domain: ntss-api

server.port: 8091

server:
  servlet:
    contextPath: /ntss-api

doma:
  dialect: postgres

ntss:
  logging:
    appender:
      file-name: /opt/ntss-api/log/{0}/{0}.log
    rolling:
      file-name-pattern:  /opt/ntss-api/log/{0}/{0}_%d'{'yyyyMMdd'}'.log
      max-history: 14
