client = yes

;foreground = yes

; log 
debug = 5
output = /var/log/stunnel4/ntss.log
;output = /dev/stdout

sessionCacheSize = 100
sessionCacheTimeout = 300

[ntss-proxy]
accept  = 127.0.0.1:8443
connect = fnwsi-vpn-dline.iesfn.com:443

; TLS 1.3
sslVersion = TLSv1.3
sslVersionMin = TLSv1.3
