INSERT INTO ord_personal_prescription
(
   ord_prescription_no,
   facility_cd,
   pat_id,
   insurance_cd,
   insu_pub_no,
   insu_pub_pat_no,
   insu_no,
   insu_pat_mark,
   insu_pat_no,
   is_insured,
   is_dependent,
   insu_kbn,
   insu_dr_id,
   insu_dr_name,
   insu_dr_sign,
   is_doubt,
   is_information,
   is_elderly,
   is_elderly7,
   is_child,
   remarks,
   is_anesthesia,
   remarks_anesthesia,
   remarks_free,
   is_disp,
   is_del,
   reg_date,
   up_date,
   insurance_name,
   insu_name_short,
   insu_info,
   insu_pub_info,
   insu_set_info,
   insu_self_info,
   memo1,
   memo2,
   is_refill,
   refill_num
)
VALUES
(
   /*ordPersonalPrescription.ordPrescriptionNo*/null,
   /*ordPersonalPrescription.facilityCd*/null,
   /*ordPersonalPrescription.patId*/null,
   /*ordPersonalPrescription.insuranceCd*/null,
   personal_info_encrypt (/*ordPersonalPrescription.insuPubNo*/null),
   personal_info_encrypt (/*ordPersonalPrescription.insuPubPatNo*/null),
   personal_info_encrypt (/*ordPersonalPrescription.insuNo*/null),
   personal_info_encrypt (/*ordPersonalPrescription.insuPatMark*/null),
   personal_info_encrypt (/*ordPersonalPrescription.insuPatNo*/null),
   /*ordPersonalPrescription.isInsured*/null,
   /*ordPersonalPrescription.isDependent*/null,
   /*ordPersonalPrescription.insuKbn*/null,
   /*ordPersonalPrescription.insuDrId*/null,
   personal_info_encrypt (/*ordPersonalPrescription.insuDrName*/null),
   personal_info_encrypt (/*ordPersonalPrescription.insuDrSign*/null),
   /*ordPersonalPrescription.isDoubt*/null,
   /*ordPersonalPrescription.isInformation*/null,
   /*ordPersonalPrescription.isElderly*/null,
   /*ordPersonalPrescription.isElderly7*/null,
   /*ordPersonalPrescription.isChild*/null,
   /*ordPersonalPrescription.remarks*/null,
   /*ordPersonalPrescription.isAnesthesia*/null,
   personal_info_encrypt (/*ordPersonalPrescription.remarksAnesthesia*/null),
   personal_info_encrypt (/*ordPersonalPrescription.remarksFree*/null),
   /*ordPersonalPrescription.isDisp*/'1',
   /*ordPersonalPrescription.isDel*/'0',
   /*ordPersonalPrescription.regDate*/null,
   /*ordPersonalPrescription.upDate*/null,
   /*ordPersonalPrescription.insuranceName*/null,
   /*ordPersonalPrescription.insuNameShort*/null,
   /*ordPersonalPrescription.insuInfo*/null,
   /*ordPersonalPrescription.insuPubInfo*/null,
   /*ordPersonalPrescription.insuSetInfo*/null,
   /*ordPersonalPrescription.insuSelfInfo*/null,
   /*ordPersonalPrescription.memo1*/null,
   /*ordPersonalPrescription.memo2*/null,
   /*ordPersonalPrescription.isRefill*/null,
   /*ordPersonalPrescription.refillNum*/null
);