-- =============================================================
-- 02: PG FK 設定の最終データ投入
--   迴ｾ蝨ｨ縺ｮ驕狗畑迥ｶ諷九ｒ蝓ｺ貅悶↓荳ｦ縺ｳ鬆・→ ID 繧呈紛逅・＠縺溷ｮ悟・迚・-- =============================================================

TRUNCATE TABLE fk_migration_config RESTART IDENTITY;

INSERT INTO fk_migration_config
    (id, table_name, fk_type, column_name, json_column, json_path, ref_table, execution_order, enabled, where_template, where_column,remark)
VALUES
    (1, 'bbs_info', 'COLUMN', 'kind_no', NULL, NULL, 'mst_bbs_kind', 100, TRUE, NULL, NULL,NULL),
    (2, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_water_survey_point', 100, TRUE, NULL, 'template_cd=10',NULL),
    (3, 'bbs_info', 'JsonIntArray', NULL, 'staff_info', 'read', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (4, 'bbs_info', 'JsonIntArray', NULL, 'staff_info', 'target', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (5, 'medicine_latest_no', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (6, 'mni_monitor', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (7, 'mni_monitor', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL,NULL),
    (8, 'mnt_machine_state', 'COLUMN', 'bed_cd', NULL, NULL, 'mst_bed', 100, TRUE, NULL, NULL,NULL),
    (9, 'mnt_machine_state', 'COLUMN', 'next_kur_cd', NULL, NULL, 'mst_kur', 110, TRUE, NULL, NULL,NULL),
    (10, 'mnt_machine_state', 'COLUMN', 'next_ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (11, 'mnt_machine_state', 'COLUMN', 'next_patid', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL,NULL),
    (12, 'mnt_machine_state', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (13, 'mnt_machine_state', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL,NULL),
    (14, 'mnt_mainte_main', 'JSON', NULL, 'detail', '[].cate_cd', 'mst_mainte_category', 100, TRUE, NULL,'mainte_class=''1''', NULL),
    (15, 'mnt_mainte_main', 'JSON', NULL, 'detail', '[].detail_cd', 'mst_mainte_detail', 100, TRUE, NULL,'mainte_class=''1''', NULL),
    (16, 'mnt_mainte_main', 'JSON', NULL, 'detail', '[].user_id', 'mst_personal_user', 100, TRUE, NULL,'mainte_class=''1''', NULL),
    (17, 'mnt_mainte_main', 'COLUMN', 'machine_no', NULL, NULL, 'mst_machine', 100, TRUE, NULL, NULL,NULL),
    (18, 'mnt_motion_record', 'COLUMN', 'user_id', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL, NULL),
    (19, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'BBSCTLNO', 'bbs_info', 110, TRUE, '(@->>''FUNC'') = ''02002''', NULL,NULL),
    (20, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'CTLNO', 'sys_coop_no', 110, TRUE, '(@->>''FUNC'') = ''031''', NULL,NULL),
    (21, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'ORDNO', 'ord_main', 110, TRUE, '(@->>''FUNC'') = ''006''', NULL,NULL),
    (22, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'ORDNO', 'ord_main', 110, TRUE, '(@->>''FUNC'') = ''031''', NULL,NULL),
    (23, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'PATEVENTCD', 'pat_event', 110, TRUE, '(@->>''FUNC'') = ''027''', NULL,NULL),
    (24, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'PATGROUPCD', 'pat_group', 110, TRUE, '(@->>''FUNC'') = ''02303''', NULL,NULL),
    (25, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'PATID', 'pat_main', 110, TRUE, '(@->>''FUNC'') = ''006''', NULL,NULL),
    (26, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'PATID', 'pat_main', 110, TRUE, '(@->>''FUNC'') = ''007''', NULL,NULL),
    (27, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'PATID', 'pat_main', 110, TRUE, '(@->>''FUNC'') = ''014''', NULL,NULL),
    (28, 'mnt_notification_message', 'JSON', NULL, 'additional_info', 'PATID', 'pat_main', 110, TRUE, '(@->>''FUNC'') = ''027''', NULL,NULL),
    (29, 'mnt_notification_status', 'COLUMN', 'user_id', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (30, 'mnt_water_survey', 'JSON', NULL, 'survey_data', '[].inspector', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (31, 'mnt_water_survey', 'JSON', NULL, 'survey_data', '[].picker', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (32, 'mnt_water_survey', 'JSON', NULL, 'survey_data', '[].point_cd', 'mst_water_survey_point', 100, TRUE, NULL, NULL,NULL),
    (33, 'mst_addition', 'JSON', NULL, 'addition_tar_cd', '[].cd', 'mst_disease', 100, TRUE, NULL,'addition_class = ''3''',NULL),
    (34, 'mst_addition', 'JSON', NULL, 'addition_tar_cd', '[].cd', 'mst_medicine', 100, TRUE, NULL,'addition_class = ''6''',NULL),
    (35, 'mst_addition', 'JSON', NULL, 'addition_tar_cd', '[].cd', 'mst_pat_event_sub_category', 100, TRUE, NULL,'addition_class = ''7''', NULL),
    (36, 'mst_addition', 'JSON', NULL, 'addition_tar_cd', '[].cd', 'mst_treatment', 100, TRUE, NULL,'addition_class = ''4''', NULL),
    (37, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph1', 'graph1_item.[].code1', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code1'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (38, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph1', 'graph1_item.[].code2', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code2'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (39, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph1', 'graph1_item.[].code3', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code3'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (40, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph2', 'graph2_item.[].code_afr1', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code_afr1'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (41, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph2', 'graph2_item.[].code_afr2', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code_afr2'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (42, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph2', 'graph2_item.[].code_bar1', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code_bar1'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (43, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph2', 'graph2_item.[].code_bar2', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code_bar2'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (44, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph2', 'graph2_item.[].code_bfr1', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code_bfr1'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (45, 'mst_comsv_setting', 'JSON', NULL, 'lcd_graph2', 'graph2_item.[].code_bfr2', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code_bfr2'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (46, 'mst_comsv_setting', 'JSON', NULL, 'lcd_radar', 'radar_item.[].code', 'mst_exam_item', 100, TRUE, 'coalesce(@->>''code'', '''') !~ ''^0+[0-9]+$''', NULL,NULL),
    (47, 'mst_comsv_setting', 'JSON', NULL, 'lcd_staff_list', 'staff_list.[].user_id', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (48, 'mst_exam_set', 'JSON', NULL, 'exam_item_info', '[].exam_item_cd', 'mst_exam_item', 100, TRUE, NULL, NULL,NULL),
    (49, 'mst_exam_set', 'JSON', NULL, 'label_info', '[].spitz_cd', 'mst_spitz', 100, TRUE, NULL, NULL,NULL),
    (50, 'mst_job', 'JSON', NULL, 'default_disp_settings', 'patient-search.bedCdListString', 'mst_room_bed_group', 100, TRUE, NULL, NULL,NULL),
    (51, 'mst_job', 'JSON', NULL, 'default_disp_settings', 'pat-viewer.setSelectedLayoutCd', 'mst_pat_viewer_layout', 100, TRUE, NULL, NULL,NULL),
    (52, 'mst_job', 'JSON', NULL, 'default_disp_settings', 'schedule-list.bedGroupCd', 'mst_room_bed_group', 100, TRUE, NULL, NULL,NULL),
    (53, 'mst_job', 'JSON', NULL, 'default_notification_settings', '{tab_define_cd}', 'mst_personal_tab_define', 100, TRUE, NULL, NULL,NULL),
    (54, 'mst_kur', 'JSON', NULL, 'mst_user_authentication', 'data.[].*.disp_user_id', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (55, 'mst_kur', 'JSON', NULL, 'mst_user_authentication', 'data.[].*.user_id', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (56, 'mst_mainte_category', 'JSON', NULL, 'detail', '[].code', 'mst_mainte_detail', 100, TRUE, NULL,'mainte_class = ''2''', NULL),
    (57, 'mst_mainte_layout', 'JSON', NULL, 'detail_info_1', '[].cd', 'mst_mainte_category', 100, TRUE, NULL, NULL,NULL),
    (58, 'mst_mainte_layout', 'JSON', NULL, 'detail_info_2', '[].cd', 'mst_mainte_category', 100, TRUE, NULL, NULL,NULL),
    (59, 'mst_medicine_group', 'JSON', NULL, 'reg_medicine_info', '[].cd', 'mst_medicine', 100, TRUE, NULL, NULL,NULL),
    (60, 'mst_medicine_group', 'JSON', NULL, 'reg_medicine_info', '[].classCd', 'mst_medicine_class', 100, TRUE, NULL, NULL, NULL),
    (61, 'mst_medicine_mix', 'JSON', NULL, 'mix_info', '[].cd', 'mst_medicine', 100, TRUE, NULL, NULL, NULL),
    (62, 'mst_medicine_support', 'JSON', NULL, 'detail_info', 'examItemAverage.[].value', 'mst_exam_item', 100, TRUE, NULL, NULL, NULL),
    (63, 'mst_medicine_support', 'JSON', NULL, 'detail_info', 'examItemCycling.[].value', 'mst_exam_item', 100, TRUE, NULL, NULL, NULL),
    (64, 'mst_pat_list_layout', 'JSON', NULL, 'disp_item_info', '[].{data_list_detail_cd}', 'sys_data_list_detail', 110, TRUE, NULL, NULL, NULL),
    (65, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'occupations', '[]', 'mst_job', 100, TRUE, '(@ #>> ''{}'') <> ''-1''', NULL, NULL),
    (66, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_add_monitor', 100, TRUE, '[{"subCategory.component":"vital"},{"subCategory.component":"comprehensive","item.itemDivision":"5"}]', NULL, NULL),
    (67, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_complaint', 100, TRUE, '[{"subCategory.component":"complaint","item.itemNoPrefix":"Complaints*"},{"subCategory.component":"rst-info","subCategory.subCategoryNo":"56","item.itemNoPrefix":"Complaints*"}]', NULL, NULL),
    (68, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_comp_treatment', 100, TRUE, '[{"subCategory.component":"complaint","item.itemNoPrefix":"CompTreatment*"},{"subCategory.component":"rst-info","subCategory.subCategoryNo":"56","item.itemNoPrefix":"CompTreatment*"}]', NULL, NULL),
    (69, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_dialyzer', 100, TRUE, '{"subCategory.component":"dialyzer","item.itemNoType":"numeric"}', NULL, NULL),
    (70, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_equipment', 100, TRUE, '{"subCategory.component":"medical","item.itemNoType":"numeric"}', NULL, NULL),
    (71, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_exam_item', 100, TRUE, '{"subCategory.component":"exam-result","item.itemNoType":"numeric"}', NULL, NULL),
    (72, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_exam_item', 100, TRUE, '{"subCategory.component":"comprehensive","item.itemDivision":"2","item.itemNoType":"numeric"}', NULL, NULL),
    (73, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_medicine', 100, TRUE, '[{"subCategory.component":"drugAggregate","item.itemNoType":"numeric"},{"subCategory.component":"drug-graph","item.itemNoType":"numeric"},{"subCategory.component":"comprehensive","item.itemDivision":"4","item.itemNoType":"numeric"},{"subCategory.component":"drug-graph","item.itemNoPrefix":"MEDICINE"},{"subCategory.component":"comprehensive","item.itemDivision":"4","item.itemNoPrefix":"MEDICINE"}]', NULL, NULL),
    (74, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_medicine_group', 100, TRUE, '[{"subCategory.component":"drug-graph","item.itemNoPrefix":["MEDICINE_GROUPS","MEDICINE_GROUP"]},{"subCategory.component":"comprehensive","item.itemDivision":"4","item.itemNoPrefix":["MEDICINE_GROUPS","MEDICINE_GROUP"]}]', NULL, NULL),
    (75, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_medicine_mix', 100, TRUE, '[{"subCategory.component":"drug-graph","item.itemNoPrefix":"MEDICINE_MIX"},{"subCategory.component":"comprehensive","item.itemDivision":"4","item.itemNoPrefix":"MEDICINE_MIX"}]', NULL, NULL),
    (76, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_pat_event_category', 100, TRUE, '{"category.categoryNo":"16","item.itemNoPrefix":"PAT_EVENT*"}', NULL,NULL),
    (77, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_pat_event_sub_category', 100, TRUE, '{"category.categoryNo":"16","item.itemNoPrefix":"PAT_EVENT_SUB*"}', NULL,NULL),
    (78, 'mst_report', 'JSON', NULL, 'extraction_condition', '{mainte_layout_cd}', 'mst_mainte_layout', 100, TRUE, NULL, NULL,NULL),
    (79, 'mst_taboo_allergy', 'JSON', NULL, 'detail_info', '[].cd', 'mst_dialyzer', 100, TRUE, '(@->>''classCd'') = ''4''', NULL,NULL),
    (80, 'mst_taboo_allergy', 'JSON', NULL, 'detail_info', '[].cd', 'mst_equipment', 100, TRUE, '(@->>''classCd'') = ''3''', NULL,NULL),
    (81, 'mst_taboo_allergy', 'JSON', NULL, 'detail_info', '[].cd', 'mst_medicine', 100, TRUE, '(@->>''classCd'') = ''1''', NULL,NULL),
    (82, 'mst_taboo_allergy', 'JSON', NULL, 'detail_info', '[].cd', 'mst_medicine_mix', 100, TRUE, '(@->>''classCd'') = ''2''', NULL,NULL),
    (83, 'mst_treatment', 'JSON', NULL, 'monitor_data_item_print', '[].moni_data_no', 'sys_monitor_item', 100, TRUE, NULL, NULL,NULL),
    (84, 'mst_treatment', 'JSON', NULL, 'monitor_data_item_screen', '[].moni_data_no', 'sys_monitor_item', 100, TRUE, NULL, NULL,NULL),
    (85, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{10,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (86, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{11,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (87, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{13,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (88, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine', 100, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 1', NULL,NULL),
    (89, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine_mix', 100, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 2', NULL,NULL),
    (90, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine', 100, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 1', NULL,NULL),
    (91, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine_mix', 100, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 2', NULL,NULL),
    (92, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine', 100, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 1', NULL,NULL),
    (93, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine_mix', 100, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 2', NULL,NULL),
    (94, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{2,value}', 'mst_va', 100, TRUE, NULL, NULL,NULL),
    (95, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{5,value}', 'mst_dialyzer', 100, TRUE, NULL, NULL,NULL),
    (96, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{6,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (97, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{7,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (98, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{8,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (99, 'mst_treatment_set', 'JSON', NULL, 'ind_cond_info', '{9,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (100, 'mst_treatment_set', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_dialyzer', 100, TRUE, '(ind_equip_info->>''equip_type'')::int = 1', NULL,NULL),
    (101, 'mst_treatment_set', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_equipment', 100, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (102, 'mst_treatment_set', 'JSON', NULL, 'ind_equip_info', '[].class_cd', 'mst_equipment_class', 100, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (103, 'mst_treatment_set', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine', 100, TRUE, '(ind_medi_info->>''medicine_type'')::int = 1', NULL,NULL),
    (104, 'mst_treatment_set', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine_mix', 100, TRUE, '(ind_medi_info->>''medicine_type'')::int = 2', NULL,NULL),
    (105, 'mst_treatment_set', 'JSON', NULL, 'ind_medi_info', '[].procedure_cd', 'mst_procedure', 100, TRUE, NULL, NULL,NULL),
    (106, 'mst_treatment_set', 'JSON', NULL, 'ind_medi_info', '[].timing_cd', 'mst_medicate_timing', 100, TRUE, NULL, NULL,NULL),
    (107, 'mst_trend_graph_monitor_set', 'JSON', NULL, 'series_info', '[].code', 'sys_monitor_item', 100, TRUE, NULL, NULL,NULL),
    (108, 'mst_trend_graph_template', 'JSON', NULL, 'series_info', '[].moni_cd', 'sys_monitor_item', 100, TRUE, NULL, NULL,NULL),
    (109, 'mst_user', 'JSON', NULL, 'tmp_log_search_condition', '[].condition.patId.[].cd', 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (110, 'mst_user', 'JSON', NULL, 'tmp_log_search_condition', '[].condition.userId.[].cd', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (111, 'mst_user_authentication', 'COLUMN', 'user_id', NULL, NULL, 'mst_user', 10, TRUE, NULL, NULL,NULL),
    (112, 'ord_checklist', 'JSON', NULL, 'reg_staff_info', '{reg_staff_cd}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (113, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{checklist_cd}', 'mst_checklist', 110, TRUE, NULL, NULL,NULL),
    (114, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_dialyzer', 110, TRUE, 'func_class = 1 AND (rst_checklist_info->>''class_cd'') = ''5''', NULL,NULL),
    (115, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_dialyzer', 110, TRUE, 'func_class = 2 AND (rst_checklist_info->>''class_cd'') = ''0''', NULL,NULL),
    (116, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_equipment', 110, TRUE, 'func_class = 1 AND (rst_checklist_info->>''class_cd'') IN (''6'',''7'',''8'',''9'',''10'',''11'',''13'')', NULL,NULL),
    (117, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_equipment', 110, TRUE, 'func_class = 2 AND (rst_checklist_info->>''class_cd'') != ''0''', NULL,NULL),
    (118, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_medicine', 110, TRUE, 'func_class = 1 AND (rst_checklist_info->>''class_cd'') IN (''15'',''19'',''25'') AND (rst_checklist_info->>''medicine_type'') != ''2''', NULL,NULL),
    (119, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_medicine', 110, TRUE, 'func_class = 3 AND (rst_checklist_info->>''medicine_type'') != ''2''', NULL,NULL),
    (120, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_medicine_mix', 110, TRUE, 'func_class = 1 AND (rst_checklist_info->>''class_cd'') IN (''15'',''19'',''25'') AND (rst_checklist_info->>''medicine_type'') = ''2''', NULL,NULL),
    (121, 'ord_checklist', 'JSON', NULL, 'rst_checklist_info', '{code}', 'mst_medicine_mix', 110, TRUE, 'func_class = 3 AND (rst_checklist_info->>''medicine_type'') = ''2''', NULL,NULL),
    (122, 'ord_coop_no', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (123, 'ord_coop_no', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL,NULL),
    (124, 'ord_exception_period', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (125, 'ord_main', 'JSON', NULL, 'addition_info', '[].cd', 'mst_addition', 110, TRUE, NULL, NULL,NULL),
    (126, 'ord_main', 'JSON', NULL, 'bvms_path', '{created_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (127, 'ord_main', 'JSON', NULL, 'bvms_path', '{create_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (128, 'ord_main', 'JSON', NULL, 'bvms_path', '{ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (129, 'ord_main', 'JSON', NULL, 'bvms_path', '{reg_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (130, 'ord_main', 'JSON', NULL, 'bvms_path', '{updated_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (131, 'ord_main', 'COLUMN', 'ind_bed_cd', NULL, NULL, 'mst_bed', 100, TRUE, NULL, NULL,NULL),
    (132, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{10,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (133, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{11,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (134, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{13,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (135, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine', 110, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 1', NULL,NULL),
    (136, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine_mix', 110, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 2', NULL,NULL),
    (137, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine', 110, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 1', NULL,NULL),
    (138, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine_mix', 110, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 2', NULL,NULL),
    (139, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine', 110, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 1', NULL,NULL),
    (140, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine_mix', 110, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 2', NULL,NULL),
    (141, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{2,value}', 'mst_va', 110, TRUE, NULL, NULL,NULL),
    (142, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{5,value}', 'mst_dialyzer', 110, TRUE, NULL, NULL,NULL),
    (143, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{6,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (144, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{7,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (145, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{8,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (146, 'ord_main', 'JSON', NULL, 'ind_cond_info', '{9,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (147, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{bvufc,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (148, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{bvufc,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (149, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{dc,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (150, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{dc,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (151, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{dia,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (152, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{dia,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (153, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{ihdf,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (154, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{ihdf,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (155, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{na,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (156, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{na,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (157, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{qbqd,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (158, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{qbqd,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (159, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{ufr,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (160, 'ord_main', 'JSON', NULL, 'ind_device_set_info', '{ufr,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (161, 'ord_main', 'JSON', NULL, 'ind_dw_user_info', '{ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (162, 'ord_main', 'JSON', NULL, 'ind_dw_user_info', '{upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (163, 'ord_main', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_dialyzer', 110, TRUE, '(ind_equip_info->>''equip_type'')::int = 1', NULL,NULL),
    (164, 'ord_main', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_equipment', 110, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (165, 'ord_main', 'JSON', NULL, 'ind_equip_info', '[].class_cd', 'mst_equipment_class', 110, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (166, 'ord_main', 'JSON', NULL, 'ind_equip_info', '[].ind_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (167, 'ord_main', 'JSON', NULL, 'ind_equip_info', '[].upd_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (168, 'ord_main', 'COLUMN', 'ind_kur_cd', NULL, NULL, 'mst_kur', 100, TRUE, NULL, NULL,NULL),
    (169, 'ord_main', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine', 110, TRUE, '(ind_medi_info->>''medicine_type'')::int = 1', NULL,NULL),
    (170, 'ord_main', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine_mix', 110, TRUE, '(ind_medi_info->>''medicine_type'')::int = 2', NULL,NULL),
    (171, 'ord_main', 'JSON', NULL, 'ind_medi_info', '[].class_cd', 'mst_medicine_class', 110, TRUE, NULL, NULL,NULL),
    (172, 'ord_main', 'JSON', NULL, 'ind_medi_info', '[].ind_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (173, 'ord_main', 'JSON', NULL, 'ind_medi_info', '[].procedure_cd', 'mst_procedure', 110, TRUE, NULL, NULL,NULL),
    (174, 'ord_main', 'JSON', NULL, 'ind_medi_info', '[].timing_cd', 'mst_medicate_timing', 110, TRUE, NULL, NULL,NULL),
    (175, 'ord_main', 'JSON', NULL, 'ind_medi_info', '[].upd_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (176, 'ord_main', 'JSON', NULL, 'ind_schedule_user_info', '{ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (177, 'ord_main', 'JSON', NULL, 'ind_schedule_user_info', '{upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (178, 'ord_main', 'COLUMN', 'ind_treatment_cd', NULL, NULL, 'mst_treatment', 100, TRUE, NULL, NULL,NULL),
    (179, 'ord_main', 'COLUMN', 'ind_va_cd', NULL, NULL, 'mst_va', 100, TRUE, NULL, NULL,NULL),
    (180, 'ord_main', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (181, 'ord_main', 'COLUMN', 'rst_bed_cd', NULL, NULL, 'mst_bed', 100, TRUE, NULL, NULL,NULL),
    (182, 'ord_main', 'JSON', NULL, 'rst_charge_user_info', '{user_id_1}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (183, 'ord_main', 'JSON', NULL, 'rst_charge_user_info', '{user_id_2}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (184, 'ord_main', 'JSON', NULL, 'rst_complaint_info', '[].comp_cd', 'mst_complaint', 110, TRUE, NULL, NULL,NULL),
    (185, 'ord_main', 'COLUMN', 'rst_course_cd', NULL, NULL, 'mst_course', 100, TRUE, NULL, NULL,NULL),
    (186, 'ord_main', 'JSON', NULL, 'rst_equip_info', '[].cd', 'mst_dialyzer', 110, TRUE, '(rst_equip_info->>''equip_type'')::int = 1', NULL,NULL),
    (187, 'ord_main', 'JSON', NULL, 'rst_equip_info', '[].cd', 'mst_equipment', 110, TRUE, '(rst_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (188, 'ord_main', 'JSON', NULL, 'rst_equip_info', '[].class_cd', 'mst_equipment_class', 110, TRUE, '(rst_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (189, 'ord_main', 'JSON', NULL, 'rst_equip_info', '[].ind_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (190, 'ord_main', 'JSON', NULL, 'rst_equip_info', '[].upd_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (191, 'ord_main', 'COLUMN', 'rst_kur_cd', NULL, NULL, 'mst_kur', 100, TRUE, NULL, NULL,NULL),
    (192, 'ord_main', 'JSON', NULL, 'rst_medi_info', '[].cd', 'mst_medicine', 110, TRUE, NULL, NULL,NULL),
    (193, 'ord_main', 'JSON', NULL, 'rst_medi_info', '[].class_cd', 'mst_medicine_class', 110, TRUE, NULL, NULL,NULL),
    (194, 'ord_main', 'JSON', NULL, 'rst_medi_info', '[].effect_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (195, 'ord_main', 'JSON', NULL, 'rst_medi_info', '[].procedure_cd', 'mst_procedure', 110, TRUE, NULL, NULL,NULL),
    (196, 'ord_main', 'JSON', NULL, 'rst_medi_info', '[].timing_cd', 'mst_medicate_timing', 110, TRUE, NULL, NULL,NULL),
    (197, 'ord_main', 'JSON', NULL, 'rst_puncture_user_info', '{user_id_1}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (198, 'ord_main', 'JSON', NULL, 'rst_puncture_user_info', '{user_id_2}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (199, 'ord_main', 'JSON', NULL, 'rst_return_user_info', '{user_id_1}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (200, 'ord_main', 'JSON', NULL, 'rst_return_user_info', '{user_id_2}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (201, 'ord_main', 'JSON', NULL, 'rst_rounds_info', '{created_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (202, 'ord_main', 'JSON', NULL, 'rst_rounds_info', '{ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (203, 'ord_main', 'JSON', NULL, 'rst_rounds_info', '{reg_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (204, 'ord_main', 'JSON', NULL, 'rst_rounds_info', '{updated_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (205, 'ord_main', 'JSON', NULL, 'rst_tare_info', '{wheel_chair_cd}', 'mst_wheel_chair', 110, TRUE, NULL, NULL,NULL),
    (206, 'ord_main', 'COLUMN', 'rst_treatment_cd', NULL, NULL, 'mst_treatment', 100, TRUE, NULL, NULL,NULL),
    (207, 'ord_main', 'JSON', NULL, 'rst_treatment_info', '[].procedure_cd', 'mst_procedure', 110, TRUE, NULL, NULL,NULL),
    (208, 'ord_main', 'JSON', NULL, 'rst_treatment_info', '[].treat_cd', 'mst_comp_treatment', 110, TRUE, NULL, NULL,NULL),
    (209, 'ord_main', 'JSON', NULL, 'rst_treatment_info', '[].treat_medicine_cd', 'mst_medicine', 110, TRUE, NULL, NULL,NULL),
    (210, 'ord_main', 'JSON', NULL, 'rst_treat_staff_info', '[].treat_staff_cd', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (211, 'ord_main', 'COLUMN', 'rst_ward_cd', NULL, NULL, 'mst_ward', 100, TRUE, NULL, NULL,NULL),
    (212, 'ord_main_restore', 'JSON', NULL, 'addition_info', '[].cd', 'mst_addition', 110, TRUE, NULL, NULL,NULL),
    (213, 'ord_main_restore', 'JSON', NULL, 'bvms_path', '{created_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (214, 'ord_main_restore', 'JSON', NULL, 'bvms_path', '{create_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (215, 'ord_main_restore', 'JSON', NULL, 'bvms_path', '{ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (216, 'ord_main_restore', 'JSON', NULL, 'bvms_path', '{reg_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (217, 'ord_main_restore', 'JSON', NULL, 'bvms_path', '{updated_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (218, 'ord_main_restore', 'COLUMN', 'ind_bed_cd', NULL, NULL, 'mst_bed', 100, TRUE, NULL, NULL,NULL),
    (219, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{10,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (220, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{11,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (221, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{13,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (222, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine', 110, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 1', NULL,NULL),
    (223, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine_mix', 110, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 2', NULL,NULL),
    (224, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine', 110, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 1', NULL,NULL),
    (225, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine_mix', 110, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 2', NULL,NULL),
    (226, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine', 110, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 1', NULL,NULL),
    (227, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine_mix', 110, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 2', NULL,NULL),
    (228, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{2,value}', 'mst_va', 110, TRUE, NULL, NULL,NULL),
    (229, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{5,value}', 'mst_dialyzer', 110, TRUE, NULL, NULL,NULL),
    (230, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{6,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (231, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{7,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (232, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{8,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (233, 'ord_main_restore', 'JSON', NULL, 'ind_cond_info', '{9,value}', 'mst_equipment', 110, TRUE, NULL, NULL,NULL),
    (234, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{bvufc,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (235, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{bvufc,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (236, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{dc,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (237, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{dc,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (238, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{dia,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (239, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{dia,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (240, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{ihdf,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (241, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{ihdf,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (242, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{na,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (243, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{na,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (244, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{qbqd,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (245, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{qbqd,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (246, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{ufr,ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (247, 'ord_main_restore', 'JSON', NULL, 'ind_device_set_info', '{ufr,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (248, 'ord_main_restore', 'JSON_MULTI', NULL, 'ind_dw_user_info', '{ind_user_id,upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    --(249, 'ord_main_restore', 'JSON', NULL, 'ind_dw_user_info', '{upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (250, 'ord_main_restore', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_dialyzer', 110, TRUE, '(ind_equip_info->>''equip_type'')::int = 1', NULL,NULL),
    (251, 'ord_main_restore', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_equipment', 110, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (252, 'ord_main_restore', 'JSON', NULL, 'ind_equip_info', '[].class_cd', 'mst_equipment_class', 110, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (253, 'ord_main_restore', 'JSON', NULL, 'ind_equip_info', '[].ind_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (254, 'ord_main_restore', 'JSON', NULL, 'ind_equip_info', '[].upd_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (255, 'ord_main_restore', 'COLUMN', 'ind_kur_cd', NULL, NULL, 'mst_kur', 100, TRUE, NULL, NULL,NULL),
    (256, 'ord_main_restore', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine', 110, TRUE, '(ind_medi_info->>''medicine_type'')::int = 1', NULL,NULL),
    (257, 'ord_main_restore', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine_mix', 110, TRUE, '(ind_medi_info->>''medicine_type'')::int = 2', NULL,NULL),
    (258, 'ord_main_restore', 'JSON', NULL, 'ind_medi_info', '[].class_cd', 'mst_medicine_class', 110, TRUE, NULL, NULL,NULL),
    (259, 'ord_main_restore', 'JSON', NULL, 'ind_medi_info', '[].ind_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (260, 'ord_main_restore', 'JSON', NULL, 'ind_medi_info', '[].procedure_cd', 'mst_procedure', 110, TRUE, NULL, NULL,NULL),
    (261, 'ord_main_restore', 'JSON', NULL, 'ind_medi_info', '[].timing_cd', 'mst_medicate_timing', 110, TRUE, NULL, NULL,NULL),
    (262, 'ord_main_restore', 'JSON', NULL, 'ind_medi_info', '[].upd_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (263, 'ord_main_restore', 'JSON', NULL, 'ind_schedule_user_info', '{ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (264, 'ord_main_restore', 'JSON', NULL, 'ind_schedule_user_info', '{upd_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (265, 'ord_main_restore', 'COLUMN', 'ind_treatment_cd', NULL, NULL, 'mst_treatment', 100, TRUE, NULL, NULL,NULL),
    (266, 'ord_main_restore', 'COLUMN', 'ind_va_cd', NULL, NULL, 'mst_va', 100, TRUE, NULL, NULL,NULL),
    (267, 'ord_main_restore', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (268, 'ord_main_restore', 'COLUMN', 'rst_bed_cd', NULL, NULL, 'mst_bed', 100, TRUE, NULL, NULL,NULL),
    (269, 'ord_main_restore', 'JSON', NULL, 'rst_charge_user_info', '{user_id_1}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (270, 'ord_main_restore', 'JSON', NULL, 'rst_charge_user_info', '{user_id_2}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (271, 'ord_main_restore', 'JSON', NULL, 'rst_complaint_info', '[].comp_cd', 'mst_complaint', 110, TRUE, NULL, NULL,NULL),
    (272, 'ord_main_restore', 'COLUMN', 'rst_course_cd', NULL, NULL, 'mst_course', 100, TRUE, NULL, NULL,NULL),
    (273, 'ord_main_restore', 'JSON', NULL, 'rst_equip_info', '[].cd', 'mst_dialyzer', 110, TRUE, '(rst_equip_info->>''equip_type'')::int = 1', NULL,NULL),
    (274, 'ord_main_restore', 'JSON', NULL, 'rst_equip_info', '[].cd', 'mst_equipment', 110, TRUE, '(rst_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (275, 'ord_main_restore', 'JSON', NULL, 'rst_equip_info', '[].class_cd', 'mst_equipment_class', 110, TRUE, '(rst_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (276, 'ord_main_restore', 'JSON', NULL, 'rst_equip_info', '[].ind_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (277, 'ord_main_restore', 'JSON', NULL, 'rst_equip_info', '[].upd_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (278, 'ord_main_restore', 'COLUMN', 'rst_kur_cd', NULL, NULL, 'mst_kur', 100, TRUE, NULL, NULL,NULL),
    (279, 'ord_main_restore', 'JSON', NULL, 'rst_medi_info', '[].cd', 'mst_medicine', 110, TRUE, NULL, NULL,NULL),
    (280, 'ord_main_restore', 'JSON', NULL, 'rst_medi_info', '[].class_cd', 'mst_medicine_class', 110, TRUE, NULL, NULL,NULL),
    (281, 'ord_main_restore', 'JSON', NULL, 'rst_medi_info', '[].effect_user_id', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (282, 'ord_main_restore', 'JSON', NULL, 'rst_medi_info', '[].procedure_cd', 'mst_procedure', 110, TRUE, NULL, NULL,NULL),
    (283, 'ord_main_restore', 'JSON', NULL, 'rst_medi_info', '[].timing_cd', 'mst_medicate_timing', 110, TRUE, NULL, NULL,NULL),
    (284, 'ord_main_restore', 'JSON', NULL, 'rst_puncture_user_info', '{user_id_1}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (285, 'ord_main_restore', 'JSON', NULL, 'rst_puncture_user_info', '{user_id_2}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (286, 'ord_main_restore', 'JSON', NULL, 'rst_return_user_info', '{user_id_1}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (287, 'ord_main_restore', 'JSON', NULL, 'rst_return_user_info', '{user_id_2}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (288, 'ord_main_restore', 'JSON', NULL, 'rst_rounds_info', '{created_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (289, 'ord_main_restore', 'JSON', NULL, 'rst_rounds_info', '{ind_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (290, 'ord_main_restore', 'JSON', NULL, 'rst_rounds_info', '{reg_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (291, 'ord_main_restore', 'JSON', NULL, 'rst_rounds_info', '{updated_user_id}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (292, 'ord_main_restore', 'JSON', NULL, 'rst_tare_info', '{*.wheel_chair_cd}', 'mst_wheel_chair', 110, TRUE, NULL, NULL,NULL),
    (293, 'ord_main_restore', 'COLUMN', 'rst_treatment_cd', NULL, NULL, 'mst_treatment', 100, TRUE, NULL, NULL,NULL),
    (294, 'ord_main_restore', 'JSON', NULL, 'rst_treatment_info', '[].procedure_cd', 'mst_procedure', 110, TRUE, NULL, NULL,NULL),
    (295, 'ord_main_restore', 'JSON', NULL, 'rst_treatment_info', '[].treat_cd', 'mst_comp_treatment', 110, TRUE, NULL, NULL,NULL),
    (296, 'ord_main_restore', 'JSON', NULL, 'rst_treatment_info', '[].treat_medicine_cd', 'mst_medicine', 110, TRUE, NULL, NULL,NULL),
    (297, 'ord_main_restore', 'JSON', NULL, 'rst_treat_staff_info', '[].treat_staff_cd', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (298, 'ord_main_restore', 'COLUMN', 'rst_ward_cd', NULL, NULL, 'mst_ward', 100, TRUE, NULL, NULL,NULL),
    (299, 'ord_material_save', 'COLUMN', 'class_cd', NULL, NULL, 'mst_equipment_class', 110, TRUE, NULL,'supplies_class IN (''00'',''01'',''02'',''03'',''04'',''05'',''06'',''07'',''11'')', NULL),
    (300, 'ord_material_save', 'COLUMN', 'class_cd', NULL, NULL, 'mst_medicine_class', 110, TRUE,  NULL,'supplies_class IN (''08'',''09'',''10'',''12'',''13'',''14'',''15'',''16'',''17'',''20'',''21'',''22'',''23'',''24'')', NULL),
    (301, 'ord_material_save', 'COLUMN', 'medicine_mix_cd', NULL, NULL, 'mst_medicine_mix', 110, TRUE, NULL, NULL, NULL),
    (302, 'ord_material_save', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL, NULL),
    (303, 'ord_material_save', 'COLUMN', 'procedure_cd', NULL, NULL, 'mst_procedure', 110, TRUE, NULL, NULL, NULL),
    (304, 'ord_material_save', 'JSON', NULL, 'receipt_conversion', '{cd}', 'mst_medicine', 110, TRUE, NULL, NULL, NULL),
    (305, 'ord_material_save', 'COLUMN', 'supplies_base_no', NULL, NULL, 'ord_main', 110, TRUE, NULL,'supplies_source_class IN (''0'',''1'',''2'',''3'')',NULL),
    (306, 'ord_material_save', 'COLUMN', 'supplies_base_no', NULL, NULL, 'ord_prescription', 110, TRUE,NULL, 'supplies_source_class = ''4''', NULL),
    (307, 'ord_material_save', 'COLUMN', 'supplies_cd', NULL, NULL, 'mst_dialyzer', 110, TRUE, NULL,'supplies_class = ''01''', NULL),
    (308, 'ord_material_save', 'COLUMN', 'supplies_cd', NULL, NULL, 'mst_equipment', 110, TRUE, NULL,'supplies_class IN (''00'',''02'',''03'',''04'',''05'',''06'',''07'',''11'')', NULL),
    (309, 'ord_material_save', 'COLUMN', 'supplies_cd', NULL, NULL, 'mst_medicine', 110, TRUE, NULL,'supplies_class IN (''08'',''09'',''10'',''12'',''14'',''16'',''20'',''21'',''22'',''23'')', NULL),
    (310, 'ord_material_save', 'COLUMN', 'supplies_cd', NULL, NULL, 'mst_medicine_mix', 110, TRUE, NULL,'supplies_class IN (''13'',''15'',''17'')', NULL),
    (311, 'ord_material_save', 'COLUMN', 'timing_cd', NULL, NULL, 'mst_medicate_timing', 110, TRUE, NULL, NULL,NULL),
    (312, 'ord_personal_prescription', 'COLUMN', 'insurance_cd', NULL, NULL, 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (313, 'ord_personal_prescription', 'JSON', NULL, 'insu_set_info', '[].insu_cd', 'pat_insurance', 200, TRUE, NULL,NULL, NULL),
    (314, 'ord_personal_prescription', 'JSON', NULL, 'insu_set_info', '[].insu_pub1_cd', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (315, 'ord_personal_prescription', 'JSON', NULL, 'insu_set_info', '[].insu_pub2_cd', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (316, 'ord_personal_prescription', 'JSON', NULL, 'insu_set_info', '[].insu_pub3_cd', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (317, 'ord_personal_prescription', 'JSON', NULL, 'insu_set_info', '[].insu_pub4_cd', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (318, 'ord_personal_prescription', 'COLUMN', 'pat_id', NULL, NULL, 'pat_personal_main', 200, TRUE, NULL, NULL,NULL),
    (319, 'ord_prescription', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL,NULL),
    (320, 'ord_prescription', 'JSON', NULL, 'prescription_detail', '[].medicine_cd', 'mst_medicine', 110, TRUE, '(prescription_detail->> ''medicine_type'') ~ ''^[0-9]+$'' AND (prescription_detail->>''medicine_type'')::int = 1', NULL,NULL),
    (321, 'ord_prescription', 'JSON', NULL, 'prescription_detail', '[].medicine_cd', 'mst_medicine_mix', 110, TRUE, '(prescription_detail->> ''medicine_type'') ~ ''^[0-9]+$'' AND (prescription_detail->>''medicine_type'')::int = 2', NULL,NULL),
    (322, 'ord_schedule', 'COLUMN', 'bed_cd', NULL, NULL, 'mst_bed', 110, TRUE, NULL, NULL,NULL),
    (323, 'ord_schedule', 'COLUMN', 'kur_cd', NULL, NULL, 'mst_kur', 110, TRUE, NULL, NULL,NULL),
    (324, 'ord_schedule', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (325, 'ord_schedule', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL,NULL),
    (326, 'ord_treat_condition', 'COLUMN', 'machine_no', NULL, NULL, 'mst_machine', 110, TRUE, NULL, NULL,NULL),
    (327, 'ord_treat_condition', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (328, 'ord_weight_scale', 'COLUMN', 'bed_cd', NULL, NULL, 'mst_bed', 110, TRUE, NULL, NULL,NULL),
    (329, 'ord_weight_scale', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (330, 'ord_weight_scale', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 110, TRUE, NULL, NULL,NULL),
    (331, 'pat_coop_detail', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (332, 'pat_event', 'JSON', NULL, 'letter_info', '{report_cd}', 'mst_report', 110, TRUE, NULL, NULL,NULL),
    (333, 'pat_event', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (334, 'pat_event', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (335, 'pat_event', 'JSON', NULL, 'reg_staff_info', '{reg_staff_cd}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (336, 'pat_event', 'JSON', NULL, 'result_params', '[].va_cd', 'mst_va', 110, TRUE, NULL, NULL,NULL),
    (337, 'pat_event', 'JSON', NULL, 'up_staff_info', '{up_staff_cd}', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (338, 'pat_exam_main', 'JSON', NULL, 'exam_order_info', '[].item_cd', 'mst_exam_item', 110, TRUE, NULL, NULL,NULL),
    (339, 'pat_exam_main', 'JSON', NULL, 'exam_order_info', '[].set_cd', 'mst_exam_set', 110, TRUE, NULL, NULL,NULL),
    (340, 'pat_exam_main', 'JSON', NULL, 'exam_result_info', '[].item_cd', 'mst_exam_item', 110, TRUE, NULL, NULL,NULL),
    (341, 'pat_exam_main', 'JSON', NULL, 'order_exam_set_info', '[].set_cd', 'mst_exam_set', 110, TRUE, NULL, NULL,NULL),
    (342, 'pat_exam_main', 'JSON', NULL, 'order_label_info', '[].spitz_cd', 'mst_spitz', 110, TRUE, NULL, NULL,NULL),
    (343, 'pat_exam_main', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (344, 'pat_exam_main', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (345, 'pat_exam_main_hst', 'JSON', NULL, 'exam_order_info', '[].item_cd', 'mst_exam_item', 110, TRUE, NULL, NULL,NULL),
    (346, 'pat_exam_main_hst', 'JSON', NULL, 'exam_order_info', '[].set_cd', 'mst_exam_set', 110, TRUE, NULL, NULL,NULL),
    (347, 'pat_exam_main_hst', 'JSON', NULL, 'exam_result_info', '[].item_cd', 'mst_exam_item', 110, TRUE, NULL, NULL,NULL),
    (348, 'pat_exam_main_hst', 'JSON', NULL, 'order_exam_set_info', '[].set_cd', 'mst_exam_set', 110, TRUE, NULL, NULL,NULL),
    (349, 'pat_exam_main_hst', 'JSON', NULL, 'order_label_info', '[].spitz_cd', 'mst_spitz', 110, TRUE, NULL, NULL,NULL),
    (350, 'pat_exam_main_hst', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (351, 'pat_exam_main_hst', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (352, 'pat_exam_pattern', 'JSON', NULL, 'exam_order_info', '[].exam_item_cd', 'mst_exam_item', 110, TRUE, NULL, NULL,NULL),
    (353, 'pat_exam_pattern', 'COLUMN', 'order_exam_set_cd', NULL, NULL, 'mst_exam_set', 110, TRUE, NULL, NULL,NULL),
    (354, 'pat_exam_pattern', 'JSON', NULL, 'order_label_info', '[].spitz_cd', 'mst_spitz', 110, TRUE, NULL, NULL,NULL),
    (355, 'pat_group_detail', 'COLUMN', 'pat_group_cd', NULL, NULL, 'pat_group', 100, TRUE, NULL, NULL,NULL),
    (356, 'pat_group_detail', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (357, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'itemInfo.itemCd', 'mst_treatment', 100, TRUE, '{"entry.component":"treat-method"}', NULL,NULL),
    (358, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_bed', 100, TRUE, '{"entry.component":"schedule","item.itemNo":"3"}', NULL,NULL),
    (359, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_dialyzer', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"5"}', NULL,NULL),
    (360, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_dialyzer', 100, TRUE, '{"entry.component":"equipment","item.itemType":"1"}', NULL,NULL),
    (361, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_equipment', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":["6","7","8","9","10","11","13"]}', NULL,NULL),
    (362, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_equipment', 100, TRUE, '{"entry.component":"equipment","item.itemType":"0"}', NULL,NULL),
    (363, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_kur', 100, TRUE, '{"entry.component":"schedule","item.itemNo":"1"}', NULL,NULL),
    (364, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":["15","19","25"],"item.itemType":"1"}', NULL,NULL),
    (365, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine', 100, TRUE, '{"entry.component":"medicine","item.itemType":"1"}', NULL,NULL),
    (366, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine_mix', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"25","item.itemType":"2"}', NULL,NULL),
    (367, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine_mix', 100, TRUE, '{"entry.component":"medicine","item.itemType":"2"}', NULL,NULL),
    (368, 'pat_ind_approve', 'JSON', NULL, 'approve_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_va', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"2"}', NULL,NULL),
    (369, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'itemInfo.itemCd', 'mst_treatment', 100, TRUE, '{"entry.component":"treat-method"}', NULL,NULL),
    (370, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_bed', 100, TRUE, '{"entry.component":"schedule","item.itemNo":"3"}', NULL,NULL),
    (371, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_dialyzer', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"5"}', NULL,NULL),
    (372, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_dialyzer', 100, TRUE, '{"entry.component":"equipment","item.itemType":"1"}', NULL,NULL),
    (373, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_equipment', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":["6","7","8","9","10","11","13"]}', NULL,NULL),
    (374, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_equipment', 100, TRUE, '{"entry.component":"equipment","item.itemType":"0"}', NULL,NULL),
    (375, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_kur', 100, TRUE, '{"entry.component":"schedule","item.itemNo":"1"}', NULL,NULL),
    (376, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":["15","19","25"],"item.itemType":"1"}', NULL,NULL),
    (377, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine', 100, TRUE, '{"entry.component":"medicine","item.itemType":"1"}', NULL,NULL),
    (378, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine_mix', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"25","item.itemType":"2"}', NULL,NULL),
    (379, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine_mix', 100, TRUE, '{"entry.component":"medicine","item.itemType":"2"}', NULL,NULL),
    (380, 'pat_ind_approve', 'JSON', NULL, 'check_content', 'subCategoryItem.[].itemInfo.itemCd', 'mst_va', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"2"}', NULL,NULL),
    (381, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'itemInfo.itemCd', 'mst_treatment', 100, TRUE, '{"entry.component":"treat-method"}', NULL,NULL),
    (382, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_bed', 100, TRUE, '{"entry.component":"schedule","item.itemNo":"3"}', NULL,NULL),
    (383, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_dialyzer', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"5"}', NULL,NULL),
    (384, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_dialyzer', 100, TRUE, '{"entry.component":"equipment","item.itemType":"1"}', NULL,NULL),
    (385, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_equipment', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":["6","7","8","9","10","11","13"]}', NULL,NULL),
    (386, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_equipment', 100, TRUE, '{"entry.component":"equipment","item.itemType":"0"}', NULL,NULL),
    (387, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_kur', 100, TRUE, '{"entry.component":"schedule","item.itemNo":"1"}', NULL,NULL),
    (388, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":["15","19","25"],"item.itemType":"1"}', NULL,NULL),
    (389, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine', 100, TRUE, '{"entry.component":"medicine","item.itemType":"1"}', NULL,NULL),
    (390, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine_mix', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"25","item.itemType":"2"}', NULL,NULL),
    (391, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_medicine_mix', 100, TRUE, '{"entry.component":"medicine","item.itemType":"2"}', NULL,NULL),
    (392, 'pat_ind_approve', 'JSON', NULL, 'content_for_map', 'subCategoryItem.[].itemInfo.itemCd', 'mst_va', 100, TRUE, '{"entry.component":"treat-cond","item.itemNo":"2"}', NULL,NULL),
    --(393, 'pat_ind_approve', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (394, 'pat_ind_approve_history', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (395, 'pat_ind_approve_history', 'COLUMN', 'approve_bef_id', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (396, 'pat_ind_approve_history', 'COLUMN', 'approve_aft_id', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (397, 'pat_ind_approve_history', 'COLUMN', 'user_id', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (398, 'pat_insurance', 'JSON', NULL, 'insu_set_info', '{insu_cd}', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (399, 'pat_insurance', 'JSON', NULL, 'insu_set_info', '{insu_pub1_cd}', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (400, 'pat_insurance', 'JSON', NULL, 'insu_set_info', '{insu_pub2_cd}', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (401, 'pat_insurance', 'JSON', NULL, 'insu_set_info', '{insu_pub3_cd}', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (402, 'pat_insurance', 'JSON', NULL, 'insu_set_info', '{insu_pub4_cd}', 'pat_insurance', 200, TRUE, NULL, NULL,NULL),
    (403, 'pat_insurance', 'COLUMN', 'pat_id', NULL, NULL, 'pat_personal_main', 200, TRUE, NULL, NULL,NULL),
    (404, 'pat_main', 'JSON', NULL, 'acceptance_status_info', '[].ord_no', 'ord_main', 100, TRUE, NULL, NULL,NULL),
    (405, 'pat_main', 'JSON', NULL, 'addition_info', '[].cd', 'mst_addition', 100, TRUE, NULL, NULL,NULL),
    (406, 'pat_main', 'JSON', NULL, 'charge_staff_info', '[].staff_cd', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (407, 'pat_main', 'JSON', NULL, 'implant_info', '[].implant_cd', 'mst_implant', 100, TRUE, NULL, NULL,NULL),
    (408, 'pat_main', 'JSON', NULL, 'infect_info', '[].infection_cd', 'mst_infection', 100, TRUE, NULL, NULL,NULL),
    (409, 'pat_main', 'JSON', NULL, 'medical_care_info', '{dialysis_course_cd}', 'mst_course', 100, TRUE, NULL, NULL,NULL),
    (410, 'pat_main', 'JSON', NULL, 'medical_care_info', '{main_course_cd}', 'mst_course', 100, TRUE, NULL, NULL,NULL),
    (411, 'pat_main', 'JSON', NULL, 'medical_care_info', '{ward_cd}', 'mst_ward', 100, TRUE, NULL, NULL,NULL),
    (412, 'pat_main', 'JSON', NULL, 'pat_group_info', '[].patGroupCd', 'pat_group', 100, TRUE, NULL, NULL,NULL),
    (413, 'pat_main', 'JSON', NULL, 'taboo_allergy_info', '[].taboo_allergy_cd', 'mst_taboo_allergy', 100, TRUE, NULL, NULL,NULL),
    (414, 'pat_personal_main', 'JSON', NULL, 'dial_diff_com_info', '[].dial_diff_cd', 'mst_dialysis_difficulty', 200, TRUE, NULL, NULL,NULL),
    (415, 'pat_personal_main', 'JSON', NULL, 'other_contact_info', '[].relation_cd', 'mst_relationship', 200, TRUE, NULL, NULL,NULL),
    (416, 'pat_rad_main', 'COLUMN', 'cop_order_no1', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (417, 'pat_rad_main', 'COLUMN', 'cop_order_no2', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (418, 'pat_rad_main', 'COLUMN', 'ind_user_id', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (419, 'pat_rad_main', 'JSON', NULL, 'order_rad_set_info', '[].rad_set_cd', 'mst_rad_set', 110, TRUE, NULL, NULL,NULL),
    (420, 'pat_rad_main', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (421, 'pat_rad_main', 'COLUMN', 'reg_staff', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (422, 'pat_rad_main', 'COLUMN', 'up_staff', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (423, 'pat_rad_main_hst', 'COLUMN', 'cop_order_no1', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (424, 'pat_rad_main_hst', 'COLUMN', 'cop_order_no2', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (425, 'pat_rad_main_hst', 'COLUMN', 'ind_user_id', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (426, 'pat_rad_main_hst', 'JSON', NULL, 'order_rad_set_info', '[].rad_set_cd', 'mst_rad_set', 110, TRUE, NULL, NULL,NULL),
    (427, 'pat_rad_main_hst', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (428, 'pat_rad_main_hst', 'COLUMN', 'reg_staff', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (429, 'pat_rad_main_hst', 'COLUMN', 'up_staff', NULL, NULL, 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (430, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{10,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (431, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{11,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (432, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{13,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (433, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine', 100, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 1', NULL,NULL),
    (434, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{15,value}', 'mst_medicine_mix', 100, TRUE, '(ind_cond_info->''15''->>''medicine_type'')::int = 2', NULL,NULL),
    (435, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine', 100, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 1', NULL,NULL),
    (436, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{19,value}', 'mst_medicine_mix', 100, TRUE, '(ind_cond_info->''19''->>''medicine_type'')::int = 2', NULL,NULL),
    (437, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine', 100, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 1', NULL,NULL),
    (438, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{25,value}', 'mst_medicine_mix', 100, TRUE, '(ind_cond_info->''25''->>''medicine_type'')::int = 2', NULL,NULL),
    (439, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{2,value}', 'mst_va', 100, TRUE, NULL, NULL,NULL),
    (440, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{5,value}', 'mst_dialyzer', 100, TRUE, NULL, NULL,NULL),
    (441, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{6,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (442, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{7,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (443, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{8,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (444, 'pat_treatment_pattern', 'JSON', NULL, 'ind_cond_info', '{9,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (445, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{bvufc,ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (446, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{bvufc,upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (447, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{dc,ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (448, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{dc,upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (449, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{dia,ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (450, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{dia,upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (451, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{ihdf,ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (452, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{ihdf,upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (453, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{na,ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (454, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{na,upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (455, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{qbqd,ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (456, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{qbqd,upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (457, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{ufr,ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (458, 'pat_treatment_pattern', 'JSON', NULL, 'ind_device_set_info', '{ufr,upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (459, 'pat_treatment_pattern', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_dialyzer', 100, TRUE, '(ind_equip_info->>''equip_type'')::int = 1', NULL,NULL),
    (460, 'pat_treatment_pattern', 'JSON', NULL, 'ind_equip_info', '[].cd', 'mst_equipment', 100, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (461, 'pat_treatment_pattern', 'JSON', NULL, 'ind_equip_info', '[].class_cd', 'mst_equipment_class', 100, TRUE, '(ind_equip_info->>''equip_type'')::int = 0', NULL,NULL),
    (462, 'pat_treatment_pattern', 'COLUMN', 'ind_kur_cd', NULL, NULL, 'mst_kur', 100, TRUE, NULL, NULL,NULL),
    (463, 'pat_treatment_pattern', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine', 100, TRUE, '(ind_medi_info->>''medicine_type'')::int = 1', NULL,NULL),
    (464, 'pat_treatment_pattern', 'JSON', NULL, 'ind_medi_info', '[].cd', 'mst_medicine_mix', 100, TRUE, '(ind_medi_info->>''medicine_type'')::int = 2', NULL,NULL),
    (465, 'pat_treatment_pattern', 'JSON', NULL, 'ind_medi_info', '[].procedure_cd', 'mst_procedure', 100, TRUE, NULL, NULL,NULL),
    (466, 'pat_treatment_pattern', 'JSON', NULL, 'ind_medi_info', '[].timing_cd', 'mst_medicate_timing', 100, TRUE, NULL, NULL,NULL),
    (467, 'pat_treatment_pattern', 'JSON', NULL, 'ind_sch_info', '{ind_bed_cd}', 'mst_bed', 100, TRUE, NULL, NULL,NULL),
    (468, 'pat_treatment_pattern', 'JSON', NULL, 'ind_sch_info', '{ind_kur_cd_before}', 'mst_kur', 100, TRUE, NULL, NULL,NULL),
    (469, 'pat_treatment_pattern', 'JSON', NULL, 'ind_sch_info', '{ind_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (470, 'pat_treatment_pattern', 'JSON', NULL, 'ind_sch_info', '{upd_user_id}', 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (471, 'pat_treatment_pattern', 'COLUMN', 'ind_treatment_cd', NULL, NULL, 'mst_treatment', 100, TRUE, NULL, NULL,NULL),
    (472, 'pat_unique', 'JSON', NULL, 'medical_hst_info', '[].diagnostician_cd', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (473, 'pat_unique', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (474, 'pat_unique', 'JSON', NULL, 'physical_info', '[].indicator_cd', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (475, 'sys_notification_list', 'COLUMN', 'user_id', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (476, 'sys_signin_manager', 'COLUMN', 'user_id', NULL, NULL, 'mst_user_authentication', 20, TRUE, NULL, NULL,NULL),
    (477, 'pat_unique', 'JSON', NULL, 'medical_hst_info', '[].disease_cd', 'mst_disease', 110, TRUE, NULL, NULL,NULL),
    (478, 'pat_unique', 'JSON', NULL, 'medical_hst_info', '[].course_cd', 'mst_course', 110, TRUE, NULL, NULL,NULL),
    (479, 'pat_main', 'COLUMN', 'wheel_chair_cd', NULL, NULL, 'mst_wheel_chair', 100, TRUE, NULL, NULL,NULL),
    (480, 'pat_personal_main', 'COLUMN', 'severity_cd', NULL, NULL, 'mst_severity', 100, TRUE, NULL, NULL,NULL),
    (481, 'pat_personal_main', 'COLUMN', 'transport_cd', NULL, NULL, 'mst_transport', 100, TRUE, NULL, NULL,NULL),
    (482, 'pat_personal_main', 'COLUMN', 'primary_disease_cd', NULL, NULL, 'mst_disease', 100, TRUE, NULL, NULL,NULL),
    (483, 'pat_ind_approve', 'COLUMN', 'check_user1_cd', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (484, 'pat_ind_approve', 'COLUMN', 'check_user2_cd', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (485, 'pat_ind_approve', 'COLUMN', 'approve_user1_cd', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (486, 'pat_ind_approve', 'COLUMN', 'approve_user2_cd', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (487, 'ord_personal_prescription', 'COLUMN', 'ord_prescription_no', NULL, NULL, 'ord_prescription', 100, TRUE, NULL, NULL,NULL),
    (488, 'mst_wheel_chair', 'COLUMN', 'scale_user_id', NULL, NULL, 'mst_user', 100, TRUE, NULL, NULL,NULL),
    (489, 'mst_mainte_category_hst', 'JSON', NULL, 'detail', '[].code', 'mst_mainte_detail', 100, TRUE, NULL,'mainte_class = ''2''', NULL),
    (490, 'pat_unique', 'JSON', NULL, 'in_out_visit_history_info', '[].to_course', 'mst_course', 110, TRUE, NULL, NULL,NULL),
    (491, 'pat_unique', 'JSON', NULL, 'in_out_visit_history_info', '[].to_doctor', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (492, 'pat_unique', 'JSON', NULL, 'in_out_visit_history_info', '[].from_course', 'mst_course', 110, TRUE, NULL, NULL,NULL),
    (493, 'pat_unique', 'JSON', NULL, 'in_out_visit_history_info', '[].from_doctor', 'mst_user', 110, TRUE, NULL, NULL,NULL),
    (494, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{15,value}', 'mst_medicine', 110, TRUE, '(rst_cond_info->''15''->>''medicine_type'')::int = 1', NULL,NULL),
    (495, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{15,value}', 'mst_medicine_mix', 110, TRUE, '(rst_cond_info->''15''->>''medicine_type'')::int = 2', NULL,NULL),
    (496, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{25,value}', 'mst_medicine', 110, TRUE, '(rst_cond_info->''25''->>''medicine_type'')::int = 1', NULL,NULL),
    (497, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{25,value}', 'mst_medicine_mix', 110, TRUE, '(rst_cond_info->''25''->>''medicine_type'')::int = 2', NULL,NULL),
    (498, 'ord_checklist', 'COLUMN', 'ord_no', NULL, NULL, 'ord_main', 110, TRUE, NULL, NULL,NULL),
    (499, 'mnt_mainte_main', 'COLUMN', 'mainte_layout_cd', NULL, NULL, 'mst_mainte_layout', 100, TRUE, NULL, NULL,NULL),
    (500, 'mst_treatment_set', 'COLUMN', 'treatment_cd', NULL, NULL, 'mst_treatment', 100, TRUE, NULL, NULL,NULL),
    (501, 'mst_equipment', 'COLUMN', 'class_cd', NULL, NULL, 'mst_equipment_class', 100, TRUE, NULL, NULL,NULL),
    (502, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{2,value}', 'mst_va', 110, TRUE, NULL, NULL,NULL),
    (503, 'mst_water_survey_point', 'COLUMN', 'survey_type_cd', NULL, NULL, 'mst_water_survey_type', 100, TRUE, NULL, NULL,NULL),
    (504,'mst_mainte_layout_group', 'JsonIntArray', NULL, 'layout_list', '[]', 'mst_mainte_layout', 100, 't', NULL, NULL,NULL),
    (505,'mst_mainte_layout_group_hst', 'JsonIntArray', NULL, 'layout_list', '[]', 'mst_mainte_layout', 100, 't', NULL, NULL,NULL),
    (506, 'mst_equipment', 'COLUMN', 'class_cd', NULL, NULL, 'mst_equipment_class', 100, TRUE, NULL, NULL,NULL),
    (508, 'mst_room_bed_group', 'JsonIntArray', NULL,'bed_list',  '[]', 'mst_bed', 100, TRUE, NULL, NULL,NULL),
    (509, 'mnt_mainte_main', 'COLUMN', 'mainte_layout_group_cd', NULL, NULL, 'mst_mainte_layout_group', 100, TRUE, NULL, NULL,NULL),
    (510, 'mst_wheel_chair', 'COLUMN', 'pat_id', NULL, NULL, 'pat_main', 100, TRUE, NULL, NULL,NULL),
    (511, 'mst_water_survey_point', 'COLUMN', 'machine_no', NULL, NULL, 'mst_machine', 100, TRUE, NULL, NULL,NULL),
    (512, 'mst_mainte_category', 'JSON', NULL, 'detail', 'detail_list.[].code', 'mst_mainte_detail', 100, TRUE, NULL,'mainte_class = ''1''', NULL),
    (513, 'mst_mainte_category_hst', 'JSON', NULL, 'detail', 'detail_list.[].code', 'mst_mainte_detail', 100, TRUE, NULL,'mainte_class = ''1''', NULL),
    (514, 'mnt_mainte_main', 'JSON', NULL, 'detail', '[].[].cate_cd', 'mst_mainte_category', 100, TRUE, NULL,'mainte_class=''2''', NULL),
    (515, 'mnt_mainte_main', 'JSON', NULL, 'detail', '[].[].detail_cd', 'mst_mainte_detail', 100, TRUE, NULL,'mainte_class=''2''', NULL),
    (516, 'mnt_mainte_main', 'JSON', NULL, 'detail', '[].[].user_id', 'mst_personal_user', 100, TRUE, NULL,'mainte_class=''2''', NULL),
    (517, 'mnt_mainte_main', 'COLUMN', 'checker_id_1', NULL, NULL, 'mst_personal_user', 100, TRUE, NULL, NULL,NULL),
    (518, 'mnt_mainte_main', 'COLUMN', 'checker_id_2', NULL, NULL, 'mst_personal_user', 100, TRUE, NULL, NULL,NULL),
    (519, 'mnt_mainte_main', 'JSON', NULL, 'mainte_category_cd', '[].mainteCategoryCd', 'mst_mainte_category', 100, TRUE, NULL,'mainte_class=''1''', NULL),
    (520, 'mst_mainte_layout_hst', 'JSON', NULL, 'detail_info_1', '[].cd', 'mst_mainte_category', 100, TRUE, NULL, NULL,NULL),
    (521, 'mst_mainte_layout_hst', 'JSON', NULL, 'detail_info_2', '[].cd', 'mst_mainte_category', 100, TRUE, NULL, 'layout_class = ''2''',NULL),
    (522, 'mst_addition', 'JSON', NULL, 'addition_tar_cd', '[].cd', 'mst_dialysis_difficulty', 100, TRUE, NULL,'addition_class = ''2''',NULL),
    (523, 'mst_pat_event_sub_category', 'COLUMN', 'category_cd', null, null, 'mst_pat_event_category', 100, TRUE, NULL,NULL,NULL),
    (524, 'mst_pat_event_sub_category', 'COLUMN', 'template_cd', null, null, 'mst_pat_event_data_template', 100, TRUE, NULL,NULL,NULL),
    (525, 'mst_medicine', 'COLUMN', 'class_cd', null, null, 'mst_medicine_class', 100, TRUE, NULL,NULL,NULL),
    (526, 'mst_medicine', 'COLUMN', 'procedure_cd', null, null, 'mst_procedure', 100, TRUE, NULL,NULL,NULL),
    (527, 'mst_medicine', 'COLUMN', 'medicate_timing_cd', null, null, 'mst_medicate_timing', 100, TRUE, NULL,NULL,NULL),
    (528, 'mst_medicine_mix', 'COLUMN', 'class_cd', null, null, 'mst_medicine_class', 100, TRUE, NULL,NULL,NULL),
    (529, 'ord_personal_prescription', 'COLUMN', 'insu_dr_id', NULL, NULL, 'mst_personal_user', 200, TRUE, NULL, NULL,NULL),
    (530,'mst_com_fixed_phrase', 'JsonIntArray', NULL, 'occupations', '[]', 'mst_job', 100, 't', NULL, NULL,NULL),
    (531, 'mst_medicine_mix', 'COLUMN', 'medicate_timing_cd', null, null, 'mst_medicate_timing', 100, TRUE, NULL,NULL,NULL),
    (532, 'mst_medicine_mix', 'COLUMN', 'procedure_cd', null, null, 'mst_procedure', 100, TRUE, NULL,NULL,NULL),
    (533, 'mst_medicine_set', 'JSON', NULL, 'set_info', '[].cd', 'mst_medicine', 100, TRUE, '(set_info->>''class'') = ''1''',NULL, NULL),
    (534, 'mst_medicine_set', 'JSON', NULL, 'set_info', '[].cd', 'mst_medicine_mix', 100, TRUE, '(set_info->>''class'') = ''2''',NULL, NULL),
    (535, 'mst_medicine_set', 'JSON', NULL, 'set_info', '[].medicate_timing_cd', 'mst_medicate_timing', 100, TRUE, NULL,NULL, NULL),
    (536, 'mst_medicine_set', 'JSON', NULL, 'set_info', '[].procedure_timing_cd', 'mst_procedure', 100, TRUE, NULL,NULL, NULL),
    (537, 'mst_equipment_set', 'JSON', NULL, 'set_info', '[].cd', 'mst_equipment', 100, TRUE, NULL,NULL, NULL),
    (538, 'mst_equipment_set', 'JSON', NULL, 'set_info', '[].equip_type', 'mst_equipment_class', 100, TRUE, NULL,NULL, NULL),
    (539, 'mst_medicine_support', 'JSON', NULL, 'detail_info', 'examItemRegression.[].value', 'mst_exam_item', 100, TRUE, NULL, NULL, NULL),
    (540, 'mst_medicine_support', 'JSON', NULL, 'detail_info', 'medicineESA.[].value', 'mst_medicine_group', 100, TRUE, NULL, NULL, NULL),
    (541, 'mst_medicine_support', 'JSON', NULL, 'detail_info', 'medicineAverage.[].value', 'mst_medicine', 100, TRUE, '(detail_info->>''type'')::int = 1', NULL, NULL),
    (542, 'mst_medicine_support', 'JSON', NULL, 'detail_info', 'medicineAverage.[].value', 'mst_medicine_mix', 100, TRUE, '(detail_info->>''type'')::int = 2', NULL, NULL),
    (543, 'mst_medicine_support', 'JSON', NULL, 'detail_info', 'medicineAverage.[].value', 'mst_medicine_group', 100, TRUE, '(detail_info->>''type'')::int = 3', NULL, NULL),
    (544, 'mst_comp_treatment', 'COLUMN', 'treat_medicine_cd', null, null, 'mst_medicine', 100, TRUE, NULL,'treat_class=''1''',NULL),
    (545, 'mst_comp_treatment', 'COLUMN', 'treat_medicine_cd', null, null, 'mst_medicine_mix', 100, TRUE, NULL,'treat_class=''0''',NULL),
    (546, 'mst_comp_treatment', 'COLUMN', 'procedure_cd', null, null, 'mst_procedure', 100, TRUE, NULL,NULL,NULL),
    (547, 'mst_exam_item', 'COLUMN', 'spitz_cd', null, null, 'mst_spitz', 100, TRUE, NULL,NULL,NULL),
    (548, 'mst_graph_setting', 'COLUMN', 'value', null, null, 'pat_group', 100, TRUE, NULL,'graph_setting_no in(''34'',''35'',''36'',''37'',''38'',''39'',''40'',''41'',''42'')',NULL),
    (549, 'mst_graph_setting', 'COLUMN', 'value', null, null, 'mst_exam_item', 100, TRUE, NULL,'graph_setting_no in(''2'',''3'')',NULL),
    (550, 'mst_prescription_set', 'JSON', NULL, 'set_info', '[].medicine_cd', 'mst_medicine', 110, TRUE, '(set_info->> ''medicine_type'') ~ ''^[0-9]+$'' AND (set_info->>''medicine_type'')::int = 1', NULL,NULL),
    (551, 'mst_prescription_set', 'JSON', NULL, 'set_info', '[].medicine_cd', 'mst_medicine_mix', 110, TRUE, '(set_info->> ''medicine_type'') ~ ''^[0-9]+$'' AND (set_info->>''medicine_type'')::int = 2', NULL,NULL),
    (552, 'mst_exam_item', 'COLUMN', 'infection_cd', null, null, 'mst_infection', 100, TRUE, NULL,NULL,NULL),
    (553, 'mst_facility_calendar_layout', 'JSON', null, 'disp_item_info', '[].cd', 'mst_kur', 100, TRUE, '(disp_item_info->>''key'')= ''treatments_by_course_number''',NULL,NULL),
    (554, 'mst_facility_calendar_layout', 'JSON', null, 'disp_item_info', '[].cd', 'mst_pat_event_category', 100, TRUE, '(disp_item_info->>''key'')= ''repeat_pat_event_category''',NULL,NULL),
    (555, 'mst_facility_calendar_layout', 'JSON', null, 'disp_item_info', '[].cd', 'mst_bbs_kind', 100, TRUE, '(disp_item_info->>''key'')= ''repeat_facility_event_categories''',NULL,NULL),
    (556, 'mst_pat_calendar_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_pat_event_sub_category', 100, TRUE, '(disp_item_info->>''categoryName'')= ''患者イベント''', NULL, NULL),
    (557, 'mst_pat_calendar_layout', 'JSON', NULL, 'disp_item_info', '[].categoryItem.[].subCategoryItem.[].itemNo', 'mst_bbs_kind', 100, TRUE, '(disp_item_info->>''categoryName'')= ''施設イベント''', NULL, NULL),
    (558, 'mst_pat_viewer_layout', 'JSON', NULL, 'disp_item_info', '[].medicineGroupCd', 'mst_medicine_support', 100, TRUE, '(disp_item_info->>''categoryNo'')::int= 1028', NULL, NULL),
    (559, 'mst_status_map_bed_layout', 'JSON', NULL, 'bed_layout', 'obj_list.[].bed_cd', 'mst_bed', 100, TRUE, NULL, NULL, NULL),
    (560, 'bbs_info', 'JsonIntArray', NULL, 'pat_info', 'detail', 'pat_personal_main', 100, TRUE, NULL, NULL,NULL),
    (561, 'mst_function_report', 'COLUMN', 'report_cd', null, null, 'mst_report', 100, TRUE, NULL,NULL,NULL),
    (562, 'pat_personal_main', 'COLUMN', 'die_cd', null, null, 'mst_disease', 100, TRUE, NULL,NULL,NULL),
    (563, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_mainte_layout_group', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int in(1391,1351) ', 'template_cd in (12,9)',NULL),
    (564, 'ord_main', 'JSON', NULL, 'ind_ind_comment_info', '[].ind_user_id', 'mst_personal_user', 100, TRUE, NULL, NULL, NULL),
    (565, 'ord_main', 'JSON', NULL, 'ind_ind_comment_info', '[].upd_user_id', 'mst_personal_user', 100, TRUE, NULL, NULL, NULL),
    (567, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{10,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (568, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{11,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (569, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{13,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (570, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{19,value}', 'mst_medicine', 100, TRUE, '(rst_cond_info->''19''->>''medicine_type'')::int = 1', NULL,NULL),
    (571, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{19,value}', 'mst_medicine_mix', 100, TRUE, '(rst_cond_info->''19''->>''medicine_type'')::int = 2', NULL,NULL),
    (572, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{5,value}', 'mst_dialyzer', 100, TRUE, NULL, NULL,NULL),
    (583, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{6,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (584, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{7,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (585, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{8,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (586, 'ord_main', 'JSON', NULL, 'rst_cond_info', '{9,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (587, 'ord_main', 'JSON', NULL, 'rst_tare_info', '{after,wheel_chair_cd}', 'mst_wheel_chair', 100, TRUE, NULL, NULL,NULL),
    (588, 'ord_main', 'JSON', NULL, 'rst_tare_info', '{before,wheel_chair_cd}', 'mst_wheel_chair', 100, TRUE, NULL, NULL,NULL),
    (589, 'ord_main', 'JSON', NULL, 'rst_complaint_info', '[].comp_cd', 'mst_complaint', 100, TRUE, NULL, NULL,NULL),
    (590, 'ord_main', 'JSON', NULL, 'rst_rounds_info', '{round_type_cd}', 'mst_round_type', 100, TRUE, NULL, NULL,NULL),
    (591, 'ord_main', 'COLUMN', 'up_ind_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (592, 'ord_main', 'COLUMN', 'up_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (593, 'ord_main', 'JSON', NULL, 'rst_rounds_info', '{create_user_id}', 'mst_personal_user', 100, TRUE, NULL, NULL,NULL),
    (594, 'mni_monitor', 'COLUMN', 'upd_staff_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (595, 'pat_event', 'COLUMN', 'sub_category_cd', null, null, 'mst_pat_event_sub_category', 100, TRUE, NULL,NULL,NULL),
    (596, 'pat_event', 'COLUMN', 'category_cd', null, null, 'mst_pat_event_category', 100, TRUE, NULL,NULL,NULL),
    (597, 'pat_event', 'COLUMN', 'template_cd', null, null, 'mst_pat_event_data_template', 100, TRUE, NULL,NULL,NULL),
    (598, 'pat_event', 'COLUMN', 'bbs_ctl_no', null, null, 'bbs_info', 100, TRUE, NULL,NULL,NULL),
    (599, 'ord_weight_scale', 'COLUMN', 'weight_cd', null, null, 'mst_weight', 100, TRUE, NULL,NULL,NULL),
    (600, 'ord_weight_scale', 'COLUMN', 'kur_cd', null, null, 'mst_kur', 100, TRUE, NULL,NULL,NULL),
    (601, 'ord_weight_scale', 'COLUMN', 'wheel_chair_cd', null, null, 'mst_wheel_chair', 100, TRUE, NULL,NULL,NULL),
    (602, 'ord_weight_scale', 'COLUMN', 'user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (603, 'ord_weight_scale', 'COLUMN', 'treatment_cd', null, null, 'mst_treatment', 100, TRUE, NULL,NULL,NULL),
    (604, 'bbs_info', 'COLUMN', 'reg_staff_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (605, 'bbs_info', 'COLUMN', 'upd_staff_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (606, 'pat_event', 'JSON', null,'input_params',  '[].item_json.kind_no', 'mst_bbs_kind', 100, TRUE, NULL,NULL,NULL),
    (607, 'pat_event', 'JsonIntArray', null,'result_params',  '[].result_value.staff_info.staff_cd', 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (608, 'pat_exam_main', 'COLUMN', 'ind_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (609, 'pat_exam_main', 'COLUMN', 'reg_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (610, 'pat_exam_main', 'COLUMN', 'up_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (611, 'pat_exam_main_hst', 'COLUMN', 'ind_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (612, 'pat_exam_main_hst', 'COLUMN', 'reg_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (613, 'pat_exam_main_hst', 'COLUMN', 'up_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (614, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{15,value}', 'mst_medicine', 110, TRUE, '(rst_cond_info->''15''->>''medicine_type'')::int = 1', NULL,NULL),
    (615, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{15,value}', 'mst_medicine_mix', 110, TRUE, '(rst_cond_info->''15''->>''medicine_type'')::int = 2', NULL,NULL),
    (616, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{25,value}', 'mst_medicine', 110, TRUE, '(rst_cond_info->''25''->>''medicine_type'')::int = 1', NULL,NULL),
    (617, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{25,value}', 'mst_medicine_mix', 110, TRUE, '(rst_cond_info->''25''->>''medicine_type'')::int = 2', NULL,NULL),
    (618, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{2,value}', 'mst_va', 110, TRUE, NULL, NULL,NULL),
    (619, 'ord_main_restore', 'JSON', NULL, 'ind_ind_comment_info', '[].ind_user_id', 'mst_personal_user', 100, TRUE, NULL, NULL, NULL),
    (620, 'ord_main_restore', 'JSON', NULL, 'ind_ind_comment_info', '[].upd_user_id', 'mst_personal_user', 100, TRUE, NULL, NULL, NULL),
    (621, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{10,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (622, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{11,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (623, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{13,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (624, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{19,value}', 'mst_medicine', 100, TRUE, '(rst_cond_info->''19''->>''medicine_type'')::int = 1', NULL,NULL),
    (625, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{19,value}', 'mst_medicine_mix', 100, TRUE, '(rst_cond_info->''19''->>''medicine_type'')::int = 2', NULL,NULL),
    (626, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{5,value}', 'mst_dialyzer', 100, TRUE, NULL, NULL,NULL),
    (627, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{6,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (628, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{7,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (629, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{8,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (630, 'ord_main_restore', 'JSON', NULL, 'rst_cond_info', '{9,value}', 'mst_equipment', 100, TRUE, NULL, NULL,NULL),
    (631, 'ord_main_restore', 'JSON', NULL, 'rst_tare_info', '{after,wheel_chair_cd}', 'mst_wheel_chair', 100, TRUE, NULL, NULL,NULL),
    (632, 'ord_main_restore', 'JSON', NULL, 'rst_tare_info', '{before,wheel_chair_cd}', 'mst_wheel_chair', 100, TRUE, NULL, NULL,NULL),
    (633, 'ord_main_restore', 'JSON', NULL, 'rst_complaint_info', '[].comp_cd', 'mst_complaint', 100, TRUE, NULL, NULL,NULL),
    (634, 'ord_main_restore', 'JSON', NULL, 'rst_rounds_info', '{round_type_cd}', 'mst_round_type', 100, TRUE, NULL, NULL,NULL),
    (635, 'ord_main_restore', 'COLUMN', 'up_ind_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (636, 'ord_main_restore', 'COLUMN', 'up_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (637, 'ord_main_restore', 'JSON', NULL, 'rst_rounds_info', '{create_user_id}', 'mst_personal_user', 100, TRUE, NULL, NULL,NULL),
    (638, 'pat_rad_main', 'COLUMN', 'ind_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (639, 'pat_rad_main', 'COLUMN', 'reg_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (640, 'pat_rad_main', 'COLUMN', 'up_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (641, 'pat_rad_main_hst', 'COLUMN', 'ind_user_id', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (642, 'pat_rad_main_hst', 'COLUMN', 'reg_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (643, 'pat_rad_main_hst', 'COLUMN', 'up_staff', null, null, 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (644, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_mainte_layout', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int in(1390,1350) ', 'template_cd in (12,9) ',NULL),
    (645, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_dialyzer', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int in(4,8,41,45) ', 'template_cd in(1,2)',NULL),
    (646, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_medicine_class', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int  in(1,2,5,6,38,39,43)', 'template_cd in(1,2)',NULL),
    (647, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_equipment_class', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int  in(3,7,40,44)', 'template_cd in(1,2)',NULL),
    (648, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_treatment', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int in(51,58,14,21) ', 'template_cd in(1,2)',NULL),
    (649, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_kur', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int in(22,15,52,59)', 'template_cd in(1,2)',NULL),
    (650, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_pat_event_sub_category', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int in(37,74)', 'template_cd in(1,2)',NULL),
    (651, 'mst_pat_list_layout', 'JsonIntArray', NULL, 'disp_item_info', '[].items', 'mst_addition', 100, TRUE, '(obj #>> ''{data_list_detail_cd}'')::int in(1348,1349 ) ', 'template_cd in(1,2) ',NULL),
    (652, 'mnt_motion_record', 'COLUMN', 'ord_no', null, null, 'ord_main', 100, TRUE, NULL,NULL,NULL),
    (653, 'pat_treatment_pattern', 'COLUMN', 'pat_id', null, null, 'pat_main', 100, TRUE, NULL,NULL,NULL),
    (654, 'pat_treatment_pattern', 'JSON_MULTI', null,'ind_cond_info',  '*.{ind_user_id,upd_user_id}', 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (655, 'pat_treatment_pattern', 'JSON_MULTI', null,'ind_medi_info',  '[].{ind_user_id,upd_user_id}', 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (656, 'pat_treatment_pattern', 'JSON_MULTI', null,'ind_equip_info',  '[].{ind_user_id,upd_user_id}', 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (657, 'pat_treatment_pattern', 'JSON_MULTI', null,'ind_ind_comment_info',  '[].{ind_user_id,upd_user_id}', 'mst_personal_user', 100, TRUE, NULL,NULL,NULL),
    (658, 'pat_exam_main_hst', 'COLUMN', 'exam_main_cd', null, null, 'pat_exam_main', 100, TRUE, NULL,NULL,NULL);





INSERT INTO fk_migration_config
    (id, table_name, fk_type, column_name, json_column, json_path, ref_table, execution_order, enabled, where_template, where_column,encrypt_flag,remark)
VALUES
    (507, 'mst_personal_user', 'COLUMN', 'job_cd', NULL, NULL, 'mst_job', 100, TRUE, NULL, NULL,TRUE,NULL);

SELECT setval('fk_migration_config_id_seq', COALESCE((SELECT MAX(id) FROM fk_migration_config), 1), true);

