-- =============================================================
-- 03: Mongo FK 設定の最終データ投入
--   現在の運用状態を基準に並び順と ID を整理した完全版
-- =============================================================

TRUNCATE TABLE fk_mongo_migration_config RESTART IDENTITY;

INSERT INTO fk_mongo_migration_config
    (id, collection_name, field_path, ref_table_name, field_encoding, execution_order, where_condition, enabled, remark)
VALUES
    (1, 'ind_history', 'created_user_id', 'mst_user', 'BSON', 100, NULL, TRUE, NULL),
    (2, 'ind_history', 'ord_no', 'ord_main', 'BSON', 110, NULL, TRUE, NULL),
    (3, 'ind_history', 'pat_id', 'pat_personal_main', 'BSON', 100, NULL, TRUE, NULL),
    (4, 'ind_history', 'updated_user_id', 'mst_user', 'BSON', 100, NULL, TRUE, NULL),
    (5, 'ord_main_hst', 'ind_bed_cd', 'mst_bed', 'BSON', 100, NULL, TRUE, NULL),
    (6, 'ord_main_hst', 'ind_cond_info.10.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (7, 'ord_main_hst', 'ind_cond_info.11.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (8, 'ord_main_hst', 'ind_cond_info.13.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (9, 'ord_main_hst', 'ind_cond_info.15.value', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (10, 'ord_main_hst', 'ind_cond_info.15.value', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (11, 'ord_main_hst', 'ind_cond_info.19.value', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (12, 'ord_main_hst', 'ind_cond_info.19.value', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (13, 'ord_main_hst', 'ind_cond_info.25.value', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (14, 'ord_main_hst', 'ind_cond_info.25.value', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (15, 'ord_main_hst', 'ind_cond_info.2.value', 'mst_va', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (16, 'ord_main_hst', 'ind_cond_info.5.value', 'mst_dialyzer', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (17, 'ord_main_hst', 'ind_cond_info.6.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (18, 'ord_main_hst', 'ind_cond_info.7.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (19, 'ord_main_hst', 'ind_cond_info.8.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (20, 'ord_main_hst', 'ind_cond_info.9.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (21, 'ord_main_hst', 'ind_cond_info.*.ind_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (22, 'ord_main_hst', 'ind_cond_info.*.upd_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (23, 'ord_main_hst', 'ind_device_set_info.*.ind_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (24, 'ord_main_hst', 'ind_device_set_info.*.upd_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (25, 'ord_main_hst', 'ind_dw_user_info.ind_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (26, 'ord_main_hst', 'ind_dw_user_info.upd_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (27, 'ord_main_hst', 'ind_equip_info[].cd', 'mst_dialyzer', 'JSON_STRING', 100, '{"equip_type": 1}', TRUE, NULL),
    (28, 'ord_main_hst', 'ind_equip_info[].cd', 'mst_equipment', 'JSON_STRING', 100, '{"equip_type": 0}', TRUE, NULL),
    (29, 'ord_main_hst', 'ind_equip_info[].class_cd', 'mst_equipment_class', 'JSON_STRING', 100, '{"equip_type": 0}', TRUE, NULL),
    (30, 'ord_main_hst', 'ind_equip_info[].ind_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (31, 'ord_main_hst', 'ind_equip_info[].upd_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (32, 'ord_main_hst', 'ind_kur_cd', 'mst_kur', 'BSON', 100, NULL, TRUE, NULL),
    (33, 'ord_main_hst', 'ind_medi_info[].cd', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (34, 'ord_main_hst', 'ind_medi_info[].cd', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (35, 'ord_main_hst', 'ind_medi_info[].class_cd', 'mst_medicine_class', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (36, 'ord_main_hst', 'ind_medi_info[].ind_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (37, 'ord_main_hst', 'ind_medi_info[].procedure_cd', 'mst_procedure', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (38, 'ord_main_hst', 'ind_medi_info[].timing_cd', 'mst_medicate_timing', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (39, 'ord_main_hst', 'ind_medi_info[].upd_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (40, 'ord_main_hst', 'ind_schedule_user_info.ind_kur_cd_before', 'mst_kur', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (41, 'ord_main_hst', 'ind_schedule_user_info.ind_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (42, 'ord_main_hst', 'ind_schedule_user_info.upd_user_id', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (43, 'ord_main_hst', 'ind_treatment_cd', 'mst_treatment', 'BSON', 100, NULL, TRUE, NULL),
    (44, 'ord_main_hst', 'ind_va_cd', 'mst_va', 'BSON', 100, NULL, TRUE, NULL),
    (45, 'ord_main_hst', 'ord_no', 'ord_main', 'BSON', 110, NULL, TRUE, NULL),
    (46, 'ord_main_hst', 'pat_id', 'pat_personal_main', 'BSON', 100, NULL, TRUE, NULL),
    (47, 'ord_main_hst', 'rst_bed_cd', 'mst_bed', 'BSON', 100, NULL, TRUE, NULL),
    (48, 'ord_main_hst', 'rst_charge_user_info.user_id_1', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (49, 'ord_main_hst', 'rst_charge_user_info.user_id_2', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (50, 'ord_main_hst', 'rst_cond_info.10.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (51, 'ord_main_hst', 'rst_cond_info.11.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (52, 'ord_main_hst', 'rst_cond_info.13.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (53, 'ord_main_hst', 'rst_cond_info.15.value', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (54, 'ord_main_hst', 'rst_cond_info.15.value', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (55, 'ord_main_hst', 'rst_cond_info.19.value', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (56, 'ord_main_hst', 'rst_cond_info.19.value', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (57, 'ord_main_hst', 'rst_cond_info.25.value', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (58, 'ord_main_hst', 'rst_cond_info.25.value', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (59, 'ord_main_hst', 'rst_cond_info.2.value', 'mst_va', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (60, 'ord_main_hst', 'rst_cond_info.5.value', 'mst_dialyzer', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (61, 'ord_main_hst', 'rst_cond_info.6.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (62, 'ord_main_hst', 'rst_cond_info.7.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (63, 'ord_main_hst', 'rst_cond_info.8.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (64, 'ord_main_hst', 'rst_cond_info.9.value', 'mst_equipment', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (65, 'ord_main_hst', 'rst_course_cd', 'mst_course', 'BSON', 100, NULL, TRUE, NULL),
    (66, 'ord_main_hst', 'rst_equip_info[].cd', 'mst_dialyzer', 'JSON_STRING', 100, '{"equip_type": 1}', TRUE, NULL),
    (67, 'ord_main_hst', 'rst_equip_info[].cd', 'mst_equipment', 'JSON_STRING', 100, '{"equip_type": 0}', TRUE, NULL),
    (68, 'ord_main_hst', 'rst_equip_info[].class_cd', 'mst_equipment_class', 'JSON_STRING', 100, '{"equip_type": 0}', TRUE, NULL),
    (69, 'ord_main_hst', 'rst_kur_cd', 'mst_kur', 'BSON', 100, NULL, TRUE, NULL),
    (70, 'ord_main_hst', 'rst_medi_info[].cd', 'mst_medicine', 'JSON_STRING', 100, '{"medicine_type": 1}', TRUE, NULL),
    (71, 'ord_main_hst', 'rst_medi_info[].cd', 'mst_medicine_mix', 'JSON_STRING', 100, '{"medicine_type": 2}', TRUE, NULL),
    (72, 'ord_main_hst', 'rst_medi_info[].class_cd', 'mst_medicine_class', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (73, 'ord_main_hst', 'rst_medi_info[].procedure_cd', 'mst_procedure', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (74, 'ord_main_hst', 'rst_medi_info[].timing_cd', 'mst_medicate_timing', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (75, 'ord_main_hst', 'rst_puncture_user_info.user_id_1', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (76, 'ord_main_hst', 'rst_puncture_user_info.user_id_2', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (77, 'ord_main_hst', 'rst_return_user_info.user_id_1', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (78, 'ord_main_hst', 'rst_return_user_info.user_id_2', 'mst_user', 'JSON_STRING', 100, NULL, TRUE, NULL),
    (79, 'ord_main_hst', 'rst_treatment_cd', 'mst_treatment', 'BSON', 100, NULL, TRUE, NULL),
    (80, 'ord_main_hst', 'rst_ward_cd', 'mst_ward', 'BSON', 100, NULL, TRUE, NULL),
    (81, 'ord_main_hst', 'up_ind_user_id', 'mst_user', 'BSON', 100, NULL, TRUE, NULL),
    (82, 'ord_main_hst', 'up_user_id', 'mst_user', 'BSON', 100, NULL, TRUE, NULL),
    (83, 'pat_group_detail_history', 'pat_group_cd', 'pat_group', 'BSON', 100, NULL, TRUE, NULL),
    (84, 'pat_group_detail_history', 'pat_id', 'pat_personal_main', 'BSON', 100, NULL, TRUE, NULL),
    (85, 'pat_insurance_history', 'insurance_cd', 'pat_insurance', 'BSON', 200, NULL, TRUE, NULL),
    (86, 'pat_insurance_history', 'pat_id', 'pat_personal_main', 'BSON', 100, NULL, TRUE, NULL),
    (87, 'pat_main_history', 'acceptance_status_info[].ord_no', 'ord_main', 'JSON_STRING', 110, NULL, TRUE, NULL),
    (88, 'pat_main_history', 'addition_info[].cd', 'mst_addition', 'BSON', 100, NULL, TRUE, NULL),
    (89, 'pat_main_history', 'charge_staff_info[].staff_cd', 'mst_user', 'BSON', 100, NULL, TRUE, NULL),
    (90, 'pat_main_history', 'implant_info[].implant_cd', 'mst_implant', 'BSON', 100, NULL, TRUE, NULL),
    (91, 'pat_main_history', 'infect_info[].infection_cd', 'mst_infection', 'BSON', 100, NULL, TRUE, NULL),
    (92, 'pat_main_history', 'medical_care_info.dialysis_course_cd', 'mst_course', 'BSON', 100, NULL, TRUE, NULL),
    (93, 'pat_main_history', 'medical_care_info.main_course_cd', 'mst_course', 'BSON', 100, NULL, TRUE, NULL),
    (94, 'pat_main_history', 'medical_care_info.ward_cd', 'mst_ward', 'BSON', 100, NULL, TRUE, NULL),
    (95, 'pat_main_history', 'pat_group_info[].pat_group_cd', 'pat_group', 'BSON', 100, NULL, TRUE, NULL),
    (96, 'pat_main_history', 'pat_id', 'pat_personal_main', 'BSON', 100, NULL, TRUE, NULL),
    (97, 'pat_main_history', 'taboo_allergy_info[].taboo_allergy_cd', 'mst_taboo_allergy', 'BSON', 100, NULL, TRUE, NULL),
    (98, 'pat_personal_main_history', 'dial_diff_com_info[].dial_diff_cd', 'mst_dialysis_difficulty', 'BSON', 100, NULL, TRUE, NULL),
    (99, 'pat_personal_main_history', 'pat_id', 'pat_personal_main', 'BSON', 100, NULL, TRUE, NULL),
    (100, 'pat_unique_history', 'in_out_visit_history_info[].from_course', 'mst_course', 'BSON', 100, '{"course_is_free": "0"}', TRUE, NULL),
    (101, 'pat_unique_history', 'in_out_visit_history_info[].from_doctor', 'mst_user', 'BSON', 100, '{"doctor_is_free": "0"}', TRUE, NULL),
    (102, 'pat_unique_history', 'in_out_visit_history_info[].to_course', 'mst_course', 'BSON', 100, '{"course_is_free": "0"}', TRUE, NULL),
    (103, 'pat_unique_history', 'in_out_visit_history_info[].to_doctor', 'mst_user', 'BSON', 100, '{"doctor_is_free": "0"}', TRUE, NULL),
    (104, 'pat_unique_history', 'medical_hst_info[].course_cd', 'mst_course', 'BSON', 100, '{"course_is_free": "0"}', TRUE, NULL),
    (105, 'pat_unique_history', 'medical_hst_info[].diagnostician_cd', 'mst_user', 'BSON', 100, '{"diagnostician_is_free": "0"}', TRUE, NULL),
    (106, 'pat_unique_history', 'medical_hst_info[].disease_cd', 'mst_disease', 'BSON', 100, NULL, TRUE, NULL),
    (107, 'pat_unique_history', 'pat_id', 'pat_personal_main', 'BSON', 100, NULL, TRUE, NULL),
    (108, 'pat_unique_history', 'physical_info[].changer_cd', 'mst_user', 'BSON', 100, NULL, TRUE, NULL),
    (109, 'pat_unique_history', 'physical_info[].indicator_cd', 'mst_user', 'BSON', 100, NULL, TRUE, NULL),
    (110, 'rst_history', 'ord_no', 'ord_main', 'BSON', 110, NULL, TRUE, NULL),
    (111, 'rst_history', 'up_user_id', 'mst_user', 'BSON', 100, NULL, TRUE, NULL);


SELECT setval('fk_mongo_migration_config_id_seq', COALESCE((SELECT MAX(id) FROM fk_mongo_migration_config), 1), true);

