WITH SET_MEDI_TMP AS (
  SELECT distinct
    SET_MEDI.MEDICINE_GROUP_CD
    ,SET_MEDI.SET_MEDICINE_CD
    ,SET_MEDI.UP_DATE MAX_SET_UP_DATE
    ,CLASS_NAME.CLASS_NAME
  FROM MST_SET_MEDI_NAME SET_MEDI
  INNER JOIN IND_DEVELOP_MEDI MEDI
    ON SET_MEDI.SET_MEDICINE_CD = MEDI.MEDICINE_CD
    AND SET_MEDI.UP_DATE = (SELECT MAX(UP_DATE) FROM MST_SET_MEDI_NAME WHERE SET_MEDICINE_CD = MEDI.MEDICINE_CD AND UP_DATE < MEDI.UP_DATE)
  LEFT JOIN MST_CLASS_NAME CLASS_NAME
    ON CLASS_NAME.CLASS_KIND = '3'
    AND CLASS_NAME.CLASS_CD = SET_MEDI.MEDICINE_GROUP_CD
    AND CLASS_NAME.UP_DATE < SET_MEDI.UP_DATE
  WHERE
    {0}
),
IND_DEVELOP_MEDI_NEW AS (
	SELECT
		IND_ID,
		DIALYSIS_DATE,
		SET_MEDICINE_FLG,
		CLASS_CD,
		CLASS_NAME,
  		MEDICINE_CD,
  		MEDICINE_NAME,
  		UNIT,
  		VALUE,
  		TIMING_CD,
  		TIMING_NAME,
  		PROCEDURE_CD,
  		PROCEDURE_NAME,
  		INDICATOR_CD,
  		UPDATE_STAFF_CD,
		SPE_IND_FLG,
  		COP_ORDER_NUMBER,
  		EDITABLE_FLG,
		UP_DATE,
		PLURAL,
		CTL_NO,
		PATID,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM UPDATE_STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS UPDATE_STAFF_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM INDICATOR_NAME ) ), '　', ' ' ), '\s+', ' ')) AS INDICATOR_NAME_NEW
	FROM
		IND_DEVELOP_MEDI
        WHERE
        {0}
)
SELECT
  MEDI.IND_ID
  ,MEDI.DIALYSIS_DATE
  ,SM.NO as CTL_NO
  ,CASE MEDI.SET_MEDICINE_FLG
    WHEN '0' THEN MEDI.CLASS_CD
    WHEN '1' THEN SET_MEDI.MEDICINE_GROUP_CD
    END CLASS_CD
  ,CASE MEDI.SET_MEDICINE_FLG
    WHEN '0' THEN MEDI.CLASS_NAME
    WHEN '1' THEN SET_MEDI.CLASS_NAME
    END CLASS_NAME
  ,MEDI.MEDICINE_CD
  ,MEDI.SET_MEDICINE_FLG
  ,MEDI.MEDICINE_NAME
  ,MEDI_PLAN.COMMENTS
  ,MEDI.UNIT
  ,MEDI.VALUE
  ,MEDI.TIMING_CD
  ,MEDI.TIMING_NAME
  ,MEDI.PROCEDURE_CD
  ,MEDI.PROCEDURE_NAME
  ,MEDI.INDICATOR_CD
  ,case when instr(MEDI.UPDATE_STAFF_NAME_NEW,' ')=0 then MEDI.UPDATE_STAFF_NAME_NEW
      when instr(MEDI.UPDATE_STAFF_NAME_NEW,' ')>0 then substr(MEDI.UPDATE_STAFF_NAME_NEW,0,instr(MEDI.UPDATE_STAFF_NAME_NEW,' ')-1)
    end as UPD_USER_LAST_NAME
  ,case when instr(MEDI.UPDATE_STAFF_NAME_NEW,' ')>0 then substr(MEDI.UPDATE_STAFF_NAME_NEW,instr(MEDI.UPDATE_STAFF_NAME_NEW,' ')+1)
      else ' '
    end as UPD_USER_FIRST_NAME
  ,case when instr(MEDI.INDICATOR_NAME_NEW,' ')=0 then MEDI.INDICATOR_NAME_NEW
      when instr(MEDI.INDICATOR_NAME_NEW,' ')>0 then substr(MEDI.INDICATOR_NAME_NEW,0,instr(MEDI.INDICATOR_NAME_NEW,' ')-1)
    end as IND_USER_LAST_NAME
  ,case when instr(MEDI.INDICATOR_NAME_NEW,' ')>0 then substr(MEDI.INDICATOR_NAME_NEW,instr(MEDI.INDICATOR_NAME_NEW,' ')+1)
      else ' '
    end as IND_USER_FIRST_NAME
  ,MEDI.UPDATE_STAFF_CD
  ,CASE 
    WHEN MEDI.SPE_IND_FLG IN (0,1) THEN '1' 
    WHEN MEDI.SPE_IND_FLG IN (2,3) THEN '2'
   END SPE_IND_FLG
  ,MEDI.COP_ORDER_NUMBER
  ,MEDI.EDITABLE_FLG
FROM
  IND_DEVELOP_MEDI_NEW MEDI
  LEFT JOIN SET_MEDI_TMP SET_MEDI
    ON SET_MEDI.SET_MEDICINE_CD = MEDI.MEDICINE_CD
    AND SET_MEDI.MAX_SET_UP_DATE < MEDI.UP_DATE
    left join  SYNC_MEDICINE_LATEST_NO SM on  SM.PATID=MEDI.PATID and SM.IND_NO=MEDI.CTL_NO and  SM.PLURAL=MEDI.PLURAL and SM.SERIES_CD='{SERIES_CD}'
    LEFT JOIN (select PATID, PLURAL,IND_START_DATE,IND_END_DATE, CTL_NO,MEDICINE_CD,COMMENTS, ROW_NUMBER() OVER (PARTITION BY PATID, PLURAL,CTL_NO,MEDICINE_CD ORDER BY UP_DATE DESC) as rn from IND_DIALYSIS_MEDI ) MEDI_PLAN
    ON MEDI.PATID = MEDI_PLAN.PATID
    AND MEDI.PLURAL = MEDI_PLAN.PLURAL
    AND MEDI.DIALYSIS_DATE BETWEEN MEDI_PLAN.IND_START_DATE AND MEDI_PLAN.IND_END_DATE
    AND MEDI.CTL_NO = MEDI_PLAN.CTL_NO
    AND MEDI.MEDICINE_CD = MEDI_PLAN.MEDICINE_CD AND MEDI_PLAN.rn = 1

ORDER BY
    MEDI.IND_ID
    ,MEDI.CTL_NO