WITH  IND_DEVELOP_COND_NEW AS (
 SELECT
		IND_ID,
		CTL_NO,
		VALUE,
		UNIT,
		VALUE_NAME1,
		VALUE_NAME2,
		UP_DATE,
		INDICATOR_CD,
		UPDATE_STAFF_CD,
		SPE_IND_FLG,
  		COP_ORDER_NUMBER,
  		EDITABLE_FLG,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM UPDATE_STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS UPDATE_STAFF_NAME_NEW,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM INDICATOR_NAME ) ), '　', ' ' ), '\s+', ' ')) AS INDICATOR_NAME_NEW
	FROM
		IND_DEVELOP_COND
        WHERE
     {0}
)
,CTL_NO_TMP AS (
  SELECT
    A.IND_ID
    ,A.CTL_NO
  FROM
    IND_DEVELOP_COND_NEW A
    LEFT JOIN SCH_DIALYSIS_PLAN SCH ON A.IND_ID=SCH.IND_ID
    INNER JOIN SYS_TREAT_COND_SETTING C
      ON C.TREAT_ITEM_CD = SCH.TREAT_ITEM_CD
        AND C.COND_CTL_NO = A.CTL_NO
        AND C.USE_FLG = '1' 
  WHERE
   A.CTL_NO NOT IN ('026', '027', '028') 
  UNION ALL
  SELECT
    A.IND_ID
    ,A.CTL_NO
  FROM
    IND_DEVELOP_COND_NEW A
  WHERE
 A.CTL_NO IN ('001', '006')
)
,V_IND_DEVELOP_COND AS
(
SELECT
  A.IND_ID
  ,CASE A.CTL_NO 
    WHEN '001' THEN '001' 
    WHEN '002' THEN '1' 
    WHEN '003' THEN '2' 
    WHEN '005' THEN '3' 
    WHEN '006' THEN '006' 
    WHEN '007' THEN '4' 
    WHEN '008' THEN '5' 
    WHEN '009' THEN '6' 
    WHEN '010' THEN '14' 
    WHEN '011' THEN '25' 
    WHEN '012' THEN '26' 
    WHEN '013' THEN '27' 
    WHEN '014' THEN '28' 
    WHEN '015' THEN '29' 
    WHEN '016' THEN '31' 
    WHEN '017' THEN '32' 
    WHEN '018' THEN '15' 
    WHEN '019' THEN '16' 
    WHEN '020' THEN '17' 
    WHEN '021' THEN '18' 
    WHEN '022' THEN '19' 
    WHEN '023' THEN '20' 
    WHEN '024' THEN '21' 
    WHEN '025' THEN '23' 
    WHEN '029' THEN '12' 
    WHEN '030' THEN '22' 
    WHEN '031' THEN '30' 
    WHEN '032' THEN '34' 
    WHEN '033' THEN '35' 
    WHEN '034' THEN '36' 
    WHEN '035' THEN '37' 
    WHEN '036' THEN '38' 
    WHEN '037' THEN '33' 
    WHEN '038' THEN '24' 
    WHEN '039' THEN '7' 
    WHEN '040' THEN '8' 
    WHEN '004' THEN '39'
     END CTL_NO
  ,CASE 
    WHEN A.CTL_NO = '011' THEN SUBSTR(A.VALUE, 2)
    WHEN A.CTL_NO IN ('018', '022')
      THEN 
        CASE SUBSTR(A.VALUE, 1, 1) 
          WHEN '1' THEN 'TS' || SUBSTR(A.VALUE, 4) ELSE SUBSTR(A.VALUE, 2) END
    WHEN A.CTL_NO IN ('004','005','007','012','013','014') THEN
        TO_CHAR(A.VALUE, 'FM9999990.00') 
    WHEN A.CTL_NO IN ('016','017','021','023','025','037') THEN
        TO_CHAR(A.VALUE, 'FM9999990.0')
    ELSE A.VALUE 
  END VALUE
  ,A.UNIT
  ,A.VALUE_NAME1
  ,A.VALUE_NAME2
  ,A.UP_DATE
  ,A.INDICATOR_CD
  ,case when instr(A.UPDATE_STAFF_NAME_NEW,' ')=0 then A.UPDATE_STAFF_NAME_NEW
      when instr(A.UPDATE_STAFF_NAME_NEW,' ')>0 then substr(A.UPDATE_STAFF_NAME_NEW,0,instr(A.UPDATE_STAFF_NAME_NEW,' ')-1)
    end as UPD_USER_LAST_NAME
  ,case when instr(A.UPDATE_STAFF_NAME_NEW,' ')>0 then substr(A.UPDATE_STAFF_NAME_NEW,instr(A.UPDATE_STAFF_NAME_NEW,' ')+1)
      else ' '
    end as UPD_USER_FIRST_NAME
  ,case when instr(A.INDICATOR_NAME_NEW,' ')=0 then A.INDICATOR_NAME_NEW
      when instr(A.INDICATOR_NAME_NEW,' ')>0 then substr(A.INDICATOR_NAME_NEW,0,instr(A.INDICATOR_NAME_NEW,' ')-1)
    end as IND_USER_LAST_NAME
  ,case when instr(A.INDICATOR_NAME_NEW,' ')>0 then substr(A.INDICATOR_NAME_NEW,instr(A.INDICATOR_NAME_NEW,' ')+1)
      else ' '
    end as IND_USER_FIRST_NAME
  ,A.UPDATE_STAFF_CD
  ,CASE 
    WHEN A.SPE_IND_FLG IN (0,1) THEN '1' 
    WHEN A.SPE_IND_FLG IN (2,3) THEN '2'
      END AS SPE_IND_FLG
  ,A.COP_ORDER_NUMBER
  ,A.EDITABLE_FLG
  ,CASE 
    WHEN A.CTL_NO = '011' THEN
            CASE SUBSTR(A.VALUE, 1, 1)
            WHEN '0' THEN '1'
                ELSE '2' END   
    WHEN A.CTL_NO IN ('018', '022') THEN '1'
        END AS ADD_MEDICINE_TYPE 
FROM
    IND_DEVELOP_COND_NEW A
    INNER JOIN CTL_NO_TMP CNT
      ON A.IND_ID = CNT.IND_ID
      AND A.CTL_NO = CNT.CTL_NO
)
(
SELECT 
  IND_ID
  ,CTL_NO
  ,VALUE
  ,UNIT
  ,VALUE_NAME1
  ,VALUE_NAME2
  ,UP_DATE
  ,INDICATOR_CD
  ,IND_USER_FIRST_NAME
  ,IND_USER_LAST_NAME
  ,UPDATE_STAFF_CD
  ,UPD_USER_FIRST_NAME
  ,UPD_USER_LAST_NAME
  ,SPE_IND_FLG
  ,COP_ORDER_NUMBER
  ,EDITABLE_FLG
  ,ADD_MEDICINE_TYPE 
FROM V_IND_DEVELOP_COND
) 
UNION
(SELECT
    B.IND_ID AS IND_ID
  ,C.CTL_NO AS CTL_NO
  ,NULL VALUE
  ,NULL UNIT
  ,NULL VALUE_NAME1
  ,NULL VALUE_NAME2
  ,B.UP_DATE
  ,B.INDICATOR_CD
  ,B.IND_USER_FIRST_NAME
  ,B.IND_USER_LAST_NAME
  ,B.UPDATE_STAFF_CD
  ,B.UPD_USER_FIRST_NAME
  ,B.UPD_USER_LAST_NAME
  ,'1' SPE_IND_FLG
  ,NULL COP_ORDER_NUMBER
  ,1 EDITABLE_FLG
  ,NULL ADD_MEDICINE_TYPE 
FROM(
  SELECT
    A.IND_ID
    ,MAX(A.UP_DATE) UP_DATE
    ,MAX(A.UPDATE_STAFF_CD) UPDATE_STAFF_CD
    ,MAX(A.IND_USER_FIRST_NAME) IND_USER_FIRST_NAME
    ,MAX(A.IND_USER_LAST_NAME) IND_USER_LAST_NAME
    ,MAX(A.INDICATOR_CD) INDICATOR_CD
    ,MAX(A.UPD_USER_FIRST_NAME) UPD_USER_FIRST_NAME
    ,MAX(A.UPD_USER_LAST_NAME) UPD_USER_LAST_NAME
  FROM
    V_IND_DEVELOP_COND A
  GROUP BY A.IND_ID
) B
CROSS JOIN (
  SELECT '9' AS CTL_NO FROM DUAL
  UNION
  SELECT '10' AS CTL_NO FROM DUAL
  UNION
  SELECT '11' AS CTL_NO FROM DUAL
  UNION
  SELECT '13' AS CTL_NO FROM DUAL
) C
)
ORDER BY 1, 2