SELECT
  DIALYSIS_DATE
  ,PATID
  ,PLURAL
  ,IND_ID
  ,('"'|| PATID ||'","'|| PLURAL|| '"' ) IND_ID_CONNECT
  ,VALUE
  ,OPE_IND_PLAN
  ,CASE SUBSTR( VALUE, 0, 4 ) WHEN 'NON' THEN 0 ELSE TO_NUMBER(SUBSTR( VALUE, 0, 4 )) END BED_NO
  ,SUBSTR( VALUE, 5, 3 ) KUR_CD
  ,CASE OPE_IND_PLAN WHEN '1' THEN '0' ELSE TO_CHAR(CYCLE_WEEK) END AS CYCLE_WEEK
  ,CASE TO_CHAR(TO_DATE(DIALYSIS_DATE, 'yyyyMMdd'), 'D') 
        WHEN '1' THEN 7
        WHEN '2' THEN 1
        WHEN '3' THEN 2
        WHEN '4' THEN 3
        WHEN '5' THEN 4
        WHEN '6' THEN 5
        WHEN '7' THEN 6
        END ADD_TREAT_WEEK
  ,INDICATOR_CD
  ,UPDATE_STAFF_CD
  ,'0' RST_DIALYSIS_STATE
  ,'' OFF_WATER
  ,'' TARE
  ,UP_DATE
FROM
  SYNC_ORD_MAIN_SCH_PLAN S
WHERE
  S.PATID IN ({0})
  AND S.DIALYSIS_DATE >= TO_DATE(:START_DATE, 'yyyyMMdd')
  AND S.DIALYSIS_DATE <= TO_DATE(:END_DATE, 'yyyyMMdd')
  AND {1}
ORDER BY
  PATID
  ,DIALYSIS_DATE