WITH MST_STAFF_NEW AS (
	SELECT
		s.STAFF_CD,
		s.UP_DATE,
        TRIM(REGEXP_REPLACE( REGEXP_REPLACE( TRIM( BOTH ' ' FROM TRIM( BOTH '　' FROM STAFF_NAME ) ), '　', ' ' ), '\s+', ' ')) AS STAFF_NAME_NEW
	FROM
		MST_STAFF s INNER JOIN SYS_STAFF_DISP  d  on d.STAFF_CD=s.STAFF_CD and  d.SERIES_CD='{SERIES_CD}'
)
SELECT
	* 
FROM
	(
	SELECT
		RD.DIALYSIS_NO,
		null KIND_ID,
		A.SEQ_ID,
		A.UP_DATE,
		A.PATID,
		A.STAFF_CD,
		TO_DATE( A.REG_DATE || A.REG_TIME, 'YYYYMMDDHH24MISS' ) AS REG_DATE_TIME,
		A.BBS_SEQ_ID,
		(SELECT
		    case when instr(STAFF_NAME_NEW,' ')>0 then substr(STAFF_NAME_NEW,instr(STAFF_NAME_NEW,' ')+1)
            else '' end
		 FROM MST_STAFF_NEW MS
		 WHERE A.STAFF_CD = MS.STAFF_CD
		   AND UP_DATE = (SELECT MAX(UP_DATE) FROM MST_STAFF_NEW WHERE STAFF_CD = A.STAFF_CD AND UP_DATE < A.UP_DATE)) FIRST_NAME,
		(SELECT
		    case when instr(STAFF_NAME_NEW,' ')=0 then STAFF_NAME_NEW
            when instr(STAFF_NAME_NEW,' ')>0 then substr(STAFF_NAME_NEW,0,instr(STAFF_NAME_NEW,' ')-1)
		    end
		 FROM MST_STAFF_NEW MS
		 WHERE A.STAFF_CD = MS.STAFF_CD
		   AND UP_DATE = (SELECT MAX(UP_DATE) FROM MST_STAFF_NEW WHERE STAFF_CD = A.STAFF_CD AND UP_DATE < A.UP_DATE)) LAST_NAME,
		A.EDIT_CD,
		A.DETAIL1,
		A.UPDATE_CNT,
		A.SH_FLG,
		M.KIND_NAME,
		A.DEL_FLG,
		'0' IS_IND_COMMENT_POST,
		'0' POSTING_CLASS,
		ROW_NUMBER ( ) OVER ( PARTITION BY RD.DIALYSIS_NO ORDER BY A.UP_DATE DESC ) AS NUM1 
	FROM
		RST_DIALYSIS RD
		INNER JOIN (
		SELECT
			* 
		FROM
			( SELECT P.*, ROW_NUMBER ( ) OVER ( PARTITION BY P.SEQ_ID ORDER BY P.UP_DATE DESC ) AS NUM FROM PAT_LIFE_LIST P ) D 
		WHERE
			D.NUM = 1 
		) A ON A.PATID = RD.PATID 
		AND TO_DATE( A.REG_DATE || A.REG_TIME, 'YYYYMMDDHH24MISS' ) BETWEEN RD.ENTER_DATE 
		AND RD.LEAVE_DATE
		LEFT JOIN (
		SELECT
			* 
		FROM
			( SELECT KIND_ID, KIND_NAME, ROW_NUMBER ( ) OVER ( PARTITION BY KIND_ID ORDER BY UP_DATE DESC ) AS NUM FROM MST_LLT_KIND ) MM
		WHERE 
			NUM = 1 
		) M ON M.KIND_ID = A.KIND_ID
	WHERE
		{0}
		AND A.KIND_ID = (SELECT R_R FROM SYNC_CONDSET where SERIES_CD='{SERIES_CD}')
	) R 
WHERE
	NUM1 = 1