WITH MAX_RST_DIALYSIS_ADDITION AS ( 
SELECT
  DIALYSIS_NO
  ,CTL_NO 
  ,ADDITION
  ,COP_ORDER_NUMBER
  ,EDITABLE_FLG
  ,1 INPUT_CLASS
  ,ROW_NUMBER() OVER (PARTITION BY DIALYSIS_NO,ADDITION ORDER BY CTL_NO DESC,UP_DATE DESC) AS rn 
FROM
    RST_DIALYSIS_ADDITION RD
WHERE
    {0}
),MIN_RST_DIALYSIS_ADDITION AS ( 
SELECT DIALYSIS_NO, MIN( CTL_NO ) AS CTL_NO, ADDITION FROM RST_DIALYSIS_ADDITION RD WHERE {0} 
GROUP BY DIALYSIS_NO, ADDITION )

select 
    max.DIALYSIS_NO,  
    min.CTL_NO,  
    max.ADDITION,  
    COP_ORDER_NUMBER,  
    EDITABLE_FLG,  
    INPUT_CLASS
FROM  MAX_RST_DIALYSIS_ADDITION max
INNER JOIN  MIN_RST_DIALYSIS_ADDITION  min ON max.DIALYSIS_NO=min.DIALYSIS_NO and  max.ADDITION=min.ADDITION
WHERE  
    rn = 1
order by
     max.DIALYSIS_NO
    , min.CTL_NO