SELECT
	sdp.IND_ID 
FROM
	(
	SELECT
		PATID,
		min( IND_START_DATE ) AS IND_START_DATE,
		max( IND_END_DATE ) AS IND_END_DATE,
		PLURAL
	FROM
		IND_DIALYSIS_MEDI  
	WHERE
		{0} and up_date > :CONVERT_DATETIME
	GROUP BY
		PATID, PLURAL 
	) r
INNER JOIN SYNC_ORD_MAIN_SCH_PLAN sdp
    ON sdp.PATID = r.PATID
	AND sdp.PLURAL = r.PLURAL 
    AND sdp.DIALYSIS_DATE >= r.IND_START_DATE 
    AND sdp.DIALYSIS_DATE <= r.IND_END_DATE