-- テーブル削除
-- DROP TABLE SYNC_CONV_REASON CASCADE CONSTRAINTS;
declare
      num number;
begin
    select count(1) into num from user_tables where table_name = upper('SYNC_CONV_REASON') ;
    if num > 0 then
        execute immediate 'drop table SYNC_CONV_REASON CASCADE CONSTRAINTS' ;
    end if;
end;
/
-- テーブル作成
CREATE TABLE SYNC_CONV_REASON
(
    DEVICE_TYPE_CD VARCHAR2(50),  --NTSSテーブル名
    CHECKLIST_ITEM_NO NUMBER(3,0),  --NTSSテーブル名
    EFFECT_START_DATE VARCHAR2(50),  --ユニーク制約名
    ITEM_KIND VARCHAR2(5),  --ユニークカラム
    ITEM_NAME VARCHAR2(50),  --シーケンス発番カラム名
    SUPPLEMENT_UNIT VARCHAR2(20),
	DEL_FLG CHAR(1),
	MAINTE_CLASS NUMBER(3,0),
	ANS_PATTERN NUMBER(3,0),
	IS_CMT NUMBER(3,0),
	EDITION_NO NUMBER(3,0),
	IS_DISP CHAR(1),
	MAINTE_CONTENT VARCHAR2(50)
)
    tablespace NKK_DATA_COP;
-- コメント追加

INSERT INTO "NKK"."SYNC_CONV_REASON" ("DEVICE_TYPE_CD", "CHECKLIST_ITEM_NO", "EFFECT_START_DATE", "ITEM_KIND", "ITEM_NAME", "SUPPLEMENT_UNIT", "DEL_FLG", "MAINTE_CLASS", "ANS_PATTERN", "IS_CMT", "EDITION_NO", "IS_DISP", "MAINTE_CONTENT") VALUES ('9999001', NULL, NULL, '0', '試運転調整', NULL, '0', '2', '2', '0', '1', '1', '理由');
INSERT INTO "NKK"."SYNC_CONV_REASON" ("DEVICE_TYPE_CD", "CHECKLIST_ITEM_NO", "EFFECT_START_DATE", "ITEM_KIND", "ITEM_NAME", "SUPPLEMENT_UNIT", "DEL_FLG", "MAINTE_CLASS", "ANS_PATTERN", "IS_CMT", "EDITION_NO", "IS_DISP", "MAINTE_CONTENT") VALUES ('9999002', NULL, NULL, '0', '修理', NULL, '0', '2', '2', '1', '1', '1', '理由');
INSERT INTO "NKK"."SYNC_CONV_REASON" ("DEVICE_TYPE_CD", "CHECKLIST_ITEM_NO", "EFFECT_START_DATE", "ITEM_KIND", "ITEM_NAME", "SUPPLEMENT_UNIT", "DEL_FLG", "MAINTE_CLASS", "ANS_PATTERN", "IS_CMT", "EDITION_NO", "IS_DISP", "MAINTE_CONTENT") VALUES ('9999003', NULL, NULL, '0', '構成の変更', NULL, '0', '2', '2', '1', '1', '1', '理由');
INSERT INTO "NKK"."SYNC_CONV_REASON" ("DEVICE_TYPE_CD", "CHECKLIST_ITEM_NO", "EFFECT_START_DATE", "ITEM_KIND", "ITEM_NAME", "SUPPLEMENT_UNIT", "DEL_FLG", "MAINTE_CLASS", "ANS_PATTERN", "IS_CMT", "EDITION_NO", "IS_DISP", "MAINTE_CONTENT") VALUES ('9999004', NULL, NULL, '1', '定期点検', 'ヶ月毎', '0', '2', '2', '1', '1', '1', '理由');

