import org.gradle.internal.os.OperatingSystem

buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("https://start.spring.io/plugins-release") }
    maven { url = uri("https://start.spring.io/milestone") }
    maven { url = uri("https://plugins.gradle.org/m2/") }
  }
  dependencies {
    classpath "org.springframework.boot:spring-boot-gradle-plugin:${spring_boot_version}"
//    classpath 'io.spring.gradle:propdeps-plugin:0.0.10.RELEASE'
    classpath "io.spring.gradle:dependency-management-plugin:${dependency_management_plugin_version}"
  }
}

apply plugin: 'maven-publish'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
//apply plugin: 'propdeps'
//apply plugin: 'propdeps-eclipse'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'idea'
defaultTasks 'bootRun'

bootJar {
  archiveBaseName = 'ntss-client-comm'
  mainClass = 'jp.co.nikkiso.ntss.client_comm.NtssApplication'
  manifest {
    attributes 'Start-Class': 'jp.co.nikkiso.ntss.client_comm.NtssApplication'
  }
}

bootWar {
  mainClass = 'jp.co.nikkiso.ntss.client_comm.NtssApplication'
}

war {
  enabled = true
  archiveBaseName = 'ntss-client-comm'
}

springBoot {
  mainClass = 'jp.co.nikkiso.ntss.client_comm.NtssApplication'
  buildInfo()
}

if (OperatingSystem.current().isWindows()) {
  task pathingJar(type: Jar) {
    dependsOn configurations.runtimeClasspath
    archiveAppendix = 'pathing'

    doFirst {
      manifest {
        attributes 'Class-Path': configurations.runtimeClasspath.getFiles().collect {
          it.toURI().toString().replaceFirst(/file:\/+/, '/').replaceAll(' ', '%20')
        }.join(' ')
      }
    }
  }

  bootRun {
    dependsOn pathingJar
    doFirst {
      classpath = files("$buildDir/classes/java/main", "$buildDir/resources/main", pathingJar.archiveFile)
    }
  }
} else {
  bootRun {
    jvmArgs = ["-Dspring.output.ansi.enabled=ALWAYS"]
  }
}

jacoco {
  toolVersion = "0.8.8"
}

jacocoTestReport {
  reports {
      xml.required = false
      csv.required = false
  }
}

apply from: 'gradle/eclipse.gradle'
apply from: 'gradle/docker.gradle'
//jhipster-needle-gradle-apply-from - JHipster will add additional gradle scripts to be applied here

if (project.hasProperty('prod')) {
  apply from: 'gradle/profile_prod.gradle'
} else {
  apply from: 'gradle/profile_dev.gradle'
}

description = ''

repositories {
  mavenLocal()
  mavenCentral()
  maven { url = uri('https://start.spring.io/milestone') }
  maven { url = uri('https://start.spring.io/snapshot') }
  maven { url = uri('https://repository.jboss.org/nexus/content/repositories/releases') }
  maven { url = uri('https://oss.sonatype.org/content/repositories/releases') }
  maven { url = uri('https://oss.sonatype.org/content/repositories/snapshots') }
  maven { url = uri('https://repo.maven.apache.org/maven2') }
}

dependencies {
  implementation "org.springframework.boot:spring-boot-autoconfigure"
  implementation "org.springframework.boot:spring-boot-starter-web"
  implementation "org.springframework.boot:spring-boot-starter-tomcat"
  implementation "org.springframework.boot:spring-boot-starter-jdbc"
  implementation "org.springframework.boot:spring-boot-starter-actuator"
  implementation "org.projectlombok:lombok:${lombok_version}"
  annotationProcessor "org.projectlombok:lombok:${lombok_version}"
  implementation "org.modelmapper:modelmapper:${modelmapper_version}"
  testImplementation ("org.springframework.boot:spring-boot-starter-test") {
    exclude group: 'com.vaadin.external.google', module: 'android-json'
  }
  testImplementation "org.springframework.boot:spring-boot-test"
  testImplementation "junit:junit"
  testImplementation "org.mockito:mockito-core"
  annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
  // websocket
  implementation "org.springframework.boot:spring-boot-starter-websocket"
  implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
  testCompileOnly "org.projectlombok:lombok:${lombok_version}"
  testAnnotationProcessor "org.projectlombok:lombok:${lombok_version}"
  implementation "org.springframework.boot:spring-boot-starter-aspectj"
  implementation "org.seasar.doma.boot:doma-spring-boot-starter:${doma_spring_version}"
  implementation "org.seasar.doma:doma-core:${doma_core_version}"
  annotationProcessor "org.seasar.doma:doma-processor:${doma_core_version}"
}

clean { delete "target" }

task cleanResources(type: Delete) { delete 'build/resources' }


task stage(dependsOn: [bootWar, bootJar]) {
}

assemble.dependsOn bootJar

// Doma2のSQLファイルをJavaのコンパイル前にコピーしておく
// SQLファイルが存在するかしないとJavaのコンパイル時にSQLファイルが存在するかのチェックでエラーになるため。
def domaResources = ['doma.compile.config', 'META-INF/**/*.sql']
task copyDomaResourcesJava(type: Copy) {
  from sourceSets.main.resources.srcDirs
  into compileJava.destinationDirectory
  include domaResources
}
compileJava {
  dependsOn copyDomaResourcesJava
}
processResources {
  exclude domaResources
}

processResources.dependsOn cleanResources, bootBuildInfo
bootBuildInfo.mustRunAfter cleanResources
