version: '2'
services:
    ntss-postgresql:
        image: postgres:15.2
        ports:
            - 5432:5432
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        environment:
           - POSTGRES_PASSWORD=password
    ntss-test-db:
        image: postgres:15.2
        ports:
            - 5433:5432
        volumes:
            - ./init_test:/docker-entrypoint-initdb.d
        environment:
           - POSTGRES_PASSWORD=password
