//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NKSConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Log")]
        public string TraceFolder {
            get {
                return ((string)(this["TraceFolder"]));
            }
            set {
                this["TraceFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000000")]
        public int TraceSize {
            get {
                return ((int)(this["TraceSize"]));
            }
            set {
                this["TraceSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int TraceNumber {
            get {
                return ((int)(this["TraceNumber"]));
            }
            set {
                this["TraceNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14.00:00:00")]
        public global::System.TimeSpan TraceSpan {
            get {
                return ((global::System.TimeSpan)(this["TraceSpan"]));
            }
            set {
                this["TraceSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TraceIsZip {
            get {
                return ((bool)(this["TraceIsZip"]));
            }
            set {
                this["TraceIsZip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Log")]
        public string ErrorFolder {
            get {
                return ((string)(this["ErrorFolder"]));
            }
            set {
                this["ErrorFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000000")]
        public int ErrorSize {
            get {
                return ((int)(this["ErrorSize"]));
            }
            set {
                this["ErrorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ErrorNumber {
            get {
                return ((int)(this["ErrorNumber"]));
            }
            set {
                this["ErrorNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14.00:00:00")]
        public global::System.TimeSpan ErrorSpan {
            get {
                return ((global::System.TimeSpan)(this["ErrorSpan"]));
            }
            set {
                this["ErrorSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ErrorIsZip {
            get {
                return ((bool)(this["ErrorIsZip"]));
            }
            set {
                this["ErrorIsZip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift-JIS")]
        public string Encoding {
            get {
                return ((string)(this["Encoding"]));
            }
            set {
                this["Encoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Export")]
        public string DefaultExportFolderPath {
            get {
                return ((string)(this["DefaultExportFolderPath"]));
            }
            set {
                this["DefaultExportFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isSimpleConvertValueDirect {
            get {
                return ((bool)(this["isSimpleConvertValueDirect"]));
            }
            set {
                this["isSimpleConvertValueDirect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string ChunkSize {
            get {
                return ((string)(this["ChunkSize"]));
            }
            set {
                this["ChunkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkSelectAllSpan {
            get {
                return ((bool)(this["chkSelectAllSpan"]));
            }
            set {
                this["chkSelectAllSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkExclusion {
            get {
                return ((bool)(this["chkExclusion"]));
            }
            set {
                this["chkExclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string chkbBloodCircuit {
            get {
                return ((string)(this["chkbBloodCircuit"]));
            }
            set {
                this["chkbBloodCircuit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string chkbPunctureA {
            get {
                return ((string)(this["chkbPunctureA"]));
            }
            set {
                this["chkbPunctureA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string chkbPunctureV {
            get {
                return ((string)(this["chkbPunctureV"]));
            }
            set {
                this["chkbPunctureV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string chkbPunctureSN {
            get {
                return ((string)(this["chkbPunctureSN"]));
            }
            set {
                this["chkbPunctureSN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cmbSeriesCd {
            get {
                return ((string)(this["cmbSeriesCd"]));
            }
            set {
                this["cmbSeriesCd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string txtChunkSize {
            get {
                return ((string)(this["txtChunkSize"]));
            }
            set {
                this["txtChunkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime dtpStartDate {
            get {
                return ((global::System.DateTime)(this["dtpStartDate"]));
            }
            set {
                this["dtpStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool btnDeleteTable_Visible {
            get {
                return ((bool)(this["btnDeleteTable_Visible"]));
            }
            set {
                this["btnDeleteTable_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string maxFileSize {
            get {
                return ((string)(this["maxFileSize"]));
            }
            set {
                this["maxFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isDiff {
            get {
                return ((bool)(this["isDiff"]));
            }
            set {
                this["isDiff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("diff")]
        public string param {
            get {
                return ((string)(this["param"]));
            }
            set {
                this["param"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploadServPath")]
        public string uploadServPathKey {
            get {
                return ((string)(this["uploadServPathKey"]));
            }
            set {
                this["uploadServPathKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploadFiles")]
        public string multipartKey {
            get {
                return ((string)(this["multipartKey"]));
            }
            set {
                this["multipartKey"] = value;
            }
        }
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool btnDeleteConvTable_Visible {
            get {
                return ((bool)(this["btnDeleteConvTable_Visible"]));
            }
            set {
                this["btnDeleteConvTable_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int dialysisChunkSize {
            get {
                return ((int)(this["dialysisChunkSize"]));
            }
            set {
                this["dialysisChunkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int dialysisThreadSize {
            get {
                return ((int)(this["dialysisThreadSize"]));
            }
            set {
                this["dialysisThreadSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/uploadfile")]
        public string ConvertRestFileUploadUrlFormat {
            get {
                return ((string)(this["ConvertRestFileUploadUrlFormat"]));
            }
            set {
                this["ConvertRestFileUploadUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/checkDBConnection")]
        public string ConvertRestCheckConnection {
            get {
                return ((string)(this["ConvertRestCheckConnection"]));
            }
            set {
                this["ConvertRestCheckConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/upload")]
        public string ConvertLogFileUploadUrlFormat {
            get {
                return ((string)(this["ConvertLogFileUploadUrlFormat"]));
            }
            set {
                this["ConvertLogFileUploadUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/deleteTableJob")]
        public string ConvertRestDeleteTableJobUrlFormat {
            get {
                return ((string)(this["ConvertRestDeleteTableJobUrlFormat"]));
            }
            set {
                this["ConvertRestDeleteTableJobUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/login")]
        public string ConvertLogin {
            get {
                return ((string)(this["ConvertLogin"]));
            }
            set {
                this["ConvertLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/execute")]
        public string ConvertRestExecuteUrlFormat {
            get {
                return ((string)(this["ConvertRestExecuteUrlFormat"]));
            }
            set {
                this["ConvertRestExecuteUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/deleteConvertTableJob")]
        public string ConvertRestDeleteConvTableJobUrlFormat {
            get {
                return ((string)(this["ConvertRestDeleteConvTableJobUrlFormat"]));
            }
            set {
                this["ConvertRestDeleteConvTableJobUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/tableStatus")]
        public string ConvertRestTableStatusUrlFormat {
            get {
                return ((string)(this["ConvertRestTableStatusUrlFormat"]));
            }
            set {
                this["ConvertRestTableStatusUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/status")]
        public string ConvertRestStatusUrlFormat {
            get {
                return ((string)(this["ConvertRestStatusUrlFormat"]));
            }
            set {
                this["ConvertRestStatusUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/tableStatusForLog")]
        public string ConvertRestTableLogUrlFormat {
            get {
                return ((string)(this["ConvertRestTableLogUrlFormat"]));
            }
            set {
                this["ConvertRestTableLogUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/executeRestart")]
        public string ConvertRestExecuteReStartUrlFormat {
            get {
                return ((string)(this["ConvertRestExecuteReStartUrlFormat"]));
            }
            set {
                this["ConvertRestExecuteReStartUrlFormat"] = value;
            }
        }
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/stop")]
        public string ConvertRestStopJobUrlFormat {
            get {
                return ((string)(this["ConvertRestStopJobUrlFormat"]));
            }
            set {
                this["ConvertRestStopJobUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/getMstFacility")]
        public string ConvertgetMstFacilityUrlFormat {
            get {
                return ((string)(this["ConvertgetMstFacilityUrlFormat"]));
            }
            set {
                this["ConvertgetMstFacilityUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/updateMstFacility")]
        public string ConvertUpdateMstFacilityUrlFormat {
            get {
                return ((string)(this["ConvertUpdateMstFacilityUrlFormat"]));
            }
            set {
                this["ConvertUpdateMstFacilityUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConvertTool_TRACE_FNW-FNWSi-Converter")]
        public string TraceFile {
            get {
                return ((string)(this["TraceFile"]));
            }
            set {
                this["TraceFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConvertTool_ERROR")]
        public string ErrorFile {
            get {
                return ((string)(this["ErrorFile"]));
            }
            set {
                this["ErrorFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/health/check")]
        public string ConvertHealthCheck {
            get {
                return ((string)(this["ConvertHealthCheck"]));
            }
            set {
                this["ConvertHealthCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/getOrdMain")]
        public string ConvergetOrdMainFormat {
            get {
                return ((string)(this["ConvergetOrdMainFormat"]));
            }
            set {
                this["ConvergetOrdMainFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/var/lib/ntss-convert/CopySQL")]
        public string ConvertRestInputFilePath {
            get {
                return ((string)(this["ConvertRestInputFilePath"]));
            }
            set {
                this["ConvertRestInputFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/var/lib/ntss-convert/CopySQL")]
        public string uploadServPathValue {
            get {
                return ((string)(this["uploadServPathValue"]));
            }
            set {
                this["uploadServPathValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/job/convert/getPatLatestNo")]
        public string ConvertgetPatLatestNo {
            get {
                return ((string)(this["ConvertgetPatLatestNo"]));
            }
            set {
                this["ConvertgetPatLatestNo"] = value;
            }
        }
    }
}
