INSERT INTO mst_equipment(
facility_cd,
fn_equipment_cd,
standard_equipment_cd,
is_trial,
equipment_name,
equipment_short_name,
class_cd,
unit,
use_start_date,
use_end_date,
in_hospital_cd_1,
in_hospital_cd_2,
in_hospital_cd_3,
is_disp,
is_del,
reg_date,
up_date,
in_hospital_cd_4)
VALUES(
/* mstEquipment.facilityCd */null,
/* mstEquipment.fnEquipmentCd*/null,
/* mstEquipment.standardEquipmentCd */null,
/* mstEquipment.isTrial */null,
/* mstEquipment.equipmentName */null,
/* mstEquipment.equipmentShortName */null,
/* mstEquipment.classCd */null,
/* mstEquipment.unit */null,
/* mstEquipment.useStartDate */null,
/* mstEquipment.useEndDate */null,
/* mstEquipment.inHospitalCd_1 */null,
/* mstEquipment.inHospitalCd_2 */null,
/* mstEquipment.inHospitalCd_3 */null,
/* mstEquipment.isDisp */'1',
/* mstEquipment.isDel */'0',
to_timestamp(/*mstEquipment.regDate*/null, 'YYYY-MM-DD HH24:MI:SS'),
to_timestamp(/*mstEquipment.upDate*/null, 'YYYY-MM-DD HH24:MI:SS'),
/* mstEquipment.inHospitalCd_4 */null);
