; デバイスAWS通信アプリの設定
;

; 生体モニタリングアップロード間隔（秒）
AWS_MONI_UPLOAD_INTERVAL=10
; データ取得アプリのファイルパス
COLLECT_APP=./ntss_pcap.exe
; データ収集アップロードアプリのファイルパス
UPLOAD_APP=./ntss_datacollect.exe
; FTPファイル収集のスケジュール（HH:mm）カンマ区切り
FTP_SCHEDULE=2:00
