; デバイスキャプチャ処理アプリ設定
;
;

; パケットキャプチャ設定
;
CAPTURE_DEVICE=br0
CAPTURE_FILTER=tcp and net 192.168.1.0 mask 255.255.255.0 and ( dst port 7000 or dst port 7010 )

; 通信サーバー端末情報
;
FN_COMM_SERVER=192.168.1.10:7000/192.168.1.10:7010

; 装置死活監視間隔[秒]
;
M_ALIVE_INTERVAL=30

