; デバイス通信サーバアプリの設定
;

; 新通信用接続待受ポート
RECEIVE_PORT=7000

; NX通信用接続待受ポート
RECEIVE_PORT_NX=7010

; 共通プロトコル通信用リクエスト間隔（秒）
REQUEST_TIME_CP=10

; 共通プロトコル通信V4用タイムアウト設定（0:使用しない,1:使用する）
RESPONSE_TIMEOUT_CP=1

; 仮想端末データキャッシュ（0:使用しない,1:使用する）
LCD_DATA_CASH=0
