spring:
  datasource:
    default:
      #jdbc-url: jdbc:postgresql://ntss-platform-rds.chzddp07crsf.ap-northeast-1.rds.amazonaws.com:5432/ntss_db5?currentSchema=ntss&stringtype=unspecified
      #jdbc-url: jdbc:postgresql://ntss-platform-service-rds.c39h9ck7e4ad.ap-northeast-1.rds.amazonaws.com:5432/ntss_db5?currentSchema=ntss&stringtype=unspecified
      #      jdbc-url: jdbc:postgresql://172.30.15.151:5432/ntss_db5?currentSchema=ntss&stringtype=unspecified
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db5_git?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk5
      password: nkk5
    personal:
      #jdbc-url: jdbc:postgresql://ntss-platform-rds.chzddp07crsf.ap-northeast-1.rds.amazonaws.com:5432/ntss_db6?currentSchema=ntss&stringtype=unspecified
      #jdbc-url: jdbc:postgresql://ntss-platform-service-rds.c39h9ck7e4ad.ap-northeast-1.rds.amazonaws.com:5432/ntss_db6?stringtype=unspecified&stringtype=unspecified
      #      jdbc-url: jdbc:postgresql://172.30.15.151:5432/ntss_db6?currentSchema=ntss&stringtype=unspecified
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db6_git?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk6
      password: nkk6
    auth:
      #jdbc-url: jdbc:postgresql://ntss-platform-rds.chzddp07crsf.ap-northeast-1.rds.amazonaws.com:5432/ntss_db4?currentSchema=ntss&stringtype=unspecified
      #jdbc-url: jdbc:postgresql://ntss-platform-service-rds.c39h9ck7e4ad.ap-northeast-1.rds.amazonaws.com:5432/ntss_db4?stringtype=unspecified&stringtype=unspecified
      #      jdbc-url: jdbc:postgresql://172.30.15.151:5432/ntss_db4?currentSchema=ntss&stringtype=unspecified
      jdbc-url: jdbc:postgresql://localhost:5432/ntss_db4_git?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk4
      password: nkk4
  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: ntss-web-api
  jmx:
    default-domain: ntss-web-api

server:
  servlet:
    contextPath: /ntss-web-api
  port:
    8088

doma:
  dialect: postgres

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

securityporicy:
  accesskeycheck: true

schedule-extend:
  cron: 0 0 2 * * *
  execute: true

#cloud:
#  aws:
#    region:
#      auto: false
#      static: ap-northeast-1
cloud:
  aws:
    region:
      auto: true
    stack:
      auto: false

fileIO:
  pathSeparator: /
  processTimeout: 300
  deleteFileTimeout: 10
  upload:
    tempDir: /var/lib/tomcat9/webapps/ntss-web-api/ntssUploadTemp
    tempPreFix: NtssUploadTempFile
    tempSufFix: .tmp
  download:
    tempDir: /var/lib/tomcat9/webapps/ntss-web-api/ntssDownloadTemp

ntss:
  web-api:
    web-socket-notify:
      app-sv:
        ws-port: 8090
        ws-api: '/ntss-client-comm/api/sendclient'
        header-name: 'SSECCAYEK'
        header-value: 'NTSS-NKK-ESM-TDC-YSK'
