/* eslint-disable */
export const RECEIVE_BEDGROUPLIST = 'RECEIVE_BEDGROUPLIST';
export const RECEIVE_GRAPHSETTINGLIST = 'RECEIVE_GRAPHSETTINGLIST';
export const RECEIVE_GRAPHSETTING = 'RECEIVE_GRAPHSETTING';
export const RECEIVE_MSTMONITOR = 'RECEIVE_MSTMONITOR';
export const RECEIVE_MSTMACHINE = 'RECEIVE_MSTMACHINE';
export const RECEIVE_MSTFACILITY = 'RECEIVE_MSTFACILITY';
export const RECEIVE_DATRST = 'RECEIVE_DATRST';
export const SET_DETAILINDEX = 'SET_DETAILINDEX';
export const SET_DETAILGRAPH = 'SET_DETAILGRAPH';
export const SET_VIEWDATA = 'SET_VIEWDATA';
export const SET_FRAME_SHOW_MODE = 'SET_FRAME_SHOW_MODE';
export const SET_STATE = 'SET_STATE';
export const SET_DISPNO = 'SET_DISPNO';
export const SET_DETAILGRAPH_ITEM = 'SET_DETAILGRAPH_ITEM';
export const SET_DEFAULT_APPITEM = 'SET_DEFAULT_APPITEM';
export const CHANGE_GRAPHSETTING_LIST = 'CHANGE_GRAPHSETTING_LIST';
export const CHANGE_GRAPHSETTING_DETAIL = 'CHANGE_GRAPHSETTING_DETAIL';

export const CHANGE_WORDS = 'CHANGE_WORDS';
export const SET_FACILITY_CODE = 'SET_FACILITY_CODE';
