/* 治療条件項目 */
export const IND_COND_ID = {
  // 治療時間
  DIALYSIS_TIME: "1",
  // VA
  VA: "2",
  // 目標体重 
  WEIGHT: "3",
  // 除水量制限
  OFFWATER: "4",
  // ダイアライザ
  DIALYZER: "5",
  // 吸着カラム
  ADSORPTIONCOLUMN: "6",
  // 1次膜
  FILM1: "7",
  // 2次膜
  FILM2: "8",
  // 穿刺針(A針)
  NEEDLE_A: "9",
  // 穿刺針(V針)
  NEEDLE_V: "10",
  // 穿刺針(SN)
  NEEDLE_SN: "11",
  // シングルニードル使用
  SINGLENEEDLE: "12",
  // 血液回路
  BLOODCIRCUIT: "13",
  // 血流量
  BLOODFLOW: "14",
  // 透析液
  DIALYSISFLUID: "15",
  // 透析液流量
  DIALYSISFLUID_FLOW: "16",
  // 透析液量
  DIALYSISFLUID_AMOUNT: "17",
  // 透析液温度
  DIALYSISFLUID_TEMPERATURE: "18",
  // 補液
  REPLENISHER: "19",
  // 補液量
  REPLENISHER_AMOUNT: "20",
  // 補液選択
  REPLENISHER_SELECT: "21",
  // 補液使用数
  REPLENISHER_NUM: "22",
  // 補液温度
  REPLENISHER_TEMPERATURE: "23",
  // 補液速度
  REPLENISHER_SPEED: "24",
  // 抗凝固剤
  ANTICOAGULANT: "25",
  // 抗凝固剤ワンショット量
  ANTICOAGULANT_ONESHOT: "26",
  // 抗凝固剤持続速度
  ANTICOAGULANT_SPEED: "27",
  // 抗凝固剤持総総量
  ANTICOAGULANT_AMOUNT: "28",
  // IP使用選択
  IP_USE: "29",
  // IPスタート
  IP_START: "30",
  // IPワンショット量
  IP_ONESHOT: "31",
  // IP速度
  IP_SPEED: "32",
  // IP速度最大値
  IP_SPEED_MAX: "33",
  // IPワンショットスタート
  AUTOONESHOT: "34",
  // IP電源自動切り
  IP_AUTOOFF: "35",
  // IP電源自動切り時間
  IP_AUTOOFF_TIME: "36",
  // IP電源OKモニタ切り
  IP_MONITOROFF: "37",
  // IP電源OKモニタ切り時間
  IP_MONITOROFF_TIME: "38"
};