// --------------------------------------
// レイアウトエリア
// --------------------------------------

export const layoutArea = [
  //
  {
    dataButtonNo: 1,
    index: "",
    dataButtonName: "区切",
    buttonItems: [
      {
        itemName: "check-box1",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkBox",
        hidden: true,
      },
      {
        itemName: "check-box2",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkBox",
        hidden: true,
      },
      {
        itemName: "text-readonly",
        /* mod FutreNetWeb+SI課題管理 劉全航 start */
        // itemWidth: "97.85%",
        itemWidth: "",
        /* mod FutreNetWeb+SI課題管理 劉全航 end */
        itemValue: "",
        disabled: true,
        type: "text-readonly",
        hidden: false,
      }
    ]
  },
  {
    dataButtonNo: 2,
    index: "",
    dataButtonName: "薬剤",
    buttonItems: [
      {
        itemName: "check-box1",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkBox",
        hidden: false,
      },
      {
        itemName: "check-box2",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkBox",
        hidden: false,
      },
      {
        itemName: "F1",
        itemWidth: "",
        itemValueCd: "",
        itemValue: "",
        itemValueType: "",
        disabled: true,
        type: "text",
        hidden: false,
      },
      {
        itemName: "button",
        itemWidth: "6em",
        disabled: false,
        name: "選択",
        type: "button",
        hidden: false,
      },
      {
        itemName: "F2",
        itemWidth: "",
        itemMaxWidth: "9em",
        itemMinWidth: "6em",
        disabled: false,
        itemValue: "",
        listClass: "01",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F5",
        itemWidth: "5em",
        itemMinWidth: "5em",
        disabled: false,
        itemValue: 0,
        unitDecimalPoint: 0,
        type: "number",
        hidden: false,
      },
      {
        itemName: "F6",
        itemWidth: "7em",
        itemMinWidth: "7em",
        disabled: false,
        itemValue: "",
        //mod FNSI-7151 処方画面への遷移、ボタン押下等の操作を行うとTypeErrorが発生する 劉全航 start
        // dataList: {},
        dataList: {unit: '', unitSecond: ''},
        //mod FNSI-7151 処方画面への遷移、ボタン押下等の操作を行うとTypeErrorが発生する 劉全航 end
        type: "dataList",
        hidden: false,
      }
    ]
  },
  {
    dataButtonNo: 3,
    index: "",
    dataButtonName: "内服",
    buttonItems: [
      {
        itemName: "check-box1",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "check-box2",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "F1",
        itemWidth: "",
        itemMinWidth: "11em",
        disabled: false,
        itemValue: "",
        listClass: "10",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F2",
        itemWidth: "",
        itemMinWidth: "11em",
        disabled: false,
        itemValue: "",
        listClass: "11",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F5",
        itemWidth: "5em",
        itemMinWidth: "5em",
        disabled: false,
        itemValue: 0,
        type: "number",
        hidden: false,
      },
      {
        itemName: "F6",
        itemWidth: "7em",
        itemMinWidth: "7em",
        disabled: false,
        itemValue: "日分",
        type: "dataList",
        hidden: false,
      },
    ]
  },
  {
    dataButtonNo: 4,
    index: "",
    dataButtonName: "外用",
    buttonItems: [
      {
        itemName: "check-box1",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "check-box2",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "F1",
        itemWidth: "",
        itemMinWidth: "10em",
        disabled: false,
        itemValue: "",
        listClass: "20",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F2",
        itemWidth: "",
        itemMinWidth: "4em",
        disabled: false,
        itemValue: "",
        listClass: "21",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F3",
        itemWidth: "",
        itemMinWidth: "4em",
        disabled: false,
        itemValue: "",
        listClass: "22",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F4",
        itemWidth: "",
        itemMinWidth: "4em",
        disabled: false,
        itemValue: "",
        listClass: "23",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F5",
        itemWidth: "5em",
        itemMinWidth: "5em",
        disabled: false,
        itemValue: 0,
        type: "number",
        hidden: false,
      },
      {
        itemName: "F6",
        itemWidth: "7em",
        itemMinWidth: "7em",
        disabled: false,
        // mod 5520 院外処方箋プレビューが正しく表示されない 王永吉 start
        // itemValue: "",
        itemValue: "日分",
        // mod 5520 院外処方箋プレビューが正しく表示されない 王永吉 end
        type: "dataList",
        hidden: false,
      },
    ]
  },
  {
    dataButtonNo: 5,
    index: "",
    dataButtonName: "頓内",
    buttonItems: [
      {
        itemName: "check-box1",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "check-box2",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "F1",
        itemWidth: "",
        itemMinWidth: "11em",
        disabled: false,
        itemValue: "",
        listClass: "30",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F2",
        itemWidth: "",
        itemMinWidth: "11em",
        disabled: false,
        itemValue: "",
        listClass: "11",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F5",
        itemWidth: "5em",
        itemMinWidth: "5em",
        disabled: false,
        itemValue: 0,
        type: "number",
        hidden: false,
      },
      {
        itemName: "F6",
        itemWidth: "7em",
        itemMinWidth: "7em",
        disabled: false,
        itemValue: "回分",
        type: "dataList",
        hidden: false,
      },
    ]
  },
  {
    dataButtonNo: 6,
    index: "",
    dataButtonName: "頓外",
    buttonItems: [
      {
        itemName: "check-box1",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "check-box2",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "F1",
        itemWidth: "",
        itemMinWidth: "10em",
        disabled: false,
        itemValue: "",
        listClass: "40",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F2",
        itemWidth: "",
        itemMinWidth: "4em",
        disabled: false,
        itemValue: "",
        listClass: "21",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F3",
        itemWidth: "",
        itemMinWidth: "4em",
        disabled: false,
        itemValue: "",
        listClass: "22",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F4",
        itemWidth: "",
        itemMinWidth: "4em",
        disabled: false,
        itemValue: "",
        listClass: "23",
        type: "dataList",
        hidden: false,
      },
      {
        itemName: "F5",
        itemWidth: "5em",
        itemMinWidth: "5em",
        disabled: false,
        itemValue: 0,
        type: "number",
        hidden: false,
      },
      {
        itemName: "F6",
        itemWidth: "7em",
        itemMinWidth: "7em",
        disabled: false,
        // mod 5520 院外処方箋プレビューが正しく表示されない 王永吉 start
        // itemValue: "",
        itemValue: "日分",
        // mod 5520 院外処方箋プレビューが正しく表示されない 王永吉 end
        type: "dataList",
        hidden: false,
      },
    ]
  },
  {
    dataButtonNo: 7,
    index: "",
    dataButtonName: "ｺﾒﾝﾄ",
    buttonItems: [
      {
        itemName: "check-box1",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "check-box2",
        itemWidth: "",
        itemMaxWidth: "2.5em",
        disabled: false,
        itemValue: false,
        type: "checkbox",
        hidden: true,
      },
      {
        itemName: "F1",
        /* mod FutreNetWeb+SI課題管理 劉全航 start */
        // itemWidth: "97.85%",
        itemWidth: "",
        /* mod FutreNetWeb+SI課題管理 劉全航 end */
        disabled: false,
        listClass: "99",
        itemValue: "",
        type: "dataList",
        hidden: false,
      },
    ]
  },
]
