template (name="NodeRedDynFile" type="string" string="/home/ntss/if_edge/logs/nodered/node-red_%$YEAR%%$MONTH%%$DAY%.log")
if $programname == 'node-red' then action(type="omfile" dynaFile="NodeRedDynFile")
& stop
