/**
 * 在宅透析患者用パンくず履歴特定用キー定義
 */

// お知らせ画面
export const HISTORY_KEY_PAT_HOME_DIALYSIS = "PAT_HOME_DIALYSIS";

// 前体重入力
export const HISTORY_KEY_PAT_HOME_DIALYSIS_WEIGHT_BEFORE = "PAT_HOME_DIALYSIS_WEIGHT_BEFORE";

// 透析状況確認
export const HISTORY_KEY_PAT_HOME_DIALYSIS_STATUS = "PAT_HOME_DIALYSIS_STATUS";

// 後体重入力
export const HISTORY_KEY_PAT_HOME_DIALYSIS_WEIGHT_AFTER = "PAT_HOME_DIALYSIS_WEIGHT_AFTER";