-- 既存のテーブル削除
DECLARE
    tbl_num NUMBER;
BEGIN
    SELECT COUNT(1) INTO tbl_num
    FROM user_tables
    WHERE table_name = UPPER('SYNC_SET_MEDICINE');

    IF tbl_num > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE SYNC_SET_MEDICINE CASCADE CONSTRAINTS';
    END IF;
END;
/

-- テーブル作成
CREATE TABLE SYNC_SET_MEDICINE
(
    SET_MEDICINE_CD CHAR(10),
    MEDICINE_CD     CHAR(10),
	FUNCTION_CD	  CHAR(1),
	SERIES_CD CHAR(3) NOT NULL
)
TABLESPACE NKK_DATA_COP;

-- コメント追加
COMMENT ON TABLE SYNC_SET_MEDICINE IS 'セット薬剤と個別薬剤の対応マスタ';

COMMENT ON COLUMN SYNC_SET_MEDICINE.SET_MEDICINE_CD IS 'セット薬剤コード';
COMMENT ON COLUMN SYNC_SET_MEDICINE.MEDICINE_CD     IS '薬剤コード';
COMMENT ON COLUMN SYNC_SET_MEDICINE.FUNCTION_CD     IS '機能コード';
COMMENT ON COLUMN SYNC_SET_MEDICINE.SERIES_CD       IS '施設コード';