-- テーブル削除
-- DROP TABLE TSS_PAT CASCADE CONSTRAINTS;
declare
      num number;
begin
    select count(1) into num from user_tables where table_name = upper('TSS_PAT') ;
    if num > 0 then
        execute immediate 'drop table TSS_PAT CASCADE CONSTRAINTS' ;
    end if;
end;
/
-- テーブル作成
CREATE TABLE TSS_PAT
(
    FNW_TABLE_NAME VARCHAR2(50) NOT NULL,  --FNWテーブル名
    FNW_COLUMN_NAME VARCHAR2(50) NOT NULL,  --FNWカラム名
    NTSS_TABLE_NAME VARCHAR2(50) NOT NULL,  --NTSSテーブル名
    NTSS_COLUMN_NO NUMBER(3,0) NOT NULL,  --NTSSカラム番号
    NTSS_COLUMN_NAME VARCHAR2(50) NOT NULL,  --NTSSカラム名
    NTSS_COLUMN_TYPE VARCHAR2(30) NOT NULL,  --NTSSカラムデータタイプ
    COLUMN_IS_ARRAY CHAR(1),  --配列フラグ
    JSON_KEY VARCHAR2(50),  --JSON情報 キー名
    JSON_VALUE_TYPE VARCHAR2(30),  --JSON情報 型
    JSON_DATA_FORMAT CHAR(1),  --JSON情報 形式
    JSON_KEY_ITEM CHAR(1),  --JSON情報 キー項目
    PK_FLG CHAR(1),  --主キーフラグ
    XML_CONFIG_NAME VARCHAR2(150),  --XML設定名
    SQL_CREATION_EXCLUSION_FLG NUMBER(1),  --SQL作成除外フラグ
    DELAY_BOUND_TARGET_FLG NUMBER(1),  --遅延バインド対象フラグ
    DELAY_BOUND_VARIABLE_FLG NUMBER(1),  --遅延バインド変数フラグ
    ENCRYPTION_FLG NUMBER(1)  --暗号化対象フラグ
)
    tablespace NKK_DATA_COP;
-- コメント追加
COMMENT ON TABLE "TSS_PAT" IS '患者情報継承定義';
COMMENT ON COLUMN "TSS_PAT"."FNW_TABLE_NAME" IS 'FNWテーブル名';
COMMENT ON COLUMN "TSS_PAT"."FNW_COLUMN_NAME" IS 'FNWカラム名';
COMMENT ON COLUMN "TSS_PAT"."NTSS_TABLE_NAME" IS 'NTSSテーブル名';
COMMENT ON COLUMN "TSS_PAT"."NTSS_COLUMN_NO" IS 'NTSSカラム番号';
COMMENT ON COLUMN "TSS_PAT"."NTSS_COLUMN_NAME" IS 'NTSSカラム名';
COMMENT ON COLUMN "TSS_PAT"."NTSS_COLUMN_TYPE" IS 'NTSSカラムデータタイプ';
COMMENT ON COLUMN "TSS_PAT"."COLUMN_IS_ARRAY" IS '配列フラグ';
COMMENT ON COLUMN "TSS_PAT"."JSON_KEY" IS 'JSON情報 キー名';
COMMENT ON COLUMN "TSS_PAT"."JSON_VALUE_TYPE" IS 'JSON情報 型';
COMMENT ON COLUMN "TSS_PAT"."JSON_DATA_FORMAT" IS 'JSON情報 形式';
COMMENT ON COLUMN "TSS_PAT"."JSON_KEY_ITEM" IS 'JSON情報 キー項目';
COMMENT ON COLUMN "TSS_PAT"."PK_FLG" IS '主キーフラグ';
COMMENT ON COLUMN "TSS_PAT"."XML_CONFIG_NAME" IS 'XML設定名';
COMMENT ON COLUMN "TSS_PAT"."SQL_CREATION_EXCLUSION_FLG" IS 'SQL作成除外フラグ';
COMMENT ON COLUMN "TSS_PAT"."DELAY_BOUND_TARGET_FLG" IS '遅延バインド対象フラグ';
COMMENT ON COLUMN "TSS_PAT"."DELAY_BOUND_VARIABLE_FLG" IS '遅延バインド変数フラグ';
