-- テーブル削除
-- DROP TABLE SYNC_ORD_CHECKLIST_HIST CASCADE CONSTRAINTS;
declare
      num number;
begin
    select count(1) into num from user_tables where table_name = upper('SYNC_ORD_CHECKLIST_HIST') ;
    if num > 0 then
        execute immediate 'drop table SYNC_ORD_CHECKLIST_HIST CASCADE CONSTRAINTS' ;
    end if;
end;
/
-- テーブル作成
CREATE TABLE SYNC_ORD_CHECKLIST_HIST
(
	PATID VARCHAR2(50),
	IND_ID VARCHAR2(50),
	DIALYSIS_DATE VARCHAR2(20),
	BED_NO NUMBER(4,0),
	KUR_CD CHAR(3),
	CODE CHAR(10),
	RST_CHECK_COUNT NUMBER,
	UP_DATE DATE
)
    tablespace NKK_DATA_COP;
-- コメント追加
COMMENT ON TABLE "SYNC_ORD_CHECKLIST_HIST" IS 'チェックリスト項目設定履歴';
COMMENT ON COLUMN "SYNC_ORD_CHECKLIST_HIST"."PATID" IS '患者ID';
COMMENT ON COLUMN "SYNC_ORD_CHECKLIST_HIST"."IND_ID" IS '患者ID + 透析日 + 同日複数回';
COMMENT ON COLUMN "SYNC_ORD_CHECKLIST_HIST"."DIALYSIS_DATE" IS '透析日';
COMMENT ON COLUMN "SYNC_ORD_CHECKLIST_HIST"."BED_NO" IS 'ベッド';
COMMENT ON COLUMN "SYNC_ORD_CHECKLIST_HIST"."KUR_CD" IS 'クール';
COMMENT ON COLUMN "SYNC_ORD_CHECKLIST_HIST"."CODE" IS '医材コード';
COMMENT ON COLUMN "SYNC_ORD_CHECKLIST_HIST"."RST_CHECK_COUNT" IS '実際チェック';

CREATE INDEX "NKK"."SYNC_ORD_CHECKLIST_HIST_IDX1" ON "NKK"."SYNC_ORD_CHECKLIST_HIST" ("PATID", "DIALYSIS_DATE", "BED_NO", "KUR_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

CREATE INDEX "NKK"."SYNC_ORD_CHECKLIST_HIST_IDX2" ON "NKK"."SYNC_ORD_CHECKLIST_HIST" ("PATID", "UP_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"