TRUNCATE TABLE SYNC_SEQ_COLUMN; 
INSERT INTO SYNC_SEQ_COLUMN(NTSS_TABLE_NAME,NTSS_COLUMN_NO,NTSS_COLUMN_NAME,UNIQUE_COLUMNS) VALUES ('mst_equipment_class',1,'class_cd','facility_cd,fn_class_cd');
INSERT INTO SYNC_SEQ_COLUMN(NTSS_TABLE_NAME,NTSS_COLUMN_NO,NTSS_COLUMN_NAME,UNIQUE_COLUMNS) VALUES ('mst_medicine',1,'medicine_cd','facility_cd,fn_medicine_cd');
INSERT INTO SYNC_SEQ_COLUMN(NTSS_TABLE_NAME,NTSS_COLUMN_NO,NTSS_COLUMN_NAME,UNIQUE_COLUMNS) VALUES ('mst_medicine_class',1,'class_cd','facility_cd,fn_class_cd');
INSERT INTO SYNC_SEQ_COLUMN(NTSS_TABLE_NAME,NTSS_COLUMN_NO,NTSS_COLUMN_NAME,UNIQUE_COLUMNS) VALUES ('mst_water_survey_type',1,'survey_tepy_cd','facility_cd,fn_survey_type_cd');
INSERT INTO SYNC_SEQ_COLUMN(NTSS_TABLE_NAME,NTSS_COLUMN_NO,NTSS_COLUMN_NAME,UNIQUE_COLUMNS) VALUES ('ord_main',1,'ord_no','fn_pat_id,treat_date,rst_fn_dialysis_no');
INSERT INTO SYNC_SEQ_COLUMN(NTSS_TABLE_NAME,NTSS_COLUMN_NO,NTSS_COLUMN_NAME,UNIQUE_COLUMNS) VALUES ('pat_main',1,'pat_id','facility_cd,fn_pat_id');

COMMIT;
