INSERT INTO mst_medicine(
facility_cd,
fn_medicine_cd,
standard_medicine_cd,
is_trial,
medicine_name,
medicine_short_name,
unit,
unit_second,
class_cd,
is_shot,
use_start_date,
use_end_date,
is_medicated,
unit_converted_amount,
unit_converted_amount_second,
anticoagulant_original_quantity,
after_anticoagulant_quantity,
in_hospital_cd_1,
in_hospital_cd_2,
in_hospital_cd_3,
is_disp,
is_del,
reg_date,
up_date,
is_exchange,
medicate_timing_cd,
procedure_cd,
unit_decimal_point,
unit_decimal_point_second,
in_hospital_cd_4)
VALUES(
/* mstMedicine.facilityCd */null,
/* mstMedicine.fnMedicineCd*/null,
/* mstMedicine.standardMedicineCd */null,
/* mstMedicine.isTrial */null,
/* mstMedicine.medicineName */null,
/* mstMedicine.medicineShortName */null,
/* mstMedicine.unit */null,
/* mstMedicine.unitSecond */null,
/* mstMedicine.classCd */null,
/* mstMedicine.isShot */null,
/* mstMedicine.useStartDate */null,
/* mstMedicine.useEndDate */null,
/* mstMedicine.isMedicated */null,
/* mstMedicine.unitConvertedAmount */null,
/* mstMedicine.unitConvertedAmountSecond */null,
/* mstMedicine.anticoagulantOriginalQuantity */null,
/* mstMedicine.afterAnticoagulantQuantity */null,
/* mstMedicine.inHospitalCd_1 */null,
/* mstMedicine.inHospitalCd_2 */null,
/* mstMedicine.inHospitalCd_3 */null,
/* mstMedicine.isDisp */'1',
/* mstMedicine.isDel */'0',
to_timestamp(/*mstMedicine.regDate*/null, 'YYYY-MM-DD HH24:MI:SS'),
to_timestamp(/*mstMedicine.upDate*/null, 'YYYY-MM-DD HH24:MI:SS'),
/* mstMedicine.isExchange */null,
/* mstMedicine.medicateTimingCd */null,
/* mstMedicine.procedureCd */null,
/* mstMedicine.unitDecimalPoint */null,
/* mstMedicine.unitDecimalPointSecond */null,
/* mstMedicine.inHospitalCd_4 */null);
