SET COLSEP ','
SET PAGESIZE 0
SET LINESIZE 1000
SET FEEDBACK OFF
SET TRIMSPOOL ON
SET TRIMOUT ON
SPOOL mst_coop_ini.csv

SELECT 
	'NKK' || ',' ||
	INI_SECTION || ',' ||
	INI_KEY || ',' ||
	INI_VALUE || ',' ||
	'' || ',' ||
	DEFAULT_VALUE || ',' ||
	'1'	
FROM SYS_COOP_INI_DATA
UNION
SELECT 
	'NKK' || ',' ||
	CASE WHEN COOP_FUNCTION_ID='410' THEN 'DIALYSISSCHESEND' ELSE 'DIALYSISSEND' END || ',' ||
	'MODIFY_SEND_CLASS' || ',' ||
	MODIFY_SEND_CLASS || ',' ||
	'' || ',' ||
	'0' || ',' ||
	'1'	
FROM MST_COOP_ID
WHERE IS_COOP_FLG ='1' AND COOP_FUNCTION_ID IN ('410','420')
;

SPOOL OFF

EXIT;
