SET COLSEP ','
SET PAGESIZE 0
SET LINESIZE 1000
SET FEEDBACK OFF
SET TRIMSPOOL ON
SET TRIMOUT ON
SPOOL mst_coop_facility.csv

SELECT 
	COOP_FUNCTION_ID || ',' ||
    ORDER_NUMBER_MANAGE_ID || ',' ||
    COOP_NAME || ',' ||
    COOP_ID || ',' ||
    SEND_LIMIT || ',' ||
    SEND_RECEIVE_CLASS
FROM MST_COOP_ID
WHERE IS_COOP_FLG ='1'
;

SPOOL OFF

EXIT;
