; データ収集アプリ設定
;
;


; 作業用ファイル格納先フォルダ
;
;WORK_FOLDER1=/mnt/usb/ntss/DataCollect_Work
;WORK_FOLDER2=/mnt/sd/ntss/DataCollect_Work
;WORK_FOLDER3=./DataCollect_Work
WORK_FOLDER1=./DataCollect_Work
WORK_FOLDER2=
WORK_FOLDER3=


; 装置FTPフォルダ
;
FTP_FOLDER=/DBCT/
; FTPユーザー名
;
FTP_USER=GUEST
; FTPパスワード
;
FTP_PW=GUEST
; FTPウエイト秒数
;
FTP_WAIT=2
; FTPリトライ回数
;
FTP_RETRY=1


; 圧縮パスワード
;
ZIP_PW=NTSS
; 圧縮ファイル最大サイズ(MB単位)
; ※超えた場合はファイルが分割される
;
;ZIP_FILE_MAXSIZE=8
ZIP_FILE_MAXSIZE=20

; API-Gateway経由
;; ユーザーキー
;;AWS_USER_KEY=AKIAI3BBPXCSRQAHDVZA
;AWS_USER_KEY=U2FsdGVkX18zLxYYzIz51N2Omrzv0BVWHKX+GTWnxFyLx0iZP6iALI9FV7n1hhSV
;; ユーザーシークレットキー
;;AWS_USER_SECRET_KEY=FpL+6PFhmF0CcdvKFpAsJUl7NpsSe0FymgvXr0I5
;AWS_USER_SECRET_KEY=U2FsdGVkX19nA+FC03h97aJTt5ctic6cAnJ62o2NnjFyRB6PfiGL3sU3eM7st66tz/2j/hPVtH2SwKPewBOs7g==
;; APIキー
;;AWS_API_KEY=y2AXo1QwYslwdsop01Q11nNQjBRT5BK4PFqqBcji
;AWS_API_KEY=U2FsdGVkX1/sfJxcjKdMv2PyfBpVn7O0x1yomwB/SG1Awt4UoCirxGw8CQDn++PPD2XQCnASnt76lsL83keidw==
;; AWSリージョン
;AWS_REGION=ap-northeast-1
;; AWSサービス名
;AWS_SERVICE=execute-api
;; AWSホスト名
;AWS_HOST=c6q4tmwurc.execute-api.ap-northeast-1.amazonaws.com
;; AWSアドレス
;AWS_ADDRESS=/ntss_gateway_s3/ntss-s3-root/
;; AWSファイルセキュリティ
;AWS_FILE_SECURITY=authenticated-read

; EC2経由
; AWSホスト名
AWS_HOST=http://tdc-public-alb-1851439829.ap-northeast-1.elb.amazonaws.com
; AWSアドレス
AWS_ADDRESS=/data_gathering/api/upload
