flyway.user=nkk5
flyway.password=nkk5
flyway.url=jdbc:postgresql://dev-ies-ntss-platform-service-cluster.cluster-cnr7cvlcb4ym.ap-northeast-1.rds.amazonaws.com:5432/ntss_db5_ait1
flyway.locations=filesystem:ntss-core/src/main/resources/db5/migration,filesystem:ntss-core/src/main/resources/db5/testdata,filesystem:ntss-core/src/main/resources/db5/testdata_e2e
flyway.schemas=ntss
