flyway.user=nkk6
flyway.password=nkk6
flyway.url=jdbc:postgresql://dev-ies-ntss-platform-service-cluster.cluster-cnr7cvlcb4ym.ap-northeast-1.rds.amazonaws.com:5432/ntss_db6_ait1
flyway.locations=filesystem:ntss-core/src/main/resources/db6/migration,filesystem:ntss-core/src/main/resources/db6/testdata,filesystem:ntss-core/src/main/resources/db6/testdata_e2e
flyway.schemas=ntss
