SELECT DISTINCT
	A.PATID
FROM
	IND_RECEIVE A
WHERE
	NOT EXISTS (
		SELECT * FROM IND_RECEIVE C
		WHERE
			A.PATID || A.DIALYSIS_DATE || A.PLURAL || A.CHECK_CLASS = C.PATID || C.DIALYSIS_DATE || C.PLURAL || C.CHECK_CLASS
			AND A.REG_DATE < C.REG_DATE 
		) 
	AND A.DIALYSIS_DATE >= :START_DATE AND A.DIALYSIS_DATE < :END_DATE AND {0}
