WITH SYS_TREAT_COND_SETTING_INFO AS (
SELECT DISTINCT TREAT_ITEM_CD  FROM  
SYS_TREAT_COND_SETTING STCS WHERE STCS.UP_DATE > TO_DATE(:MST_DIFF_DATETIME, 'YYYY/MM/DD HH24:MI:SS')),
IND_DIALYSIS_COND_INFO AS (
	SELECT DISTINCT
		IDC.PATID 
	FROM
		SYS_TREAT_COND_SETTING_INFO STCS
		INNER JOIN IND_DIALYSIS_COND IDC ON IDC.VALUE_1W1N = STCS.TREAT_ITEM_CD 
		OR IDC.VALUE_1W2N = STCS.TREAT_ITEM_CD 
		OR IDC.VALUE_1W3N = STCS.TREAT_ITEM_CD 
		OR IDC.VALUE_1W4N = STCS.TREAT_ITEM_CD 
		OR IDC.VALUE_1W5N = STCS.TREAT_ITEM_CD 
		OR IDC.VALUE_1W6N = STCS.TREAT_ITEM_CD 
		OR IDC.VALUE_1W7N = STCS.TREAT_ITEM_CD 
	WHERE
		CTL_NO = '006' 
		AND  TO_CHAR( TO_DATE(:MST_DIFF_DATETIME, 'YYYY/MM/DD HH24:MI:SS' ), 'YYYYMMDD' ) <= IDC.IND_END_DATE
		AND {0}	
	)
,SYNC_ORD_MAIN_SCH_INFO AS (
	SELECT
		SOMSP.PATID,
		SOMSP.IND_ID,
		SOMSP.DIALYSIS_DATE,
		SOMSP.PLURAL,
		SOMSP.OPE_IND_PLAN,
		SOMSP.VALUE 
	FROM
		IND_DIALYSIS_COND_INFO IDCI
		INNER JOIN SYNC_ORD_MAIN_SCH_PLAN SOMSP ON SOMSP.PATID = IDCI.PATID 
	),
	IND_ID_INFO1 AS (
	SELECT
		SYNSI.IND_ID,
		SYNSI.PATID,
		SYNSI.PLURAL,
		SYNSI.DIALYSIS_DATE,
		SYNSI.VALUE,
		SYNSI.OPE_IND_PLAN,
		IDC.UP_DATE,
		IDC.VALUE_1W1N,
		IDC.VALUE_1W2N,
		IDC.VALUE_1W3N,
		IDC.VALUE_1W4N,
		IDC.VALUE_1W5N,
		IDC.VALUE_1W6N,
		IDC.VALUE_1W7N,
		IDC.DEL_FLG 
	FROM
		SYNC_ORD_MAIN_SCH_INFO SYNSI
		INNER JOIN IND_DIALYSIS_COND IDC ON SYNSI.PATID = IDC.PATID 
		AND ( SYNSI.DIALYSIS_DATE BETWEEN IDC.IND_START_DATE AND IDC.IND_END_DATE ) 
		AND SYNSI.PLURAL = IDC.PLURAL 
		AND SYNSI.OPE_IND_PLAN = IDC.OPE_IND_PLAN 
		AND IDC.OPE_IND_PLAN = '1' 
		AND CTL_NO = '006' 
	),
	IND_ID_INFO2 AS (
	SELECT
		SYNSI.IND_ID,
		SYNSI.PATID,
		SYNSI.PLURAL,
		SYNSI.DIALYSIS_DATE,
		SYNSI.VALUE,
		SYNSI.OPE_IND_PLAN,
		IDC.UP_DATE,
		IDC.VALUE_1W1N,
		IDC.VALUE_1W2N,
		IDC.VALUE_1W3N,
		IDC.VALUE_1W4N,
		IDC.VALUE_1W5N,
		IDC.VALUE_1W6N,
		IDC.VALUE_1W7N,
		IDC.DEL_FLG 
	FROM
		SYNC_ORD_MAIN_SCH_INFO SYNSI
		INNER JOIN IND_DIALYSIS_COND IDC ON SYNSI.PATID = IDC.PATID 
		AND ( SYNSI.DIALYSIS_DATE BETWEEN IDC.IND_START_DATE AND IDC.IND_END_DATE ) 
		AND SYNSI.PLURAL = IDC.PLURAL 
		AND SYNSI.OPE_IND_PLAN = IDC.OPE_IND_PLAN 
		AND IDC.OPE_IND_PLAN = '0' 
		AND CTL_NO = '006' 
	),
	IND_ID_INFO1_MAXUPDATE AS ( SELECT PATID, DIALYSIS_DATE, PLURAL, MAX( UP_DATE ) MAX_UP_DATE FROM IND_ID_INFO1 GROUP BY PATID, DIALYSIS_DATE, PLURAL ),
	IND_ID_INFO2_MAXUPDATE AS ( SELECT PATID, DIALYSIS_DATE, PLURAL, MAX( UP_DATE ) MAX_UP_DATE FROM IND_ID_INFO2 GROUP BY PATID, DIALYSIS_DATE, PLURAL ),
	ORD_MIAN_DATA AS (
	SELECT
		III1.IND_ID,
		III1.PATID,
		III1.DIALYSIS_DATE,
		III1.OPE_IND_PLAN,
		III1.VALUE,
		III1.UP_DATE,
		III1.VALUE_1W1N,
		III1.VALUE_1W2N,
		III1.VALUE_1W3N,
		III1.VALUE_1W4N,
		III1.VALUE_1W5N,
		III1.VALUE_1W6N,
		III1.VALUE_1W7N,
		III1.DEL_FLG 
	FROM
		IND_ID_INFO1 III1
		INNER JOIN IND_ID_INFO1_MAXUPDATE III1M ON III1M.MAX_UP_DATE = III1.UP_DATE 
		AND III1M.PATID = III1.PATID 
		AND III1M.DIALYSIS_DATE = III1.DIALYSIS_DATE 
		AND III1M.PLURAL = III1.PLURAL UNION
	SELECT
		III2.IND_ID,
		III2.PATID,
		III2.DIALYSIS_DATE,
		III2.OPE_IND_PLAN,
		III2.VALUE,
		III2.UP_DATE,
		III2.VALUE_1W1N,
		III2.VALUE_1W2N,
		III2.VALUE_1W3N,
		III2.VALUE_1W4N,
		III2.VALUE_1W5N,
		III2.VALUE_1W6N,
		III2.VALUE_1W7N,
		III2.DEL_FLG 
	FROM
		IND_ID_INFO2 III2
		INNER JOIN IND_ID_INFO2_MAXUPDATE III2M ON III2M.MAX_UP_DATE = III2.UP_DATE 
		AND III2M.PATID = III2.PATID 
		AND III2M.DIALYSIS_DATE = III2.DIALYSIS_DATE 
		AND III2M.PLURAL = III2.PLURAL 
	),
	ORD_MIAN_DATA_TREAT AS (
	SELECT
		IND_ID,
		DIALYSIS_DATE,
	CASE
			SUBSTR( VALUE, - 1, 1 ) 
			WHEN '1' THEN
			VALUE_1W1N 
			WHEN '2' THEN
			VALUE_1W2N 
			WHEN '3' THEN
			VALUE_1W3N 
			WHEN '4' THEN
			VALUE_1W4N 
			WHEN '5' THEN
			VALUE_1W5N 
			WHEN '6' THEN
			VALUE_1W6N 
			WHEN '7' THEN
			VALUE_1W7N 
		END AS TREAT_ITEM_CD 
	FROM
		ORD_MIAN_DATA 
	) SELECT
	IND_ID 
FROM
	ORD_MIAN_DATA_TREAT OMDT
	INNER JOIN SYS_TREAT_COND_SETTING_INFO STTSI ON STTSI.TREAT_ITEM_CD = OMDT.TREAT_ITEM_CD 
WHERE
	OMDT.DIALYSIS_DATE >= TO_CHAR( TO_DATE(:MST_DIFF_DATETIME, 'YYYY/MM/DD HH24:MI:SS' ), 'YYYYMMDD' )