-- ？？？？患者の実績を作成

insert into ord_main
  (pat_id,
  treat_date,
  treat_week,
  facility_cd,
  facility_name,
  rst_kur_cd,
  rst_kur_name,
  rst_bed_cd,
  rst_bed_name,
  rst_machine_no,
  rst_machine_name,
  rst_dialysis_state,
  rst_start_date,
  rst_dialysis_cnt,
  rst_puncture_user_info,
  rst_return_user_info,
  rst_charge_user_info,
  rst_tare_info,
  rst_off_water_info,
  rst_weight_info,
  ind_cond_info,
  ind_medi_info,
  ind_equip_info,
  rst_input_class,
  up_date,
  reg_date)
values
  (/*param.patId*/null,
  /*param.treatDate*/'1970/01/01',
  /*param.treatWeek*/0,
  /*param.facilityCd*/'000001',
  (select facility_name from mst_facility where facility_cd = /*param.facilityCd*/'000001'),
  /*param.rstKurCd*/0,
  /*param.rstKurName*/null,
  /*param.rstBedCd*/0,
  /*param.rstBedName*/null,
  /*param.rstMachineNo*/1,
  (select machine_name from mst_machine where machine_no = /*param.rstMachineNo*/1),
  /*param.dialState*/0,
  /*param.startDate*/'1970/01/01 00:00:00',
  /*param.rstDialysisCnt*/0,
  /*param.rstPunctureUserInfo*/null,
  /*param.rstReturnUserInfo*/null,
  /*param.rstChargeUserInfo*/null,
  /*param.rstTareInfo*/null,
  /*param.rstOffWaterInfo*/null,
  /*param.rstWeightInfo*/null,
  /*param.indCondInfo*/null,
  /*param.indMediInfo*/null,
  /*param.indEquipInfo*/null,
  '1',
  /*param.upDate*/'1970/01/01 00:00:00',
  /*param.regDate*/'1970/01/01 00:00:00')
;
