insert into sys_facility (
  facility_cd,
  prefectures_cd,
  facility_name,
  facility_short_name,
  jsdt_facility_cd,
  medical_institution_cd,
  zipcd,
  address,
  address_kana,
  phone_no1,
  phone_no2,
  fax_no1,
  fax_no2,
  up_date,
  reg_date,
  is_disp,
  is_del
) values (
  /* sysFacility.facilityCd */null,
  /* sysFacility.prefecturesCd */null,
  /* sysFacility.facilityName */null,
  /* sysFacility.facilityShortName */null,
  /* sysFacility.jsdtFacilityCd */null,
  /* sysFacility.medicalInstitutionCd */null,
  /* sysFacility.zipcd */null,
  /* sysFacility.address */null,
  /* sysFacility.addressKana */null,
  /* sysFacility.phoneNo1 */null,
  /* sysFacility.phoneNo2 */null,
  /* sysFacility.faxNo1 */null,
  /* sysFacility.faxNo2 */null,
  CURRENT_TIMESTAMP(3),
  CURRENT_TIMESTAMP(3),
  '1',
  '0'
);
