; 取得対象コマンド設定[固定長]
; 通信方式[1桁]('0':通信なし/'1':新通信/'2'：NX通信/'3':通信共通V4),コマンド番号[4桁],識別文字列[6桁],データ格納先[1桁](0：緊急発報/１：データ収集)
;
1,62  ,MON   ,1
1,64  ,MNT   ,1
1,66  ,LOG   ,0
2,0002,MON   ,1
2,0003,OPE   ,1
2,0005,LOG   ,0
;2,0100,MT0   ,1
;2,0101,MT1   ,1
;2,0400,DAR   ,1
2,0A00,DAR   ,1