flyway.user=nkk4
flyway.password=nkk4
flyway.url=jdbc:postgresql://172.16.80.64:5432/ntss_db4
flyway.locations=filesystem:ntss-core/src/main/resources/db4/migration,filesystem:ntss-core/src/main/resources/db4/testdata
flyway.schemas=ntss
