flyway.user=nkk5
flyway.password=nkk5
flyway.url=jdbc:postgresql://172.16.80.64:5432/ntss_db5
flyway.locations=filesystem:ntss-core/src/main/resources/db5/migration,filesystem:ntss-core/src/main/resources/db5/testdata
flyway.schemas=ntss
