; デバイスログ処理アプリの設定
;

; ログ処理待受ホスト（IPアドレス）
;
LOGSV_HOST=127.0.0.1

; ログ処理待受ポート
;
LOGSV_PORT=7100

; ログ処理タイムアウト（秒）
;
LOGSV_TIMEOUT=600

; ログ処理格納先フォルダ
;
LOGSV_FOLDER1=/mnt/usb/ntss/log
LOGSV_FOLDER2=/mnt/sd/ntss/log
LOGSV_FOLDER3=./log

; ログ処理作業用フォルダ
;
LOGSV_TEMP_FOLDER=./temp

; アップロード先
;
; 開発環境 
UPLOAD_PATH=s3://ntss-s3-root/LOG/%s
; 検証環境(IoT)
;UPLOAD_PATH=s3://ntss-s3-root-verification/LOG/%s
; 検証環境(非IoT)
;UPLOAD_PATH=s3://ntss-s3-root-verification-provisional/LOG/%s

; アップロード実施時間
;
UPLOAD_TIME=18:30
