; デバイスキャプチャ処理アプリ設定
;
;

; パケットキャプチャ設定
;
;CAPTURE_DEVICE=ens37
CAPTURE_DEVICE=ens33
; 通信共通がない場合
;CAPTURE_FILTER=tcp and net 192.168.1.0 mask 255.255.255.0 and ( dst port 7000 or dst port 7010 )
;CAPTURE_FILTER=tcp and net 192.168.102.0 mask 255.255.255.0 and ( dst port 7000 or dst port 7010 )
; 通信共通がある場合
CAPTURE_FILTER=tcp and dst host 192.168.102.168 and ( src port 1401 or dst port 7000 or dst port 7010 )

; 通信サーバー端末情報
;
FN_COMM_SERVER=192.168.102.168:0

; 装置死活監視間隔[秒]
;
M_ALIVE_INTERVAL=30
