spring:
  datasource:
    # NKK aws
    # url: jdbc:postgresql://ntss-platform-rds.chzddp07crsf.ap-northeast-1.rds.amazonaws.com:5432/ntss?stringtype=unspecified
    # TDC aws
    # url: jdbc:postgresql://testdbinstance.cc0dnsfhoqgq.ap-northeast-1.rds.amazonaws.com:5432/ntss?stringtype=unspecified
    # TDC kataguchi local
    # url: jdbc:postgresql://localhost:5432/ntss
#    driver-class-name: org.postgresql.Driver
#    username: nkk
#    password: nkk
    default:
      jdbc-url: jdbc:postgresql://192.168.102.184:5432/ntss?currentSchema=ntss&stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: nkk
      password: nkk
  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: ntss-tdc-develop-disp
  jmx:
    default-domain: ntss-tdc-develop-disp

doma:
  dialect: postgres

logging:
  level:
    org.springframework.transaction.interceptor: TRACE

cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-1 # 東京リージョン
