delete from mst_personal_user;

INSERT INTO mst_personal_user
  (
    user_id, 
    facility_cd,
    user_last_name,
    user_first_name,
    user_email_address_1,
    user_email_address_2,
    user_type,
    job_cd
    
  )
VALUES
    (
    101,
    '09999',
    personal_info_encrypt('テスト1'),
    personal_info_encrypt('太郎1'),
    personal_info_encrypt('test1@esm.co.jp'),
    personal_info_encrypt('test２@example.co.jp'),
    0,
    personal_info_encrypt('01')
    ),
    (
    102,
    '09999',
    personal_info_encrypt('テスト2'),
    personal_info_encrypt('太郎2'),
    personal_info_encrypt('test2@esm.co.jp'),
    personal_info_encrypt('test2@example.co.jp'),
    0,
    personal_info_encrypt('02')
    ),
    (
    103,
    '09999',
    personal_info_encrypt('テスト3'),
    personal_info_encrypt('太郎3'),
    personal_info_encrypt('test@test3@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('03')
    ),
    (
    104,
    '09999',
    personal_info_encrypt('テスト4'),
    personal_info_encrypt('太郎4'),
    personal_info_encrypt('test4@esm.co.jp'),
    personal_info_encrypt('test4+test@example.co.jp'),
    0,
    personal_info_encrypt('04')
    ),
    (
    105,
    '09999',
    personal_info_encrypt('テスト5'),
    personal_info_encrypt('太郎5'),
    personal_info_encrypt('test5@esm.co.jp'),
    personal_info_encrypt('test5@example.co.jp'),
    0,
    personal_info_encrypt('05')
    ),
    (
    106,
    '09999',
    personal_info_encrypt('テスト6'),
    personal_info_encrypt('太郎6'),
    personal_info_encrypt('test6@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('06')
    ),
    (
    107,
    '09999',
    personal_info_encrypt('テスト7'),
    personal_info_encrypt('太郎7'),
    personal_info_encrypt('1test7@esm.co.jp'),
    personal_info_encrypt('test7@example.co.jp'),
    0,
    personal_info_encrypt('07')
    ),
    (
    108,
    '09999',
    personal_info_encrypt('テスト8'),
    personal_info_encrypt('太郎8'),
    personal_info_encrypt('te.st8@esm.co.jp'),
    personal_info_encrypt('test8@example.co.jp'),
    0,
    personal_info_encrypt('08')
    ),
    (
    109,
    '09999',
    personal_info_encrypt('テスト9'),
    personal_info_encrypt('太郎9'),
    personal_info_encrypt('test9@esm.co.jp'),
    personal_info_encrypt('test9@example.co.jp'),
    0,
    personal_info_encrypt('09')
    ),
    (
    110,
    '09999',
    personal_info_encrypt('テスト10'),
    personal_info_encrypt('太郎10'),
    personal_info_encrypt('test10@esm.co.jp'),
    personal_info_encrypt('test10@example.co.jp'),
    0,
    personal_info_encrypt('10')
    ),
    (
    111,
    '09999',
    personal_info_encrypt('テスト11'),
    personal_info_encrypt('太郎11'),
    personal_info_encrypt('test11@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('11')
    ),
    (
    112,
    '09999',
    personal_info_encrypt('テスト12'),
    personal_info_encrypt('太郎12'),
    personal_info_encrypt('test12@esm.co.jp'),
    personal_info_encrypt('test12@example.co.jp'),
    0,
    personal_info_encrypt('12')
    ),
    (
    113,
    '09999',
    personal_info_encrypt('テスト13'),
    personal_info_encrypt('太郎13'),
    personal_info_encrypt('test13@esm.co.jp'),
    personal_info_encrypt('test13@example.co.jp'),
    0,
    personal_info_encrypt('13')
    ),
    (
    114,
    '09999',
    personal_info_encrypt('テスト14'),
    personal_info_encrypt('太郎14'),
    personal_info_encrypt('test14@esm.co.jp'),
    personal_info_encrypt('test14@example.co.jp'),
    0,
    personal_info_encrypt('14')
    ),
    (
    115,
    '09999',
    personal_info_encrypt('テスト15'),
    personal_info_encrypt('太郎15'),
    personal_info_encrypt('test15@esm.co.jp'),
    personal_info_encrypt('test15@example.co.jp'),
    0,
    personal_info_encrypt('15')
    ),
    (
    116,
    '09999',
    personal_info_encrypt('テスト16'),
    personal_info_encrypt('太郎16'),
    personal_info_encrypt('test16@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('16')
    ),
    (
    117,
    '09999',
    personal_info_encrypt('テスト17'),
    personal_info_encrypt('太郎17'),
    personal_info_encrypt('test17@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('17')
    ),
    (
    118,
    '09999',
    personal_info_encrypt('テスト18'),
    personal_info_encrypt('太郎18'),
    personal_info_encrypt('test18@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('18')
    ),
    (
    119,
    '09999',
    personal_info_encrypt('テスト19'),
    personal_info_encrypt('太郎19'),
    personal_info_encrypt('test19@esm.co.jp'),
    personal_info_encrypt('test19@example.co.jp'),
    0,
    personal_info_encrypt('19')
    ),
    (
    120,
    '09999',
    personal_info_encrypt('テスト20'),
    personal_info_encrypt('太郎20'),
    personal_info_encrypt('test20@esm.co.jp'),
    personal_info_encrypt('test20@example.co.jp'),
    0,
    personal_info_encrypt('20')
    ),
    (
    121,
    '09999',
    personal_info_encrypt('テスト21'),
    personal_info_encrypt('太郎21'),
    personal_info_encrypt('test21@esm.co.jp'),
    personal_info_encrypt('test21@example.co.jp'),
    0,
    personal_info_encrypt('21')
    ),
    (
    122,
    '09999',
    personal_info_encrypt('テスト22'),
    personal_info_encrypt('太郎22'),
    personal_info_encrypt('test22@esm.co.jp'),
    personal_info_encrypt('test22@example.co.jp'),
    0,
    personal_info_encrypt('22')
    ),
    (
    123,
    '09999',
    personal_info_encrypt('テスト23'),
    personal_info_encrypt('太郎23'),
    personal_info_encrypt('test23@esm.co.jp'),
    personal_info_encrypt('test23@example.co.jp'),
    0,
    personal_info_encrypt('23')
    ),
    (
    124,
    '09999',
    personal_info_encrypt('テスト24'),
    personal_info_encrypt('太郎24'),
    personal_info_encrypt('test24@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('24')
    ),
    (
    125,
    '09999',
    personal_info_encrypt('テスト25'),
    personal_info_encrypt('太郎25'),
    personal_info_encrypt('test25@esm.co.jp'),
    personal_info_encrypt('test25@example.co.jp'),
    0,
    personal_info_encrypt('25')
    ),
    (
    126,
    '09999',
    personal_info_encrypt('テスト26'),
    personal_info_encrypt('太郎26'),
    personal_info_encrypt('test26@esm.co.jp'),
    personal_info_encrypt('test26@example.co.jp'),
    0,
    personal_info_encrypt('26')
    ),
    (
    127,
    '09999',
    personal_info_encrypt('テスト27'),
    personal_info_encrypt('太郎27'),
    personal_info_encrypt('test27@esm.co.jp'),
    personal_info_encrypt('test27@example.co.jp'),
    0,
    personal_info_encrypt('27')
    ),
    (
    128,
    '09999',
    personal_info_encrypt('テスト28'),
    personal_info_encrypt('太郎28'),
    personal_info_encrypt('test28@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('28')
    ),
    (
    129,
    '09999',
    personal_info_encrypt('テスト29'),
    personal_info_encrypt('太郎29'),
    personal_info_encrypt('test29@esm.co.jp'),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('29')
    ),
    (
    130,
    '09999',
    personal_info_encrypt('テスト30'),
    personal_info_encrypt('太郎30'),
    personal_info_encrypt('test30@esm.co.jp'),
    personal_info_encrypt('test30@example.co.jp'),
    0,
    personal_info_encrypt('30')
    ),
    (
    131,
    '09999',
    personal_info_encrypt('MailAddressテスト1'),
    personal_info_encrypt('空欄'),
    personal_info_encrypt(''),
    personal_info_encrypt(''),
    0,
    personal_info_encrypt('31')
    ),
    (
    132,
    '09999',
    personal_info_encrypt('MailAddressテスト2'),
    personal_info_encrypt('nullデータ'),
    null,
    null,
    0,
    personal_info_encrypt('32')
    ),
    (
    201,
    '09997',
    personal_info_encrypt('Nテスト1'),
    personal_info_encrypt('N太郎1'),
    personal_info_encrypt('ntest1@esm.co.jp'),
    personal_info_encrypt('ntest1@example.co.jp'),
    1,
    personal_info_encrypt('01')
    ),
    (
    202,
    '09997',
    personal_info_encrypt('Nテスト2'),
    personal_info_encrypt('N太郎2'),
    personal_info_encrypt('ntest2@esm.co.jp'),
    personal_info_encrypt('ntest2@example.co.jp'),
    1,
    personal_info_encrypt('02')
    ),
    (
    203,
    '09997',
    personal_info_encrypt('Nテスト3'),
    personal_info_encrypt('N太郎3'),
    personal_info_encrypt('ntest3@esm.co.jp'),
    personal_info_encrypt(''),
    1,
    personal_info_encrypt('03')
    ),
    (
    204,
    '09997',
    personal_info_encrypt('Nテスト4'),
    personal_info_encrypt('N太郎4'),
    personal_info_encrypt('ntest4@esm.co.jp'),
    personal_info_encrypt('ntest4@example.co.jp'),
    1,
    personal_info_encrypt('04')
    ),
    (
    205,
    '09997',
    personal_info_encrypt('Nテスト5'),
    personal_info_encrypt('N太郎5'),
    personal_info_encrypt('ntest5@esm.co.jp'),
    personal_info_encrypt('ntest5@example.co.jp'),
    1,
    personal_info_encrypt('05')
    ),
    (
    206,
    '09997',
    personal_info_encrypt('Nテスト6'),
    personal_info_encrypt('N太郎6'),
    personal_info_encrypt('ntest6@esm.co.jp'),
    personal_info_encrypt('ntest6@example.co.jp'),
    1,
    personal_info_encrypt('06')
    ),
    (
    207,
    '09997',
    personal_info_encrypt('Nテスト7'),
    personal_info_encrypt('N太郎7'),
    personal_info_encrypt('ntest7@esm.co.jp'),
    personal_info_encrypt('ntest7@example.co.jp'),
    1,
    personal_info_encrypt('07')
    ),
    (
    208,
    '09997',
    personal_info_encrypt('Nテスト8'),
    personal_info_encrypt('N太郎8'),
    personal_info_encrypt('ntest8@esm.co.jp'),
    personal_info_encrypt('ntest8@example.co.jp'),
    1,
    personal_info_encrypt('08')
    ),
    (
    209,
    '09997',
    personal_info_encrypt('Nテスト9'),
    personal_info_encrypt('N太郎9'),
    personal_info_encrypt('ntest9@esm.co.jp'),
    personal_info_encrypt('ntest9@example.co.jp'),
    1,
    personal_info_encrypt('09')
    ),
    (
    210,
    '09997',
    personal_info_encrypt('Nテスト10'),
    personal_info_encrypt('N太郎10'),
    personal_info_encrypt('ntest10@esm.co.jp'),
    personal_info_encrypt('ntest10@example.co.jp'),
    1,
    personal_info_encrypt('10')
    ),
    (
    211,
    '09997',
    personal_info_encrypt('Nテスト11'),
    personal_info_encrypt('N太郎11'),
    personal_info_encrypt('ntest11@esm.co.jp'),
    personal_info_encrypt('ntest11@example.co.jp'),
    1,
    personal_info_encrypt('11')
    ),
    (
    212,
    '09997',
    personal_info_encrypt('Nテスト12'),
    personal_info_encrypt('N太郎12'),
    personal_info_encrypt('ntest12@esm.co.jp'),
    personal_info_encrypt('ntest12@example.co.jp'),
    1,
    personal_info_encrypt('12')
    ),
    (
    213,
    '09997',
    personal_info_encrypt('Nテスト13'),
    personal_info_encrypt('N太郎13'),
    personal_info_encrypt('ntest13@esm.co.jp'),
    personal_info_encrypt('ntest13@example.co.jp'),
    1,
    personal_info_encrypt('13')
    ),
    (
    214,
    '09997',
    personal_info_encrypt('Nテスト14'),
    personal_info_encrypt('N太郎14'),
    personal_info_encrypt('ntest14@esm.co.jp'),
    personal_info_encrypt('ntest14@example.co.jp'),
    1,
    personal_info_encrypt('14')
    ),
    (
    215,
    '09997',
    personal_info_encrypt('Nテスト15'),
    personal_info_encrypt('N太郎15'),
    personal_info_encrypt('ntest15@esm.co.jp'),
    personal_info_encrypt('ntest15@example.co.jp'),
    1,
    personal_info_encrypt('15')
    ),
    (
    216,
    '09997',
    personal_info_encrypt('Nテスト16'),
    personal_info_encrypt('N太郎16'),
    personal_info_encrypt('ntest16@esm.co.jp'),
    personal_info_encrypt('ntest16@example.co.jp'),
    1,
    personal_info_encrypt('16')
    ),
    (
    217,
    '09997',
    personal_info_encrypt('Nテスト17'),
    personal_info_encrypt('N太郎17'),
    personal_info_encrypt('ntest17@esm.co.jp'),
    personal_info_encrypt('ntest17@example.co.jp'),
    1,
    personal_info_encrypt('17')
    ),
    (
    218,
    '09997',
    personal_info_encrypt('Nテスト18'),
    personal_info_encrypt('N太郎18'),
    personal_info_encrypt('ntest18@esm.co.jp'),
    personal_info_encrypt('ntest18@example.co.jp'),
    1,
    personal_info_encrypt('18')
    ),
    (
    219,
    '09997',
    personal_info_encrypt('Nテスト19'),
    personal_info_encrypt('N太郎19'),
    personal_info_encrypt('ntest19@esm.co.jp'),
    personal_info_encrypt('ntest19@example.co.jp'),
    1,
    personal_info_encrypt('19')
    ),
    (
    220,
    '09997',
    personal_info_encrypt('Nテスト20'),
    personal_info_encrypt('N太郎20'),
    personal_info_encrypt('ntest20@esm.co.jp'),
    personal_info_encrypt('ntest20@example.co.jp'),
    1,
    personal_info_encrypt('20')
    ),
    (
    221,
    '09997',
    personal_info_encrypt('Nテスト21'),
    personal_info_encrypt('N太郎21'),
    personal_info_encrypt('ntest21@esm.co.jp'),
    personal_info_encrypt('ntest21@example.co.jp'),
    1,
    personal_info_encrypt('21')
    ),
    (
    222,
    '09997',
    personal_info_encrypt('Nテスト22'),
    personal_info_encrypt('N太郎22'),
    personal_info_encrypt('ntest22@esm.co.jp'),
    personal_info_encrypt('ntest22@example.co.jp'),
    1,
    personal_info_encrypt('22')
    ),
    (
    223,
    '09997',
    personal_info_encrypt('Nテスト23'),
    personal_info_encrypt('N太郎23'),
    personal_info_encrypt('ntest23@esm.co.jp'),
    personal_info_encrypt('ntest23@example.co.jp'),
    1,
    personal_info_encrypt('23')
    ),
    (
    224,
    '09997',
    personal_info_encrypt('Nテスト24'),
    personal_info_encrypt('N太郎24'),
    personal_info_encrypt('ntest24@esm.co.jp'),
    personal_info_encrypt('ntest24@example.co.jp'),
    1,
    personal_info_encrypt('24')
    ),
    (
    225,
    '09997',
    personal_info_encrypt('Nテスト25'),
    personal_info_encrypt('N太郎25'),
    personal_info_encrypt('ntest25@esm.co.jp'),
    personal_info_encrypt('ntest25@example.co.jp'),
    1,
    personal_info_encrypt('25')
    ),
    (
    226,
    '09997',
    personal_info_encrypt('Nテスト26'),
    personal_info_encrypt('N太郎26'),
    personal_info_encrypt('ntest26@esm.co.jp'),
    personal_info_encrypt('ntest26@example.co.jp'),
    1,
    personal_info_encrypt('26')
    ),
    (
    227,
    '09997',
    personal_info_encrypt('Nテスト27'),
    personal_info_encrypt('N太郎27'),
    personal_info_encrypt('ntest27@esm.co.jp'),
    personal_info_encrypt('ntest27@example.co.jp'),
    1,
    personal_info_encrypt('27')
    ),
    (
    228,
    '09997',
    personal_info_encrypt('Nテスト28'),
    personal_info_encrypt('N太郎28'),
    personal_info_encrypt('ntest28@esm.co.jp'),
    personal_info_encrypt(''),
    1,
    personal_info_encrypt('28')
    ),
    (
    229,
    '09997',
    personal_info_encrypt('Nテスト29'),
    personal_info_encrypt('N太郎29'),
    personal_info_encrypt('ntest29@esm.co.jp'),
    personal_info_encrypt('ntest29@example.co.jp'),
    1,
    personal_info_encrypt('29')
    ),
    (
    230,
    '09997',
    personal_info_encrypt('Nテスト30'),
    personal_info_encrypt('N太郎30'),
    personal_info_encrypt('ntest30@esm.co.jp'),
    personal_info_encrypt('ntest30@example.co.jp'),
    1,
    personal_info_encrypt('30')
    ),
    (
    301,
    '09998',
    personal_info_encrypt('Qテスト1'),
    personal_info_encrypt('Q太郎1'),
    personal_info_encrypt('Qtest1@esm.co.jp'),
    personal_info_encrypt('Qtest1@example.co.jp'),
    0,
    personal_info_encrypt('01')
    ),
    (
    302,
    '09998',
    personal_info_encrypt('Qテスト2'),
    personal_info_encrypt('Q太郎2'),
    personal_info_encrypt('Qtest2@esm.co.jp'),
    personal_info_encrypt('Qtest2@example.co.jp'),
    0,
    personal_info_encrypt('02')
    )
;
