﻿DROP INDEX IF EXISTS idx_ord_main_03;
CREATE INDEX idx_ord_main_03 ON ord_main USING btree (rst_dialysis_state);
DROP INDEX IF EXISTS idx_ord_main_02;
CREATE INDEX idx_ord_main_02 ON ord_main USING btree (facility_cd,treat_date,ind_kur_cd,ind_bed_cd,is_del);
DROP INDEX IF EXISTS idx_ord_main_ind_medi_info_14;
CREATE INDEX idx_ord_main_ind_medi_info_14 ON ord_main USING GIN ((ind_medi_info -> 'cd'));
DROP INDEX IF EXISTS idx_ord_main_ind_equip_info_13;
CREATE INDEX idx_ord_main_ind_equip_info_13 ON ord_main USING GIN ((ind_equip_info -> 'cd'));
DROP INDEX IF EXISTS idx_ord_main_rst_equip_info_12;
CREATE INDEX idx_ord_main_rst_equip_info_12 ON ord_main USING GIN ((rst_equip_info -> 'cd'));
DROP INDEX IF EXISTS idx_ord_main_ind_cond_info_11;
CREATE INDEX idx_ord_main_ind_cond_info_11 ON ord_main USING GIN ((ind_cond_info -> 'value'))﻿;
DROP INDEX IF EXISTS idx_ord_main_rst_treat_staff_info_10;
CREATE INDEX idx_ord_main_rst_treat_staff_info_10 ON ord_main USING GIN ((rst_treat_staff_info -> 'occur_date'));
DROP INDEX IF EXISTS idx_ord_main_rst_treatment_info_09;
CREATE INDEX idx_ord_main_rst_treatment_info_09 ON ord_main USING GIN ((rst_treatment_info -> 'occur_date'), (rst_treatment_info -> 'oxygen_start'), (rst_treatment_info -> 'oxygen_amount'));
DROP INDEX IF EXISTS idx_ord_main_ind_schedule_user_info_08;
CREATE INDEX idx_ord_main_ind_schedule_user_info_08 ON ord_main USING GIN ((ind_schedule_user_info -> 'ind_user_id'));
DROP INDEX IF EXISTS idx_ord_main_rst_medi_info_07;
CREATE INDEX idx_ord_main_rst_medi_info_07 ON ord_main USING GIN ((rst_medi_info -> 'cd'),(rst_medi_info -> 'effect_date'),(rst_medi_info -> 'medicine_type'),(rst_medi_info -> 'timing_cd'));
DROP INDEX IF EXISTS idx_ord_main_addition_info_06;
CREATE INDEX idx_ord_main_addition_info_06 ON ord_main USING GIN ((addition_info -> 'cd'))﻿;
DROP INDEX IF EXISTS idx_ord_main_rst_treatment_info_05;
CREATE INDEX idx_ord_main_rst_treatment_info_05 ON ord_main USING GIN ((rst_treatment_info -> 'occur_date'), (rst_treatment_info -> 'ctl_no'), (rst_treatment_info -> 'oxygen_start'), (rst_treatment_info -> 'oxygen_speed'), (rst_treatment_info -> 'oxygen_amount'), (rst_treatment_info -> 'electrocardiogram_type'), (rst_treatment_info -> 'treat_name'));
DROP INDEX IF EXISTS idx_ord_main_rst_treat_staff_info_04;
CREATE INDEX idx_ord_main_rst_treat_staff_info_04 ON ord_main USING GIN ((rst_treat_staff_info -> 'occur_date'), (rst_treat_staff_info -> 'ctl_no'))﻿;