-- テーブル削除
declare
      num number;
begin
    select count(1) into num from user_tables where table_name = upper('SYNC_MAINTE_PARTS_DETAIL') ;
    if num > 0 then
        execute immediate 'drop table SYNC_MAINTE_PARTS_DETAIL CASCADE CONSTRAINTS' ;
    end if;
end;
/
-- テーブル作成
CREATE TABLE SYNC_MAINTE_PARTS_DETAIL
(
    EXCHANGE_TIME_CODE CHAR(1) NOT NULL,
    CALC_EXCHANGE_TIME CHAR(7),
	CALC_ID NUMBER
)
    tablespace NKK_DATA_COP;


INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '1500h', '1');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '3000h', '2');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '4500h', '3');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '6000h', '4');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '7500h', '5');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '9000h', '6');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '10500h', '7');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '12000h', '8');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '13500h', '9');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '15000h', '10');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '16500h', '11');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '18000h', '12');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '19500h', '13');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('0', '21000h', '14');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('1', '3000h', '1');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('1', '6000h', '2');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('1', '9000h', '3');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('1', '12000h', '4');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('1', '15000h', '5');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('1', '18000h', '6');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('1', '21000h', '7');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('2', '6000h', '1');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('2', '12000h', '2');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('2', '18000h', '3');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('3', '9000h', '1');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('3', '18000h', '2');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('4', '12000h', '1');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('5', '18000h', '1');
INSERT INTO "NKK"."SYNC_MAINTE_PARTS_DETAIL" ("EXCHANGE_TIME_CODE", "CALC_EXCHANGE_TIME", "CALC_ID") VALUES ('6', '21000h', '1');

