-- ============================
-- Table: mst_user_switch
-- ============================

CREATE TABLE IF NOT EXISTS mst_user_switch (
  switch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_cd VARCHAR(6) NOT NULL,
  user_id BIGINT NOT NULL,
  group_id VARCHAR(36) NOT NULL,
  opt_status CHAR(1) NOT NULL,
  is_del VARCHAR(1) DEFAULT '0',
  reg_date TIMESTAMP(3),
  reg_staff BIGINT,
  up_date TIMESTAMP(3),
  up_staff BIGINT
  );

-- ============================
-- Comments
-- ============================

COMMENT ON TABLE mst_user_switch IS '利用者切替マスタ';
COMMENT ON COLUMN mst_user_switch.switch_id IS 'ID';
COMMENT ON COLUMN mst_user_switch.facility_cd IS '施設コード';
COMMENT ON COLUMN mst_user_switch.user_id IS '利用者ID';
COMMENT ON COLUMN mst_user_switch.group_id IS 'グループID';
COMMENT ON COLUMN mst_user_switch.opt_status IS '秘密鍵 認証状態（Staff切替画面）';
COMMENT ON COLUMN mst_user_switch.is_del IS '削除フラグ';
COMMENT ON COLUMN mst_user_switch.reg_date IS '登録日時';
COMMENT ON COLUMN mst_user_switch.reg_staff IS '登録スタッフ';
COMMENT ON COLUMN mst_user_switch.up_date IS '更新日時';
COMMENT ON COLUMN mst_user_switch.up_staff IS '最終更新スタッフ';
