INSERT INTO V_IND_DIALYSIS_MEDI  VALUES (
'@patid',
'@dialysisDate',
'@plural',
'@ctlNo',
to_date('@upDate','yyyy-mm-dd hh24:mi:ss'),
'@medicineCd',
'@medicineCd2',
'@medicineName',
'@mediClassName',
'@amount',
'@uint',
'@timingName',
'@procedureCd',
'@procedureCd2',
'@peocedureName',
'@comments',
'@indicatorCd',
'@opeIndPlan'
);