INSERT INTO V_PAT_REVISE_TARE  VALUES (
'@patid',
'@name',
'@ctlNo',
to_date('@upDate','yyyy-mm-dd hh24:mi:ss'),
'@reviseName',
'@reviseWeight',
'@hospWheelchairCd',
'@wheelchairName',
to_date('@monUpDate','yyyy-mm-dd hh24:mi:ss'),
'@monReviseName',
'@monReviseWeight',
'@monHospWheelchairCd',
'@monWheelchairName',
to_date('@tueUpDate','yyyy-mm-dd hh24:mi:ss'),
'@tueReviseName',
'@tueReviseWeight',
'@tueHospWheelchairCd',
'@tueWheelchairName',
to_date('@wedUpDate','yyyy-mm-dd hh24:mi:ss'),
'@wedReviseName',
'@wedReviseWeight',
'@wedHospWheelchairCd',
'@wedWheelchairName',
to_date('@thuUpDate','yyyy-mm-dd hh24:mi:ss'),
'@thuReviseName',
'@thuReviseWeight',
'@thuHospWheelchairCd',
'@thuWheelchairName',
to_date('@friUpDate','yyyy-mm-dd hh24:mi:ss'),
'@friReviseName',
'@friReviseWeight',
'@friHospWheelchairCd',
'@friWheelchairName',
to_date('@satUpDate','yyyy-mm-dd hh24:mi:ss'),
'@satReviseName',
'@satReviseWeight',
'@satHospWheelchairCd',
'@satWheelchairName',
to_date('@sunUpDate','yyyy-mm-dd hh24:mi:ss'),
'@sunReviseName',
'@sunReviseWeight',
'@sunHospWheelchairCd',
'@sunWheelchairName'
);